import AxeBuilder from "@axe-core/playwright";
import { expect, test, type Page, type TestInfo } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import { TAGS } from "../a11y/axe-shared";
import { ADMIN_WORKSPACES, type AdminWorkspaceId } from "../../../src/lib/admin-workspaces";
import { OPS_FIXTURE_API_KEY_COUNT, OPS_FIXTURE_NOW_MS, installOpsApiFixtures } from "./ops-api-fixtures";

const HYDRATION_TIMEOUT_MS = 30_000;
const DOCUMENT_OVERFLOW_TOLERANCE_PX = 1;

const WORKSPACE_HEADINGS: Record<AdminWorkspaceId, string> = {
  triage: "Triage",
  pipeline: "Pipeline Health",
  reliability: "Reliability Workbench",
  crons: "Cron Lanes",
  actions: "Actions",
  comms: "Comms",
  history: "Incident History",
  "api-management": "API Management",
};

test.describe.configure({ timeout: 60_000 });

test.beforeEach(async ({ page }) => {
  await page.clock.setFixedTime(new Date(OPS_FIXTURE_NOW_MS));
  await installOpsApiFixtures(page);
});

async function attachJson(testInfo: TestInfo, name: string, value: unknown): Promise<void> {
  // Both paths are generated by Playwright and confined to this test's ignored output directory.
  // eslint-disable-next-line security/detect-non-literal-fs-filename
  await mkdir(testInfo.outputDir, { recursive: true });
  const path = testInfo.outputPath(`${name}.json`);
  // eslint-disable-next-line security/detect-non-literal-fs-filename
  await writeFile(path, `${JSON.stringify(value, null, 2)}\n`, "utf8");
  await testInfo.attach(name, { path, contentType: "application/json" });
}

async function waitForWorkspace(page: Page, workspaceId: AdminWorkspaceId): Promise<void> {
  await expect(page.getByRole("heading", { level: 2, name: WORKSPACE_HEADINGS[workspaceId], exact: true })).toBeVisible(
    { timeout: HYDRATION_TIMEOUT_MS },
  );

  if (workspaceId === "api-management") {
    await expect(page.getByText("Loading API keys...", { exact: true })).toBeHidden({
      timeout: HYDRATION_TIMEOUT_MS,
    });
    await expect(page.getByRole("table", { name: "API key inventory" })).toBeVisible({
      timeout: HYDRATION_TIMEOUT_MS,
    });
  }
}

async function assertOpsNavigation(page: Page, workspaceId: AdminWorkspaceId): Promise<void> {
  const workspace = ADMIN_WORKSPACES.find((candidate) => candidate.id === workspaceId);
  if (!workspace) throw new Error(`Missing workspace fixture for ${workspaceId}`);

  const nav = page.getByRole("navigation", { name: "Operator workspaces" });
  const activeLink = nav.getByRole("link", { name: workspace.label, exact: true });

  await expect(nav).toBeVisible();
  await expect(nav.getByRole("link")).toHaveCount(ADMIN_WORKSPACES.length);
  await expect(activeLink).toHaveAttribute("aria-current", "page");
  await expect.soft(activeLink, "active workspace should be visibly reachable in the nav").toBeInViewport({
    ratio: 0.5,
  });
}

async function assertPublicChromeAbsent(page: Page): Promise<void> {
  await expect(page.getByRole("navigation", { name: "Sections" })).toHaveCount(0);
  await expect(page.getByRole("navigation", { name: "Main navigation" })).toHaveCount(0);
  await expect(page.locator('[aria-label="Recent events tape"]')).toHaveCount(0);
  await expect(page.getByRole("contentinfo")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Feedback", exact: true })).toHaveCount(0);
}

async function assertNoDocumentOverflow(page: Page, testInfo: TestInfo): Promise<void> {
  const measurements = await page.evaluate((overflowTolerancePx) => {
    const root = document.documentElement;
    const body = document.body;
    const viewportWidth = root.clientWidth;
    const documentWidth = Math.max(root.scrollWidth, body?.scrollWidth ?? 0);
    const elements = Array.from(document.querySelectorAll<HTMLElement>("body *"));

    return {
      viewport: { width: viewportWidth, height: root.clientHeight },
      document: { width: documentWidth, height: Math.max(root.scrollHeight, body?.scrollHeight ?? 0) },
      root: { clientWidth: root.clientWidth, scrollWidth: root.scrollWidth },
      body: body ? { clientWidth: body.clientWidth, scrollWidth: body.scrollWidth } : null,
      horizontalOverflowPx: Math.max(0, documentWidth - viewportWidth),
      pathname: window.location.pathname,
      overflowingElements: elements
        .map((element) => {
          const rect = element.getBoundingClientRect();
          return {
            tag: element.tagName.toLowerCase(),
            id: element.id || null,
            className: typeof element.className === "string" ? element.className : null,
            text: (element.textContent ?? "").replace(/\s+/g, " ").trim().slice(0, 160),
            left: Math.round(rect.left),
            right: Math.round(rect.right),
            width: Math.round(rect.width),
          };
        })
        .filter((element) => element.right > viewportWidth + overflowTolerancePx || element.left < 0)
        .sort((left, right) => right.right - left.right)
        .slice(0, 20),
      intrinsicOverflowElements: elements
        .map((element) => {
          const style = window.getComputedStyle(element);
          return {
            tag: element.tagName.toLowerCase(),
            id: element.id || null,
            className: typeof element.className === "string" ? element.className : null,
            text: (element.textContent ?? "").replace(/\s+/g, " ").trim().slice(0, 160),
            clientWidth: element.clientWidth,
            scrollWidth: element.scrollWidth,
            overflowX: style.overflowX,
          };
        })
        .filter(
          (element) =>
            element.overflowX === "visible" && element.scrollWidth > element.clientWidth + overflowTolerancePx,
        )
        .sort((left, right) => right.scrollWidth - right.clientWidth - (left.scrollWidth - left.clientWidth))
        .slice(0, 20),
    };
  }, DOCUMENT_OVERFLOW_TOLERANCE_PX);

  await attachJson(testInfo, "layout-measurements", measurements);
  expect
    .soft(measurements.horizontalOverflowPx, "document-level horizontal overflow in CSS pixels")
    .toBeLessThanOrEqual(DOCUMENT_OVERFLOW_TOLERANCE_PX);
}

async function assertTriageScope(page: Page): Promise<void> {
  await expect(page.getByRole("heading", { name: "API Keys", exact: true })).toHaveCount(0);
  await expect(page.getByRole("table", { name: "API key inventory" })).toHaveCount(0);
  await expect(page.getByText("Browser Endpoint Probes", { exact: true })).toHaveCount(0);

  const lastWorkspace = ADMIN_WORKSPACES.at(-1);
  if (!lastWorkspace) throw new Error("Admin workspace registry is empty");
  const lastLink = page
    .getByRole("navigation", { name: "Operator workspaces" })
    .getByRole("link", { name: lastWorkspace.label, exact: true });
  await expect(lastLink).toHaveAttribute("href", lastWorkspace.path);
  await lastLink.scrollIntoViewIfNeeded();
  await expect(lastLink).toBeInViewport();
}

async function assertLargeSanitizedInventory(page: Page, inventoryResponse: Promise<unknown>): Promise<void> {
  const payload = (await inventoryResponse) as {
    keys?: Array<{ ownerEmail?: string | null; maskedToken?: string }>;
  };
  const keys = payload.keys ?? [];

  expect(keys).toHaveLength(OPS_FIXTURE_API_KEY_COUNT);
  expect(
    keys.every(
      (key) =>
        key.maskedToken?.endsWith("...fixture") === true &&
        (key.ownerEmail == null || key.ownerEmail.endsWith("@example.invalid")),
    ),
  ).toBe(true);

  const tableRows = page.getByRole("table", { name: "API key inventory" }).locator("tbody tr");
  const renderedRowCount = await tableRows.count();
  expect(renderedRowCount).toBeGreaterThan(0);
  expect(renderedRowCount).toBeLessThanOrEqual(OPS_FIXTURE_API_KEY_COUNT);
  await expect(page.locator('[aria-label="API key inventory summary"]').getByText("75", { exact: true })).toBeVisible();
}

for (const workspace of ADMIN_WORKSPACES) {
  test(`${workspace.label} hydrates with isolated ops chrome`, async ({ page }, testInfo) => {
    const inventoryResponse =
      workspace.id === "api-management"
        ? page
            .waitForResponse((response) => new URL(response.url()).pathname === "/api/admin/api-keys")
            .then((response) => response.json())
        : null;

    await page.goto(workspace.path, { waitUntil: "domcontentloaded" });
    await expect.poll(() => page.evaluate(() => window.location.hostname)).toBe("ops.pharos.watch");
    await expect.poll(() => page.evaluate(() => window.location.pathname)).toBe(workspace.path);
    await waitForWorkspace(page, workspace.id);
    await assertOpsNavigation(page, workspace.id);
    await assertPublicChromeAbsent(page);

    if (workspace.id === "triage") {
      await assertTriageScope(page);
    }
    if (workspace.id === "api-management" && inventoryResponse) {
      await assertLargeSanitizedInventory(page, inventoryResponse);
    }

    await assertNoDocumentOverflow(page, testInfo);
  });
}

for (const route of [
  { path: "/admin/", workspaceId: "triage" as const },
  { path: "/admin-api/", workspaceId: "api-management" as const },
]) {
  test(`axe hydrated: ${route.path}`, async ({ page }, testInfo) => {
    test.skip(testInfo.project.name !== "chromium-1440", "One hydrated axe pass per route is sufficient");

    await page.goto(route.path, { waitUntil: "domcontentloaded" });
    await waitForWorkspace(page, route.workspaceId);

    const results = await new AxeBuilder({ page }).withTags(TAGS).analyze();
    const violations = results.violations.map((violation) => ({
      id: violation.id,
      impact: violation.impact,
      help: violation.help,
      nodeCount: violation.nodes.length,
      targets: violation.nodes.flatMap((node) => node.target.map(String)),
    }));

    await attachJson(testInfo, "axe-violations", violations);
    expect(violations, `axe-core violations for ${route.path}`).toEqual([]);
  });
}
