import AxeBuilder from "@axe-core/playwright";
import { expect, test, type Page, type TestInfo } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import { TAGS } from "../a11y/axe-shared";
import { ADMIN_WORKSPACES, type AdminWorkspaceId } from "../../../src/lib/admin-workspaces";
import { OPS_FIXTURE_API_KEY_COUNT, OPS_FIXTURE_NOW_MS, installOpsApiFixtures } from "./ops-api-fixtures";

const HYDRATION_TIMEOUT_MS = 30_000;
const DOCUMENT_OVERFLOW_TOLERANCE_PX = 1;

const WORKSPACE_HEADINGS: Record<AdminWorkspaceId, string> = {
  triage: "Triage",
  pipeline: "Pipeline Health",
  reliability: "Reliability Workbench",
  crons: "Cron Lanes",
  actions: "Actions",
  comms: "Comms",
  history: "Incident History",
  "api-management": "API Management",
};

test.describe.configure({ timeout: 60_000 });

test.beforeEach(async ({ page }) => {
  await page.clock.setFixedTime(new Date(OPS_FIXTURE_NOW_MS));
  await installOpsApiFixtures(page);
});

async function attachJson(testInfo: TestInfo, name: string, value: unknown): Promise<void> {
  // Both paths are generated by Playwright and confined to this test's ignored output directory.
  // eslint-disable-next-line security/detect-non-literal-fs-filename
  await mkdir(testInfo.outputDir, { recursive: true });
  const path = testInfo.outputPath(`${name}.json`);
  // eslint-disable-next-line security/detect-non-literal-fs-filename
  await writeFile(path, `${JSON.stringify(value, null, 2)}\n`, "utf8");
  await testInfo.attach(name, { path, contentType: "application/json" });
}

async function waitForWorkspace(page: Page, workspaceId: AdminWorkspaceId): Promise<void> {
  await expect(page.getByRole("heading", { level: 1, name: WORKSPACE_HEADINGS[workspaceId], exact: true })).toBeVisible(
    { timeout: HYDRATION_TIMEOUT_MS },
  );

  if (workspaceId === "api-management") {
    await expect(page.getByText("Loading API keys...", { exact: true })).toBeHidden({
      timeout: HYDRATION_TIMEOUT_MS,
    });
    await expect(page.getByRole("table", { name: "API key inventory" })).toBeVisible({
      timeout: HYDRATION_TIMEOUT_MS,
    });
  }
}

async function assertOpsNavigation(page: Page, workspaceId: AdminWorkspaceId): Promise<void> {
  const workspace = ADMIN_WORKSPACES.find((candidate) => candidate.id === workspaceId);
  if (!workspace) throw new Error(`Missing workspace fixture for ${workspaceId}`);

  const nav = page.getByRole("navigation", { name: "Operator workspaces" });
  const activeLink = nav.getByRole("link", { name: workspace.label, exact: true });

  await expect(nav).toBeVisible();
  await expect(nav.getByRole("link")).toHaveCount(ADMIN_WORKSPACES.length);
  await expect(activeLink).toHaveAttribute("aria-current", "page");
  await expect.soft(activeLink, "active workspace should be visibly reachable in the nav").toBeInViewport({
    ratio: 0.5,
  });
}

async function assertPublicChromeAbsent(page: Page): Promise<void> {
  await expect(page.getByRole("navigation", { name: "Sections" })).toHaveCount(0);
  await expect(page.getByRole("navigation", { name: "Main navigation" })).toHaveCount(0);
  await expect(page.locator('[aria-label="Recent events tape"]')).toHaveCount(0);
  await expect(page.getByRole("contentinfo")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Feedback", exact: true })).toHaveCount(0);
}

async function assertNoDocumentOverflow(
  page: Page,
  testInfo: TestInfo,
  artifactName = "layout-measurements",
): Promise<void> {
  const measurements = await page.evaluate((overflowTolerancePx) => {
    const root = document.documentElement;
    const body = document.body;
    const viewportWidth = root.clientWidth;
    const documentWidth = Math.max(root.scrollWidth, body?.scrollWidth ?? 0);
    const elements = Array.from(document.querySelectorAll<HTMLElement>("body *"));

    return {
      viewport: { width: viewportWidth, height: root.clientHeight },
      document: { width: documentWidth, height: Math.max(root.scrollHeight, body?.scrollHeight ?? 0) },
      root: { clientWidth: root.clientWidth, scrollWidth: root.scrollWidth },
      body: body ? { clientWidth: body.clientWidth, scrollWidth: body.scrollWidth } : null,
      horizontalOverflowPx: Math.max(0, documentWidth - viewportWidth),
      pathname: window.location.pathname,
      overflowingElements: elements
        .map((element) => {
          const rect = element.getBoundingClientRect();
          return {
            tag: element.tagName.toLowerCase(),
            id: element.id || null,
            className: typeof element.className === "string" ? element.className : null,
            text: (element.textContent ?? "").replace(/\s+/g, " ").trim().slice(0, 160),
            left: Math.round(rect.left),
            right: Math.round(rect.right),
            width: Math.round(rect.width),
          };
        })
        .filter((element) => element.right > viewportWidth + overflowTolerancePx || element.left < 0)
        .sort((left, right) => right.right - left.right)
        .slice(0, 20),
      intrinsicOverflowElements: elements
        .map((element) => {
          const style = window.getComputedStyle(element);
          return {
            tag: element.tagName.toLowerCase(),
            id: element.id || null,
            className: typeof element.className === "string" ? element.className : null,
            text: (element.textContent ?? "").replace(/\s+/g, " ").trim().slice(0, 160),
            clientWidth: element.clientWidth,
            scrollWidth: element.scrollWidth,
            overflowX: style.overflowX,
          };
        })
        .filter(
          (element) =>
            element.overflowX === "visible" && element.scrollWidth > element.clientWidth + overflowTolerancePx,
        )
        .sort((left, right) => right.scrollWidth - right.clientWidth - (left.scrollWidth - left.clientWidth))
        .slice(0, 20),
    };
  }, DOCUMENT_OVERFLOW_TOLERANCE_PX);

  await attachJson(testInfo, artifactName, measurements);
  expect
    .soft(measurements.horizontalOverflowPx, "document-level horizontal overflow in CSS pixels")
    .toBeLessThanOrEqual(DOCUMENT_OVERFLOW_TOLERANCE_PX);
}

async function assertWorkspaceVisibleAtCurrentViewport(page: Page, workspaceId: AdminWorkspaceId): Promise<void> {
  await waitForWorkspace(page, workspaceId);
  await assertOpsNavigation(page, workspaceId);
  await expect(page.locator("main#ops-main-content")).toBeVisible();
}

function parseCssDurations(values: string): number[] {
  return values.split(",").map((value) => {
    const normalized = value.trim();
    const duration = Number.parseFloat(normalized) || 0;
    return normalized.endsWith("ms") ? duration / 1000 : duration;
  });
}

async function assertTriageScope(page: Page): Promise<void> {
  await expect(page.getByRole("heading", { name: "API Keys", exact: true })).toHaveCount(0);
  await expect(page.getByRole("table", { name: "API key inventory" })).toHaveCount(0);
  await expect(page.getByText("Browser Endpoint Probes", { exact: true })).toHaveCount(0);

  const lastWorkspace = ADMIN_WORKSPACES.at(-1);
  if (!lastWorkspace) throw new Error("Admin workspace registry is empty");
  const lastLink = page
    .getByRole("navigation", { name: "Operator workspaces" })
    .getByRole("link", { name: lastWorkspace.label, exact: true });
  await expect(lastLink).toHaveAttribute("href", lastWorkspace.path);
  await lastLink.scrollIntoViewIfNeeded();
  await expect(lastLink).toBeInViewport();
}

async function assertLargeSanitizedInventory(page: Page, inventoryResponse: Promise<unknown>): Promise<void> {
  const payload = (await inventoryResponse) as {
    keys?: Array<{ ownerEmail?: string | null; maskedToken?: string }>;
  };
  const keys = payload.keys ?? [];

  expect(keys).toHaveLength(OPS_FIXTURE_API_KEY_COUNT);
  expect(
    keys.every(
      (key) =>
        key.maskedToken?.endsWith("...fixture") === true &&
        (key.ownerEmail == null || key.ownerEmail.endsWith("@example.invalid")),
    ),
  ).toBe(true);

  const tableRows = page.getByRole("table", { name: "API key inventory" }).locator("tbody tr");
  const renderedRowCount = await tableRows.count();
  expect(renderedRowCount).toBeGreaterThan(0);
  expect(renderedRowCount).toBeLessThanOrEqual(OPS_FIXTURE_API_KEY_COUNT);
  await expect(page.locator('[aria-label="API key inventory summary"]').getByText("75", { exact: true })).toBeVisible();
}

for (const workspace of ADMIN_WORKSPACES) {
  test(`${workspace.label} hydrates with isolated ops chrome`, async ({ page }, testInfo) => {
    const inventoryResponse =
      workspace.id === "api-management"
        ? page
            .waitForResponse((response) => new URL(response.url()).pathname === "/api/admin/api-keys")
            .then((response) => response.json())
        : null;

    await page.goto(workspace.path, { waitUntil: "domcontentloaded" });
    await expect.poll(() => page.evaluate(() => window.location.hostname)).toBe("ops.pharos.watch");
    await expect.poll(() => page.evaluate(() => window.location.pathname)).toBe(workspace.path);
    await waitForWorkspace(page, workspace.id);
    await assertOpsNavigation(page, workspace.id);
    await assertPublicChromeAbsent(page);

    if (workspace.id === "triage") {
      await assertTriageScope(page);
    }
    if (workspace.id === "api-management" && inventoryResponse) {
      await assertLargeSanitizedInventory(page, inventoryResponse);
    }

    await assertNoDocumentOverflow(page, testInfo);
  });
}

for (const route of [
  { path: "/admin/", workspaceId: "triage" as const },
  { path: "/admin-api/", workspaceId: "api-management" as const },
]) {
  test(`axe hydrated: ${route.path}`, async ({ page }, testInfo) => {
    test.skip(testInfo.project.name !== "chromium-1440", "One hydrated axe pass per route is sufficient");

    await page.goto(route.path, { waitUntil: "domcontentloaded" });
    await waitForWorkspace(page, route.workspaceId);

    const results = await new AxeBuilder({ page }).withTags(TAGS).analyze();
    const violations = results.violations.map((violation) => ({
      id: violation.id,
      impact: violation.impact,
      help: violation.help,
      nodeCount: violation.nodes.length,
      targets: violation.nodes.flatMap((node) => node.target.map(String)),
    }));

    await attachJson(testInfo, "axe-violations", violations);
    expect(violations, `axe-core violations for ${route.path}`).toEqual([]);
  });
}

test.describe("Phase 6 media and reflow matrix", () => {
  test("@phase6 200% text zoom preserves workspace reflow and navigation", async ({ page }, testInfo) => {
    await page.goto("/admin/", { waitUntil: "domcontentloaded" });
    await assertWorkspaceVisibleAtCurrentViewport(page, "triage");
    const baselineFontSize = await page.evaluate(() =>
      Number.parseFloat(getComputedStyle(document.documentElement).fontSize),
    );

    await page.evaluate(() => {
      document.documentElement.style.fontSize = "200%";
    });

    await expect
      .poll(() => page.evaluate(() => Number.parseFloat(getComputedStyle(document.documentElement).fontSize)))
      .toBeGreaterThanOrEqual(baselineFontSize * 1.99);
    await assertWorkspaceVisibleAtCurrentViewport(page, "triage");
    await assertNoDocumentOverflow(page, testInfo, "layout-200-percent-text-zoom");
  });

  test("@phase6 light and dark schemes retain readable workspace chrome", async ({ page }, testInfo) => {
    const samples: Record<string, { backgroundColor: string; color: string; darkClass: boolean }> = {};

    for (const theme of ["light", "dark"] as const) {
      await page.emulateMedia({ colorScheme: theme });
      await page.goto("/admin/", { waitUntil: "domcontentloaded" });
      await page.evaluate((selectedTheme) => localStorage.setItem("theme", selectedTheme), theme);
      await page.reload({ waitUntil: "domcontentloaded" });
      await assertWorkspaceVisibleAtCurrentViewport(page, "triage");

      const sample = await page.evaluate(() => {
        const style = getComputedStyle(document.body);
        return {
          backgroundColor: style.backgroundColor,
          color: style.color,
          darkClass: document.documentElement.classList.contains("dark"),
          mediaDark: matchMedia("(prefers-color-scheme: dark)").matches,
        };
      });
      expect(sample.darkClass).toBe(theme === "dark");
      expect(sample.mediaDark).toBe(theme === "dark");
      expect(sample.backgroundColor).not.toBe(sample.color);
      samples[theme] = sample;
      await assertNoDocumentOverflow(page, testInfo, `layout-${theme}-scheme`);
    }

    expect(samples.light?.backgroundColor).not.toBe(samples.dark?.backgroundColor);
    expect(samples.light?.color).not.toBe(samples.dark?.color);
    await attachJson(testInfo, "theme-computed-colors", samples);
  });

  test("@phase6 forced colors preserves current navigation and selected workspace controls", async ({
    page,
  }, testInfo) => {
    await page.emulateMedia({ forcedColors: "active", colorScheme: "light" });

    await page.goto("/admin/pipeline/", { waitUntil: "domcontentloaded" });
    await assertWorkspaceVisibleAtCurrentViewport(page, "pipeline");
    expect(await page.evaluate(() => matchMedia("(forced-colors: active)").matches)).toBe(true);

    const activeWorkspace = page
      .getByRole("navigation", { name: "Operator workspaces" })
      .getByRole("link", { name: "Pipeline", exact: true });
    const selectedTab = page.getByRole("tab", { selected: true }).first();
    await expect(activeWorkspace).toBeVisible();
    await expect(selectedTab).toBeVisible();
    await expect(selectedTab).toHaveAttribute("aria-controls", /.+/);

    const activeBorder = await activeWorkspace.evaluate((element) => {
      const style = getComputedStyle(element);
      return { style: style.borderTopStyle, width: Number.parseFloat(style.borderTopWidth) || 0 };
    });
    expect(activeBorder.style).not.toBe("none");
    expect(activeBorder.width).toBeGreaterThanOrEqual(1);
    await assertNoDocumentOverflow(page, testInfo, "layout-forced-colors");
  });

  test("@phase6 reduced motion disables key ops navigation and workspace transitions", async ({ page }, testInfo) => {
    await page.emulateMedia({ reducedMotion: "reduce" });

    await page.goto("/admin/pipeline/", { waitUntil: "domcontentloaded" });
    await assertWorkspaceVisibleAtCurrentViewport(page, "pipeline");
    expect(await page.evaluate(() => matchMedia("(prefers-reduced-motion: reduce)").matches)).toBe(true);

    const activeWorkspace = page
      .getByRole("navigation", { name: "Operator workspaces" })
      .getByRole("link", { name: "Pipeline", exact: true });
    const selectedTab = page.getByRole("tab", { selected: true }).first();
    const workspaceTransitionDuration = await activeWorkspace.evaluate(
      (element) => getComputedStyle(element).transitionDuration,
    );
    const tabTransitionDuration = await selectedTab.evaluate((element) => getComputedStyle(element).transitionDuration);
    const transitionDurations = [
      ...parseCssDurations(workspaceTransitionDuration),
      ...parseCssDurations(tabTransitionDuration),
    ];

    expect(Math.max(...transitionDurations)).toBeLessThanOrEqual(0.01);
    expect(await page.evaluate(() => getComputedStyle(document.documentElement).scrollBehavior)).toBe("auto");
    await assertNoDocumentOverflow(page, testInfo, "layout-reduced-motion");
  });
});
