// Generated by scripts/maintenance/generate-case-study-client-index.ts.
// Do not edit by hand. Run `npm run prebuild` or `tsx scripts/maintenance/generate-case-study-client-index.ts`.

import type { CaseStudyOutcome } from "@/lib/case-study-outcomes";
import {
  resolveCaseStudySlugForEvent,
  type CaseStudyEventWindowResolverItem,
} from "@/lib/case-study-event-window";

export interface CaseStudyClientSummary {
  readonly slug: string;
  readonly title: string;
  readonly outcome: CaseStudyOutcome;
}

export const CASE_STUDY_CLIENT_BY_COIN_ID: Record<string, CaseStudyClientSummary> = {
  "usdc-circle": {
    "slug": "usdc-svb-2023",
    "title": "USDC and the Silicon Valley Bank weekend",
    "outcome": "survived"
  },
  "lusd-liquity": {
    "slug": "lusd-flight-to-safety-2023",
    "title": "LUSD: the peg that held during the SVB weekend",
    "outcome": "survived"
  },
  "dai-makerdao": {
    "slug": "dai-black-thursday",
    "title": "Dai: Black Thursday and the PSM dependency",
    "outcome": "survived"
  },
  "usde-ethena": {
    "slug": "usde-oracle-2025",
    "title": "USDe and the October 2025 Binance oracle print",
    "outcome": "survived"
  },
  "buidl-blackrock": {
    "slug": "buidl-tokenized-tbill-2025",
    "title": "BUIDL: the tokenized T-bill that held",
    "outcome": "survived"
  },
  "usyc-hashnote": {
    "slug": "usyc-nav-pricing-2025",
    "title": "USYC: when a T-bill fund became DeFi collateral",
    "outcome": "wounded"
  },
  "usd0-usual": {
    "slug": "usd0pp-usual-2025",
    "title": "USD0++ depeg: when Usual changed the redemption floor",
    "outcome": "wounded"
  },
  "crvusd-curve": {
    "slug": "crvusd-exploit-trilogy",
    "title": "crvUSD's exploit trilogy: three shocks, no collapse",
    "outcome": "survived"
  },
  "susd-synthetix": {
    "slug": "susd-sip420-2025",
    "title": "sUSD and SIP-420: the depeg a governance vote chose",
    "outcome": "died"
  },
  "usr-resolv": {
    "slug": "usr-resolv-2026",
    "title": "Resolv USD: when one key minted eighty million",
    "outcome": "died"
  },
  "usdf-falcon": {
    "slug": "usdf-falcon-2025",
    "title": "USDf and the opacity discount",
    "outcome": "wounded"
  },
  "fdusd-first-digital": {
    "slug": "fdusd-sun-fdt-2025",
    "title": "FDUSD and the insolvency tweet",
    "outcome": "wounded"
  },
  "usdd-tron-dao-reserve": {
    "slug": "usdd-tron-reserve-2024",
    "title": "USDD: when the issuer pulled the Bitcoin",
    "outcome": "wounded"
  },
  "usdx-kava": {
    "slug": "usdx-kava-2022",
    "title": "Kava USDX: one toxic collateral leg",
    "outcome": "died"
  },
  "mai-qidao": {
    "slug": "mai-qidao-bridge-2023",
    "title": "MAI: the bridge that broke the peg",
    "outcome": "wounded"
  },
  "pmusd-precious-metals": {
    "slug": "pmusd-precious-metals",
    "title": "pmUSD and the in-situ gold collateral chain",
    "outcome": "wounded"
  },
  "apxusd-apyx": {
    "slug": "apxusd-dat-collateral",
    "title": "apxUSD and the Bitcoin-treasury collateral chain",
    "outcome": "wounded"
  }
};

/**
 * Client-safe cemetery-id -> study lookup. Mirrors the server registry without
 * importing the full article modules, so client surfaces can link to studies
 * without shipping long-form prose.
 */
export const CASE_STUDY_CLIENT_BY_CEMETERY_ID: Record<string, CaseStudyClientSummary> = {
  "ust-terrausd-2022-05": {
    "slug": "terra-ust-2022",
    "title": "TerraUSD: the death spiral that erased $18 billion",
    "outcome": "died"
  },
  "iron-iron-2021-06": {
    "slug": "iron-titan-2021",
    "title": "IRON Finance & TITAN: the algorithmic prequel to Terra",
    "outcome": "died"
  },
  "usdn-neutrino-usd-2022-04": {
    "slug": "usdn-neutrino-2022",
    "title": "Neutrino USD: the stablecoin collapse before Terra",
    "outcome": "died"
  },
  "fei-fei-usd-2022-08": {
    "slug": "fei-protocol",
    "title": "Fei Protocol: the peg that broke at birth",
    "outcome": "died"
  },
  "usr-resolv": {
    "slug": "usr-resolv-2026",
    "title": "Resolv USD: when one key minted eighty million",
    "outcome": "died"
  },
  "xusd-stream-finance-xusd-2025-11": {
    "slug": "stream-elixir-contagion-2025",
    "title": "Stream Finance: loss broke three stablecoins",
    "outcome": "died"
  },
  "busd-binance-usd-2023-02": {
    "slug": "busd-paxos-2023",
    "title": "BUSD: the regulator's off-switch",
    "outcome": "died"
  },
  "usdc-m-multichain-usdc-2023-07": {
    "slug": "multichain-usdc-2023",
    "title": "Multichain USDC: the bridge died, not the dollar",
    "outcome": "died"
  },
  "husd-husd-2022-10": {
    "slug": "ftx-contagion-2022",
    "title": "The FTX weekend: which pegs broke",
    "outcome": "died"
  },
  "usdr-real-usd-2023-10": {
    "slug": "usdr-real-usd-2023",
    "title": "USDR: tokenized houses cannot sell at 3 AM",
    "outcome": "died"
  },
  "eurt-euro-tether-2024-11": {
    "slug": "eurt-mica-exit-2024",
    "title": "Euro Tether: the stablecoin that died by jurisdiction",
    "outcome": "died"
  }
};

/**
 * Minimal event-window index used by chart annotations. Keep this module free
 * of imports from ./index or content modules; it is part of charted-page client
 * bundles.
 */
export const CASE_STUDY_EVENT_WINDOWS: readonly CaseStudyEventWindowResolverItem[] = [
  {
    "slug": "usdc-svb-2023",
    "primaryCoinId": "usdc-circle",
    "relatedCoinIds": [
      "dai-makerdao",
      "frax-frax",
      "alusd-alchemix"
    ],
    "startISO": "2023-03-10",
    "endISO": "2023-03-13"
  },
  {
    "slug": "lusd-flight-to-safety-2023",
    "primaryCoinId": "lusd-liquity",
    "relatedCoinIds": [
      "usdc-circle",
      "dai-makerdao",
      "frax-frax"
    ],
    "startISO": "2023-03-10",
    "endISO": "2023-03-13"
  },
  {
    "slug": "terra-ust-2022",
    "primaryCoinId": null,
    "relatedCoinIds": [
      "usdt-tether",
      "mim-abracadabra"
    ],
    "startISO": "2022-05-07",
    "endISO": "2022-05-13"
  },
  {
    "slug": "dai-black-thursday",
    "primaryCoinId": "dai-makerdao",
    "relatedCoinIds": [
      "usdc-circle"
    ],
    "startISO": "2020-03-12",
    "endISO": "2023-03-13"
  },
  {
    "slug": "usde-oracle-2025",
    "primaryCoinId": "usde-ethena",
    "relatedCoinIds": [],
    "startISO": "2025-10-10",
    "endISO": "2025-10-11"
  },
  {
    "slug": "buidl-tokenized-tbill-2025",
    "primaryCoinId": "buidl-blackrock",
    "relatedCoinIds": [
      "usyc-hashnote"
    ],
    "startISO": "2024-03-20",
    "endISO": "2025-03-13"
  },
  {
    "slug": "usyc-nav-pricing-2025",
    "primaryCoinId": "usyc-hashnote",
    "relatedCoinIds": [
      "usd0-usual"
    ],
    "startISO": "2025-01-09",
    "endISO": "2025-01-21"
  },
  {
    "slug": "usd0pp-usual-2025",
    "primaryCoinId": "usd0-usual",
    "relatedCoinIds": [],
    "startISO": "2025-01-09",
    "endISO": "2025-01-16"
  },
  {
    "slug": "crvusd-exploit-trilogy",
    "primaryCoinId": "crvusd-curve",
    "relatedCoinIds": [
      "reusd-resupply"
    ],
    "startISO": "2023-08-03",
    "endISO": "2025-06-26"
  },
  {
    "slug": "susd-sip420-2025",
    "primaryCoinId": "susd-synthetix",
    "relatedCoinIds": [],
    "startISO": "2025-04-18",
    "endISO": "2026-06-26"
  },
  {
    "slug": "iron-titan-2021",
    "primaryCoinId": null,
    "relatedCoinIds": [],
    "startISO": "2021-06-16",
    "endISO": "2021-06-17"
  },
  {
    "slug": "usdn-neutrino-2022",
    "primaryCoinId": null,
    "relatedCoinIds": [],
    "startISO": "2022-03-31",
    "endISO": "2022-05-11"
  },
  {
    "slug": "fei-protocol",
    "primaryCoinId": null,
    "relatedCoinIds": [],
    "startISO": "2021-04-03",
    "endISO": "2022-09-22"
  },
  {
    "slug": "usr-resolv-2026",
    "primaryCoinId": "usr-resolv",
    "relatedCoinIds": [],
    "startISO": "2026-03-22",
    "endISO": "2026-04-27"
  },
  {
    "slug": "stream-elixir-contagion-2025",
    "primaryCoinId": null,
    "relatedCoinIds": [],
    "startISO": "2025-11-04",
    "endISO": "2025-11-08"
  },
  {
    "slug": "usdf-falcon-2025",
    "primaryCoinId": "usdf-falcon",
    "relatedCoinIds": [
      "usde-ethena",
      "usr-resolv"
    ],
    "startISO": "2025-07-08",
    "endISO": "2025-07-11"
  },
  {
    "slug": "fdusd-sun-fdt-2025",
    "primaryCoinId": "fdusd-first-digital",
    "relatedCoinIds": [
      "tusd-trueusd",
      "usdc-circle"
    ],
    "startISO": "2025-04-02",
    "endISO": "2025-04-09"
  },
  {
    "slug": "busd-paxos-2023",
    "primaryCoinId": null,
    "relatedCoinIds": [
      "usdp-paxos",
      "fdusd-first-digital"
    ],
    "startISO": "2023-02-03",
    "endISO": "2023-12-31"
  },
  {
    "slug": "multichain-usdc-2023",
    "primaryCoinId": null,
    "relatedCoinIds": [
      "usdc-circle"
    ],
    "startISO": "2023-07-06",
    "endISO": "2023-07-14"
  },
  {
    "slug": "ftx-contagion-2022",
    "primaryCoinId": null,
    "relatedCoinIds": [
      "usdt-tether",
      "usdd-tron-dao-reserve"
    ],
    "startISO": "2022-10-31",
    "endISO": "2022-11-16"
  },
  {
    "slug": "usdr-real-usd-2023",
    "primaryCoinId": null,
    "relatedCoinIds": [],
    "startISO": "2023-10-10",
    "endISO": "2023-10-12"
  },
  {
    "slug": "eurt-mica-exit-2024",
    "primaryCoinId": null,
    "relatedCoinIds": [
      "eurc-circle",
      "eure-monerium"
    ],
    "startISO": "2024-06-30",
    "endISO": "2024-11-27"
  },
  {
    "slug": "usdd-tron-reserve-2024",
    "primaryCoinId": "usdd-tron-dao-reserve",
    "relatedCoinIds": [
      "dai-makerdao"
    ],
    "startISO": "2024-08-19",
    "endISO": "2025-01-25"
  },
  {
    "slug": "usdx-kava-2022",
    "primaryCoinId": "usdx-kava",
    "relatedCoinIds": [],
    "startISO": "2022-05-11",
    "endISO": "2022-05-13"
  },
  {
    "slug": "mai-qidao-bridge-2023",
    "primaryCoinId": "mai-qidao",
    "relatedCoinIds": [],
    "startISO": "2023-07-06",
    "endISO": "2024-02-22"
  },
  {
    "slug": "pmusd-precious-metals",
    "primaryCoinId": "pmusd-precious-metals",
    "relatedCoinIds": [],
    "startISO": "2026-02-15",
    "endISO": "2026-05-04"
  },
  {
    "slug": "apxusd-dat-collateral",
    "primaryCoinId": "apxusd-apyx",
    "relatedCoinIds": [
      "apyusd-apyx"
    ],
    "startISO": "2026-06-02",
    "endISO": "2026-06-18"
  }
];

/**
 * Resolve the case study that covers a charted event for `coinId` at `tsMs`
 * without importing article bodies into the client bundle.
 */
export function caseStudySlugForEvent(coinId: string, tsMs: number): string | undefined {
  return resolveCaseStudySlugForEvent(CASE_STUDY_EVENT_WINDOWS, coinId, tsMs);
}
