interface ChainMeta {
  name: string;
  explorerUrl: string;
  evmChainId: number | null;
  type: "evm" | "tron" | "other";
  logoPath: string;
}

export const CHAIN_META: Record<string, ChainMeta> = {
  ethereum:  { name: "Ethereum",  explorerUrl: "https://etherscan.io",              evmChainId: 1,     type: "evm",  logoPath: "/chains/ethereum.png"  },
  arbitrum:  { name: "Arbitrum",  explorerUrl: "https://arbiscan.io",               evmChainId: 42161, type: "evm",  logoPath: "/chains/arbitrum.png"  },
  base:      { name: "Base",      explorerUrl: "https://basescan.org",              evmChainId: 8453,  type: "evm",  logoPath: "/chains/base.png"      },
  optimism:  { name: "Optimism",  explorerUrl: "https://optimistic.etherscan.io",   evmChainId: 10,    type: "evm",  logoPath: "/chains/optimism.png"  },
  polygon:   { name: "Polygon",   explorerUrl: "https://polygonscan.com",           evmChainId: 137,   type: "evm",  logoPath: "/chains/polygon.png"   },
  avalanche: { name: "Avalanche", explorerUrl: "https://snowscan.xyz",              evmChainId: 43114, type: "evm",  logoPath: "/chains/avalanche.png" },
  bsc:       { name: "BSC",       explorerUrl: "https://bscscan.com",               evmChainId: 56,    type: "evm",  logoPath: "/chains/bsc.png"       },
  gnosis:    { name: "Gnosis",    explorerUrl: "https://gnosisscan.io",             evmChainId: 100,   type: "evm",  logoPath: "/chains/gnosis.png"    },
  fantom:    { name: "Fantom",    explorerUrl: "https://ftmscan.com",               evmChainId: 250,   type: "evm",  logoPath: "/chains/fantom.png"    },
  celo:      { name: "Celo",      explorerUrl: "https://celoscan.io",               evmChainId: 42220, type: "evm",  logoPath: "/chains/celo.png"      },
  zksync:    { name: "zkSync",    explorerUrl: "https://explorer.zksync.io",       evmChainId: 324,   type: "evm",  logoPath: "/chains/zksync.png"    },
  sonic:     { name: "Sonic",     explorerUrl: "https://sonicscan.org",            evmChainId: 146,   type: "evm",  logoPath: "/chains/sonic.png"     },
  sei:       { name: "Sei",       explorerUrl: "https://seitrace.com",             evmChainId: 1329,  type: "evm",  logoPath: "/chains/sei.png"       },
  worldchain:{ name: "World Chain",explorerUrl: "https://worldscan.org",           evmChainId: 480,   type: "evm",  logoPath: "/chains/worldchain.png"},
  unichain:  { name: "Unichain",  explorerUrl: "https://uniscan.xyz",             evmChainId: 130,   type: "evm",  logoPath: "/chains/unichain.png"  },
  ink:       { name: "Ink",       explorerUrl: "https://explorer.inkonchain.com",  evmChainId: 57073, type: "evm",  logoPath: "/chains/ink.png"       },
  moonriver: { name: "Moonriver", explorerUrl: "https://moonriver.moonscan.io",   evmChainId: 1285,  type: "evm",  logoPath: "/chains/moonriver.png" },
  klaytn:    { name: "Klaytn",    explorerUrl: "https://klaytnscope.com",          evmChainId: 8217,  type: "evm",  logoPath: "/chains/klaytn.png"    },
  plume:     { name: "Plume",     explorerUrl: "https://explorer.plumenetwork.xyz",evmChainId: 98866, type: "evm",  logoPath: "/chains/plume.png"     },
  hyperevm:  { name: "HyperEVM",  explorerUrl: "https://purrsec.com",             evmChainId: 999,   type: "evm",  logoPath: "/chains/hyperevm.png"  },
  monad:     { name: "Monad",     explorerUrl: "https://explorer.monad.xyz",       evmChainId: 143,   type: "evm",  logoPath: "/chains/monad.png"     },
  xdc:       { name: "XDC Network",explorerUrl: "https://xdcscan.io",             evmChainId: 50,    type: "evm",  logoPath: "/chains/xdc.png"       },
  mantle:    { name: "Mantle",    explorerUrl: "https://mantlescan.xyz",           evmChainId: 5000,  type: "evm",  logoPath: "/chains/mantle.png"    },
  linea:     { name: "Linea",    explorerUrl: "https://lineascan.build",           evmChainId: 59144, type: "evm",  logoPath: "/chains/linea.png"     },
  scroll:    { name: "Scroll",   explorerUrl: "https://scrollscan.com",            evmChainId: 534352,type: "evm",  logoPath: "/chains/scroll.png"    },
  blast:     { name: "Blast",    explorerUrl: "https://blastscan.io",              evmChainId: 81457, type: "evm",  logoPath: "/chains/blast.png"     },
  mode:      { name: "Mode",     explorerUrl: "https://modescan.io",              evmChainId: 34443, type: "evm",  logoPath: "/chains/mode.png"      },
  manta:     { name: "Manta",    explorerUrl: "https://pacific-explorer.manta.network", evmChainId: 169, type: "evm", logoPath: "/chains/manta.png"  },
  berachain: { name: "Berachain",explorerUrl: "https://berascan.com",             evmChainId: 80094, type: "evm",  logoPath: "/chains/berachain.png" },
  bob:       { name: "BOB",     explorerUrl: "https://explorer.gobob.xyz",        evmChainId: 60808, type: "evm",  logoPath: "/chains/bob.png"       },
  fraxtal:   { name: "Fraxtal", explorerUrl: "https://fraxscan.com",             evmChainId: 252,   type: "evm",  logoPath: "/chains/fraxtal.png"   },
  taiko:     { name: "Taiko",   explorerUrl: "https://taikoscan.io",             evmChainId: 167000,type: "evm",  logoPath: "/chains/taiko.png"     },
  "polygon-zkevm": { name: "Polygon zkEVM", explorerUrl: "https://zkevm.polygonscan.com", evmChainId: 1101, type: "evm", logoPath: "/chains/polygon-zkevm.png" },
  aurora:    { name: "Aurora",  explorerUrl: "https://explorer.aurora.dev",       evmChainId: 1313161554, type: "evm", logoPath: "/chains/aurora.png" },
  moonbeam:  { name: "Moonbeam",explorerUrl: "https://moonbeam.moonscan.io",     evmChainId: 1284,  type: "evm",  logoPath: "/chains/moonbeam.png"  },
  boba:      { name: "Boba",    explorerUrl: "https://bobascan.com",              evmChainId: 288,   type: "evm",  logoPath: "/chains/boba.png"      },
  soneium:   { name: "Soneium", explorerUrl: "https://soneium.blockscout.com",   evmChainId: 1868,  type: "evm",  logoPath: "/chains/soneium.png"   },
  zircuit:   { name: "Zircuit", explorerUrl: "https://explorer.zircuit.com",     evmChainId: 48900, type: "evm",  logoPath: "/chains/zircuit.png"   },
  metis:     { name: "Metis",   explorerUrl: "https://andromeda-explorer.metis.io", evmChainId: 1088, type: "evm", logoPath: "/chains/metis.png"   },
  astar:     { name: "Astar",   explorerUrl: "https://astar.blockscout.com",     evmChainId: 592,   type: "evm",  logoPath: "/chains/astar.png"     },
  plasma:    { name: "Plasma",  explorerUrl: "https://plasma-explorer.com",       evmChainId: 9745,  type: "evm",  logoPath: "/chains/plasma.png"    },
  "morph-l2":{ name: "Morph",   explorerUrl: "https://explorer.morphl2.io",      evmChainId: 2818,  type: "evm",  logoPath: "/chains/morph-l2.png"  },
  swellchain:{ name: "Swellchain",explorerUrl: "https://explorer.swellnetwork.io",evmChainId: 1923,  type: "evm",  logoPath: "/chains/swellchain.png"},
  xlayer:    { name: "X Layer", explorerUrl: "https://www.oklink.com/xlayer",     evmChainId: 196,   type: "evm",  logoPath: "/chains/xlayer.png"    },
  apechain:  { name: "ApeChain",explorerUrl: "https://apescan.io",               evmChainId: 33139, type: "evm",  logoPath: "/chains/apechain.png"  },
  bittorrent:{ name: "BitTorrent",explorerUrl: "https://bttcscan.com",           evmChainId: 199,   type: "evm",  logoPath: "/chains/bittorrent.png"},
  viction:   { name: "Viction", explorerUrl: "https://tomoscan.io",              evmChainId: 88,    type: "evm",  logoPath: "/chains/viction.png"   },
  flare:     { name: "Flare",   explorerUrl: "https://flarescan.com",            evmChainId: 14,    type: "evm",  logoPath: "/chains/flare.png"     },
  songbird:  { name: "Songbird",explorerUrl: "https://songbird-explorer.flare.network", evmChainId: 19, type: "evm", logoPath: "/chains/songbird.png"},
  bitlayer:  { name: "Bitlayer",explorerUrl: "https://www.btrscan.com",          evmChainId: 200901,type: "evm",  logoPath: "/chains/bitlayer.png"  },
  tron:      { name: "Tron",      explorerUrl: "https://tronscan.org",              evmChainId: null,  type: "tron",  logoPath: "/chains/tron.png"      },
  aptos:     { name: "Aptos",     explorerUrl: "https://explorer.aptoslabs.com",   evmChainId: null,  type: "other", logoPath: "/chains/aptos.png"     },
  sui:       { name: "Sui",       explorerUrl: "https://suiscan.xyz",              evmChainId: null,  type: "other", logoPath: "/chains/sui.png"       },
  solana:    { name: "Solana",   explorerUrl: "https://solscan.io",               evmChainId: null,  type: "other", logoPath: "/chains/solana.svg"    },
  ton:       { name: "TON",       explorerUrl: "https://tonviewer.com",            evmChainId: null,  type: "other", logoPath: "/chains/ton.png"       },
  near:      { name: "NEAR",      explorerUrl: "https://nearblocks.io",            evmChainId: null,  type: "other", logoPath: "/chains/near.png"      },
  algorand:  { name: "Algorand",  explorerUrl: "https://explorer.perawallet.app",  evmChainId: null,  type: "other", logoPath: "/chains/algorand.png"  },
  stellar:   { name: "Stellar",  explorerUrl: "https://stellar.expert",           evmChainId: null,  type: "other", logoPath: "/chains/stellar.png"  },
  starknet:  { name: "Starknet",  explorerUrl: "https://starkscan.co",             evmChainId: null,  type: "other", logoPath: "/chains/starknet.png"  },
  hedera:    { name: "Hedera",    explorerUrl: "https://hashscan.io",              evmChainId: null,  type: "other", logoPath: "/chains/hedera.png"    },
  polkadot:  { name: "Polkadot",  explorerUrl: "https://polkadot.subscan.io",     evmChainId: null,  type: "other", logoPath: "/chains/polkadot.png"  },
  xrpl:      { name: "XRP Ledger",explorerUrl: "https://xrpscan.com",             evmChainId: null,  type: "other", logoPath: "/chains/xrpl.png"      },
  kava:      { name: "Kava",     explorerUrl: "https://kavascan.com",             evmChainId: 2222,  type: "evm",   logoPath: "/chains/kava.png"      },
  tezos:     { name: "Tezos",   explorerUrl: "https://tzkt.io",                  evmChainId: null,  type: "other", logoPath: "/chains/tezos.png"     },
  cardano:   { name: "Cardano", explorerUrl: "https://cardanoscan.io",           evmChainId: null,  type: "other", logoPath: "/chains/cardano.png"   },
  icp:       { name: "Internet Computer", explorerUrl: "https://dashboard.internetcomputer.org", evmChainId: null, type: "other", logoPath: "/chains/icp.png" },
  noble:     { name: "Noble",   explorerUrl: "https://www.mintscan.io/noble",    evmChainId: null,  type: "other", logoPath: "/chains/noble.png"     },
  osmosis:   { name: "Osmosis", explorerUrl: "https://www.mintscan.io/osmosis",  evmChainId: null,  type: "other", logoPath: "/chains/osmosis.png"   },
  mantra:    { name: "MANTRA",  explorerUrl: "https://www.mintscan.io/mantra",   evmChainId: null,  type: "other", logoPath: "/chains/mantra.png"    },
  provenance:{ name: "Provenance",explorerUrl: "https://www.mintscan.io/provenance", evmChainId: null, type: "other", logoPath: "/chains/provenance.png" },
  hydration: { name: "Hydration",explorerUrl: "https://hydration.subscan.io",    evmChainId: null,  type: "other", logoPath: "/chains/hydration.png" },
};
