export type CommandPaletteStablecoinSearchItem = readonly [
  id: string,
  name: string,
  symbol: string,
  status?: "pre-launch" | "frozen",
  frozenAt?: string,
];

// Lightweight static search rows for the lazy command palette.
// Keep in sync with shared/lib/stablecoins via src/lib/__tests__/stablecoin-static-data.test.ts.
export const COMMAND_PALETTE_STABLECOINS = [
  ["usdt-tether", "Tether", "USDT"],
  ["susdt-spark", "Spark Savings USDT", "spUSDT"],
  ["steakusdt-steakhouse", "Steakhouse USDT V2", "steakUSDT"],
  ["usdc-circle", "USD Coin", "USDC"],
  ["susdc-spark", "Spark Savings USDC", "spUSDC"],
  ["gtusdcp-gauntlet", "Gauntlet USDC Prime", "gtUSDCp"],
  ["gtusdc-gauntlet", "Gauntlet USDC Prime V1", "gtUSDC"],
  ["yvusdc-yearn", "Yearn v3 USDC Vault", "yvUSDC-1"],
  ["steakusdc-steakhouse", "Steakhouse USDC V2", "steakUSDC"],
  ["bbqusdc-steakhouse", "Smokehouse USDC", "bbqUSDC"],
  ["usde-ethena", "Ethena USDe", "USDe"],
  ["srusde-strata", "Strata Senior USDe", "srUSDe"],
  ["susde-ethena", "Ethena Staked USDe", "sUSDe"],
  ["usds-sky", "Sky Dollar", "USDS"],
  ["susds-sky", "Sky Savings USDS", "sUSDS"],
  ["stusds-sky", "Staked USDS", "stUSDS"],
  ["usd1-world-liberty-financial", "World Liberty Financial USD", "USD1"],
  ["susd1plus-lorenzo", "staked USD1+", "sUSD1+"],
  ["dai-makerdao", "Dai", "DAI"],
  ["sdai-sky", "Savings Dai", "sDAI"],
  ["pyusd-paypal", "PayPal USD", "PYUSD"],
  ["usdf-falcon", "Falcon USD", "USDf"],
  ["aa-falconx-mev-capital", "Pareto FalconX Credit Vault", "AA_FalconXUSDC"],
  ["usyc-hashnote", "Circle USYC", "USYC"],
  ["usdg-paxos", "Global Dollar", "USDG"],
  ["rlusd-ripple", "Ripple USD", "RLUSD"],
  ["usdy-ondo-finance", "Ondo US Dollar Yield", "USDY"],
  ["buidl-blackrock", "BlackRock USD Institutional Digital Liquidity Fund", "BUIDL"],
  ["benji-franklin-templeton", "Franklin OnChain U.S. Government Money Fund", "BENJI"],
  ["wtgxx-wisdomtree", "WisdomTree Treasury Money Market Digital Fund", "WTGXX"],
  ["vbill-vaneck", "VanEck Treasury Fund", "VBILL"],
  ["acred-apollo-securitize", "Apollo Diversified Credit Securitize Fund", "ACRED"],
  ["jaaa-janus-henderson-anemoy", "Janus Henderson Anemoy AAA CLO Fund", "JAAA"],
  ["acrdx-anemoy-apollo", "Anemoy Tokenized Apollo Diversified Credit Fund", "ACRDX"],
  ["stac-securitize", "Securitize Tokenized AAA CLO Fund", "STAC"],
  ["hlscope-hamilton-lane", "Hamilton Lane Senior Credit Opportunities Securitize Fund", "HLSCOPE"],
  ["pc0000031-tradable", "Tradable NA Rent Financing Platform SSTN", "PC0000031"],
  ["pc0000033-tradable", "Tradable APAC Diversified Finance Provider SSTN", "PC0000033"],
  ["pc0000101-tradable", "Tradable NA Post-Settlement Legal Financing Receivables", "PC0000101"],
  ["pc0000089-tradable", "Tradable LatAm Residential SSTL", "PC0000089"],
  ["usdd-tron-dao-reserve", "USDD", "USDD"],
  ["susdd-tron-dao-reserve", "Savings USDD", "sUSDD"],
  ["usdtb-ethena", "Ethena USDtb", "USDTB"],
  ["bfusd-binance", "BFUSD", "BFUSD"],
  ["m-m0", "M by M0", "M"],
  ["u-united-stables", "United Stables", "U"],
  ["usdai-usd-ai", "USD.AI", "USDai"],
  ["susdai-usd-ai", "Staked USDai", "sUSDai"],
  ["usd0-usual", "Usual USD", "USD0"],
  ["busd0-usual", "Bond USD0", "bUSD0"],
  ["gho-aave", "GHO", "GHO"],
  ["sgho-aave", "Aave Savings GHO", "sGHO"],
  ["stkgho-umbrella-aave", "Aave Umbrella stkGHO", "stkGHO.v1"],
  ["a7a5-old-vector", "A7A5", "A7A5"],
  ["tusd-trueusd", "TrueUSD", "TUSD"],
  ["fdusd-first-digital", "First Digital USD", "FDUSD"],
  ["cusd-cap", "Cap cUSD", "CUSD"],
  ["stcusd-cap", "Staked Cap USD", "stcUSD"],
  ["eurc-circle", "EURC", "EURC"],
  ["usr-resolv", "Resolv USD", "USR", "frozen", "2026-04-27"],
  ["ylds-figure", "YLDS", "YLDS"],
  ["crvusd-curve", "crvUSD", "crvUSD"],
  ["scrvusd-curve", "Savings crvUSD", "scrvUSD"],
  ["usx-solstice", "Solstice USX", "USX"],
  ["usda-avalon", "Avalon USDa", "USDA"],
  ["frax-frax", "Frax", "FRAX"],
  ["dola-inverse-finance", "Dola", "DOLA"],
  ["sdola-inverse-finance", "Inverse Staked DOLA", "sDOLA"],
  ["ausd-agora", "Agora Dollar", "AUSD"],
  ["iusd-infinifi", "infiniFi USD", "IUSD"],
  ["usdf-astherus", "Aster USDF", "USDF"],
  ["asusdf-astherus", "Aster Staked USDF", "asUSDF"],
  ["dusd-standx", "StandX DUSD", "DUSD"],
  ["satusd-river", "River Stablecoin", "satUSD"],
  ["brz-transfero", "Brazilian Digital", "BRZ"],
  ["gusd-gate", "Gate USD", "GUSD"],
  ["frxusd-frax", "Frax USD", "FRXUSD"],
  ["sfrxusd-frax", "Staked Frax USD", "sfrxUSD"],
  ["rwausdi-multipli", "rwaUSDi", "rwaUSDi"],
  ["avusd-avant", "Avant USD", "avUSD"],
  ["savusd-avant", "Avant Staked USD", "savUSD"],
  ["reusd-re-protocol", "Re Protocol reUSD", "reUSD"],
  ["pmusd-precious-metals", "pmUSD", "pmUSD"],
  ["usdz-anzen", "Anzen USDz", "USDz"],
  ["cash-phantom", "CASH", "CASH"],
  ["usdkg-gold-dollar", "USDKG", "USDKG"],
  ["mnee-mnee", "MNEE USD", "MNEE"],
  ["pusd-polymarket", "Polymarket USD", "PUSD"],
  ["tbill-openeden", "OpenEden TBILL", "TBILL"],
  ["fpi-frax", "Frax Price Index", "FPI"],
  ["usdu-unitas", "Unitas", "USDU"],
  ["usdh-native-markets", "USDH Stablecoin", "USDH", "frozen", "2026-07-11"],
  ["xdai-gnosis", "xDAI", "xDAI"],
  ["lisusd-lista", "Lista USD", "LISUSD"],
  ["usdon-ondo", "Ondo U.S. Dollar Token", "USDon"],
  ["usdo-openeden", "OpenEden OpenDollar", "USDO"],
  ["cusdo-openeden", "Compounding OpenDollar", "cUSDO"],
  ["cgusd-cygnus-finance", "Cygnus Finance Global USD", "cgUSD"],
  ["eurcv-societe-generale-forge", "EUR CoinVertible", "EURCV"],
  ["aeur-anchored-coins", "Anchored Coins AEUR", "AEUR", "frozen", "2026-07-11"],
  ["usdq-quantoz", "Quantoz USDQ", "USDQ"],
  ["reusd-resupply", "Resupply USD", "REUSD"],
  ["euri-banking-circle", "Eurite", "EURI"],
  ["gusd-gemini", "Gemini Dollar", "GUSD"],
  ["usdp-paxos", "Pax Dollar", "USDP"],
  ["usdsui-sui", "Sui Dollar", "USDsui"],
  ["suiusde-sui", "eSui Dollar", "suiUSDe"],
  ["brlv-crown", "Crown BRLV", "BRLV"],
  ["reur-royal-euro", "Royal Euro", "REUR"],
  ["ausdt-tether-alloy", "Alloy Tether", "aUSD₮", "frozen", "2026-07-11"],
  ["usdx-hex-trust", "Hex Trust USDX", "USDX"],
  ["hbd-hive", "Hive Backed Dollar", "HBD"],
  ["xusd-straitsx", "StraitsX XUSD", "XUSD"],
  ["musd-metamask", "MetaMask USD", "MUSD"],
  ["yusd-aegis", "Aegis YUSD", "YUSD"],
  ["syusd-aegis", "Aegis Staked YUSD", "sYUSD"],
  ["susd-synthetix", "sUSD", "sUSD", "frozen", "2026-06-26"],
  ["bold-liquity", "Liquity BOLD", "BOLD"],
  ["sbold-k3-capital", "sBOLD by K3 Capital", "sBOLD"],
  ["ybold-yearn", "Yearn BOLD", "yBOLD"],
  ["hyusd-hylo", "Hylo HYUSD", "HYUSD"],
  ["lusd-liquity", "Liquity USD", "LUSD"],
  ["fxusd-f-x-protocol", "fxUSD", "fxUSD"],
  ["fxsave-f-x-protocol", "f(x) USD Saving", "fxSAVE"],
  ["usdn-noble", "Noble Dollar", "USDN"],
  ["usdn-smardex", "SMARDEX USDN", "USDN"],
  ["mim-abracadabra", "Magic Internet Money", "MIM"],
  ["usdcv-societe-generale-forge", "USD CoinVertible", "USDCV"],
  ["honey-berachain", "Honey", "HONEY"],
  ["zchf-frankencoin", "Frankencoin", "ZCHF"],
  ["usdb-blast", "USDB Blast", "USDB"],
  ["zeusd-zoth", "Zoth ZeUSD", "ZeUSD"],
  ["eure-monerium", "Monerium EUR emoney", "EURE"],
  ["usn-noon", "Noon USN", "USN"],
  ["susn-noon", "Staked USN", "sUSN"],
  ["nect-beraborrow", "Nectar", "NECT"],
  ["eusd-electronic-usd", "Electronic USD", "EUSD"],
  ["mai-qidao", "MAI", "MAI"],
  ["buck-bucket-protocol", "Bucket Protocol BUCK", "BUCK"],
  ["meusd-mezo", "Mezo USD", "MUSD"],
  ["uty-xsy", "Unity", "UTY"],
  ["eurs-stasis", "Stasis Euro", "EURS"],
  ["msusd-metronome", "Metronome Synth USD", "MSUSD"],
  ["rusd-royal-dollar", "Royal Dollar", "RUSD"],
  ["usdr-ring", "Ring USD", "USDR"],
  ["usdaf-asymmetry", "Asymmetry USDaf", "USDaf"],
  ["usnd-nerite", "Nerite USND", "USND", "frozen", "2026-05-10"],
  ["usdq-quill", "Quill USD", "USDQ"],
  ["usdk-orki", "Orki USD", "USDK", "frozen", "2026-06-30"],
  ["ebusd-ebisu", "Ebisu ebUSD", "ebUSD"],
  ["nusd-neutrl", "Neutrl USD", "NUSD"],
  ["usdh-hermetica", "Hermetica USDh", "USDh"],
  ["yzusd-yuzu", "Yuzu USD", "YZUSD"],
  ["syzusd-yuzu", "Staked Yuzu USD", "syzUSD"],
  ["jupusd-jupiter", "JupUSD", "JUPUSD"],
  ["usdm-mega", "MegaUSD", "USDM"],
  ["usdsc-startale", "Startale USD", "USDSC"],
  ["ctusd-citrea", "Citrea USD", "ctUSD"],
  ["wm-m0", "Wrapped M", "wM"],
  ["usdnr-nerona", "Nerona USD", "USDnr"],
  ["usdat-saturn", "Saturn USDat", "USDat"],
  ["usdk-kast", "KAST Dollar", "USDK"],
  ["moveusd-cfx", "CFX MoveUSD", "MOVEUSD"],
  ["xo-exodus", "XO Cash", "XO"],
  ["usat-tether", "USA₮", "USAT"],
  ["cusd-celo", "Mento Dollar", "USDm"],
  ["alusd-alchemix", "Alchemix USD", "alUSD"],
  ["feusd-felix", "Felix feUSD", "FEUSD"],
  ["fidd-fidelity", "Fidelity Digital Dollar", "FIDD"],
  ["usdgo-osl", "USDGO", "USDGO"],
  ["msusd-main-street", "Main Street USD", "MSUSD", "frozen", "2026-06-20"],
  ["msy-main-street", "Main Street Yield", "msY", "frozen", "2026-06-20"],
  ["usdm-moneta", "Moneta", "USDM"],
  ["hollar-hydrated", "Hydrated Dollar", "HOLLAR"],
  ["usda-anzens", "Anzens USDA", "USDA"],
  ["uusd-youves", "Youves uUSD", "UUSD"],
  ["aznd-mu-digital", "Mu Digital AZND", "AZND"],
  ["pusd-plume", "Plume USD", "pUSD"],
  ["wusd-worldwide", "Worldwide USD", "WUSD"],
  ["sbc-brale", "Brale SBC", "SBC"],
  ["ousd-origin-protocol", "Origin Dollar", "OUSD"],
  ["btcusd-btcfi", "Bitcoin USD", "BtcUSD"],
  ["usbd-bima", "Bima USBD", "USBD"],
  ["doc-money-on-chain", "Dollar on Chain", "DOC"],
  ["dllr-sovryn", "Sovryn Dollar", "DLLR"],
  ["xusd-babelfish", "XUSD", "XUSD"],
  ["usdrif-rif", "RIF US Dollar", "USDRIF"],
  ["usp-pikudao", "PikuDAO USP", "USP"],
  ["usdr-stablr", "StablR USD", "USDR", "frozen", "2026-05-24"],
  ["usdu-usdu-finance", "USDU Finance", "USDU"],
  ["dusd-dtrinity", "dTRINITY dUSD", "dUSD"],
  ["sdusd-dtrinity", "dTRINITY Staked dUSD", "sdUSD"],
  ["dusd-alto", "Alto DUSD", "DUSD"],
  ["ustb-superstate", "Invesco Short Duration US Government Securities Fund", "USTB"],
  ["ousg-ondo-finance", "Ondo OUSG", "OUSG"],
  ["slvon-ondo", "iShares Silver Trust (Ondo Tokenized)", "SLVon"],
  ["iauon-ondo", "iShares Gold Trust (Ondo Tokenized)", "IAUon"],
  ["mtbill-midas", "Midas mTBILL", "mTBILL"],
  ["mre7yield-midas", "Midas mRe7YIELD", "mRe7YIELD"],
  ["mf-one-midas", "Midas mF-ONE", "mF-ONE"],
  ["mglobal-midas-fasanara", "Midas Fasanara Global", "mGLOBAL"],
  ["mhyper-midas", "Midas mHYPER", "mHYPER"],
  ["mmev-midas", "Midas mMEV", "mMEV"],
  ["mapollo-midas", "Midas mAPOLLO", "mAPOLLO"],
  ["safo-spiko-usd", "Spiko Amundi Overnight Swap Fund", "SAFO"],
  ["spkcc-spiko", "Spiko Digital Assets Cash & Carry Fund", "SPKCC"],
  ["eursafo-spiko", "Spiko Amundi Overnight Swap Fund (EUR)", "EURSAFO"],
  ["eurspkcc-spiko", "Spiko Digital Assets Cash & Carry Fund - Euro Share Class", "EURSPKCC"],
  ["uktbl-spiko", "Spiko UK T-Bills Money Market Fund", "UKTBL"],
  ["gbpsafo-spiko", "Spiko Amundi Overnight Swap Fund (GBP)", "GBPSAFO"],
  ["jtrsy-anemoy", "Janus Henderson Anemoy Treasury Fund", "JTRSY"],
  ["ustbl-spiko", "Spiko US T-Bills Money Market Fund", "USTBL"],
  ["bib01-backed", "Backed IB01 Treasury Bond 0-1yr", "bIB01"],
  ["thbill-theo", "Theo thBILL", "thBILL"],
  ["rusd-reservoir", "Reservoir rUSD", "rUSD"],
  ["wsrusd-reservoir", "Wrapped Savings rUSD", "wsrUSD"],
  ["srusd-reservoir", "Savings rUSD", "srUSD"],
  ["usdp-parallel", "Parallel USDp", "USDp"],
  ["xsgd-straitsx", "StraitsX XSGD", "XSGD"],
  ["gyen-gyen", "GYEN", "GYEN", "frozen", "2026-07-08"],
  ["audd-novatti", "AUDD", "AUDD"],
  ["jpyc-jpyc", "JPY Coin", "JPYC"],
  ["jpyc-jpyc-v1", "JPY Coin v1", "JPYC", "frozen", "2026-07-11"],
  ["axcnh-anchorx", "AxCNH", "AxCNH"],
  ["idrt-rupiah-token", "Rupiah Token", "IDRT"],
  ["audm-macropod", "Macropod", "AUDM"],
  ["kgst-kyrgyz-som", "Kyrgyz Som Stablecoin", "KGST"],
  ["audf-forte", "Forte AUD", "AUDF"],
  ["tryb-bilira", "BiLira", "TRYB"],
  ["xaut-tether", "Tether Gold", "XAUT"],
  ["xnk-kinka", "Kinka", "XNK"],
  ["paxg-paxos", "PAX Gold", "PAXG"],
  ["gldy-streamex", "Streamex Gold Yield", "GLDY"],
  ["kau-kinesis", "Kinesis Gold", "KAU"],
  ["xaum-matrixdock", "Matrixdock Gold", "XAUm"],
  ["xagm-matrixdock", "Matrixdock Silver", "XAGm"],
  ["vnxau-vnx", "VNX Gold", "VNXAU"],
  ["gramg-token-teknoloji", "Gram Gold", "GRAMG"],
  ["grams-token-teknoloji", "Gram Silver", "GRAMS"],
  ["cgo-comtech", "Comtech Gold", "CGO"],
  ["dgld-gold-token-sa", "DGLD Tokenized Gold", "DGLD"],
  ["pgold-pleasing", "Pleasing Gold", "PGOLD"],
  ["ggbr-goldfish-gold", "Goldfish Gold", "GGBR"],
  ["gldt-gold-dao", "Gold Token", "GLDT"],
  ["kag-kinesis", "Kinesis Silver", "KAG"],
  ["ceur-celo", "Mento Euro", "EURm"],
  ["euroe-membrane", "EUROe", "EUROe", "frozen", "2026-05-15"],
  ["eutbl-spiko", "Spiko EU T-Bills Money Market Fund", "EUTBL"],
  ["bc3m-backed", "Backed GOVIES 0-6 months EURO investment grade", "bC3M"],
  ["gbpm-mento", "Mento British Pound", "GBPm"],
  ["gbpe-monerium", "Monerium GBP emoney", "GBPe"],
  ["jpym-mento", "Mento Japanese Yen", "JPYm"],
  ["chfm-mento", "Mento Swiss Franc", "CHFm"],
  ["brlm-mento", "Mento Brazilian Real", "BRLm"],
  ["phpm-mento", "Mento Philippine Peso", "PHPm"],
  ["kesm-mento", "Mento Kenyan Shilling", "KESm"],
  ["copm-mento", "Mento Colombian Peso", "COPm"],
  ["cadm-mento", "Mento Canadian Dollar", "CADm"],
  ["audm-mento", "Mento Australian Dollar", "AUDm"],
  ["ghsm-mento", "Mento Ghanaian Cedi", "GHSm"],
  ["zarm-mento", "Mento South African Rand", "ZARm"],
  ["veur-vnx", "VNX EURO", "VEUR"],
  ["eurr-stablr", "StablR Euro", "EURR", "frozen", "2026-05-24"],
  ["europ-schuman", "Schuman EUROP", "EUROP"],
  ["eurq-quantoz", "Quantoz EURQ", "EURQ"],
  ["eurau-allunity", "AllUnity EUR", "EURAU"],
  ["deuro-deuro", "Decentralized Euro", "DEURO"],
  ["audx-aussie-dollar-token", "Aussie Dollar Token", "AUDX"],
  ["chfau-allunity", "AllUnity CHF", "CHFAU"],
  ["vchf-vnx", "VNX Swiss Franc", "VCHF"],
  ["vgbp-vnx", "VNX British Pound", "VGBP"],
  ["tgbp-tokenised", "Tokenised GBP", "tGBP"],
  ["zarp-zarp", "ZARP Stablecoin", "ZARP"],
  ["isc-international-stable-currency", "International Stable Currency", "ISC"],
  ["cadc-cad-coin", "CAD Coin", "CADC"],
  ["qcad-stablecorp", "Stablecorp QCAD", "QCAD"],
  ["cadd-cad-digital", "CAD Digital", "CADD"],
  ["pht-pht", "PHT Stablecoin", "PHT"],
  ["cetes-etherfuse", "Etherfuse CETES", "CETES"],
  ["syrupusdc-maple", "Maple syrupUSDC", "syrupUSDC"],
  ["syrupusdt-maple", "Maple syrupUSDT", "syrupUSDT"],
  ["yousd-yield-optimizer", "Yield Optimizer USD", "yoUSD"],
  ["inalpha-nest", "Nest Alpha Vault LP", "inALPHA"],
  ["ntbill-nest", "Nest Treasury Vault", "nTBILL"],
  ["nbasis-nest", "Nest Basis Vault", "nBASIS"],
  ["nopal-nest", "Nest BlackOpal LiquidStone II Vault", "nOPAL"],
  ["nwisdom-nest", "Nest Wisdom Vault", "nWISDOM"],
  ["eusd-telcoin", "eUSD", "eUSD"],
  ["fusd-freedom-dollar", "Freedom Dollar", "FUSD"],
  ["fusd-finchain", "FinChain Dollar", "FUSD"],
  ["zsd-zephyr-protocol", "Zephyr Stable Dollar", "ZSD"],
  ["zys-zephyr-protocol", "Zephyr Yield Share", "ZYS"],
  ["autousd-auto-finance", "Auto Finance autoUSD", "autoUSD"],
  ["eearn-ember", "Ember Earn", "eEARN"],
  ["yusd-yieldfi", "YieldFi yUSD", "YUSD"],
  ["spusd-soulpeg", "SoulPeg USD", "spUSD"],
  ["uusd-anything-labs", "Unity USD", "UUSD"],
  ["jusd-jusd-stable-token", "JUSD", "JUSD"],
  ["jusd-juicedollar", "Juice Dollar", "JUSD"],
  ["usda-alpha-partner", "Alpha Partner USDA", "USDA"],
  ["aid-gaib", "GAIB AID", "AID"],
  ["said-gaib", "GAIB sAID", "sAID"],
  ["apxusd-apyx", "apxUSD", "apxUSD"],
  ["apyusd-apyx", "apyUSD", "apyUSD"],
  ["nxusd-nereus", "NXUSD", "NXUSD"],
  ["nusd-nexus", "Nexus USD", "NUSD"],
  ["stusd-stoneyield", "StoneYield USD", "stUSD"],
  ["vusd-virtue", "Virtue USD", "VUSD"],
  ["lvusd-leverup", "LeverUp USD", "lvUSD"],
  ["xmd-metal-dollar", "Metal Dollar", "XMD"],
  ["hlusd-hela", "HeLa USD", "HLUSD"],
  ["usx-dforce", "dForce USD", "USX"],
  ["susd-solayer", "Solayer USD", "sUSD"],
  ["home-homecoin", "HomeCoin", "HOME"],
  ["usdx-kava", "USDX", "USDX"],
  ["usd3-reserve-protocol", "Web 3 Dollar", "USD3"],
  ["money-defi-money", "defi.money", "MONEY"],
  ["cdxusd-cod3x", "Cod3x USD", "cdxUSD"],
  ["cdp-enosys", "Enosys Loans CDP", "CDP"],
  ["vcred-vcred", "vCred", "vCRED"],
  ["susd-hedgecore", "Staked USD Coin", "sUSD"],
  ["iusd-indigo-protocol", "Indigo iUSD", "iUSD"],
  ["luausd-lumi-finance", "Lumi Finance LUAUSD", "LUAUSD"],
  ["xtusd-xt", "XTUSD", "XTUSD"],
  ["wemix-dollar-wemix", "WEMIX Dollar", "WEMIX$", "frozen", "2026-07-11"],
  ["usdglo-glo", "Glo Dollar", "USDGLO"],
  ["djed-coti", "Djed Stablecoin", "DJED"],
  ["pathusd-bridge", "PathUSD", "pathUSD"],
  ["xai-silo-finance", "XAI Silo Finance", "XAI"],
  ["usp-pareto-credit", "Pareto USP", "USP"],
  ["fxd-fathom", "Fathom Dollar", "FXD"],
  ["usdv-solomon", "Solomon USDv", "USDV"],
  ["ussd-sonic-labs", "US Sonic Dollar", "USSD"],
  ["usdpt-western-union", "US Dollar Payment Token", "USDPT"],
  ["roughrider-bnd", "Roughrider Coin", "ROUGHRIDER", "pre-launch"],
  ["fiusd-fiserv", "Fiserv USD", "FIUSD", "pre-launch"],
  ["eur-qivalis", "Qivalis Euro", "QEUR", "pre-launch"],
  ["pusd-polaris", "Polaris USD", "pUSD", "pre-launch"],
  ["pgold-polaris", "Polaris Gold", "pGOLD", "pre-launch"],
  ["usg-tangent", "Tangent USD", "USG"],
  ["klarnausd-klarna", "KlarnaUSD", "KLARNAUSD", "pre-launch"],
  ["ftusd-flying-tulip", "Flying Tulip USD", "ftUSD"],
  ["bd-basedollar", "Base Dollar", "BD", "pre-launch"],
  ["brla-brla-digital", "BRLA Digital", "BRLA"],
  ["silk-shade-protocol", "SILK", "SILK"],
  ["idrx-idrx", "IDRX", "IDRX"],
  ["cngn-compliant-naira", "Compliant Naira", "cNGN"],
  ["mxnb-juno", "MXNB", "MXNB"],
  ["mmxn-moneta-digital", "Moneta Digital", "MMXN", "pre-launch"],
  ["brl1-brl1", "BRL1", "BRL1"],
  ["wars-argentine-peso", "Argentine Peso", "WARS"],
  ["wbrl-ripio", "Ripio wBRL", "WBRL"],
  ["wclp-ripio", "Ripio wCLP", "WCLP"],
  ["wcop-ripio", "Ripio wCOP", "WCOP"],
  ["wpen-ripio", "Ripio wPEN", "WPEN"],
  ["cjpy-yamato", "Convertible JPY Token", "CJPY"],
  ["trusd-tori", "Tori trUSD", "trUSD", "pre-launch"],
  ["buck-buck-assets", "Buck", "BUCK", "frozen", "2026-04-30"],
  ["rgbp-revolut", "Revolut GBP Stablecoin", "RGBP", "pre-launch"],
  ["jpysc-sbi-startale", "JPYSC", "JPYSC", "pre-launch"],
  ["myrc-blox", "MYRC", "MYRC"],
  ["vndc-jade-labs", "VNDC", "VNDC"],
  ["krwq-iq", "KRWQ", "KRWQ"],
  ["eur0-usual", "Usual EUR", "EUR0"],
  ["emxn-telcoin", "Telcoin MXN", "eMXN"],
  ["hchf-hedera-swiss-franc", "Hedera Swiss Franc", "HCHF"],
  ["eurot-token-teknoloji", "Euro Token", "EUROT"],
  ["mxne-real-mxn", "Real MXN", "MXNe"],
  ["jpyt-dephaser", "Dephaser JPY", "JPYT"],
  ["wmxn-ripio", "Ripio wMXN", "WMXN"],
  ["xofm-mento", "Mento West African CFA Franc", "XOFm"],
  ["euro3-3a-dao", "EURO3", "EURO3"],
  ["krwo-gimswap", "KRWO", "KRWO"],
  ["usdb-bridge", "Bridge USDB", "USDB", "pre-launch"],
  ["hkdap-anchorpoint", "HKDAP", "HKDAP", "pre-launch"],
  ["hkd-hsbc", "HSBC HKD Stablecoin", "HKD-HSBC", "pre-launch"],
  ["okrw-hashed", "OKRW", "OKRW", "pre-launch"],
  ["arc-anq", "ARC", "ARC", "pre-launch"],
  ["brl-b3", "B3 BRL Stablecoin", "BRL-B3", "pre-launch"],
  ["usdf-flipcash", "Flipcash USDF", "USDF", "pre-launch"],
  ["hkdr-rd-technologies", "RD Technologies HKDR", "HKDR", "pre-launch"],
  ["brd-volpon", "BRD Stablecoin", "BRD", "pre-launch"],
  ["krw1-bdacs", "BDACS KRW1", "KRW1", "pre-launch"],
  ["rusd-revolut", "Revolut USD Stablecoin", "RUSD", "pre-launch"],
  ["brl-itau", "Itau Unibanco BRL Stablecoin", "BRL-ITAU", "pre-launch"],
  ["usd-nubank", "Nubank USD Stablecoin", "USD-NU", "pre-launch"],
  ["krw-imbank", "iM Bank KRW Stablecoin", "KRW-iM", "pre-launch"],
  ["sofid-sofi", "SoFiUSD", "SOFID"],
  ["onyc-onre", "Onchain Yield Coin", "ONyc"],
  ["hbusdt-hyperbeat", "Hyperbeat USDT", "hbUSDT"],
  ["usdm-monetrix", "Monetrix USD", "USDM"],
  ["witry-brix", "Wrapped iTRY", "wiTRY"],
  ["scusd-rings", "Rings scUSD", "scUSD"],
  ["weusd-picwe", "WEUSD", "WEUSD"],
  ["iusd-initia", "Initia iUSD", "iUSD"],
  ["usdxl-last", "Last USD", "USDXL"],
  ["dusd-fluid", "Fluid DigitalDollar", "DUSD"],
  ["bnusd-balanced", "Balanced Dollar", "BNUSD"],
  ["usdcx-movement", "Movement USDCx", "USDCx"],
  ["ist-agoric", "Inter Stable Token", "IST", "frozen", "2025-06-26"],
  ["usdh-hubble", "Hubble USDH", "USDH"],
  ["zkusd-goal3", "zkUSD Dollar", "zkUSD"],
  ["gynusd-gyndore", "Gyndore", "gynUSD", "pre-launch"],
  ["gelt-tether", "Tether Georgian Lari Stablecoin", "GEL₮", "pre-launch"],
  ["tgld-tenbin", "Tenbin Gold", "tGLD", "pre-launch"],
  ["ejpy-jbfd", "EJPY", "EJPY", "pre-launch"],
  ["aed-rakbank", "RAKBank AED Stablecoin", "AED-RAKBANK", "pre-launch"],
  ["bils-bitsofgold", "BILS", "BILS", "pre-launch"],
  ["kusd-kerne", "Kerne USD", "kUSD", "pre-launch"],
  ["ousd-open-standard", "Open USD", "OUSD", "pre-launch"],
] as const satisfies readonly CommandPaletteStablecoinSearchItem[];
