export type MethodologySectionContent = {
  id: string;
  title: string;
  markdown: string;
  markdownParagraphs: readonly string[];
};

function defineMethodologySectionContent({
  id,
  title,
  markdownParagraphs,
}: {
  id: string;
  title: string;
  markdownParagraphs: readonly string[];
}): MethodologySectionContent {
  return {
    id,
    title,
    markdownParagraphs,
    markdown: [`## ${title}`, ...markdownParagraphs].join("\n\n") + "\n",
  };
}

export const LIFECYCLE_PHASES_SECTION_CONTENT = defineMethodologySectionContent({
  id: "lifecycle-phases-methodology",
  title: "Stablecoin Lifecycle Phases",
  markdownParagraphs: [
    "Every tracked stablecoin sits in one of five lifecycle phases: active, pre-launch, quarantined, delisted, or frozen. The phase controls which surfaces ingest, score, and display the coin. It is a data-collection lifecycle policy, not a scoring methodology — per-domain version constants (Safety Scores, Liquidity, PegScore + DEWS, PSI, Yield, Mint/Burn Flow, Pricing Pipeline, Blacklist Tracker, Chain Health) are unaffected when a coin transitions between phases.",
    "Active coins receive full data collection and contribute according to listing class. Pre-launch coins have dedicated upcoming profiles but no live data. Quarantined records are temporarily withheld after a reviewed lack of positive supply or market-cap coverage; delisted records failed listing scope. Both retain static profiles without new provider collection. Frozen coins retain historical archive data in the cemetery. Missing price coverage and genuine depegs remain active monitoring problems rather than reasons to hide an asset through lifecycle state.",
  ],
});

export const PRICING_PIPELINE_SECTION_CONTENT = defineMethodologySectionContent({
  id: "pricing-pipeline-methodology",
  title: "Pricing Pipeline Methodology",
  markdownParagraphs: [
    "Every score Pharos computes starts with a price. The pricing pipeline collects live quotes from aggregators, exchanges, oracles, on-chain pools, protocol redemption feeds, FX references, and enrichment fallbacks.",
    "Pharos clusters sources by pairwise agreement, publishes the highest-confidence median, and keeps source provenance attached so downstream depeg, safety, liquidity, and PSI calculations can reason about data quality. Soft consensus can be challenged by large DEX pools; challenger snapshots retain qualifying protocol diversity before applying their TVL coverage cap so a dominant venue cannot hide a smaller independent corroborator. Challenger and DEX-bridge pools are admitted only after that pair-price coherence check — the tracked leg's USD price must agree with the pool's own pair ratio × the counter-leg's USD price — and a DEX price row with no usable primary to anchor its deviation and outlier guards is withheld rather than published. Protocol redemption prices override market data only for assets where the redemption path is the more authoritative mark.",
    "Freshness is explicit. Upstream-observed timestamps are preferred over local collection time, stale sources are excluded or downgraded, and replay-safe cache continuity is used only when it preserves a confirmed signal without inventing a new one.",
    "Fallback enrichment is bounded. CoinMarketCap, Jupiter, DexScreener, audited low-volume CoinGecko rows, exact-address providers, and reviewed protocol or exact-pool routes fill gaps for long-tail assets, but each pass has request budgets, identity checks, circuit breakers, freshness and depth requirements, corroboration checks, and plausibility gates so weak prices cannot silently become high-confidence consensus or false fixed-peg depegs. Persistent active-price gaps are scheduled ahead of breadth-oriented refresh work, exact-address fairness cursors rotate only inside priority cohorts, and eligible exact reviewed CoinGecko Onchain overrides reserve one bounded network request before ordinary network round-robin. DexScreener single-token discovery uses its complete pool-list endpoint while multi-address pricing keeps the separate batch-token endpoint. Exact reviewed pool identities take precedence over lower-fidelity derived duplicates so executable quote evidence stays attached to the physical pool. Thin executable routes can be admitted with fallback confidence for display when they pass the same severe-downside and temporal-jump corroboration guardrails as other soft sources, while remaining ineligible to drive depeg state or replay-safe cache continuity by themselves. AZND guard rejections stay explicit coverage gaps without counting as provider outages, while thrown or timed-out route work still fails its circuit.",
    "Price coverage is evaluated independently from row publication. A stablecoin can remain visible with supply and lifecycle data while its unusable price degrades cron and public health; the incident remains explicit instead of blocking the full cache or being hidden behind a nominal peg fill.",
  ],
});

export const STABILITY_INDEX_SECTION_CONTENT = defineMethodologySectionContent({
  id: "stability-index-methodology",
  title: "Stability Index Methodology",
  markdownParagraphs: [
    "The Pharos Stability Index (PSI) compresses stress across active core stablecoins and cash equivalents into a 0-100 condition score. Tracked variants and stable-value investments stay browsable but are excluded from the monetary aggregate. PSI starts at 100, subtracts penalties for severity, breadth, and stress breadth, then adds a clamped trend term before mapping the result into condition bands from BEDROCK to MELTDOWN.",
    "Severity captures how bad current deviations are. Breadth captures how many assets are involved. Stress breadth captures how many stablecoins are elevated in DEWS. Trend captures whether the system is getting better or worse over the current window: negative trend reduces the score, while positive trend can offset part of the penalty.",
    "PSI is deliberately conservative: one small depeg should not move the entire market condition, but simultaneous broad stress should pull the index down even if no single coin dominates the tape.",
  ],
});

export const SAFETY_SCORES_SECTION_CONTENT = defineMethodologySectionContent({
  id: "safety-scores-methodology",
  title: "Safety Scores Grading Methodology",
  markdownParagraphs: [
    "Safety Score V10 evaluates Backing, Exit and Economic Control, normally weighted 40%, 35% and 25%. It allows only bounded headroom above the weakest included pillar: a strong unrelated pillar cannot erase a known weak path. v10.01 stops treating our missing measurements as asset risk. Known peg problems, structural constraints, dependency limits and track record still matter; missing-data ceilings do not.",
    "Exit compares every admissible route alone and every independently usable pair, then takes the best feasible portfolio. The stronger member is primary; its backup adds min(10, 100 − primary score) × backup score / 100. An improving correlated alternative cannot displace a better independent pair. Capacity, output, fees, access, settlement and shared-resource checks still apply. Cards show selected routes, backup credit and stress-request completion separately; standalone route scores are not the Safety Score Exit pillar.",
    "Since methodology 9.44, a fully observed issuer or protocol route with zero or immaterial executable capacity remains the attributable primary evidence and scores zero instead of being discarded as unsupported. Its capacity, completion, confidence, and binding cap remain visible, and a zero Exit pillar states that no viable exit path was measured. Atomic protocol routes follow their reviewed settlement fact rather than being treated as inherently delayed.",
    "Faster settlement needs a reviewed delay and source. A route with unproven same-notional capacity, cost or settlement stays visible but receives no invented executable or backup credit. Genuine unresearched or undisclosed whole-exit uncertainty remains bounded at 35 where the policy permits it, not measured zero and not an Exit-wide ceiling. Proven pipeline or curation gaps are excluded rather than charged. The bounded floor is applied after portfolio selection; evidence explanations do not switch on or off when the floor binds. Measured exhaustion still needs complete admitted evidence.",
    "We classify why evidence is missing: A, our pipeline was unavailable; B, the required current data is public but we have not curated it; C, research found the issuer does not disclose it; U, not yet researched; D, a measured adverse fact. A/B exclusion needs proof for that asset and question, not just a missing value. U is never labelled issuer silence. Unknown values do not prove safety, failure or zero loss.",
    "Proven A/B components do not score and carry a visible Partial evidence: pipeline gap flag. If one whole pillar is excluded, the other two weights are renormalized. If two or three are excluded, we show Pipeline gap with no score or grade—not NR and not a one-pillar rating. Known restrictions and measured problems remain charged even beside a gap. Measuring a formerly excluded weak pillar can lower a partial rating because coverage has changed.",
    "For C/U, quality credit is no lower than before v10.01 and no lower than the weakest comparable ordinary disclosed rung; existing uncertainty charges and discounts remain. This does not guarantee every disclosure raises a score: cost, holder, topology, some route defaults and wrapper charges retain explicit exceptions where a genuinely weaker measurement scores lower. There are no missing-data whole-score ceilings. Evidence-based NR counts U as C. A pillar must still be limited by its pre-v10.01 evidence predicate after A/B relief and have a real compiled witness; a newly tagged bounded component alone does not qualify. A computed F without measured adversity is still withheld, explained as Score below the F threshold without a measured adverse fact.",
    "Exit shows observation, model and capacity-method confidence separately. Positive method identity maps to its tier: live-direct is 1 and same-run verified live queue/proxy is 0.75. Known queue delays and liquidity limits still count. A proven-empty, reconciled route surface is measured adverse D, not an unknown gap. A confidence gap caused by our pipeline or curation does not discount the asset, but this never makes stale capacity current or admits an invalid execution certificate. Issuer/unresearched uncertainty and genuinely weaker models still apply. Unknown holder terms are not verified eligibility; an unevaluated public fee formula is not a zero fee. Wrapper A/B gaps do not trigger form fallback charges; C/U eligibility follows cause, not a legacy disposition label. Allocation reviews resolve U custody/reuse, while other eligible local gaps keep existing charges and no missing proof grants risk-transfer credit.",
    "Live reserve percentages are scoring weights, not identities. A namespace-qualified stable source key joins an adapter-owned reserve category to reviewed classification and dependency metadata across rebalancing or label changes. Explicit keys must match uniquely and otherwise fail closed; historical unkeyed captures retain a unique normalized-name compatibility join.",
    "Classification research lasts 365 days; composition has its own clock. Named-firm attestations, audits and examinations can be admitted for 120 days inclusive from the report's as-of date, at their actual assurance strength. A named attestation is not promoted to an audit. Scope, chronology, source and fingerprint checks remain strict; unnamed generic curated composition keeps the 31-day window plus 7-day grace. Neither a later review nor publication refreshes old holdings.",
    "We keep independently identified reserve holdings instead of rejecting an entire reviewed composition because an unclassified tail exceeds 0.1%. Each remaining share carries its own cause. Researched or unresearched uncertainty is bounded; measured adverse holdings keep their measured treatment; proven pipeline or curation gaps receive no scoring weight. Original whole-asset shares and unknown tails remain visible—only scoring weights can be renormalized. Exposure and dependency shares are never rescaled to pretend the book is complete, and a defensible whole-book denominator is still required. Inherited parent Backing replaces only unknown local defaults: known local class, liquidity and source strength still bound it, with missing factors at their best ordinary rungs. An empty issuer/obligor census scores concentration at bounded-unknown 35, not diversified 98. A missing obligor affects only concentration, never a reserve row's class quality.",
    "Since methodology 9.31, curated collateral links share the reserve-envelope admission gate. When no live reserve slices exist and the curated composition is stale or otherwise inadmissible, the dependency overlay publishes no curated basket edges; the existing reserve-envelope gap carries the bounded consequence instead of an unrelated unreviewed-dependency reason. Admissible curated reviews, live-derived edges, and manual dependency reviews remain unchanged.",
    "Since methodology 9.49, variant parents, explicit wrapped-asset claims, and manual non-collateral relationships survive independently of reserve composition. The 9.48 no-revival rule remains in force for reserve weights: unmapped live reserves cannot restore older curated or manual collateral weights. Dependency facts retain per-slice rejection reasons for unmatched identities, expired matching classifications, and explicitly reviewed non-links. Curated reserve fallback applies only when no live composition exists; partial live mappings retain their live weights.",
    "Responsibility follows validated evidence about the exact missing question, not the nearest processing stage or a compiler's default label. A pipeline verdict binds the captured source and generation. Public-but-uncurated and researched-undisclosed classifications retain dated primary sources; otherwise the question is Not yet researched. Inherited gaps preserve their originating causes and evidence identities. Every attributed root receives a causal-root-qualified score path, so adding another root cannot rename an existing public fact; ownership never becomes part of fact identity. A reviewed unpriced output is not automatically a pipeline failure: the missing valuation needs its own cause proof, and never becomes assumed par proceeds. Date-only dispositions enter replay only after their reviewed UTC day. Partial control reviews retain reviewed controls without fabricated deployment shares. Unsupported coverage needs captured reader-boundary proof for A exclusion; otherwise the unresolved question remains U. Populated DEX exit surfaces retain their budgeted gap accounting and strict exact-route completeness. Missing current price is separate from measured adverse peg history and never becomes zero deviation.",
    "A current established circulating amount can size the Exit stress request even when its chain or bridge partition is unresolved. This sizes the request only: it does not invent bridge shares, transfer scope, control safety or executable capacity. Unknown, stale or unavailable amounts still cannot size it. Route valuation, cost, access and settlement admission remain; missing bridge evidence now follows the cause-aware rules rather than a generic missing-data ceiling.",
    "Since methodology 9.94, the XAUT lock/mint group attribution reconciles Tether's daily disclosure to finalized Ethereum state on the circulating liability alone: total supply minus the treasury balance must equal the disclosed authorized minus not-issued amount. Unissued treasury inventory is not a liability, so a treasury-only mint or burn after the disclosure changes both terms equally and no longer rejects the attribution. A circulating mismatch, a treasury balance above total supply, non-zero quarantined supply, and every identity, freshness, and finalized-block check still fail closed. The trigger was a 119,670.541 XAUT treasury mint at 17:08:47 UTC on 2026-09-28 that dropped XAUT from 78 B+ to 48 D although circulating supply reconciled exactly.",
    "Since methodology 9.93, a chain whose supply row several reviewed profile routes compete for no longer blocks the bridge review when that row is immaterial. The unsplit chain row is an upper bound on every candidate deployment's share, so a row below both the deployment-material and common-mode thresholds, on a chain whose candidate routes are all reviewed, is accepted as bounded supply evidence; a material ambiguous row, or one with any unreviewed candidate route, still fails closed, and shares are never summed across rows. The null-share deployment bound now includes that unsplit chain row instead of reading the unavailable within-chain share as zero. The trigger was USDC's reviewed native X Layer deployment beside its reviewed third-party X Layer representation, which made the single X Layer chain row (about 0.02% of supply) ambiguous and capped USDC at 55, and every USDC wrapper through the parent cap.",
    "Since methodology 9.92, an asset whose intake publishes only an aggregate circulating quantity and no per-chain rows no longer bounds that quantity on a bridge gap the control pillar already owns: there is no per-chain partition for the bridge-materiality join to be ambiguous about, the state is diagnosed as supply-review.unpartitioned-aggregate, and the circulating USD publishes as known so the exit pillar can size a stress request. Bridge-materiality availability keeps its single owner on the control pillar (runtime-bridge-materiality-unavailable), while a join that ran and failed over real rows, a missing bridge profile, stale input, and a missing or rejected runtime attribution packet all still fail closed. The same release attributes a gapless missing-same-notional-route — a route the method withholds by design with no authored producer gap — to integration-missing instead of producer-failed; scores, ceilings, and NR treatment are unchanged.",
    "Since methodology 9.47, a dependent's exposure to an upstream with an open reserve gap counts once per upstream cause: the backing projection folds the slice-level reasons an upstream raises into one reason per projected code, source code, and owner on each dependent exposure, and the slice paths survive in the causal key. An upstream on the audited fallback with nine stale reserve slices previously put 18 bounded-unknown-reserve-exposure facts on every direct holder. On replay of capture-20260907-0917.json at clock 1788772631, open data points fell 1,280 -> 733 (published-evidence-expired 602 -> 58, issuer-undisclosed 354 -> 351), 30 assets changed fact counts, 0 scores moved, 0 grades flipped. No evidence was added.",
    "Since methodology 9.461, two evaluator mapping defects are corrected without adding evidence. Reviewed-native selected supply rows no longer enter the bridge-exposure completeness join: evaluateV9SubthresholdUnresolvedBridgeJoins excludes them from bridgeControlsByDeployment, while the route predicate and native-liability boundary keep native controls as umbrella facts and exclude native route ids from bridgeClaimControls. On replay of capture-20260904-1100.json at clock 1788509806, this corrected a wrong join and closed 9 facts (nonmaterial-bridge-supply-unmatched on ausd-agora, pyusd-paypal, reusd-re-protocol, usbd-bima, fusd-finchain, cusd-celo, frxusd-frax, usdy-ondo-finance, plus missing-bridge-route-rows on fusd-finchain), with 0 replacements and exactly 1 mover: fusd-finchain NR -> 46/D. Floors, the completeness predicate, and unknownBridgeShare are unchanged; Pharos learned nothing new.",
    "The same 9.461 replay corrects a second evaluator defect: offchain-issuer commodity routes whose outputAssetType is bluechip-collateral (physical GOLD/SILVER delivery) now resolve as unresolved-asset rather than fiat. Removing the synthetic $1 physical-bar valuation ADDED 5 facts (unresolved-exit-output and missing-runtime-route-evidence on gldt-gold-dao, paxg-paxos, xnk-kinka) and moved 2 grades: gldt-gold-dao 47/D -> NR and xnk-kinka 41/D -> 39/F. This is an honest loss of false coverage, not newly learned adverse evidence. The affected asset set is cgo-comtech, dgld-gold-token-sa, ggbr-goldfish-gold, gldt-gold-dao, gldy-streamex, kag-kinesis, kau-kinesis, paxg-paxos, pgold-pleasing, xagm-matrixdock, xaum-matrixdock, xaut-tether, xnk-kinka. Producer-side repairs in these waves cannot manifest until a real producer cycle runs.",
    "Expired evidence stays dated history. Expiry is not proof the issuer is silent, nor that newer required data is public. Current cause proof decides whether the gap is pipeline, uncurated public data, researched non-disclosure or not yet researched. Known active adverse facts are not cleared by an expired positive review, and favorable parent inheritance still needs current whole-allocation proof.",
    "Shared-control pricing uses each receiving asset's own member facts. Admitted adverse reach/domain evidence remains charged; unknown member quality alone cannot manufacture D or a shared-failure signal. Missing/stale/unresolved members carry scoped causes, and no gap establishes high confidence or clears a known adverse path.",
    "Since methodology 9.25 the published primary-exit posture is derived from every route the Exit pillar credits, not only from routes that clear the strict score-eligibility bar. Reviewed issuer, protocol, and eventual redemption routes carry economic weight in Exit, so a posture that ignored them could report no exit for an asset whose Exit score rested on one. The posture now separates three kinds of absence rather than collapsing them onto the negative: a reviewed exit surface observed complete with zero routes reports none, an unobserved surface or one whose credited routes resolve no access fact reports undisclosed, and credited routes with unresolved access facts report unknown. Undisclosed is published as an explicit not-disclosed state instead of being dropped, because an evidence gap must not read as a clean result. The posture change itself moves no score: pillar weights, score math, grade thresholds, and every published score and grade are unchanged by it. "
      + "The same release corrects the mirror-image defect in Economic Control, where a missing reserve-reconciliation cadence was read as evidence of a periodic one because the sentinel values are non-empty strings. "
      + "An issuer that publishes no reconciliation is now graded unknown rather than periodic, which withholds a rating from two assets and lowers a third; a reviewed reconciliation still supersedes the inference, so the gap is closable by curation.",
    "Governance access posture treats reviewed global mint-domain contracts as immutable when they have no privileged capabilities, no applicable cap, no claim-impairment path, and access-only scope. A contract address alone is protocol machinery, not evidence of a concentrated administrator; deployment-scoped bridge controls remain separate.",
    "Methodology 9.4 applies the current oracle-applicability distinction to stale pre-9.17 reviews: the absence of borrower liquidation branches does not make a top-level mint, redemption, NAV, or exchange-rate authority non-applicable. Verified adverse oracle evidence remains measured adverse, unresolved applicability remains bounded, and a genuinely price-insensitive mechanism remains neutral.",
    "Control scope follows the liabilities an admitted control can reach. Known deployment-local controls need a complete reconciled supply partition for proportional pricing; no gap creates deployment shares or proves native issuance. Proven A/B uncertainty is excluded and C/U stays component-bounded, without the former control-unverified whole-score ceiling. Known adverse/root-reaching controls keep their actual constraints. Common-control census still counts independent root liabilities, not extra wrapper copies. Chain maturity is a dated five-gate review requiring 36 months of continuous production history, a 365-day liveness record, permissionless participation or at least 21 independently operated block producers or finality members, no unilateral instant change path (with L2s at Stage 1 or later and at least a 7-day holder exit), and documented bridge or data-availability dependencies with a holder exit. Cardano, Gnosis, Hedera, Rootstock, Sui, Conflux, and Kaia are the seven newly admitted chains; Celo remains excluded.",
    "Reviewed incidents are routed into the control, wrapper-local, operational, or peg component that owns the risk, with root-claim, deployment, integration-only, or holder-exit scope. Active, mitigated, and resolved evidence therefore changes an existing component without creating a fourth pillar or charging an event beyond the affected liability.",
    "Publication remains fail-closed: global or invalid-identity state holds the last accepted publication. Attributable asset-local producer failures are technical pipeline gaps, never fabricated issuer NR or measured danger. Current consumers use the accepted publication and status, not a fallback scorer. V8.17 remains documented as historical methodology.",
  ],
});

export const DEPENDENCY_EXPOSURE_SECTION_CONTENT = defineMethodologySectionContent({
  id: "dependency-exposure-methodology",
  title: "Dependency Exposure Lookup",
  markdownParagraphs: [
    "Exposure mode on the [Dependency Map](/dependency-map/?mode=exposure) finds coins linked to selected upstream assets through mapped collateral and wrapper relationships. Linked coins; not a loss forecast. It does not estimate losses or changes in Safety Scores.",
    "The lookup uses the full published edge set, regardless of Explore Focus, Type, Limit, or small-link visibility. Selected roots are listed separately and excluded from dependent counts and USD totals. Direct dependents are one link away; indirect dependents are reached through longer chains.",
    "Each root starts with a share of 100%. Basket relationships sum mapped weights multiplied by their upstream look-through shares. Serial relationships take the maximum upstream share, not a sum. When both channels apply, the lookup takes the larger of the serial maximum and the basket sum. Each dependent appears once across selected roots. A published shared backing book counts once in USD totals; direct and indirect totals can still include the same underlying value at several layers, so the headline states that overlap. These gross layer totals are not additive independent holdings.",
    "USD equals the mapped share multiplied by circulating USD at evaluation from the accepted publication. The result names its generation, methodology version, publication time, and supply clock, and labels held snapshots. It never silently substitutes current market cap. When evaluation supply was not published, USD remains unknown with the reason 'Supply at evaluation not published for this generation'. Unknown supply is not zero: the row remains visible and known-USD totals exclude its unavailable amount.",
    "Coverage is limited to published relationships and their measured or reviewed weights, which may differ from current composition. Unknown weights and cycles leave shares unresolved rather than guessed or clamped. Role dependencies are listed as 'Role dependencies (not drawn)'; 'Known, not in the scored graph' relationships are outside the lookup and totals. An absent coverage field means not published, not no gaps. Peg, liquidity, confidence, and other transmission channels are not modeled. No mapped downstream exposure found does not establish that other dependencies are absent.",
    "History examples are [case-study links](/learn/case-studies/), not runnable presets or a historical replay.",
    "Separate offline modeled scenarios are available in Exposure mode. An hourly Node workflow reuses the production Safety Score evaluator, including role dependencies, for up to 15 hubs ranked by mapped direct exposure USD from publication-bound supply and published dependencies, with shared backing books counted once. The three D1b shocks limit the root's downstream-consumed final score to 40, model a 1,000 bps one-day depeg with captured peg history and exit facts held fixed, or model mint-control compromise. Each selection shocks one root, not all selected roots together. Results name their source publication, artifact age, and two-hour freshness budget. Earlier-generation results are explicitly labelled; stale or unavailable results withhold modeled numbers. NR remains NR. Modeled with the production Safety Score evaluator; not a forecast. These artifacts do not change canonical cards, journals, publication identity, or scoring policy. Structural exposure lookup remains separate and adds no scoring override.",
  ],
});

export const MINT_AUTHORITY_SCORE_SECTION_CONTENT = defineMethodologySectionContent({
  id: "mint-authority-score",
  title: "Mint Authority Score",
  markdownParagraphs: [
    "Mint authority measures how much durable stablecoin supply can be created, authorized, or expanded on the canonical native-issuance deployment or deployments.",
    "Since methodology v9.1 it is graded once, by the Safety Score V9 Economic Control pillar. The mint component starts from a derived posture (cap semantics, claim impairment, reconciliation, supervision), then applies resolved-incident age decay, a key-custody penalty that MPC or HSM attestation waives, a multisig quorum ladder, and a small Safe module modifier.",
    "Representations and cross-chain machinery are assessed separately by Bridge Risk at deployment scope. A shared controller may appear in both domains for distinct powers, but a bridge capability never becomes global Mint Authority risk. Missing or unresolved review data returns NR and never implies safety.",
    "Since methodology 9.3 a derived none-resolved posture scores the mint component at 100: it states that no reviewed control can mint, authorize minting, or expand issuance on this component's scope, so no headroom is reserved above it. The motivating LUSD and BOLD case proves that absence outright on immutable, owner-renounced deployments. Oracle and bridge tier tables are independent calibrations and keep their existing values.",
    "Safety Score v10.03 adds D30 minority-veto issuance at quality 70 in the Governed band: complete fresh execution-scope evidence, a closed review, a fourteen-day public window, unilateral veto at most 2% of flash-resistant votes, sole governor rooting, an executable selector-complete veto path, and enumerable issuance are required. It ranks below graded reconciliation and above affirmative governance at 60; failed minority-veto profiles never fall back to affirmative-governed. Issuance remains economically unbounded, emits a low centralized-mint signal (cap 83), and stays in DDR's fragile and unbounded sets. Ordinary seasoning clips at 79 below the prudential 80 rung.",
    "D30-S adds certified formula-bound monetary-policy interest with a hard-coded annual-ppm rate cap and minority-replaceable changes delayed at least two days; these raiseable/bounded paths do not enter the fourteen-day admission window. Admitted issuers never inherit admission delay onto their own exercise paths. D30-R admits insolvency-gated restructure only with pinned whole-token equity at least twice the threshold and reachable certificate selector binding, excluding only certified disabled-reactivatable dependent paths from window/rooting. Every guarded controller needs an active veto path and the governor has no unbounded bypass. Unknown or reachable overrides and unreviewed monetary paths fail closed; typed authority/path bindings must close cross-control reactivation alternatives.",
    "Safety Score v10.05 adds D31 / rule H, unbounded-operationally-governed: quality 55, Governed band, moderate centralized-mint signal/cap 74, ordinary seasoning and final positive merged-credit ceiling 59. It ranks below D29 at 60 and D30 at 70 and stays economically unbounded, fragile and unbounded for DDR. Discretionary expansion and operational-envelope changes require public token governance; formula interest and activity-bound compensation can execute immediately within reviewed envelopes. Economically unbounded. No surplus floor or lifetime issuance budget is required.",
    "H0–H4 require complete fresh reviewed authorization/class/member reach and typed economic/authority closure; every discretionary and envelope-raise route bound to flash-resistant affirmative governance with 172800 public code/calldata-bound seconds; source-enforced genuine-principal interest and activity-bound keeper accounting; enumerable deduplicated whole-book native liabilities; and other-class/bounded-stock/freshness closure. Latent and stopped-reactivatable controls remain in scope. Actual operational exercise can be zero seconds; proposal age and private cooldown are not public notice. There is no permanent partial rung, and incomplete certificates never erase known adverse paths.",
    "Final H screens are effective annual growth at most 500000 ppm, keeper proportional coefficient at most 1000 ppm, fixed award at most 10 ppm of unique native supply, and funded repeat interval at least 3600 seconds. The aggregate screen reuses the 5% moderate-exposure threshold: ceil(compiled certified maximum annual growth ppm × 172800 / 31536000) + ceil(repeat reward supply ppm per 86400 seconds × 172800 / 86400) <= 50000 ppm. It replaces the former daily repeat ceiling, not with an absolute initial-liquidation daily cap. Initial rewards require debt-relative anti-farming and historical paid-fragment stock proof; repeat rewards require a source-enforced whole-book in-flight bound. Missing measurements deny; known above-screen bounds are diagnosed separately.",
    "The combined-exposure certificate has domain 0 < W <= T: W reuses the existing public-governance minUnavoidableDelaySec (172800 seconds), and T is operationalFlow.annualWindowSec (31536000 seconds). Policy loading rejects W > T; pure H admission independently denies an out-of-domain anchor with H3 / aggregate-flow-unproved. This adds no threshold or duplicate policy key.",
    "Bounded delegated stock qualifies for H only with a proved finite cap, every raise/reset/replacement requiring the public 172800-second governor route, and no fresh chosen-recipient issuance outside that stock. Downstream strategy/custody losses belong in Backing; external strategy-target closure is not an extra H Mint gate. A refillable flow bucket is not finite stock. DAI/USDS conversion, savings and wrappers cannot duplicate native supply, principal or compensation budgets.",
    "Uniform D32 applies to D29, D30 and H without grandfathering, using actual source-enforced unilateral route thresholds and exact controller-plus-residual reconciliation to pinned voting supply. A holder voting its OWN locked/escrowed tokens is admissible, even above threshold and with unknown beneficial affiliation, unless positively identified issuer/team/council-affiliated. Concentration is diagnostic. A key casting OTHER holders' votes or replacing their caster without on-chain token-holder approval is council control; needing those votes to pass alone denies. Nongovernance privileged/forced vote creation or delegation denies. Controllers unable to pass alone need no identification; no universal concentration cap applies.",
    "Class certificates compress reusable contract-type invariants without weakening exact runtime/proxy/implementation, immutable/storage, full census and member/path evidence. Typed authority/economic-provenance graphs replace signer-prose rooting and close every permission, upgrade, execution, reactivation and vote-operator alternative. Compiled assets retain one issuanceFacts object; native controls only reference it. Public breakdowns.control.issuanceSummary publishes compact governance/process metadata, actual versus discretionary clocks, concentration and grouped terminal/gate/class/field failures with whole-group counts and complete sparse controlRefs. At most three path/member/evidence exemplars per group are labelled sampled/non-exhaustive, with evidenceRefCount and at most three evidence refs. Group totals are not per-control counts; the UI reads the summary once, matches full control refs and never recalculates qualification. Full process objects are not repeated in component controlDetails.",
    "ZCHF D30-S remains separate from H: its minority-replaceable seven-day rate window and uint24 nominal annual-ppm maximum 16777215 are justified by minority correction plus D30-R closure, not H's 50% effective-growth envelope. Typed provenance and uniform D32 apply to both; veto-only monetary-policy paths cannot become H. O0 corrects GHO fixed configured-pool first hops and ordinary public payload timing to 345603 seconds, current versus legacy Sky LockstakeClipper Mom authority, and positive D3M suck/grab fee/donation accounting as matched paired debt rather than atomic heal or blanket loss replacement. GHO stays mint 25 (historical captured total 42/D); removing Council chosen-recipient mint, restricting it to genuinely reserve-backed issuance, or a finite aggregate token-governed budget triggers ordinary D29 review without promising a future rating.",
    "Since methodology 9.24 a reviewed absence is scored as the fact it is rather than as missing evidence. An inventory whose every reviewed route is native issuance is not bridge-exposed, even where structured controls govern those canonical deployments; a reviewed representation route keeps Bridge Risk applicable regardless. A bridge review with an incomplete materiality picture keeps the routes it did review when the supply it could not attribute is immaterial, and still fails closed when that residual is material or unmeasured. A reviewed no-local-issuance exception scores the mint component as none-resolved only when the displaced risk is carried elsewhere: an inherited claim must compile a serial-claim edge to its parent, and an external-only representation must carry a reviewed route inventory covering every authored deployment. Absence is never inferred, and any authored control keeps the mint review in force.",
  ],
});

export const INFRASTRUCTURE_SECTION_CONTENT = defineMethodologySectionContent({
  id: "infrastructure-methodology",
  title: "Infrastructure Tagging",
  markdownParagraphs: [
    "Infrastructure tags identify stablecoins that share issuance frameworks, protocol mechanisms, or operational dependencies. Examples include Liquity v1, Liquity v2, and M0.",
    "Tags help Pharos group related assets without pretending they are the same stablecoin. They support navigation, taxonomy pages, comparison context, and dependency-aware risk review.",
    "Infrastructure tags do not override the underlying governance, backing, peg, collateral, or report-card inputs. They are descriptive metadata used to expose shared machinery.",
  ],
});

export const LIQUIDITY_SECTION_CONTENT = defineMethodologySectionContent({
  id: "liquidity-methodology",
  title: "Liquidity Score",
  markdownParagraphs: [
    "The Liquidity Score measures how safely a stablecoin can exit through decentralized markets. It combines TVL depth, volume activity, pool quality, durability, and pair diversity into a 0-100 score.",
    "TVL depth uses log-scale scoring so small assets can improve without requiring blue-chip depth, while very deep pools still receive credit. Volume rewards active markets. Pool quality adjusts for mechanism type, pool balance, pair quality, and risky counterparties. Durability measures persistence across observations, and pair diversity penalizes concentration in one venue or one unstable route.",
    "Discovery is source-aware. Pharos stages pools from DefiLlama, direct protocol APIs, CoinGecko on-chain data, GeckoTerminal, DexScreener, and curated DEX sources, then deduplicates by exact pool identity or conservative derived identity. Since v6.0, concentrated Raydium pools are classified from DefiLlama's pool metadata, so the same physical Solana pool is never counted from both DefiLlama and the direct Raydium API. Thin, stale, or identity-poor pools remain visible for diagnostics but do not receive the same scoring weight as durable high-quality venues. Secondary discovery rows with non-finite, negative, or impossible pool TVL are rejected before they can enter scoring. CoinGecko Onchain and GeckoTerminal pair rows are admitted only when the tracked leg's USD price stays coherent with the pool's own pair ratio × the counter-leg's USD price, so a provider row that publishes leg USD prices without usable pair-ratio inputs is rejected before it can stage TVL or price evidence.",
  ],
});

export const REDEMPTION_BACKSTOP_SECTION_CONTENT = defineMethodologySectionContent({
  id: "redemption-backstop-methodology",
  title: "Redemption Backstop Route Score",
  markdownParagraphs: [
    "The standalone Redemption Backstop score rates an issuer or protocol redemption route from 0 to 100. It composes access (20%), settlement (15%), execution certainty (15%), capacity (25%), output-asset quality (15%), and cost (10%), then applies route-family, eligibility, delay, queue, minimum-redemption, severe-depeg, freshness, and evidence constraints.",
    "Its modeled capacity request is 5% of supply, floored at $100,000 and capped at $25 million. Capacity blends percent-of-supply coverage with absolute executable dollars so a small percentage can still receive bounded credit without pretending it satisfies the full holder request.",
    "Since v4.39, a measured route scores zero when executable capacity is zero or below both the 1% completion and $100,000 absolute breakpoints; missing capacity remains unrated, and the same materiality gate applies to the eventual-redeemability headline. Reviewed settlement overrides are shared by the standalone row and V9, with favorable corrections subject to the 365-day evidence window. Reserve-sync routes publish full-supply eventual capacity only when dated route evidence explicitly opts into that claim.",
    "Since v4.4, an open route with an unproven settlement completion bound publishes unestablished capacity and remains unrated rather than being scored zero.",
    "Since v4.42, market-implied degradation on an open live downside incident requires a fresh authoritative current signed deviation at or below -2500 bps. The incident's historical peak does not establish present severity: when current evidence is stale, missing, cached, untrusted, or lacks an authoritative peg reference, the route publishes unknown / market-implied and remains impaired with its score withheld; a fresh non-severe deviation releases only this overlay without closing the incident.",
    "Since v4.44, Noon's USN route is modeled as an issuer-processed, days-settled rail with an exact 7-calendar-day bound taken from the five-Business-Day processing clause and rules-based-nav execution, while sUSN's request/claim rail publishes a live on-chain settlement bound read from the WithdrawalHandler's own withdrawPeriod() (604,800 seconds today, behind a 48-hour timelock and retroactive to in-flight requests) with capacity measured from the vault's idle USN as live-direct-bounded. A documented-bound route's observation also uses its same-run chain-read time as observedAt when the observation carries a direct freshness kind, with the reviewed date as the fallback.",
    "This route score is separate from Safety Score V10 Exit. The two share reviewed route-scoring primitives, but V10 re-evaluates exact same-notional evidence under its own stress request, evidence ceilings, danger interlocks, and independent-backup policy.",
  ],
});

export const MINT_BURN_FLOW_SECTION_CONTENT = defineMethodologySectionContent({
  id: "mint-burn-flow-methodology",
  title: "Mint/Burn Flow Scoring",
  markdownParagraphs: [
    "Mint/burn flow scoring tracks issuance and redemption pressure across supported token contracts. Pharos classifies transfers into mint, burn, bridge-mint, bridge-burn, atomic roundtrip, and ignored noise so the gauge reflects meaningful supply movement instead of mechanical churn.",
    "The score compares recent net flow against trailing closed-day baselines, distinguishes canonical-chain activity from bridge effects, and flags pressure shifts when risky outflows and safer inflows diverge.",
    "Coverage is intentionally explicit. Unsupported chains, deferred configs, null-price repair, and stale lanes are surfaced as metadata rather than hidden behind a clean-looking aggregate. Quiet assets retain mature coverage from completed block-scan evidence even after old event rows age out.",
  ],
});

export const YIELD_SECTION_CONTENT = defineMethodologySectionContent({
  id: "yield-intelligence-methodology",
  title: "Yield Intelligence",
  markdownParagraphs: [
    "Yield Intelligence resolves stablecoin yield from direct on-chain reads, curated pools, protocol APIs, price-derived NAV movement, and rate-derived sources. The pipeline prefers precise sources and only uses fallback tiers when identity and exposure remain unambiguous.",
    "Pharos computes effective yield by comparing APY against the relevant cash or peg benchmark, then combines source-risk-adjusted yield efficiency with sustainability to produce a Pharos Yield Score (PYS). High APY is not automatically good: unstable rates, weak safety scores, low TVL, source-risk penalties, or ambiguous exposure reduce the recommendation quality.",
    "External opportunities — lending markets, fixed-yield products, and structured tranches — are scored at the market level. The underlying stablecoin's Safety Score is one input to an opportunity-level safety score that also weighs reviewed venue risk, market size, observed utilization, and access or withdrawal constraints. Missing critical market evidence produces NR rather than a precise-looking score, and the underlying coin's own Report Card is never altered.",
    "Warnings explain why a venue is risky, missing, stale, modeled, or benchmark-adjusted so yield pages do not promote fragile opportunities as clean income. Calculation mode is separate from evidence class: deterministic proxy math is still estimated evidence. Expired or critically incomplete evidence remains visible as NR context but cannot carry an exact current PYS, and new history points retain the versioned formula inputs needed for exact recomputation.",
  ],
});

export const PEGSCORE_DEWS_SECTION_CONTENT = defineMethodologySectionContent({
  id: "pegscore-dews-methodology",
  title: "PegScore and Depeg Early Warning Score (DEWS)",
  markdownParagraphs: [
    "PegScore measures historical peg quality from time-at-peg and event severity. The tracking window starts at a reviewed replay-coverage date when one exists, otherwise it is capped by asset age or the earliest durable observation. Pharos also publishes a coverage-aware recent 90-day companion without treating unobserved days as stable.",
    "DEWS is a forward-looking stress score. It combines price deviation, source divergence, liquidity erosion, pool imbalance, supply velocity, blacklist activity, mint/burn pressure, and yield anomalies into a 0-100 warning signal.",
    "Pending depegs require source-family-aware corroboration before promotion. Pharos treats contradictory evidence as a reason to hold or reject an event, not as weak support, and it records canonical source keys behind every confirmed mutation.",
  ],
});

export const BLACKLIST_SECTION_CONTENT = defineMethodologySectionContent({
  id: "blacklist-tracker-methodology",
  title: "Blacklist Tracker Methodology",
  markdownParagraphs: [
    "The blacklist tracker monitors issuer-controlled freeze, blocklist, account-pause, and token-destruction events across supported centralized stablecoin contracts.",
    "Events are normalized by chain, stablecoin, action type, native amount, USD amount, and amount-status provenance. Recoverable amount gaps are queued for repair, while permanently unavailable rows remain auditable without polluting public aggregates.",
    "Frozen-total summaries use last-known successful freeze-ledger snapshots. New snapshots are contract/config scoped so same-symbol deployments do not overwrite each other; legacy rows can fall back to older address identity until remediated.",
    "Blacklist exposure uses the four-status report-card model: Yes, Upstream, Possible, and No. Upstream applies when a token has no direct Yes/Possible freeze control and strictly more than half of reserves are exposed to Yes, Upstream, or Possible upstream assets or rails.",
  ],
});

export const DEPEG_RESOLVER_SECTION_CONTENT = defineMethodologySectionContent({
  id: "depeg-resolver-methodology",
  title: "Depeg Duration Resolver",
  markdownParagraphs: [
    "When Pharos confirms an active depeg, the Depeg Duration Resolver (DDR) answers two questions at the public forecast lock: will it come back, and if so, when. Stage 1 emits an ordinal Resolution Outlook (Recovery Likely, At Risk, Recovery Unlikely, or Insufficient Signal) from transparent kill signals and recovery anchors over the coin's structure and the depeg's fingerprint. It is a calibrated mechanistic rubric, not fitted machine learning, because the terminal-label corpus is too thin to train a supervised classifier.",
    "DDRv4 uses a forecast-readiness-or-72h contract. Active confirmed incidents show live facts before lock, then the first healthy run with readiness score strictly greater than 0.75 freezes exactly one official prediction or no-call for the canonical incident. If readiness never triggers first, the first healthy run at or after 72h seals through the backstop. Health failures defer the lock rather than creating no-calls or predictions.",
    "Stage 2 runs only when Stage 1 is not terminal-leaning. It is an empirical landmark-survival estimate over the clean corpus of recovered incidents, conditioned on the depeg's structural stratum (depth, direction, structural class, and peg currency) most-dependable-first. It reports a median time-to-repeg with a typical range (15th-85th percentile) plus per-horizon resolution-likelihood cells, support-gated and Wilson-bounded so thin cells show their support state instead of a fabricated number.",
    "The Depeg Duration Resolver Reviewer (DDRR) scores frozen first-published predictions against later canonical depeg-event outcomes and reports coverage accountability for no-calls, pre-lock recoveries, terminal-before-lock outcomes, missed locks, publication retries/failures, data-quality gaps, invalidated rows, and legacy sticky 24h outcomes. Rollout-active incidents that predate the DDRv2 public contract use that boundary for fair coverage classification. Recovery-likelihood accuracy and duration error use only scoreable public predictions.",
    "DDR consumes the same confirmed depeg events as the detection pipeline; it does not run its own detection. Forecast readiness is a publication trigger, not a probability or confidence level, and DDR is not investment advice or a credit rating.",
  ],
});

export const CHAIN_HEALTH_SECTION_CONTENT = defineMethodologySectionContent({
  id: "chain-health-score",
  title: "Chain Health Score",
  markdownParagraphs: [
    "Chain Health Score evaluates how healthy each chain's stablecoin stack is. It combines supply-weighted Safety Score quality, chain environment, stablecoin concentration, peg stability, and RWA/crypto backing diversity.",
    "The score is computed from current stablecoin data and only a fresh, accepted V10 publication rather than a separate opaque dataset. Missing, held, stale, or invalid V10 leaves Safety quality and the composite NR; there is no V8 or stale-score fallback. A chain with large supply but one dominant issuer, weak backing, poor peg behavior, or narrow backing diversity can score below a smaller but more diversified chain.",
    "Chain Health is intended as market-structure context: it helps users understand whether a chain's stablecoin liquidity is deep, resilient, and diversified enough to support activity during stress.",
  ],
});

export const METHODOLOGY_INDEX_SECTION_CONTENT = [
  PRICING_PIPELINE_SECTION_CONTENT,
  STABILITY_INDEX_SECTION_CONTENT,
  SAFETY_SCORES_SECTION_CONTENT,
  DEPENDENCY_EXPOSURE_SECTION_CONTENT,
  MINT_AUTHORITY_SCORE_SECTION_CONTENT,
  INFRASTRUCTURE_SECTION_CONTENT,
  LIQUIDITY_SECTION_CONTENT,
  REDEMPTION_BACKSTOP_SECTION_CONTENT,
  MINT_BURN_FLOW_SECTION_CONTENT,
  YIELD_SECTION_CONTENT,
  PEGSCORE_DEWS_SECTION_CONTENT,
  DEPEG_RESOLVER_SECTION_CONTENT,
  BLACKLIST_SECTION_CONTENT,
  CHAIN_HEALTH_SECTION_CONTENT,
] as const;
