import type { PegCurrency } from "@shared/types";

// Static projection of the stablecoin registry for global shell and metadata copy.
// Keep in sync with shared/lib/stablecoins via src/lib/__tests__/stablecoin-static-data.test.ts.
export const TRACKED_STABLECOIN_COUNT = 409;
export const ACTIVE_STABLECOIN_COUNT = 364;
export const PRE_LAUNCH_STABLECOIN_COUNT = 34;
export const FROZEN_STABLECOIN_COUNT = 11;
export const DEAD_STABLECOIN_COUNT = 88;

export const ACTIVE_PEG_CURRENCY_COUNTS = {
  "USD": 263,
  "RUB": 1,
  "EUR": 20,
  "BRL": 6,
  "VAR": 3,
  "CHF": 5,
  "GBP": 6,
  "SGD": 1,
  "JPY": 6,
  "AUD": 5,
  "CNH": 1,
  "IDR": 2,
  "KGS": 1,
  "TRY": 2,
  "GOLD": 13,
  "SILVER": 3,
  "PHP": 2,
  "OTHER": 6,
  "CAD": 4,
  "ZAR": 2,
  "MXN": 5,
  "NGN": 1,
  "ARS": 1,
  "MYR": 1,
  "VND": 1,
  "KRW": 2,
  "XOF": 1,
} as const satisfies Partial<Record<PegCurrency, number>>;

export const ACTIVE_PEG_CURRENCIES = [
  "USD",
  "EUR",
  "GBP",
  "CHF",
  "BRL",
  "JPY",
  "KRW",
  "SGD",
  "MYR",
  "TRY",
  "AUD",
  "ZAR",
  "CAD",
  "PHP",
  "RUB",
  "CNH",
  "MXN",
  "VND",
  "ARS",
  "KGS",
  "NGN",
  "XOF",
  "IDR",
  "GOLD",
  "SILVER",
  "VAR",
  "OTHER",
] as const satisfies readonly PegCurrency[];

export const ACTIVE_PEG_CURRENCY_COUNT = ACTIVE_PEG_CURRENCIES.length;

export const TRACKED_STABLECOIN_IDS = [
  "usdt-tether",
  "susdt-spark",
  "steakusdt-steakhouse",
  "usdc-circle",
  "susdc-spark",
  "gtusdcp-gauntlet",
  "gtusdc-gauntlet",
  "yvusdc-yearn",
  "steakusdc-steakhouse",
  "bbqusdc-steakhouse",
  "usde-ethena",
  "srusde-strata",
  "susde-ethena",
  "usds-sky",
  "susds-sky",
  "stusds-sky",
  "usd1-world-liberty-financial",
  "susd1plus-lorenzo",
  "dai-makerdao",
  "sdai-sky",
  "pyusd-paypal",
  "usdf-falcon",
  "aa-falconx-mev-capital",
  "usyc-hashnote",
  "usdg-paxos",
  "rlusd-ripple",
  "usdy-ondo-finance",
  "buidl-blackrock",
  "benji-franklin-templeton",
  "wtgxx-wisdomtree",
  "vbill-vaneck",
  "acred-apollo-securitize",
  "jaaa-janus-henderson-anemoy",
  "acrdx-anemoy-apollo",
  "stac-securitize",
  "hlscope-hamilton-lane",
  "pc0000031-tradable",
  "pc0000033-tradable",
  "pc0000101-tradable",
  "pc0000089-tradable",
  "usdd-tron-dao-reserve",
  "susdd-tron-dao-reserve",
  "usdtb-ethena",
  "bfusd-binance",
  "m-m0",
  "u-united-stables",
  "usdai-usd-ai",
  "susdai-usd-ai",
  "usd0-usual",
  "busd0-usual",
  "gho-aave",
  "sgho-aave",
  "stkgho-umbrella-aave",
  "a7a5-old-vector",
  "tusd-trueusd",
  "fdusd-first-digital",
  "cusd-cap",
  "stcusd-cap",
  "eurc-circle",
  "usr-resolv",
  "ylds-figure",
  "crvusd-curve",
  "scrvusd-curve",
  "usx-solstice",
  "usda-avalon",
  "frax-frax",
  "dola-inverse-finance",
  "sdola-inverse-finance",
  "ausd-agora",
  "iusd-infinifi",
  "usdf-astherus",
  "asusdf-astherus",
  "dusd-standx",
  "satusd-river",
  "brz-transfero",
  "gusd-gate",
  "frxusd-frax",
  "sfrxusd-frax",
  "rwausdi-multipli",
  "avusd-avant",
  "savusd-avant",
  "reusd-re-protocol",
  "pmusd-precious-metals",
  "usdz-anzen",
  "cash-phantom",
  "usdkg-gold-dollar",
  "mnee-mnee",
  "pusd-polymarket",
  "tbill-openeden",
  "fpi-frax",
  "usdu-unitas",
  "usdh-native-markets",
  "xdai-gnosis",
  "lisusd-lista",
  "usdon-ondo",
  "usdo-openeden",
  "cusdo-openeden",
  "cgusd-cygnus-finance",
  "eurcv-societe-generale-forge",
  "aeur-anchored-coins",
  "usdq-quantoz",
  "reusd-resupply",
  "euri-banking-circle",
  "gusd-gemini",
  "usdp-paxos",
  "usdsui-sui",
  "suiusde-sui",
  "brlv-crown",
  "reur-royal-euro",
  "ausdt-tether-alloy",
  "usdx-hex-trust",
  "hbd-hive",
  "xusd-straitsx",
  "musd-metamask",
  "yusd-aegis",
  "syusd-aegis",
  "susd-synthetix",
  "bold-liquity",
  "sbold-k3-capital",
  "ybold-yearn",
  "hyusd-hylo",
  "lusd-liquity",
  "fxusd-f-x-protocol",
  "fxsave-f-x-protocol",
  "usdn-noble",
  "usdn-smardex",
  "mim-abracadabra",
  "usdcv-societe-generale-forge",
  "honey-berachain",
  "zchf-frankencoin",
  "usdb-blast",
  "zeusd-zoth",
  "eure-monerium",
  "usn-noon",
  "susn-noon",
  "nect-beraborrow",
  "eusd-electronic-usd",
  "mai-qidao",
  "buck-bucket-protocol",
  "meusd-mezo",
  "uty-xsy",
  "eurs-stasis",
  "msusd-metronome",
  "rusd-royal-dollar",
  "usdr-ring",
  "usdaf-asymmetry",
  "usnd-nerite",
  "usdq-quill",
  "usdk-orki",
  "ebusd-ebisu",
  "nusd-neutrl",
  "usdh-hermetica",
  "yzusd-yuzu",
  "syzusd-yuzu",
  "jupusd-jupiter",
  "usdm-mega",
  "usdsc-startale",
  "ctusd-citrea",
  "wm-m0",
  "usdnr-nerona",
  "usdat-saturn",
  "usdk-kast",
  "moveusd-cfx",
  "xo-exodus",
  "usat-tether",
  "cusd-celo",
  "alusd-alchemix",
  "feusd-felix",
  "fidd-fidelity",
  "usdgo-osl",
  "msusd-main-street",
  "msy-main-street",
  "usdm-moneta",
  "hollar-hydrated",
  "usda-anzens",
  "uusd-youves",
  "aznd-mu-digital",
  "pusd-plume",
  "wusd-worldwide",
  "sbc-brale",
  "ousd-origin-protocol",
  "btcusd-btcfi",
  "usbd-bima",
  "doc-money-on-chain",
  "dllr-sovryn",
  "xusd-babelfish",
  "usdrif-rif",
  "usp-pikudao",
  "usdr-stablr",
  "usdu-usdu-finance",
  "dusd-dtrinity",
  "sdusd-dtrinity",
  "dusd-alto",
  "ustb-superstate",
  "ousg-ondo-finance",
  "slvon-ondo",
  "iauon-ondo",
  "mtbill-midas",
  "mre7yield-midas",
  "mf-one-midas",
  "mglobal-midas-fasanara",
  "mhyper-midas",
  "mmev-midas",
  "mapollo-midas",
  "safo-spiko-usd",
  "spkcc-spiko",
  "eursafo-spiko",
  "eurspkcc-spiko",
  "uktbl-spiko",
  "gbpsafo-spiko",
  "jtrsy-anemoy",
  "ustbl-spiko",
  "bib01-backed",
  "thbill-theo",
  "rusd-reservoir",
  "wsrusd-reservoir",
  "srusd-reservoir",
  "usdp-parallel",
  "xsgd-straitsx",
  "gyen-gyen",
  "audd-novatti",
  "jpyc-jpyc",
  "jpyc-jpyc-v1",
  "axcnh-anchorx",
  "idrt-rupiah-token",
  "audm-macropod",
  "kgst-kyrgyz-som",
  "audf-forte",
  "tryb-bilira",
  "xaut-tether",
  "xnk-kinka",
  "paxg-paxos",
  "gldy-streamex",
  "kau-kinesis",
  "xaum-matrixdock",
  "xagm-matrixdock",
  "vnxau-vnx",
  "gramg-token-teknoloji",
  "grams-token-teknoloji",
  "cgo-comtech",
  "dgld-gold-token-sa",
  "pgold-pleasing",
  "ggbr-goldfish-gold",
  "gldt-gold-dao",
  "kag-kinesis",
  "ceur-celo",
  "euroe-membrane",
  "eutbl-spiko",
  "bc3m-backed",
  "gbpm-mento",
  "gbpe-monerium",
  "jpym-mento",
  "chfm-mento",
  "brlm-mento",
  "phpm-mento",
  "kesm-mento",
  "copm-mento",
  "cadm-mento",
  "audm-mento",
  "ghsm-mento",
  "zarm-mento",
  "veur-vnx",
  "eurr-stablr",
  "europ-schuman",
  "eurq-quantoz",
  "eurau-allunity",
  "deuro-deuro",
  "audx-aussie-dollar-token",
  "chfau-allunity",
  "vchf-vnx",
  "vgbp-vnx",
  "tgbp-tokenised",
  "zarp-zarp",
  "isc-international-stable-currency",
  "cadc-cad-coin",
  "qcad-stablecorp",
  "cadd-cad-digital",
  "pht-pht",
  "cetes-etherfuse",
  "syrupusdc-maple",
  "syrupusdt-maple",
  "yousd-yield-optimizer",
  "inalpha-nest",
  "ntbill-nest",
  "nbasis-nest",
  "nopal-nest",
  "nwisdom-nest",
  "eusd-telcoin",
  "fusd-freedom-dollar",
  "fusd-finchain",
  "zsd-zephyr-protocol",
  "zys-zephyr-protocol",
  "autousd-auto-finance",
  "eearn-ember",
  "yusd-yieldfi",
  "spusd-soulpeg",
  "uusd-anything-labs",
  "jusd-jusd-stable-token",
  "jusd-juicedollar",
  "usda-alpha-partner",
  "aid-gaib",
  "said-gaib",
  "apxusd-apyx",
  "apyusd-apyx",
  "nxusd-nereus",
  "nusd-nexus",
  "stusd-stoneyield",
  "vusd-virtue",
  "lvusd-leverup",
  "xmd-metal-dollar",
  "hlusd-hela",
  "usx-dforce",
  "susd-solayer",
  "home-homecoin",
  "usdx-kava",
  "usd3-reserve-protocol",
  "money-defi-money",
  "cdxusd-cod3x",
  "cdp-enosys",
  "vcred-vcred",
  "susd-hedgecore",
  "iusd-indigo-protocol",
  "luausd-lumi-finance",
  "xtusd-xt",
  "wemix-dollar-wemix",
  "usdglo-glo",
  "djed-coti",
  "pathusd-bridge",
  "xai-silo-finance",
  "usp-pareto-credit",
  "fxd-fathom",
  "usdv-solomon",
  "ussd-sonic-labs",
  "usdpt-western-union",
  "roughrider-bnd",
  "fiusd-fiserv",
  "eur-qivalis",
  "pusd-polaris",
  "pgold-polaris",
  "usg-tangent",
  "klarnausd-klarna",
  "ftusd-flying-tulip",
  "bd-basedollar",
  "brla-brla-digital",
  "silk-shade-protocol",
  "idrx-idrx",
  "cngn-compliant-naira",
  "mxnb-juno",
  "mmxn-moneta-digital",
  "brl1-brl1",
  "wars-argentine-peso",
  "wbrl-ripio",
  "wclp-ripio",
  "wcop-ripio",
  "wpen-ripio",
  "cjpy-yamato",
  "trusd-tori",
  "buck-buck-assets",
  "rgbp-revolut",
  "jpysc-sbi-startale",
  "myrc-blox",
  "vndc-jade-labs",
  "krwq-iq",
  "eur0-usual",
  "emxn-telcoin",
  "hchf-hedera-swiss-franc",
  "eurot-token-teknoloji",
  "mxne-real-mxn",
  "jpyt-dephaser",
  "wmxn-ripio",
  "xofm-mento",
  "euro3-3a-dao",
  "krwo-gimswap",
  "usdb-bridge",
  "hkdap-anchorpoint",
  "hkd-hsbc",
  "okrw-hashed",
  "arc-anq",
  "brl-b3",
  "usdf-flipcash",
  "hkdr-rd-technologies",
  "brd-volpon",
  "krw1-bdacs",
  "rusd-revolut",
  "brl-itau",
  "usd-nubank",
  "krw-imbank",
  "sofid-sofi",
  "onyc-onre",
  "hbusdt-hyperbeat",
  "witry-brix",
  "scusd-rings",
  "weusd-picwe",
  "iusd-initia",
  "usdxl-last",
  "dusd-fluid",
  "bnusd-balanced",
  "usdcx-movement",
  "ist-agoric",
  "usdh-hubble",
  "zkusd-goal3",
  "gynusd-gyndore",
  "gelt-tether",
  "tgld-tenbin",
  "ejpy-jbfd",
  "aed-rakbank",
  "bils-bitsofgold",
  "kusd-kerne",
  "ousd-open-standard",
] as const;

const NON_ACTIVE_STABLECOIN_ID_SET: ReadonlySet<string> = new Set([
  "usr-resolv",
  "usnd-nerite",
  "usdk-orki",
  "usdr-stablr",
  "msusd-main-street",
  "msy-main-street",
  "euroe-membrane",
  "eurr-stablr",
  "usdpt-western-union",
  "roughrider-bnd",
  "fiusd-fiserv",
  "eur-qivalis",
  "pusd-polaris",
  "pgold-polaris",
  "klarnausd-klarna",
  "bd-basedollar",
  "mmxn-moneta-digital",
  "trusd-tori",
  "buck-buck-assets",
  "rgbp-revolut",
  "jpysc-sbi-startale",
  "usdb-bridge",
  "hkdap-anchorpoint",
  "hkd-hsbc",
  "okrw-hashed",
  "arc-anq",
  "brl-b3",
  "usdf-flipcash",
  "hkdr-rd-technologies",
  "brd-volpon",
  "krw1-bdacs",
  "rusd-revolut",
  "brl-itau",
  "usd-nubank",
  "krw-imbank",
  "ist-agoric",
  "gynusd-gyndore",
  "gelt-tether",
  "tgld-tenbin",
  "ejpy-jbfd",
  "aed-rakbank",
  "bils-bitsofgold",
  "kusd-kerne",
  "susd-synthetix",
  "ousd-open-standard",
] as const);

export const ACTIVE_STABLECOIN_IDS = TRACKED_STABLECOIN_IDS.filter(
  (id) => !NON_ACTIVE_STABLECOIN_ID_SET.has(id),
);

export const ACTIVE_STABLECOIN_ID_SET: ReadonlySet<string> = new Set(ACTIVE_STABLECOIN_IDS);

export const HOMEPAGE_TOP_ACTIVE_STABLECOINS = [
  { id: "usdt-tether", name: "Tether", symbol: "USDT" },
  { id: "susdt-spark", name: "Spark Savings USDT", symbol: "spUSDT" },
  { id: "steakusdt-steakhouse", name: "Steakhouse USDT V2", symbol: "steakUSDT" },
  { id: "usdc-circle", name: "USD Coin", symbol: "USDC" },
  { id: "susdc-spark", name: "Spark Savings USDC", symbol: "spUSDC" },
  { id: "gtusdcp-gauntlet", name: "Gauntlet USDC Prime", symbol: "gtUSDCp" },
  { id: "gtusdc-gauntlet", name: "Gauntlet USDC Prime V1", symbol: "gtUSDC" },
  { id: "yvusdc-yearn", name: "Yearn v3 USDC Vault", symbol: "yvUSDC-1" },
  { id: "steakusdc-steakhouse", name: "Steakhouse USDC V2", symbol: "steakUSDC" },
  { id: "bbqusdc-steakhouse", name: "Smokehouse USDC", symbol: "bbqUSDC" },
  { id: "usde-ethena", name: "Ethena USDe", symbol: "USDe" },
  { id: "srusde-strata", name: "Strata Senior USDe", symbol: "srUSDe" },
  { id: "susde-ethena", name: "Ethena Staked USDe", symbol: "sUSDe" },
  { id: "usds-sky", name: "Sky Dollar", symbol: "USDS" },
  { id: "susds-sky", name: "Sky Savings USDS", symbol: "sUSDS" },
  { id: "stusds-sky", name: "Staked USDS", symbol: "stUSDS" },
  { id: "usd1-world-liberty-financial", name: "World Liberty Financial USD", symbol: "USD1" },
  { id: "susd1plus-lorenzo", name: "staked USD1+", symbol: "sUSD1+" },
  { id: "dai-makerdao", name: "Dai", symbol: "DAI" },
  { id: "sdai-sky", name: "Savings Dai", symbol: "sDAI" },
] as const;
