// Stable import path for the build-generated, client-safe registry projection.
export {
  ACTIVE_PEG_CURRENCIES,
  ACTIVE_PEG_CURRENCY_COUNT,
  ACTIVE_PEG_CURRENCY_COUNTS,
  ACTIVE_STABLECOIN_COUNT,
  ACTIVE_STABLECOIN_ID_SET,
  ACTIVE_STABLE_VALUE_INVESTMENT_COUNT,
  ACTIVE_VARIANT_STABLECOIN_COUNT,
  CORE_AGGREGATE_STABLECOIN_COUNT,
  DEAD_STABLECOIN_COUNT,
  HOMEPAGE_TOP_CORE_STABLECOINS,
  PRE_LAUNCH_STABLECOIN_COUNT,
  TRACKED_STABLECOIN_COUNT,
} from "@/generated/stablecoin-static-data";
