import {
  defineLazyDbRequestRoute,
  defineLazyDbRoute,
  defineLazyDbUrlRoute,
  defineLazyNoContextRoute,
  type StaticRouteDefinition,
} from "./shared";

export const PUBLIC_STATIC_ROUTES = [
  defineLazyDbRoute("stablecoins", () => import("../api/cache-handlers").then(({ handleStablecoins }) => handleStablecoins)),
  defineLazyDbRoute("stablecoin-charts", () => import("../api/cache-handlers").then(({ handleStablecoinCharts }) => handleStablecoinCharts)),
  defineLazyDbUrlRoute("blacklist", () => import("../api/blacklist").then(({ handleBlacklist }) => handleBlacklist)),
  defineLazyDbRoute("blacklist-summary", () => import("../lib/blacklist-summary-service").then(({ handleBlacklistSummary }) => handleBlacklistSummary)),
  defineLazyDbUrlRoute("depeg-events", () => import("../api/depeg-events").then(({ handleDepegEvents }) => handleDepegEvents)),
  defineLazyDbUrlRoute("events", () => import("../api/events").then(({ handleEvents }) => handleEvents)),
  defineLazyDbRoute("peg-summary", () => import("../api/peg-summary").then(({ handlePegSummary }) => handlePegSummary)),
  defineLazyDbRoute("health", () => import("../api/health").then(({ handleHealth }) => handleHealth)),
  defineLazyDbRoute("usds-status", () => import("../api/cache-handlers").then(({ handleUsdsStatus }) => handleUsdsStatus)),
  defineLazyDbRoute("bluechip-ratings", () => import("../api/cache-handlers").then(({ handleBluechipRatings }) => handleBluechipRatings)),
  defineLazyDbRoute("dex-liquidity", () => import("../api/dex-liquidity").then(({ handleDexLiquidity }) => handleDexLiquidity)),
  defineLazyDbUrlRoute("dex-liquidity-history", () => import("../api/dex-liquidity-history").then(({ handleDexLiquidityHistory }) => handleDexLiquidityHistory)),
  defineLazyDbUrlRoute("supply-history", () => import("../api/supply-history").then(({ handleSupplyHistory }) => handleSupplyHistory)),
  defineLazyDbRoute("daily-digest", () => import("../api/daily-digest").then(({ handleDailyDigest }) => handleDailyDigest)),
  defineLazyDbRoute("digest-archive", () => import("../api/digest-archive").then(({ handleDigestArchive }) => handleDigestArchive)),
  defineLazyDbUrlRoute("digest-snapshot", () => import("../api/digest-snapshot").then(({ handleDigestSnapshot }) => handleDigestSnapshot)),
  defineLazyDbRoute("snapshots-index", () => import("../api/snapshot").then(({ handleSnapshotsIndex }) => handleSnapshotsIndex)),
  defineLazyDbUrlRoute("stability-index", () => import("../api/stability-index").then(({ handleStabilityIndex }) => handleStabilityIndex)),
  defineLazyDbRoute("report-cards-v9", () => import("../api/report-cards-v9").then(({ handleReportCardsV9 }) => handleReportCardsV9)),
  defineLazyDbRoute("depeg-resolver", () => import("../api/depeg-resolver").then(({ handleDepegResolver }) => handleDepegResolver)),
  defineLazyDbRoute("depeg-resolver-review", () => import("../api/depeg-resolver-review").then(({ handleDepegResolverReview }) => handleDepegResolverReview)),
  defineLazyDbRoute("redemption-backstops", () => import("../api/redemption-backstops").then(({ handleRedemptionBackstops }) => handleRedemptionBackstops)),
  defineLazyDbUrlRoute("yield-rankings", () => import("../api/cache-handlers").then(({ handleYieldRankings }) => handleYieldRankings)),
  defineLazyNoContextRoute("yield-adapter-manifest", () => import("../api/yield-adapter-manifest").then(({ handleYieldAdapterManifest }) => handleYieldAdapterManifest)),
  defineLazyDbUrlRoute("yield-history", () => import("../api/yield-history").then(({ handleYieldHistory }) => handleYieldHistory)),
  defineLazyDbUrlRoute("safety-score-history", () => import("../api/safety-score-history").then(({ handleSafetyScoreHistory }) => handleSafetyScoreHistory)),
  defineLazyDbUrlRoute("safety-score-history-v2", () => import("../api/safety-score-history-v2").then(({ handleSafetyScoreHistoryV2 }) => handleSafetyScoreHistoryV2)),
  defineLazyDbUrlRoute("mint-burn-flows", () => import("../api/mint-burn-flows").then(({ handleMintBurnFlows }) => handleMintBurnFlows)),
  defineLazyDbUrlRoute("mint-burn-events", () => import("../api/mint-burn-events").then(({ handleMintBurnEvents }) => handleMintBurnEvents)),
  defineLazyDbUrlRoute("stress-signals", () => import("../api/stress-signals").then(({ handleStressSignals }) => handleStressSignals)),
  defineLazyDbUrlRoute("chains", () => import("../api/chains").then(({ handleChains }) => handleChains)),
  defineLazyDbUrlRoute("non-usd-share", () => import("../api/non-usd-share").then(({ handleNonUsdShare }) => handleNonUsdShare)),
  defineLazyDbRequestRoute("public-status-history", () => import("../api/public-status-history").then(({ handlePublicStatusHistory }) => handlePublicStatusHistory)),
  defineLazyDbRoute("telegram-pulse", () => import("../api/telegram-pulse").then(({ handleTelegramPulse }) => handleTelegramPulse)),
] as const satisfies readonly StaticRouteDefinition[];
