/* Auto-generated for TICKET-002: old ID -> ticker-issuer mapping table */

export const ID_MAPPING = [
  { oldId: "1", newId: "usdt-tether", symbol: "USDT", name: "Tether", issuer: "tether", geckoId: "tether" },
  { oldId: "2", newId: "usdc-circle", symbol: "USDC", name: "USD Coin", issuer: "circle", geckoId: "usd-coin" },
  { oldId: "146", newId: "usde-ethena", symbol: "USDe", name: "Ethena USDe", issuer: "ethena", geckoId: "ethena-usde" },
  { oldId: "209", newId: "usds-sky", symbol: "USDS", name: "Sky Dollar", issuer: "sky", geckoId: "usds" },
  { oldId: "262", newId: "usd1-world-liberty-financial", symbol: "USD1", name: "World Liberty Financial USD", issuer: "world-liberty-financial", geckoId: "usd1-wlfi" },
  { oldId: "5", newId: "dai-makerdao", symbol: "DAI", name: "Dai", issuer: "makerdao", geckoId: "dai" },
  { oldId: "120", newId: "pyusd-paypal", symbol: "PYUSD", name: "PayPal USD", issuer: "paypal", geckoId: "paypal-usd" },
  { oldId: "246", newId: "usdf-falcon", symbol: "USDf", name: "Falcon USD", issuer: "falcon", geckoId: "falcon-finance" },
  { oldId: "237", newId: "usyc-hashnote", symbol: "USYC", name: "Hashnote USYC", issuer: "hashnote", geckoId: "hashnote-usyc" },
  { oldId: "286", newId: "usdg-paxos", symbol: "USDG", name: "Global Dollar", issuer: "paxos", geckoId: "global-dollar" },
  { oldId: "250", newId: "rlusd-ripple", symbol: "RLUSD", name: "Ripple USD", issuer: "ripple", geckoId: "ripple-usd" },
  { oldId: "129", newId: "usdy-ondo-finance", symbol: "USDY", name: "Ondo US Dollar Yield", issuer: "ondo-finance", geckoId: "ondo-us-dollar-yield" },
  { oldId: "173", newId: "buidl-blackrock", symbol: "BUIDL", name: "BlackRock USD", issuer: "blackrock", geckoId: "blackrock-usd-institutional-digital-liquidity-fund" },
  { oldId: "14", newId: "usdd-tron-dao-reserve", symbol: "USDD", name: "USDD", issuer: "tron-dao-reserve", geckoId: "usdd" },
  { oldId: "221", newId: "usdtb-ethena", symbol: "USDTB", name: "Ethena USDtb", issuer: "ethena", geckoId: "usdtb" },
  { oldId: "213", newId: "m-m0", symbol: "M", name: "M by M0", issuer: "m0", geckoId: "m" },
  { oldId: "336", newId: "u-united-stables", symbol: "U", name: "United Stables", issuer: "united-stables", geckoId: "united-stables" },
  { oldId: "309", newId: "usdai-usd-ai", symbol: "USDai", name: "USD.AI", issuer: "usd-ai", geckoId: "usdai" },
  { oldId: "195", newId: "usd0-usual", symbol: "USD0", name: "Usual USD", issuer: "usual", geckoId: "usual-usd" },
  { oldId: "118", newId: "gho-aave", symbol: "GHO", name: "GHO", issuer: "aave", geckoId: "gho" },
  { oldId: "258", newId: "a7a5-old-vector", symbol: "A7A5", name: "A7A5", issuer: "old-vector", geckoId: "a7a5" },
  { oldId: "7", newId: "tusd-trueusd", symbol: "TUSD", name: "TrueUSD", issuer: "trueusd", geckoId: "true-usd" },
  { oldId: "119", newId: "fdusd-first-digital", symbol: "FDUSD", name: "First Digital USD", issuer: "first-digital", geckoId: "first-digital-usd" },
  { oldId: "296", newId: "cusd-cap", symbol: "CUSD", name: "Cap cUSD", issuer: "cap", geckoId: "cap-usd" },
  { oldId: "50", newId: "eurc-circle", symbol: "EURC", name: "EURC", issuer: "circle", geckoId: "euro-coin" },
  { oldId: "197", newId: "usr-resolv", symbol: "USR", name: "Resolv USD", issuer: "resolv", geckoId: "resolv-usr" },
  { oldId: "272", newId: "ylds-figure", symbol: "YLDS", name: "YLDS", issuer: "figure", geckoId: "ylds" },
  { oldId: "110", newId: "crvusd-curve", symbol: "crvUSD", name: "crvUSD", issuer: "curve", geckoId: "crvusd" },
  { oldId: "310", newId: "usx-solstice", symbol: "USX", name: "Solstice USX", issuer: "solstice", geckoId: "usx" },
  { oldId: "220", newId: "usda-avalon", symbol: "USDA", name: "Avalon USDa", issuer: "avalon", geckoId: "usda-2" },
  { oldId: "6", newId: "frax-frax", symbol: "FRAX", name: "Frax", issuer: "frax", geckoId: "frax" },
  { oldId: "15", newId: "dola-inverse-finance", symbol: "DOLA", name: "Dola", issuer: "inverse-finance", geckoId: "dola-usd" },
  { oldId: "205", newId: "ausd-agora", symbol: "AUSD", name: "Agora Dollar", issuer: "agora", geckoId: "agora-dollar" },
  { oldId: "298", newId: "iusd-infinifi", symbol: "IUSD", name: "infiniFi USD", issuer: "infinifi", geckoId: "infinifi-usd" },
  { oldId: "219", newId: "usdf-astherus", symbol: "USDF", name: "Astherus", issuer: "astherus", geckoId: "astherus-usdf" },
  { oldId: "252", newId: "dusd-standx", symbol: "DUSD", name: "StandX DUSD", issuer: "standx", geckoId: "standx-dusd" },
  { oldId: "218", newId: "satusd-river", symbol: "satUSD", name: "River Stablecoin", issuer: "river", geckoId: "satoshi-stablecoin" },
  { oldId: "249", newId: "brz-transfero", symbol: "BRZ", name: "Brazilian Digital", issuer: "transfero", geckoId: "brz" },
  { oldId: "306", newId: "gusd-gate", symbol: "GUSD", name: "Gate USD", issuer: "gate", geckoId: "gusd" },
  { oldId: "235", newId: "frxusd-frax", symbol: "FRXUSD", name: "Frax USD", issuer: "frax", geckoId: "frax-usd" },
  { oldId: "340", newId: "rwausdi-multipli", symbol: "rwaUSDi", name: "rwaUSDi", issuer: "multipli" },
  { oldId: "271", newId: "avusd-avant", symbol: "avUSD", name: "Avant USD", issuer: "avant", geckoId: "avant-usd" },
  { oldId: "341", newId: "pusd-pleasing", symbol: "PUSD", name: "Pleasing USD", issuer: "pleasing", geckoId: "pleasing-usd" },
  { oldId: "339", newId: "reusd-re-protocol", symbol: "reUSD", name: "Re Protocol reUSD", issuer: "re-protocol", geckoId: "re-protocol-reusd" },
  { oldId: "332", newId: "pmusd-precious-metals", symbol: "pmUSD", name: "pmUSD", issuer: "precious-metals", geckoId: "precious-metals-usd" },
  { oldId: "202", newId: "usdz-anzen", symbol: "USDz", name: "Anzen USDz", issuer: "anzen", geckoId: "anzen-usdz" },
  { oldId: "316", newId: "cash-phantom", symbol: "CASH", name: "CASH", issuer: "phantom", geckoId: "cash-4" },
  { oldId: "284", newId: "mnee-mnee", symbol: "MNEE", name: "MNEE USD", issuer: "mnee", geckoId: "mnee-usd-stablecoin" },
  { oldId: "257", newId: "tbill-openeden", symbol: "TBILL", name: "OpenEden TBILL", issuer: "openeden", geckoId: "openeden-tbill" },
  { oldId: "66", newId: "fpi-frax", symbol: "FPI", name: "Frax Price Index", issuer: "frax", geckoId: "frax-price-index" },
  { oldId: "283", newId: "usdu-unitas", symbol: "USDU", name: "Unitas", issuer: "unitas", geckoId: "usdu" },
  { oldId: "321", newId: "usdh-native-markets", symbol: "USDH", name: "USDH Stablecoin", issuer: "native-markets", geckoId: "usdh-2" },
  { oldId: "79", newId: "lisusd-lista", symbol: "LISUSD", name: "Lista USD", issuer: "lista", geckoId: "helio-protocol-hay" },
  { oldId: "241", newId: "usdo-openeden", symbol: "USDO", name: "OpenDollar USDO", issuer: "openeden", geckoId: "openeden-open-dollar" },
  { oldId: "166", newId: "cgusd-cygnus-finance", symbol: "cgUSD", name: "Cygnus Finance Global USD", issuer: "cygnus-finance", geckoId: "cygnus-finance-global-usd" },
  { oldId: "254", newId: "eurcv-societe-generale-forge", symbol: "EURCV", name: "EUR CoinVertible", issuer: "societe-generale-forge", geckoId: "societe-generale-forge-eurcv" },
  { oldId: "147", newId: "aeur-anchored-coins", symbol: "AEUR", name: "Anchored Coins AEUR", issuer: "anchored-coins", geckoId: "anchored-coins-eur" },
  { oldId: "275", newId: "usdq-quantoz", symbol: "USDQ", name: "Quantoz USDQ", issuer: "quantoz", geckoId: "quantoz-usdq" },
  { oldId: "256", newId: "reusd-resupply", symbol: "REUSD", name: "Resupply USD", issuer: "resupply", geckoId: "resupply-usd" },
  { oldId: "325", newId: "euri-banking-circle", symbol: "EURI", name: "Eurite", issuer: "banking-circle", geckoId: "eurite" },
  { oldId: "19", newId: "gusd-gemini", symbol: "GUSD", name: "Gemini Dollar", issuer: "gemini", geckoId: "gemini-dollar" },
  { oldId: "11", newId: "usdp-paxos", symbol: "USDP", name: "Pax Dollar", issuer: "paxos", geckoId: "paxos-standard" },
  { oldId: "263", newId: "usdx-hex-trust", symbol: "USDX", name: "Hex Trust USDX", issuer: "hex-trust", geckoId: "hex-trust-usdx" },
  { oldId: "290", newId: "xusd-straitsx", symbol: "XUSD", name: "StraitsX XUSD", issuer: "straitsx", geckoId: "straitsx-xusd" },
  { oldId: "313", newId: "musd-metamask", symbol: "MUSD", name: "Metamask USD", issuer: "metamask", geckoId: "metamask-usd" },
  { oldId: "255", newId: "yusd-aegis", symbol: "YUSD", name: "Aegis YUSD", issuer: "aegis", geckoId: "aegis-yusd" },
  { oldId: "22", newId: "susd-synthetix", symbol: "SUSD", name: "sUSD", issuer: "synthetix", geckoId: "nusd" },
  { oldId: "269", newId: "bold-liquity", symbol: "BOLD", name: "Liquity BOLD", issuer: "liquity", geckoId: "liquity-bold-2" },
  { oldId: "302", newId: "hyusd-hylo", symbol: "HYUSD", name: "Hylo HYUSD", issuer: "hylo", geckoId: "hylo-usd" },
  { oldId: "8", newId: "lusd-liquity", symbol: "LUSD", name: "Liquity USD", issuer: "liquity", geckoId: "liquity-usd" },
  { oldId: "168", newId: "fxusd-f-x-protocol", symbol: "fxUSD", name: "fxUSD", issuer: "f-x-protocol", geckoId: "f-x-protocol-fxusd" },
  { oldId: "282", newId: "usdn-noble", symbol: "USDN", name: "Noble Dollar", issuer: "noble", geckoId: "noble-dollar-usdn" },
  { oldId: "10", newId: "mim-abracadabra", symbol: "MIM", name: "Magic Internet Money", issuer: "abracadabra", geckoId: "magic-internet-money" },
  { oldId: "307", newId: "usdcv-societe-generale-forge", symbol: "USDCV", name: "USD CoinVertible", issuer: "societe-generale-forge", geckoId: "usd-coinvertible" },
  { oldId: "231", newId: "honey-berachain", symbol: "HONEY", name: "Honey", issuer: "berachain", geckoId: "honey-3" },
  { oldId: "226", newId: "zchf-frankencoin", symbol: "ZCHF", name: "Frankencoin", issuer: "frankencoin", geckoId: "frankencoin" },
  { oldId: "172", newId: "usdb-blast", symbol: "USDB", name: "USDB Blast", issuer: "blast", geckoId: "usdb" },
  { oldId: "225", newId: "zeusd-zoth", symbol: "ZeUSD", name: "Zoth ZeUSD", issuer: "zoth", geckoId: "zeusd" },
  { oldId: "101", newId: "eure-monerium", symbol: "EURE", name: "Monerium EUR emoney", issuer: "monerium", geckoId: "monerium-eur-money-2" },
  { oldId: "230", newId: "usn-noon", symbol: "USN", name: "Noon USN", issuer: "noon", geckoId: "noon-usn" },
  { oldId: "185", newId: "gyd-gyroscope", symbol: "GYD", name: "Gyroscope GYD", issuer: "gyroscope", geckoId: "gyroscope-gyd" },
  { oldId: "329", newId: "nect-beraborrow", symbol: "NECT", name: "Nectar", issuer: "beraborrow", geckoId: "nectar" },
  { oldId: "106", newId: "eusd-electronic-usd", symbol: "EUSD", name: "Electronic USD", issuer: "electronic-usd", geckoId: "electronic-usd" },
  { oldId: "154", newId: "buck-bucket-protocol", symbol: "BUCK", name: "Bucket Protocol BUCK", issuer: "bucket-protocol", geckoId: "bucket-protocol-buck-stablecoin" },
  { oldId: "55", newId: "eura-angle", symbol: "EURA", name: "EURA", issuer: "angle", geckoId: "ageur" },
  { oldId: "303", newId: "meusd-mezo", symbol: "meUSD", name: "Mezo USD", issuer: "mezo", geckoId: "mezo-usd" },
  { oldId: "305", newId: "uty-xsy", symbol: "UTY", name: "XSY UTY", issuer: "xsy", geckoId: "unity-2" },
  { oldId: "51", newId: "eurs-stasis", symbol: "EURS", name: "Stasis Euro", issuer: "stasis", geckoId: "stasis-eurs" },
  { oldId: "326", newId: "msusd-metronome", symbol: "MSUSD", name: "Metronome Synth USD", issuer: "metronome", geckoId: "metronome-synth-usd" },
  { oldId: "346", newId: "nusd-neutrl", symbol: "NUSD", name: "Neutrl USD", issuer: "neutrl", geckoId: "nusd-2" },
  { oldId: "344", newId: "yzusd-yuzu", symbol: "YZUSD", name: "Yuzu USD", issuer: "yuzu", geckoId: "yuzu-usd" },
  { oldId: "335", newId: "jupusd-jupiter", symbol: "JUPUSD", name: "JupUSD", issuer: "jupiter", geckoId: "jupusd", cmcSlug: "jupusd" },
  { oldId: "342", newId: "usdm-mega", symbol: "USDM", name: "MegaUSD", issuer: "mega", geckoId: "megausd" },
  { oldId: "343", newId: "usat-tether", symbol: "USAT", name: "Tether USA-T", issuer: "tether", geckoId: "usa" },
  { oldId: "24", newId: "cusd-celo", symbol: "cUSD", name: "Celo Dollar", issuer: "celo", geckoId: "celo-dollar" },
  { oldId: "20", newId: "alusd-alchemix", symbol: "ALUSD", name: "Alchemix USD", issuer: "alchemix", geckoId: "alchemix-usd" },
  { oldId: "251", newId: "feusd-felix", symbol: "FEUSD", name: "Felix feUSD", issuer: "felix", geckoId: "felix-feusd" },
  { oldId: "348", newId: "fidd-fidelity", symbol: "FIDD", name: "Fidelity Digital Dollar", issuer: "fidelity", geckoId: "fidelity-digital-dollar" },
  { oldId: "347", newId: "usdgo-osl", symbol: "USDGO", name: "USDGO", issuer: "osl", geckoId: "usdgo" },
  { oldId: "297", newId: "msusd-main-street", symbol: "MSUSD", name: "Main Street USD", issuer: "main-street", geckoId: "main-street-usd" },
  { oldId: "215", newId: "usdm-moneta", symbol: "USDM", name: "Moneta", issuer: "moneta", geckoId: "usdm-2" },
  { oldId: "312", newId: "hollar-hydrated", symbol: "HOLLAR", name: "Hydrated Dollar", issuer: "hydrated", geckoId: "hydrated-dollar" },
  { oldId: "245", newId: "usda-anzens", symbol: "USDA", name: "Anzens USDA", issuer: "anzens", geckoId: "anzens-usda" },
  { oldId: "75", newId: "uusd-youves", symbol: "UUSD", name: "Youves uUSD", issuer: "youves", geckoId: "youves-uusd" },
  { oldId: "327", newId: "aznd-mu-digital", symbol: "AZND", name: "Mu Digital AZND", issuer: "mu-digital", geckoId: "mu-digital-aznd" },
  { oldId: "266", newId: "pusd-plume", symbol: "pUSD", name: "Plume USD", issuer: "plume", geckoId: "plume-usd" },
  { oldId: "234", newId: "wusd-worldwide", symbol: "WUSD", name: "Worldwide USD", issuer: "worldwide", geckoId: "worldwide-usd" },
  { oldId: "324", newId: "sbc-brale", symbol: "SBC", name: "Brale SBC", issuer: "brale", geckoId: "stable-coin-2" },
  { oldId: "23", newId: "ousd-origin-protocol", symbol: "OUSD", name: "Origin Dollar", issuer: "origin-protocol", geckoId: "origin-dollar" },
  { oldId: "183", newId: "btcusd-btcfi", symbol: "BtcUSD", name: "Bitcoin USD", issuer: "btcfi", geckoId: "bitcoin-usd-btcfi" },
  { oldId: "331", newId: "usp-pikudao", symbol: "USP", name: "PikuDAO USP", issuer: "pikudao", geckoId: "usp-yield-optimized-stablecoin" },
  { oldId: "240", newId: "usdr-stablr", symbol: "USDR", name: "StablR USD", issuer: "stablr", geckoId: "stablr-usd" },
  { oldId: "304", newId: "usdu-usdu-finance", symbol: "USDU", name: "USDU Finance", issuer: "usdu-finance" },
  { oldId: "cg-ustb", newId: "ustb-superstate", symbol: "USTB", name: "Superstate USTB", issuer: "superstate", geckoId: "superstate-short-duration-us-government-securities-fund-ustb" },
  { oldId: "cg-ousg", newId: "ousg-ondo-finance", symbol: "OUSG", name: "Ondo OUSG", issuer: "ondo-finance", geckoId: "ousg" },
  { oldId: "cg-mtbill", newId: "mtbill-midas", symbol: "mTBILL", name: "Midas mTBILL", issuer: "midas", geckoId: "midas-mtbill" },
  { oldId: "cg-dinari-usd", newId: "usd-dinari", symbol: "USD+", name: "Dinari USD+", issuer: "dinari", geckoId: "dinari-usd" },
  { oldId: "cg-wrapped-savings-rusd", newId: "wsrusd-reservoir", symbol: "wsrUSD", name: "Wrapped Savings rUSD", issuer: "reservoir", geckoId: "wrapped-savings-rusd" },
  { oldId: "289", newId: "xsgd-straitsx", symbol: "XSGD", name: "StraitsX XSGD", issuer: "straitsx", geckoId: "xsgd" },
  { oldId: "122", newId: "gyen-gyen", symbol: "GYEN", name: "GYEN", issuer: "gyen", geckoId: "gyen" },
  { oldId: "165", newId: "audd-novatti", symbol: "AUDD", name: "AUDD", issuer: "novatti", geckoId: "novatti-australian-digital-dollar" },
  { oldId: "cg-jpyc", newId: "jpyc-jpyc", symbol: "JPYC", name: "JPY Coin", issuer: "jpyc", geckoId: "jpycoin" },
  { oldId: "gold-xaut", newId: "xaut-tether", symbol: "XAUT", name: "Tether Gold", issuer: "tether", geckoId: "tether-gold" },
  { oldId: "gold-paxg", newId: "paxg-paxos", symbol: "PAXG", name: "PAX Gold", issuer: "paxos", geckoId: "pax-gold" },
  { oldId: "gold-kau", newId: "kau-kinesis", symbol: "KAU", name: "Kinesis Gold", issuer: "kinesis", geckoId: "kinesis-gold" },
  { oldId: "gold-xaum", newId: "xaum-matrixdock", symbol: "XAUm", name: "Matrixdock Gold", issuer: "matrixdock", geckoId: "matrixdock-gold" },
  { oldId: "gold-cgo", newId: "cgo-comtech", symbol: "CGO", name: "Comtech Gold", issuer: "comtech", geckoId: "comtech-gold" },
  { oldId: "gold-dgld", newId: "dgld-gold-token-sa", symbol: "DGLD", name: "DGLD Tokenized Gold", issuer: "gold-token-sa", geckoId: "gold-token-sa-dgld-tokenized-gold" },
  { oldId: "silver-kag", newId: "kag-kinesis", symbol: "KAG", name: "Kinesis Silver", issuer: "kinesis", geckoId: "kinesis-silver" },
  { oldId: "52", newId: "ceur-celo", symbol: "CEUR", name: "Celo Euro", issuer: "celo", geckoId: "celo-euro" },
  { oldId: "158", newId: "veur-vnx", symbol: "VEUR", name: "VNX EURO", issuer: "vnx", geckoId: "vnx-euro" },
  { oldId: "239", newId: "eurr-stablr", symbol: "EURR", name: "StablR Euro", issuer: "stablr", geckoId: "stablr-euro" },
  { oldId: "247", newId: "europ-schuman", symbol: "EUROP", name: "Schuman EUROP", issuer: "schuman", geckoId: "schuman-europ" },
  { oldId: "cg-eurq", newId: "eurq-quantoz", symbol: "EURQ", name: "Quantoz EURQ", issuer: "quantoz", geckoId: "quantoz-eurq" },
  { oldId: "319", newId: "eurau-allunity", symbol: "EURAU", name: "AllUnity EUR", issuer: "allunity", geckoId: "allunity-eur" },
  { oldId: "cg-deuro", newId: "deuro-deuro", symbol: "DEURO", name: "Decentralized Euro", issuer: "deuro", geckoId: "decentralized-euro" },
  { oldId: "157", newId: "vchf-vnx", symbol: "VCHF", name: "VNX Swiss Franc", issuer: "vnx", geckoId: "vnx-swiss-franc" },
  { oldId: "292", newId: "vgbp-vnx", symbol: "VGBP", name: "VNX British Pound", issuer: "vnx", geckoId: "vnx-british-pound" },
  { oldId: "317", newId: "tgbp-tokenised", symbol: "tGBP", name: "Tokenised GBP", issuer: "tokenised", geckoId: "tokenised-gbp" },
  { oldId: "cg-zarp", newId: "zarp-zarp", symbol: "ZARP", name: "ZARP Stablecoin", issuer: "zarp", geckoId: "zarp-stablecoin" },
  { oldId: "186", newId: "isc-international-stable-currency", symbol: "ISC", name: "International Stable Currency", issuer: "international-stable-currency", geckoId: "international-stable-currency" },
  { oldId: "145", newId: "cadc-cad-coin", symbol: "CADC", name: "CAD Coin", issuer: "cad-coin", geckoId: "cad-coin" },
  { oldId: "299", newId: "pht-pht", symbol: "PHT", name: "PHT Stablecoin", issuer: "pht", geckoId: "pht-stablecoin" },
  { oldId: "cg-syrupusdc", newId: "syrupusdc-maple", symbol: "syrupUSDC", name: "Maple syrupUSDC", issuer: "maple", geckoId: "syrupusdc" },
  { oldId: "cg-syrupusdt", newId: "syrupusdt-maple", symbol: "syrupUSDT", name: "Maple syrupUSDT", issuer: "maple", geckoId: "syrupusdt" },
  { oldId: "cg-yousd", newId: "yousd-yield-optimizer", symbol: "yoUSD", name: "Yield Optimizer USD", issuer: "yield-optimizer", geckoId: "yield-optimizer-usd" },
  { oldId: "353", newId: "aid-gaib", symbol: "AID", name: "GAIB AID", issuer: "gaib", geckoId: "gaib-aid" },
  { oldId: "354", newId: "apxusd-apyx", symbol: "apxUSD", name: "apxUSD", issuer: "apyx" },
] as const;

export const SHADOW_ID_MAPPING = [
  { oldId: "3", newId: "ust-terra", symbol: "UST", name: "TerraUSD", issuer: "terra", geckoId: "terrausd" },
  { oldId: "iron-finance", newId: "iron-iron-finance", symbol: "IRON", name: "IRON", issuer: "iron-finance", geckoId: "iron-stablecoin" },
] as const;

export const DEAD_ID_MAPPING = [
  { oldId: "dead-usnbt-1", newId: "usnbt-nubits", symbol: "USNBT", name: "NuBits", issuer: "nubits" },
  { oldId: "dead-esd-2", newId: "esd-empty-set", symbol: "ESD", name: "Empty Set Dollar", issuer: "empty-set" },
  { oldId: "dead-dsd-3", newId: "dsd-dynamic-set", symbol: "DSD", name: "Dynamic Set Dollar", issuer: "dynamic-set" },
  { oldId: "dead-bac-4", newId: "bac-basis-cash", symbol: "BAC", name: "Basis Cash", issuer: "basis-cash" },
  { oldId: "dead-iron-5", newId: "iron-iron-finance-v1", symbol: "IRON", name: "IRON", issuer: "iron-finance-v1" },
  { oldId: "dead-vai-6", newId: "vai-venus", symbol: "VAI", name: "Vai", issuer: "venus", llamaId: "28" },
  { oldId: "dead-cash-7", newId: "cash-cashio", symbol: "CASH", name: "Cashio Dollar", issuer: "cashio" },
  { oldId: "dead-usdn-8", newId: "usdn-neutrino", symbol: "USDN", name: "Neutrino USD", issuer: "neutrino", llamaId: "12" },
  { oldId: "dead-bean-9", newId: "bean-beanstalk-v1", symbol: "BEAN", name: "Beanstalk v1", issuer: "beanstalk-v1" },
  { oldId: "3", newId: "ust-terra-classic", symbol: "UST", name: "TerraUSD", issuer: "terra-classic", llamaId: "3" },
  { oldId: "dead-krt-11", newId: "krt-terra", symbol: "KRT", name: "TerraKRW", issuer: "terra" },
  { oldId: "dead-dei-12", newId: "dei-deus", symbol: "DEI", name: "DEI", issuer: "deus" },
  { oldId: "dead-flexusd-13", newId: "flexusd-coinflex", symbol: "FLEXUSD", name: "flexUSD", issuer: "coinflex" },
  { oldId: "42", newId: "usdx-kava", symbol: "USDX", name: "Kava USDX", issuer: "kava", llamaId: "42" },
  { oldId: "63", newId: "fusd-fantom", symbol: "FUSD", name: "Fantom USD", issuer: "fantom", llamaId: "63" },
  { oldId: "dead-volt-16", newId: "volt-volt", symbol: "VOLT", name: "VOLT Protocol", issuer: "volt" },
  { oldId: "dead-fei-17", newId: "fei-fei", symbol: "FEI", name: "Fei USD", issuer: "fei", llamaId: "9" },
  { oldId: "31", newId: "usds-spice", symbol: "USDS", name: "SpiceUSD", issuer: "spice", llamaId: "31" },
  { oldId: "dead-husd-19", newId: "husd-huobi", symbol: "HUSD", name: "HUSD", issuer: "huobi", llamaId: "17" },
  { oldId: "54", newId: "usn-near", symbol: "USN", name: "USN", issuer: "near", llamaId: "54" },
  { oldId: "97", newId: "usp-unit-protocol", symbol: "USP", name: "USP Stablecoin", issuer: "unit-protocol", llamaId: "97" },
  { oldId: "dead-usds-22", newId: "usds-sperax", symbol: "USDs", name: "Sperax USD", issuer: "sperax", llamaId: "32" },
  { oldId: "dead-busd-23", newId: "busd-paxos", symbol: "BUSD", name: "Binance USD", issuer: "paxos", llamaId: "4" },
  { oldId: "dead-rsv-24", newId: "rsv-reserve-protocol", symbol: "RSV", name: "Reserve", issuer: "reserve-protocol" },
  { oldId: "dead-musd-25", newId: "musd-mstable", symbol: "MUSD", name: "mStable USD", issuer: "mstable", llamaId: "26" },
  { oldId: "dead-usdk-26", newId: "usdk-oklink", symbol: "USDK", name: "USDK", issuer: "oklink" },
  { oldId: "dead-usdp-27", newId: "usdp-unit-protocol", symbol: "USDP", name: "USDP Stablecoin", issuer: "unit-protocol" },
  { oldId: "76", newId: "usdi-interest-protocol", symbol: "USDI", name: "Interest Protocol", issuer: "interest-protocol", llamaId: "76" },
  { oldId: "dead-tor-29", newId: "tor-hector", symbol: "TOR", name: "TOR", issuer: "hector", llamaId: "29" },
  { oldId: "dead-usdc-m-30", newId: "usdc-m-multichain", symbol: "USDC.m", name: "Multichain USDC", issuer: "multichain" },
  { oldId: "dead-pai-31", newId: "pai-parrot", symbol: "PAI", name: "Parrot USD", issuer: "parrot", llamaId: "16" },
  { oldId: "dead-ausd-32", newId: "ausd-acala", symbol: "aUSD", name: "Acala USD", issuer: "acala" },
  { oldId: "61", newId: "fiat-fiatdao", symbol: "FIAT", name: "FIAT I", issuer: "fiatdao", llamaId: "61" },
  { oldId: "dead-vst-34", newId: "vst-vesta", symbol: "VST", name: "Vesta Stable", issuer: "vesta" },
  { oldId: "85", newId: "usdr-tangible", symbol: "USDR", name: "Real USD", issuer: "tangible", llamaId: "85" },
  { oldId: "115", newId: "r-raft", symbol: "R", name: "Raft R", issuer: "raft", llamaId: "115" },
  { oldId: "13", newId: "yusd-yeti", symbol: "YUSD", name: "YUSD Stablecoin", issuer: "yeti", llamaId: "13" },
  { oldId: "dead-ibeur-38", newId: "ibeur-iron-bank", symbol: "IBEUR", name: "Iron Bank EURO", issuer: "iron-bank", llamaId: "91" },
  { oldId: "dead-rai-39", newId: "rai-reflexer", symbol: "RAI", name: "Rai Reflex Index", issuer: "reflexer", llamaId: "40" },
  { oldId: "67", newId: "bean-beanstalk", symbol: "BEAN", name: "Bean", issuer: "beanstalk", llamaId: "67" },
  { oldId: "dead-eusd-41", newId: "eusd-lybra", symbol: "eUSD", name: "Lybra eUSD", issuer: "lybra", llamaId: "109" },
  { oldId: "dead-peusd-42", newId: "peusd-lybra", symbol: "peUSD", name: "Lybra peUSD", issuer: "lybra" },
  { oldId: "dead-pusd-43", newId: "pusd-jpegd", symbol: "PUSD", name: "JPEG'd PUSd", issuer: "jpegd" },
  { oldId: "dead-ush-44", newId: "ush-hedge", symbol: "USH", name: "Hedge USD", issuer: "hedge" },
  { oldId: "dead-star-45", newId: "star-preon", symbol: "STAR", name: "Preon STAR", issuer: "preon", llamaId: "123" },
  { oldId: "99", newId: "cash-stabl-fi", symbol: "CASH", name: "Stabl.fi Cash", issuer: "stabl-fi", llamaId: "99" },
  { oldId: "78", newId: "note-notional", symbol: "NOTE", name: "NOTE", issuer: "notional", llamaId: "78" },
  { oldId: "dead-seur-48", newId: "seur-synthetix", symbol: "sEUR", name: "Synthetix sEUR", issuer: "synthetix", llamaId: "53" },
  { oldId: "177", newId: "uno-nostra", symbol: "UNO", name: "Nostra UNO", issuer: "nostra", llamaId: "177" },
  { oldId: "dead-uxd-50", newId: "uxd-uxd", symbol: "UXD", name: "UXD Stablecoin", issuer: "uxd", llamaId: "64" },
  { oldId: "56", newId: "par-parallel", symbol: "PAR", name: "Parallel", issuer: "parallel", llamaId: "56" },
  { oldId: "dead-bob-52", newId: "bob-zkbob", symbol: "BOB", name: "zkBob BOB", issuer: "zkbob", llamaId: "84" },
  { oldId: "dead-mkusd-53", newId: "mkusd-prisma", symbol: "mkUSD", name: "Prisma mkUSD", issuer: "prisma", llamaId: "126" },
  { oldId: "dead-ultra-54", newId: "ultra-prismalrt", symbol: "ULTRA", name: "PrismaLRT ULTRA", issuer: "prismalrt" },
  { oldId: "dead-eurt-55", newId: "eurt-tether", symbol: "EURT", name: "Euro Tether", issuer: "tether", llamaId: "49" },
  { oldId: "dead-dai-56", newId: "dai-overnight", symbol: "DAI+", name: "Overnight DAI+", issuer: "overnight", llamaId: "111" },
  { oldId: "dead-usdv-57", newId: "usdv-verified", symbol: "USDV", name: "Verified USD", issuer: "verified" },
  { oldId: "dead-l-bold-58", newId: "l-bold-liquity", symbol: "L-BOLD", name: "Legacy BOLD", issuer: "liquity" },
  { oldId: "dead-usd-59", newId: "usd-overnight", symbol: "USD+", name: "USD+", issuer: "overnight", llamaId: "46" },
  { oldId: "132", newId: "usdm-mountain-protocol", symbol: "USDM", name: "Mountain Protocol USD", issuer: "mountain-protocol", llamaId: "132" },
  { oldId: "98", newId: "euroe-membrane", symbol: "EUROe", name: "EUROe", issuer: "membrane", llamaId: "98" },
  { oldId: "dead-dyad-62", newId: "dyad-dyad", symbol: "DYAD", name: "DYAD", issuer: "dyad" },
  { oldId: "dead-mod-63", newId: "mod-move", symbol: "MOD", name: "Move Dollar", issuer: "move", llamaId: "212" },
  { oldId: "dead-zusd-64", newId: "zusd-gmo", symbol: "ZUSD", name: "GMO ZUSD", issuer: "gmo" },
  { oldId: "dead-grai-65", newId: "grai-gravita", symbol: "GRAI", name: "Gravita GRAI", issuer: "gravita" },
  { oldId: "dead-hyusd-66", newId: "hyusd-reserve", symbol: "HYUSD", name: "High Yield USD", issuer: "reserve" },
  { oldId: "152", newId: "usdl-liquid-loans", symbol: "USDL", name: "Liquid Loans USDL", issuer: "liquid-loans", llamaId: "152" },
  { oldId: "dead-usdj-68", newId: "usdj-just", symbol: "USDJ", name: "JUST USDJ", issuer: "just", llamaId: "37" },
  { oldId: "dead-pinto-69", newId: "pinto-pinto", symbol: "PINTO", name: "Pinto", issuer: "pinto", llamaId: "232" },
  { oldId: "dead-lvlusd-70", newId: "lvlusd-level", symbol: "LVLUSD", name: "Level USD", issuer: "level", llamaId: "229" },
  { oldId: "dead-usdl-71", newId: "usdl-lift", symbol: "USDL", name: "Lift Dollar", issuer: "lift" },
  { oldId: "dead-csusdl-72", newId: "csusdl-coinshift", symbol: "csUSDL", name: "Coinshift csUSDL", issuer: "coinshift", llamaId: "243" },
  { oldId: "dead-deusd-73", newId: "deusd-elixir", symbol: "DEUSD", name: "Elixir deUSD", issuer: "elixir", llamaId: "210" },
  { oldId: "dead-usdx-74", newId: "usdx-stables-labs", symbol: "USDX", name: "Stables Labs USDX", issuer: "stables-labs" },
  { oldId: "dead-xusd-75", newId: "xusd-stream-finance", symbol: "xUSD", name: "Stream Finance xUSD", issuer: "stream-finance" },
  { oldId: "268", newId: "yu-yala", symbol: "YU", name: "YU", issuer: "yala", llamaId: "268" },
  { oldId: "315", newId: "uspd-permissionless", symbol: "USPD", name: "US Permissionless Dollar", issuer: "permissionless", llamaId: "315" },
  { oldId: "dead-pusd-78", newId: "pusd-palm", symbol: "PUSD", name: "Palm USD", issuer: "palm" },
] as const;
