import { defineBatch, type RedemptionBackstopRegistryEntry } from "../factory";
import { documentedBoundSupplyFull, issuerBase } from "../shared";
import {
  reviewedDirectRedemptionSupplyFull,
  REVIEWED_NON_USD_BATCH_AT,
  REVIEWED_REMEDIATION_AT,
} from "./shared";

export const BASE_OFFCHAIN_ISSUER_ENTRIES: RedemptionBackstopRegistryEntry[] = [
  ...defineBatch(
    [
      "usdt-tether",
      "usdc-circle",
      "pyusd-paypal",
      "fdusd-first-digital",
      "rlusd-ripple",
      "eurc-circle",
      "usdp-paxos",
      "gusd-gemini",
      "usdg-paxos",
      "usdx-hex-trust",
      "xusd-straitsx",
      "xsgd-straitsx",
      "euri-banking-circle",
      "usdq-quantoz",
      "eurq-quantoz",
      "usd1-world-liberty-financial",
      "ausd-agora",
      "usdo-openeden",
      "usdm-moneta",
      "usdcv-societe-generale-forge",
      "usdh-native-markets",
      "fidd-fidelity",
      "usdgo-osl",
      "wusd-worldwide",
      "sbc-brale",
      "m-m0",
      "usda-anzens",
      "eurcv-societe-generale-forge",
      "aeur-anchored-coins",
      "eure-monerium",
      "usdr-stablr",
      "eurr-stablr",
      "europ-schuman",
      "eurau-allunity",
      "chfau-allunity",
      "tusd-trueusd",
      "eurs-stasis",
      "gyen-gyen",
      "brz-transfero",
      "tryb-bilira",
      "idrt-rupiah-token",
      "jpyc-jpyc",
      "cadc-cad-coin",
      "tgbp-tokenised",
      "veur-vnx",
      "vchf-vnx",
      "vgbp-vnx",
      "audd-novatti",
      "axcnh-anchorx",
      "mnee-mnee",
      "cash-phantom",
      "musd-metamask",
      "a7a5-old-vector",
      "ylds-figure",
      "usat-tether",
      "usdtb-ethena",
      "pusd-plume",
      "gusd-gate",
      "usyc-hashnote",
      "ustb-superstate",
      "tbill-openeden",
      "usdn-noble",
      "reur-royal-euro",
      "kgst-kyrgyz-som",
      "audx-aussie-dollar-token",
      "cngn-compliant-naira",
      "brl1-brl1",
      "wars-argentine-peso",
    ],
    issuerBase,
  ),
  ...defineBatch(
    ["zarp-zarp", "cetes-etherfuse"],
    {
      ...issuerBase,
      ...documentedBoundSupplyFull(REVIEWED_REMEDIATION_AT),
    },
  ).map((entry) => ({
    ...entry,
    overrideReason: "Remediation review upgrades offchain issuer default to documented-bound capacity.",
  })),
  ...defineBatch(
    [
      "audx-aussie-dollar-token",
      "brl1-brl1",
      "cngn-compliant-naira",
      "kgst-kyrgyz-som",
      "reur-royal-euro",
      "wars-argentine-peso",
      "eusd-telcoin",
      "jpyc-jpyc-v1",
      "rusd-royal-dollar",
    ],
    {
      ...issuerBase,
      ...documentedBoundSupplyFull(REVIEWED_NON_USD_BATCH_AT),
    },
  ).map((entry) => ({
    ...entry,
    overrideReason: "Non-USD review cohort upgrades issuer defaults to documented-bound capacity.",
  })),
  ...defineBatch(["usyc-hashnote", "ustb-superstate", "a7a5-old-vector", "gusd-gate"], {
    ...issuerBase,
    ...reviewedDirectRedemptionSupplyFull,
  }).map((entry) => ({
    ...entry,
    overrideReason: "Direct-redemption review cohort upgrades issuer defaults to documented-bound capacity.",
  })),
];
