import type { RedemptionBackstopConfig } from "../shared";
import { documentedVariableFee, fixedFee, issuerBase, sourceRef, undisclosedReviewedFee } from "../shared";

/** Source-reviewed issuer routes from the October 2026 discovery wave.
 * Supply-full is eventual-only: reviewed legal entitlements may be documented-bound,
 * but neither that confidence nor current supply proves immediate executable capacity.
 * Each route withholds scoring for its explicitly missing executable terms. */
export const DISCOVERY_OFFCHAIN_ISSUER_CONFIGS: Record<string, RedemptionBackstopConfig> = {
  "xgz-goldzip": {
    ...issuerBase,
    capacityModel: { kind: "unquantified" },
    reviewedAt: "2026-10-07",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "opaque",
    outputAssetType: "physical-commodity-delivery",
    physicalCommodityDelivery: {
      commodity: "XAU",
      deliverableOuncesPerToken: 0.9999 / 31.1034768,
      minimumDeliveryTokens: 1_000,
      deliveryTermsUnbounded: true,
      feeModel: { bps: 0, flatUsd: 0, deliveryUsd: 0 },
      sameNotionalEligible: false,
    },
    costModel: undisclosedReviewedFee("Physical delivery, assay, logistics and redemption fees undisclosed. The 0.01% sender fee is a transfer fee only."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "The physical claim and 1,000-token delivery lot do not establish a full-supply USD redemption right or measured delivery throughput. No physical-to-USD proceeds, delivery completion deadline or all-in delivery/assay/logistics cost bound is published; the 0.01% sender fee is a transfer fee only.",
      reviewedAt: "2026-10-07",
      docs: [sourceRef("GoldZip physical claim and redemption", "https://goldzip.info/GZ_UPDATED_LITEPAPER_03.11.pdf", ["route"])],
    },
    docs: [
      sourceRef("GoldZip physical claim and redemption", "https://goldzip.info/GZ_UPDATED_LITEPAPER_03.11.pdf", ["route", "access"]),
      sourceRef("GoldZip resident restriction and bar lot", "https://goldzip.info/", ["route", "access"]),
    ],
    notes: [
      "Eligibility: AML compliance; Hong Kong residents excluded.",
      "Minimum: 1,000 XGZ per eligible delivery bar; each token represents one gross gram of 99.99%-fine gold. deliverableOuncesPerToken expresses fine-gold content (0.9999 grams / 31.1034768), while the token's nominal commodity unit is one gross gram.",
      "Do not borrow XAUT 430-token deposit or Swiss delivery terms. XGZ 1,000-token lot is 1kg nominal gold; no dealer-sale USD proceeds, fee or capacity is invented.",
      "No physical-to-USD composition is authored: delivery timing, vault pickup details and logistics cost are not bounded. Zero physical feeModel deductions mean no published USD deduction, not free delivery; the 0.01% transfer fee is not a redemption fee.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "usdu-universal": {
    ...issuerBase,
    capacityModel: { kind: "supply-full", confidence: "documented-bound", basis: "issuer-term-redemption" },
    reviewedAt: "2026-10-07",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    costModel: undisclosedReviewedFee("Fees payable; public numeric redemption fee schedule not pinned."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "The January 2026 whitepaper establishes eligible holders' eventual 1:1 USD legal claim after Aquanow onboarding and wallet checks; it does not measure immediate executable capacity. The stated two-business-day period can extend in extreme conditions with FSRA notice or direction and does not bound final bank credit. Fees are payable but the numeric schedule and all-in cost are unpublished; capacity, settlement and cost scoring remain withheld.",
      reviewedAt: "2026-10-07",
      docs: [sourceRef("USDU January 2026 whitepaper", "https://cdn.prod.website-files.com/644c2f7bb9ee913b81ea51df/69a5e87340361f8d03e80be5_USDU_Whitepaper_English_Arabic_Jan_2026.pdf", ["route", "capacity", "access", "fees", "settlement"])],
    },
    docs: [
      sourceRef("USDU January 2026 whitepaper", "https://cdn.prod.website-files.com/644c2f7bb9ee913b81ea51df/69a5e87340361f8d03e80be5_USDU_Whitepaper_English_Arabic_Jan_2026.pdf", ["route", "capacity", "access", "fees", "settlement"]),
      sourceRef("ADGM FSRA issuer register FSP250089", "https://www.adgm.com/public-registers/fsra/firms/financial-firms/universal-digital-intl-limited-250089", ["access"]),
    ],
    notes: [
      "Eligibility: Aquanow-onboarded professional clients after KYC/AML; issuer FSRA permission excludes retail clients.",
      "Minimum: $100,000 appears in the whitepaper's benchmark table dated September 12, 2025, not a fixed January 2026 contractual minimum. The minimum may change; no current numeric minimum is modeled.",
      "Do not inherit Paxos 25% hot-buffer capacity or fee values.",
      "Documented full-position entitlement is eventual-only and eligibility-gated; insolvency proceeds may be pro rata. Reserve examination/backing is not redemption capacity; no immediate USD amount, unconditional bank-credit duration or all-in fee bound is inferred.",
    ],
  },
  "filqa-fidelity-international": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "nav",
    costModel: undisclosedReviewedFee("Outside-market-hours redemption fee is 0.02% of NAV per day plus network gas, subject to directors changing terms."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Redemption is recognized investor exit; current unconditional off-hours or stress capacity not disclosed. Normal valuation21:00UK; usual dealing01:00-21:00London eligible weekdays. Off-hours facilities conditional; gates or suspension can extend realization. No guaranteed payout deadline asserted. Outside-market-hours redemption fee0.02%NAV per day plus network gas, subject to directors changing terms; maximum TER0.50% is a separate annual operating expense, not a redemption fee. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Fidelity September 14, 2026 fund prospectus (primary text recovered October 9)", "https://www.fidelityinternational.com/legal/documents/FISGF/en/pr.fisgf.en.xx.pdf", ["route"])],
    },
    docs: [
      sourceRef("Fidelity September 14, 2026 fund prospectus (primary text recovered October 9)", "https://www.fidelityinternational.com/legal/documents/FISGF/en/pr.fisgf.en.xx.pdf", ["route", "fees", "access", "settlement"]),
    ],
    notes: [
      "Eligibility: Onboarded eligible qualified/professional investors; prospectus subscriptions/redemptions through TA or Token Distributor.",
      "Minimum: Class initial investment approximately$100,000; distinct redemption-specific minimum not established.",
      "Token transfers are legally unrecognized for on-chain investors; no secondary trading route or instant supply-full capacity credited.",
      "Models the prospectus cash-to-USD-bank-account branch only. Distributor stablecoin conversion is a separate service with an unenumerated approved payout set, not an inferred USDC route.",
      "The maximum TER of 0.50% is a separate annual operating expense, not a redemption fee or a capacity limit.",
      "Source recovery observed 2026-10-09T10:33:44Z by Sol curation campaign 2026-10-09 (Lane34Usual): the September 14, 2026 primary prospectus text was retrieved through https://r.jina.ai/https://www.fidelityinternational.com/legal/documents/FISGF/en/pr.fisgf.en.xx.pdf and corroborated against Sygnum's FILQ FAQ. It prohibits recognized on-chain token transfers and requires redemption through the TA Administrator or Token Distributor. Stablecoin liquidity is limited to credit-facility/provider capacity; outside-hours orders may queue, and gates or suspension may apply. No executable same-notional capacity, guaranteed payout deadline or all-in fee bound is disclosed; source recovery does not promote those scoring fields or refresh the September prospectus date.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "eurw-newrails": {
    ...issuerBase,
    capacityModel: { kind: "supply-full", confidence: "documented-bound", basis: "issuer-term-redemption" },
    reviewedAt: "2026-10-07",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    costModel: fixedFee(0, "Zero issuer redemption fee; receiving-bank and blockchain network charges may apply."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "The policy establishes all holders' eventual par redemption right, including secondary purchasers, subject to identity, wallet control, AML and own-name SEPA-account checks. That entitlement does not quantify immediate executable liquidity. Without undue delay is not a numeric bank-credit SLA; legal/network/recovery measures can restrict execution, including pro-rata recovery. Zero issuer fees exclude receiving-bank/network charges, so all three scoring gaps remain.",
      reviewedAt: "2026-10-07",
      docs: [sourceRef("Newrails EMT redemption policy effective February 9, 2026", "https://www.newrails.xyz/en/legal/emt-redemption-policy", ["route", "capacity", "access", "fees", "settlement"])],
    },
    docs: [
      sourceRef("Newrails EMT redemption policy effective February 9, 2026", "https://www.newrails.xyz/en/legal/emt-redemption-policy", ["route", "capacity", "access", "fees", "settlement"]),
      sourceRef("Newrails EURW MiCA whitepaper notified May 26, 2026", "https://cmpl-docs.newrails.xyz/docs/Newrails%20EURW%20WP%202026-05-26.xhtml", ["route", "capacity", "access", "fees", "settlement"]),
      sourceRef("Bank of Lithuania Newrails EMI and EMT issuer register", "https://www.lb.lt/en/sfi-financial-market-participants/newrails-uab", ["access"]),
    ],
    notes: [
      "Eligibility: Any natural or legal holder after identity, wallet-control and own-name SEPA-bank-account verification; customers use the platform, other holders may onboard or contact eurw@newrails.xyz.",
      "Minimum: Undisclosed",
      "Documented full-holder entitlement is eventual-only, not permissionless execution or immediate full-supply liquidity. No numeric settlement SLA or minimum is published; the recovery plan's 60-day endeavor is not a normal payout guarantee.",
    ],
  },
  "brsrv-blackrock": {
    ...issuerBase,
    capacityModel: { kind: "supply-full", confidence: "documented-bound", basis: "issuer-term-redemption" },
    reviewedAt: "2026-10-07",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "nav",
    costModel: fixedFee(0, "No sales/redemption sales charge per prospectus; investor network gas and intermediary charges may apply."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "The July 2026 prospectus establishes registered OnChain shareholders' eventual NAV redemption through the Transfer Agent, not a funded instant USD/USDC facility. Good-order requests before 5pm ET ordinarily receive same-day federal-funds wire if the custodian is open; the Fund may take seven days and legal/emergency exceptions permit further delay. Fixed-zero issuer fees exclude gas/intermediary charges. Immediate capacity, unconditional completed settlement and all-in cost remain unbounded.",
      reviewedAt: "2026-10-07",
      docs: [sourceRef("BlackRock July 31, 2026 OnChain share prospectus", "https://www.blackrock.com/cash/literature/prospectus/pro-brsrv.pdf", ["route", "capacity", "access", "fees", "settlement"])],
    },
    docs: [
      sourceRef("BlackRock July 31, 2026 OnChain share prospectus", "https://www.blackrock.com/cash/literature/prospectus/pro-brsrv.pdf", ["route", "capacity", "access", "fees", "settlement"]),
      sourceRef("BlackRock RSVXX OnChain share-class identity and fund reporting", "https://www.blackrock.com/cash/en-us/products/351891/blackrock-daily-reinvestment-stablecoin-reserve-vehicle-onchain-shares", ["route"]),
      sourceRef("BlackRock BRSRV launch and Securitize transfer-agent identity", "https://www.blackrock.com/cash/en-us/press-release-t3", ["route", "access"]),
    ],
    notes: [
      "Eligibility: Registered whitelisted investors through Securitize; $3M initial investment (not a redemption minimum).",
      "Minimum: No subsequent investment minimum; redemption-specific minimum not found.",
      "Blockchain outages do not suspend off-chain good-order redemption processing. Do not credit full instant capacity or third-party facility capacity.",
      "Documented shareholder entitlement is eventual-only. BRSRV identifies the fund/product and RSVXX its OnChain share class, not a second asset; fund AUM and Rule 2a-7 liquid-asset ratios are not executable redemption capacity.",
    ],
  },
  "zaru-blocktower": {
    ...issuerBase,
    capacityModel: { kind: "unquantified" },
    reviewedAt: "2026-10-07",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "opaque",
    outputAssetType: "stable-single",
    costModel: undisclosedReviewedFee("Partner/issuer fees not numerically disclosed"),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "The whitepaper refers holders to separate Platform/ZARU Terms that are not publicly established here. Referral and historical 101.78% reserve coverage do not prove a full-supply legal USD claim or executable capacity. Five-business-day fiat wording is not an unconditional completed-settlement SLA; partner/issuer fees are not numerically disclosed. Capacity, settlement and all-in cost remain unquantified.",
      reviewedAt: "2026-10-07",
      docs: [sourceRef("ZARU whitepaper updated July 21, 2026", "https://framerusercontent.com/assets/pbLBuQ5dcf9LCfFb3DHZ9qgc.pdf", ["route", "access", "settlement"])],
    },
    docs: [
      sourceRef("ZARU whitepaper updated July 21, 2026", "https://framerusercontent.com/assets/pbLBuQ5dcf9LCfFb3DHZ9qgc.pdf", ["route", "access", "settlement"]),
    ],
    notes: [
      "Eligibility: Verified institutions directly; retail through network partners, with issuer contingency claim",
      "Minimum: Partner-defined thresholds, numerical minimum not published",
      "No full-supply USD quantity is modeled: missing separate Platform/ZARU Terms cannot be replaced by whitepaper referral or reserve coverage. Current executable capacity, unconditional payout timing and numeric all-in fees remain unavailable.",
    ],
  },
  "frnt-wyoming": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    costModel: undisclosedReviewedFee("Commission fee disclosed as zero; LSP and payment-rail all-in charges are not quantified."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Current executable LSP capacity and minimum are not public. Trust balance is eventual backing, not an immediate redemption-capacity measure. Commission submits the USD notional value promptly, no more than two Business Days for an authenticated approved-LSP Redemption Request made in business hours. Out-of-hours requests are treated as next-Business-Day requests. Section 4 permits delays for unforeseen circumstances; bank receipt time is not guaranteed by this submission deadline. Commission fee disclosed as zero; LSP and payment-rail all-in charges are not quantified. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Wyoming reserve and redemption rules, Chapter 4", "https://stabletoken.wyo.gov/assets/media/reserves.pdf", ["route"])],
    },
    docs: [
      sourceRef("Wyoming reserve and redemption rules, Chapter 4 (prior review)", "https://stabletoken.wyo.gov/assets/media/reserves.pdf", ["route", "fees", "access", "settlement"]),
      sourceRef("Commission issuance/redemption and fee disclosure", "https://stabletoken.wyo.gov/assets/IssuanceRedemptionPage-CM6vPxSM.js", ["route", "fees", "access"]),
    ],
    notes: [
      "Eligibility: Direct issuance/redemption restricted to approved KYB Licensed Service Providers. Ordinary retail exit is through an LSP; Commission direct-holder fallback applies only under the rules’ specified conditions.",
      "Minimum: Not publicly disclosed in retrieved issuance/redemption materials.",
      "Use LSP-gated eligibility, not permissionless issuer redemption. Preserve conditional direct-holder fallback, special-obligation limitation, unknown capacity, unknown minimum and service-provider cost gaps.",
      "Models only approved Licensed Service Providers. The Commission fee is zero; LSP and bank costs remain unquantified. Retail access and the conditional direct-holder fallback are not generalized to permissionless issuer access.",
      "October 7, 2026 direct current-terms retrieval failed TLS verification. Proposed rules and WYST wording do not establish current FRNT identity, eligibility, capacity or a final holder payout SLA; prior route claims are not positively refreshed.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "gbpa-agant": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    costModel: undisclosedReviewedFee("Platform may charge fees; numerical redemption/all-in schedule undisclosed."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Undisclosed; reserve snapshot is not executable capacity and public full-holder/backstop terms were not retrieved. Off-ramp docs describe immediate conversion and subsequent bank delivery, without a numerical bank-credit SLA. Platform may charge fees; numerical redemption/all-in schedule undisclosed. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Agant business platform terms", "https://app.agant.io/terms-of-service", ["route"])],
    },
    docs: [
      sourceRef("Agant business platform terms (Distribution Agreement controls)", "https://app.agant.io/terms-of-service", ["route", "fees", "access", "settlement"]),
      sourceRef("Agant off-ramp Rails procedure", "https://docs.agant.io/XDREhsGKwMiuddKPr5Rt/platform/off-ramp.md", ["route", "access", "settlement"]),
    ],
    notes: [
      "Eligibility: Approved UK-incorporated, appropriately FCA-authorized/registered business distribution customers completing KYB/KYC; retail holders must use a distribution customer.",
      "Minimum: Undisclosed",
      "Model only the business issuer route. Do not copy same-day/days bounds, full-supply capacity or zero fee from precedent without evidence. Holder Terms and Distribution Agreement remain gaps.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "usdsm-stable-mint": {
    ...issuerBase,
    capacityModel: { kind: "supply-full", confidence: "documented-bound", basis: "issuer-term-redemption" },
    reviewedAt: "2026-10-07",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    costModel: fixedFee(0, "Issuer redemption fee zero; third-party bank and intermediary charges can apply and are unquantified."),
    v9RouteReviewTerms: {
      minRedeemUsd: 0,
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Section 9 establishes any holder's eventual par claim for any amount, including redemption-only clients after issuer acceptance/KYC/wallet checks; no minimum applies. That legal entitlement does not measure immediate executable daily liquidity. Without undue delay and indicative private-platform periods do not bound final bank receipt. Issuer fee zero excludes bank/intermediary charges; all three scoring gaps remain.",
      reviewedAt: "2026-10-07",
      docs: [sourceRef("Stable Mint terms effective August 14, 2026, sections 5, 6 and 9", "https://stablemint.io/legal/terms-conditions/", ["route", "capacity", "access", "fees", "settlement"])],
    },
    docs: [
      sourceRef("Stable Mint terms effective August 14, 2026, sections 5, 6 and 9", "https://stablemint.io/legal/terms-conditions/", ["route", "capacity", "access", "fees", "settlement"]),
    ],
    notes: [
      "Eligibility: Legal and natural holders after issuer acceptance and full AML/KYC onboarding, including Redemption-Only Clients; no self-serve registration.",
      "Minimum: No minimum applies to redemption under section 9.1.",
      "Documented any-amount par entitlement is eventual-only, including the specified surviving claim after termination. The days category is diagnostic, not a numeric SLA; no immediate capacity or all-in zero-cost assumption is inferred.",
    ],
  },
  "chfsafo-spiko": {
    ...issuerBase,
    capacityModel: { kind: "supply-full", confidence: "documented-bound", basis: "issuer-term-redemption" },
    reviewedAt: "2026-10-07",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "nav",
    costModel: fixedFee(0, "Exact KID/API report no fund entry/exit fee; exceptional swing pricing up to 0.5% and operational/DLT/bank costs are not an all-in zero-cost guarantee. API management fee is 0.15% annually; the July KID 0.09% ongoing estimate is a different dated cost disclosure."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "The September SICAV prospectus establishes eligible shareholders' eventual NAV redemption; the 25%-NAV gate and carried-forward requests do not establish an immediate buffer. Gates can apply for 20 valuation days over three months without carry-forward precedence. Ordinary D+1 after 15:00 Paris centralization remains holiday/gate/suspension-dependent, not a completed-settlement scalar. Issuer exit fee zero excludes swing pricing up to 0.5% and bank/network costs. All three scoring gaps remain.",
      reviewedAt: "2026-10-07",
      docs: [sourceRef("Spiko SICAV prospectus, 1 September 2026", "https://cdn.spiko.finance/legal_docs/EN/Prospectus_Spiko_SICAV_EN.pdf", ["route", "capacity", "access", "fees", "settlement"])],
    },
    docs: [
      sourceRef("Spiko SICAV prospectus, 1 September 2026", "https://cdn.spiko.finance/legal_docs/EN/Prospectus_Spiko_SICAV_EN.pdf", ["route", "capacity", "access", "fees", "settlement"]),
      sourceRef("Exact CHF KID, ISIN FR0014015LG6", "https://cdn.spiko.finance/legal_docs/EN/KID_chfSAFO_EN.pdf", ["route", "fees", "access"]),
      sourceRef("Exact CHF share-class register, minimum and fee terms", "https://public-api.spiko.io/share-classes/chfSAFO", ["route", "fees", "access"]),
    ],
    notes: [
      "Eligibility: KYC/allowlisted fund shareholder; US persons excluded by exact KID.",
      "Minimum: Issuer chfSAFO API minimumRedemption = 1; prospectus class minimum CHF 1.",
      "Do not inherit EUR Chainlink oracle or EUR fiat-to-USD exit conversion. CHF reference/FX conversion is required for USD-notional scoring.",
      "Documented entitlement is eventual-only. The CHF 1 minimum is not translated into a USD minimum; D+1 is not converted to seconds. Share-class totals timestamp NAV/assets, not executable capacity; neither AUM nor the 25% gate is a buffer.",
    ],
  },
  "pyusdx-moonpay": {
    ...issuerBase,
    reviewedAt: "2026-10-07",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    outputAssets: ["pyusd-paypal"],
    costModel: fixedFee(0, "MoonPay charges no issuer redemption fee for PYUSDx to PYUSD; network and other operational charges remain unquantified."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "MoonPay's August 5, 2026 terms charge no issuer fee for PYUSDx-to-PYUSD redemption, but network/operational costs remain unbounded. Only accepted Eligible Counterparties can request services; downstream holders have no direct redemption right. PYUSD-only payout and commercially reasonable efforts can be limited/deferred/frozen; no current executable capacity, numeric minimum or unconditional payout SLA is established. Heuristic capacity and all three scoring gaps remain.",
      reviewedAt: "2026-10-07",
      docs: [sourceRef("MoonPay PYUSDx terms updated August 5, 2026", "https://www.moonpay.com/legal/pyusdx_terms", ["route", "fees", "access", "settlement"])],
    },
    docs: [
      sourceRef("MoonPay PYUSDx terms updated August 5, 2026", "https://www.moonpay.com/legal/pyusdx_terms", ["route", "fees", "access", "settlement"]),
    ],
    notes: [
      "Eligibility: MoonPay-accepted Eligible Counterparties only; downstream holders have no direct services/redemption right and must separately qualify. U.S., EEA, Canada, India and Australia excluded.",
      "Minimum: Undisclosed public numeric minimum",
      "Fixed token-for-token issuer conversion pays exclusively PYUSD. Fixed-zero models only MoonPay's issuer fee, not network/operational all-in cost or permissionless atomic execution; no capacity or settlement promotion follows.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "stbt-matrixdock": {
    ...issuerBase,
    capacityModel: { kind: "unquantified" },
    reviewedAt: "2026-10-07",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-basket",
    outputAssets: ["usdc-circle", "usdt-tether"],
    costModel: fixedFee(0, "April 28 2026 update states 0% redemption fee; signed terms permit liquidation losses and transactional costs. Custody fee 0.20% p.a. affects yield."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "The right to redeem token quantities does not establish 100% market-cap USD proceeds: signed terms permit payout down to 10% of initial contribution, trading losses and transaction costs. The published USD 1M T+0 threshold is a limit, not a funded buffer; T+2 above remains subject to legal/account restrictions. Issuer fee zero excludes deductions/gas. No USD-equivalent capacity, unconditional end-to-end settlement or all-in cost bound is established.",
      reviewedAt: "2026-10-07",
      docs: [sourceRef("STBT January 2025 terms", "https://2505056629-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FZx9GNWaNV9JB3JZlW74D%2Fuploads%2FzHip8cJaP5aud3KfdVud%2FSTBT%20Token%C2%A0Terms%20and%20Conditions.pdf?alt=media&token=79d5fd49-deae-41b4-a809-9e1afaa02f32", ["route"])],
    },
    docs: [
      sourceRef("STBT January 2025 terms", "https://2505056629-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FZx9GNWaNV9JB3JZlW74D%2Fuploads%2FzHip8cJaP5aud3KfdVud%2FSTBT%20Token%C2%A0Terms%20and%20Conditions.pdf?alt=media&token=79d5fd49-deae-41b4-a809-9e1afaa02f32", ["route", "fees", "access", "settlement"]),
      sourceRef("April 2026 settlement and fee update", "https://matrixdock.gitbook.io/matrixdock-docs/english/announcements/stbt-custodian-and-conversion-fee-reduction-and-settlement-optimization.md", ["route", "fees", "settlement"]),
    ],
    notes: [
      "Eligibility: Accredited non-U.S. investors with approved accounts and allowlisted transfers.",
      "Minimum: Current redemption minimum not established; UK acquisition threshold is not a redemption minimum.",
      "Operational 2026 fee/settlement update and January 2025 legal account-only wording are not fully harmonized; preserve unsecured claim and payout losses.",
      "The published USD 1M T+0 threshold is a route limit, not a guaranteed funded buffer; no fixed-usd capacity is authored. Zero issuer fee excludes liquidation losses, transactional costs and gas permitted by governing terms.",
      "Any-token redemption language is not full USD-value entitlement: signed terms allow proceeds down to 10% of initial contribution and trading/transaction deductions. No eventual full-supply USD amount is modeled.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "fiusd-sygnum": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "nav",
    costModel: undisclosedReviewedFee("Historical March 2025 application: 40 bps redemption, 20 bps subscription and 25 bps annual management; bank fees may apply and terms can change. Current binding client tariff unavailable"),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Not publicly quantified for the current same-notional holder route; no fund AUM proxy and no instant stress capacity credited Underlying fund same-day dealing with business-day cutoffs; current token/account credit deadline not publicly committed Historical March 2025 application: 40 bps redemption, 20 bps subscription and 25 bps annual management; bank fees may apply and terms can change. Current binding client tariff unavailable No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Sygnum issuer-authored FIUSD application dated March 20, 2025", "https://forum.arbitrum.foundation/t/sygnum-bank-ag-fidelity-international-fiusd-step-2-application/28779", ["route"])],
    },
    docs: [
      sourceRef("Sygnum historical FIUSD application dated March 20, 2025", "https://forum.arbitrum.foundation/t/sygnum-bank-ag-fidelity-international-fiusd-step-2-application/28779", ["route", "fees", "access"]),
      sourceRef("Verified deployed Arbitrum implementation", "https://arbitrum.blockscout.com/api/v2/smart-contracts/0x7616b08676117e1aab542e53fe3f7b12f7596d37", ["route", "access"]),
    ],
    notes: [
      "Eligibility: Professional bank clients with Sygnum-custodied whitelisted wallets",
      "Minimum: Historical underlying Class G has no subscription/holding minimum; current token-level bank-client minimum is not publicly established",
      "Do not admit the historical $25M collateralized off-hours lending concept as current guaranteed redemption capacity; client contract is private.",
      "Models the documented USD cash credit to the professional Sygnum investor account, not an unenumerated crypto withdrawal. The March 2025 40 bps redemption tariff is historical and is not a current fee bound; the $25M off-hours lending concept is not funded holder redemption capacity.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "cumiu-chinaamc": {
    ...issuerBase,
    capacityModel: { kind: "supply-full", confidence: "documented-bound", basis: "issuer-term-redemption" },
    reviewedAt: "2026-10-07",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "nav",
    costModel: documentedVariableFee("KFS up to 5% redemption charge; prospectus anti-dilution charge up to 5% when single investor redemption >=20% NAV. These distinct charges are not a single 5% all-in ceiling. Distributor/bank charges additional; do not substitute website up-to-1% marketing."),
    v9RouteReviewTerms: {
      minRedeemUsd: 1000,
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "The September prospectus establishes eligible shareholders' whole/part-position eventual redemption with deferred-request priority until satisfied in full. A 10%-NAV dealing-day gate is not funded executable liquidity. Normally distributor receipt T+1 plus one further business day to the investor remains subject to extreme-market, FX and regulatory delays, not a numeric unconditional completion SLA. Redemption and anti-dilution charges up to 5% each are separate, with additional distributor/bank costs; all three scoring gaps remain.",
      reviewedAt: "2026-10-07",
      docs: [sourceRef("ChinaAMC September 14, 2026 prospectus", "https://www.chinaamc.com.hk/jeecg-boot/sys/common/static/temp/E-CleanProspectus-ChinaAMCDigitalOFC-CN(September2026)_1789336483417.pdf", ["route", "capacity", "access", "fees", "settlement"])],
    },
    docs: [
      sourceRef("ChinaAMC September 14, 2026 prospectus", "https://www.chinaamc.com.hk/jeecg-boot/sys/common/static/temp/E-CleanProspectus-ChinaAMCDigitalOFC-CN(September2026)_1789336483417.pdf", ["route", "capacity", "access", "fees", "settlement"]),
      sourceRef("ChinaAMC tokenized unlisted class key facts", "https://www.chinaamc.com.hk/jeecg-boot/sys/common/static/chinaamc/resources/E-KFS-ChinaAMCUSDDigitalMMF(UnlistedClass)(April2026).pdf", ["route", "fees", "access", "settlement"]),
    ],
    notes: [
      "Eligibility: Class I USD through eligible distributors; retail requires distributor trading/custody account.",
      "Minimum: Class I USD 1000 redemption and remaining holding minimum.",
      "Documented full-position entitlement is eventual-only and distributor-gated, with carried-forward request priority until full satisfaction. The 10%-NAV gate and holdings/audit figures are not an immediate buffer; no calendar-day completion maximum or all-in fee ceiling is modeled.",
    ],
  },
  "uscc-superstate": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    outputAssets: ["usdc-circle"],
    costModel: undisclosedReviewedFee("Investor-borne gas and wire fees; current additional fund-specific redemption charges undisclosed"),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Not publicly quantified for the current same-notional holder route; no fund AUM proxy and no instant stress capacity credited T+1 before 5pm ET cutoff, T+2 after, market days Investor-borne gas and wire fees; current additional fund-specific redemption charges undisclosed No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("USCC fund, service providers and October 1 holdings", "https://superstate.com/assets/uscc", ["route"])],
    },
    docs: [
      sourceRef("USCC fund identity and service providers", "https://superstate.com/assets/uscc", ["route"]),
      sourceRef("USCC operational investor docs (binding Fund Documents remain private)", "https://docs.superstate.com/investors/tokenized-funds/available-funds/bitwise-uscc", ["route", "fees", "access", "settlement"]),
      sourceRef("Superstate deployments and administrative powers", "https://docs.superstate.com/investors/smart-contracts", ["route", "access"]),
      sourceRef("Superstate redemption procedure", "https://docs.superstate.com/investors/tokenized-funds/redeem", ["route", "fees", "access", "settlement"]),
    ],
    notes: [
      "Eligibility: Qualified Purchasers in supported jurisdictions, onboarded and allowlisted through Superstate",
      "Minimum: $100,000 initial subscription unless waived; redemption minimum not separately published",
      "Use documented market-day operational route only; do not copy USTB atomic-USDC liquidity config or assert full circulating-supply capacity.",
      "Models the explicitly documented USDC payout choice on Ethereum/Solana; the separately documented USD wire branch is not combined into an invented mixed basket. USCC is crypto-carry strategy exposure, not USTB, and neither AUM nor initial-subscription minimum establishes exit capacity or redemption minimum.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "mxnt-tether": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "opaque",
    outputAssetType: "stable-single",
    costModel: { ...documentedVariableFee("Greater of USD 1,000 or 0.1%; verification USD 150"), feeBpsMax: 10, minFeeUsd: 1_000 },
    v9RouteReviewTerms: {
      minRedeemUsd: 100000,
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Undisclosed; no executable capacity is inferred from historical reserves No guaranteed settlement deadline; issuer suspension rights apply Greater of USD 1,000 or 0.1%; verification USD 150 No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Primary holder redemption terms", "https://tether.to/en/legal/", ["route"])],
    },
    docs: [
      sourceRef("MXNT conditional personal redemption entitlement (not a full-supply bound)", "https://tether.to/en/legal/", ["route", "capacity", "fees", "access", "settlement"]),
      sourceRef("Issuer fee schedule", "https://tether.to/en/fees/", ["fees", "access"]),
    ],
    notes: [
      "Eligibility: Verified Tether customer with accepted bank account; jurisdiction and eligibility restrictions apply",
      "Minimum: USD 100,000 equivalent",
      "Evidence proposal only. Do not copy supply-full capacity or fee/cadence defaults from the precedent without exact current token evidence.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "oned-gennius": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    outputAssets: ["usdc-circle"],
    costModel: undisclosedReviewedFee("Platform fees/spreads and network costs may apply; no fixed public numeric conversion fee established"),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Undisclosed public executable capacity; 1:1 backing is not immediate redemption capacity Variable settlement depending on network and partner infrastructure; no guaranteed SLA Platform fees/spreads and network costs may apply; no fixed public numeric conversion fee established No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Coinbase ONED custody and conversion", "https://help.coinbase.com/en/coinbase/getting-started/crypto-education/cb-custom-stablecoins", ["route"])],
    },
    docs: [
      sourceRef("Coinbase ONED/Base account custody and USDC conversion", "https://help.coinbase.com/en/coinbase/getting-started/crypto-education/cb-custom-stablecoins", ["route", "access", "settlement"]),
      sourceRef("ONED issuer terms URL (currently landing shell only)", "https://oned.global/#/end-user-terms-and-conditions", ["route"]),
    ],
    notes: [
      "Eligibility: Eligible Coinbase account; native Base ONED external deposits supported; New York, Canada and EEA excluded",
      "Minimum: Undisclosed public numeric minimum",
      "Fixed token-for-token eligible issuer conversion, not a permissionless atomic on-chain backstop. Do not import precedent fees, settlement defaults, minimums or capacity ratios; all unquantified terms must remain bounded.",
      "The issuer terms URL returned only a landing shell on October 7, 2026; no ONED-specific binding terms were retrieved. Novaé/upperClub terms are unrelated. Coinbase's ONED/Base account conversion facts do not import Solana-only Verified Redemptions or a generic StableSwapper issuer obligation.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "jltxx-jpmorgan": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "nav",
    costModel: undisclosedReviewedFee("No separately verified unconditional cash-redemption fee schedule. Fund operating expenses are not a redemption transaction fee; suspension/liquidation terms must remain visible."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Reviewed holder redemption right, ordinarily within seven days; no numeric unconditional daily capacity disclosed. Statutory/SEC/NYSE emergency suspensions and permanent suspension/liquidation may apply. Ordinarily payment within seven days after a proper redemption order; multiple hourly dealing cutoffs9am-5pm ET. Suspension can extend payment beyond seven days; no always-on immediate payout asserted. No separately verified unconditional cash-redemption fee schedule. Fund operating expenses are not a redemption transaction fee; suspension/liquidation terms must remain visible. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("SEC JLTXX prospectus: Minimum Investments, How Your Account Works, Redeeming Shares, Suspension of Redemptions", "https://www.sec.gov/Archives/edgar/data/1659326/000119312526217424/d44657d485bpos.htm", ["route"])],
    },
    docs: [
      sourceRef("SEC JLTXX prospectus (prior review; current retrieval HTTP 403)", "https://www.sec.gov/Archives/edgar/data/1659326/000119312526217424/d44657d485bpos.htm", ["route", "fees", "access", "settlement"]),
    ],
    notes: [
      "Eligibility: Approved institutional Morgan Money/investor account and compatible approved blockchain address; the off-chain Investor Register determines the legal shareholding.",
      "Minimum: USD1,000,000 initial account investment, waivable; no subsequent purchase minimum. No numeric minimum redemption verified. Below-minimum accounts may be closed after60 days' notice.",
      "Model the off-chain cash shareholder route rather than fabricate USDC payout or a full-supply daily capacity. The token-burn operation is a redemption request, subject to Fund processing and Investor Register reconciliation.",
      "The ordinary seven-day cash payment term has statutory/emergency suspension exceptions. Blockchain burn submits an order; the off-chain Investor Register governs legal ownership. Initial $1M account minimum is not a redemption minimum.",
      "October 7, 2026 SEC retrieval returned HTTP 403 and the issuer prospectus portal returned a listing, not the legal body. Existing holder terms remain prior-review claims; current product AUM and 99.99% daily liquid assets are not token supply or capacity evidence.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "umint-ubs": {
    ...issuerBase,
    reviewedAt: "2026-10-07",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "opaque",
    outputAssetType: "nav",
    costModel: undisclosedReviewedFee("Native UBS uMINT binding fee schedule is not public; DigiFT DR-uMINT's historical wrapper proposal is not this token's fee evidence."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "UBS confirms a production native uMINT subscription/redemption workflow, not route-wide funded capacity or binding completion terms. The native PPM, redemption minimum, fee schedule and gates are unavailable. DigiFT's March 2025 DR-uMINT proposal is a separate wrapper; its $1,000/T+0/underlying-AUM claims do not establish native terms. Capacity, completed settlement and all-in cost remain unbounded.",
      reviewedAt: "2026-10-07",
      docs: [sourceRef("UBS native uMINT production subscription and redemption (November 4, 2025)", "https://www.ubs.com/global/en/media/display-page-ndp/en-20251104-chainlink.html", ["route"]), sourceRef("UBS native Ethereum uMINT launch", "https://www.ubs.com/global/en/media/display-page-ndp/en-20241101-first-tokenized-investment-fund.html", ["route", "access"])],
    },
    docs: [
      sourceRef("UBS native uMINT production subscription and redemption (November 4, 2025)", "https://www.ubs.com/global/en/media/display-page-ndp/en-20251104-chainlink.html", ["route"]),
      sourceRef("UBS Ethereum uMINT launch", "https://www.ubs.com/global/en/media/display-page-ndp/en-20241101-first-tokenized-investment-fund.html", ["route", "access"]),
    ],
    notes: [
      "Eligibility: Authorized distributor onboarding and native fund investor eligibility; current binding PPM not public.",
      "Minimum: Current native UBS uMINT redemption minimum is not public. The historical $1,000 claim belongs to the distinct proposed DigiFT DR-uMINT wrapper and is not modeled.",
      "UBS production workflow proves route existence only. The DR-uMINT proposal's T+0, minimum, tariff and underlying AUM do not establish native UBS holder guarantees or funded liquidity.",
      "Current native payout currency and binding PPM remain unconfirmed. The inherited fiat projection is diagnostic compatibility, not new USD/stablecoin settlement evidence.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
};
