import type { RedemptionBackstopConfig } from "../shared";
import { documentedVariableFee, fixedFee, issuerBase, sourceRef, sourceRefFull, undisclosedReviewedFee } from "../shared";

/** Source-reviewed issuer routes from the October 2026 discovery wave.
 * Like the thUSD bounded-terms precedent, supply-full is an eventual-only
 * diagnostic default, never an immediate buffer or documented-bound capacity.
 * Each route withholds scoring for its explicitly missing executable terms. */
export const DISCOVERY_OFFCHAIN_ISSUER_CONFIGS: Record<string, RedemptionBackstopConfig> = {
  "xgz-goldzip": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "opaque",
    outputAssetType: "physical-commodity-delivery",
    physicalCommodityDelivery: {
      commodity: "XAU",
      deliverableOuncesPerToken: 0.9999 / 31.1034768,
      minimumDeliveryTokens: 1_000,
      deliveryTermsUnbounded: true,
      feeModel: { bps: 0, flatUsd: 0, deliveryUsd: 0 },
      sameNotionalEligible: false,
    },
    costModel: undisclosedReviewedFee("Physical delivery, assay, logistics and redemption fees undisclosed. The 0.01% sender fee is a transfer fee only."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Issuer-described gold backing and physical route; no measured current delivery throughput or independently reconciled capacity. Undisclosed delivery settlement timing. Physical delivery, assay, logistics and redemption fees undisclosed. The 0.01% sender fee is a transfer fee only. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("GoldZip physical claim and redemption", "https://goldzip.info/GZ_UPDATED_LITEPAPER_03.11.pdf", ["route"])],
    },
    docs: [
      sourceRefFull("GoldZip physical claim and redemption", "https://goldzip.info/GZ_UPDATED_LITEPAPER_03.11.pdf"),
      sourceRef("GoldZip resident restriction and bar lot", "https://goldzip.info/", ["route", "capacity", "access"]),
    ],
    notes: [
      "Eligibility: AML compliance; Hong Kong residents excluded.",
      "Minimum: 1,000 XGZ per eligible delivery bar; each token represents one gross gram of 99.99%-fine gold. deliverableOuncesPerToken expresses fine-gold content (0.9999 grams / 31.1034768), while the token's nominal commodity unit is one gross gram.",
      "Do not borrow XAUT 430-token deposit or Swiss delivery terms. XGZ 1,000-token lot is 1kg nominal gold; no dealer-sale USD proceeds, fee or capacity is invented.",
      "No physical-to-USD composition is authored: delivery timing, vault pickup details and logistics cost are not bounded. Zero physical feeModel deductions mean no published USD deduction, not free delivery; the 0.01% transfer fee is not a redemption fee.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "usdu-universal": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    costModel: undisclosedReviewedFee("Fees payable; public numeric redemption fee schedule not pinned."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Public redemption capacity not quantified; 100% historical reserve backing is not executable capacity. Generally two business days after due diligence; extension possible in extreme conditions with FSRA notification or direction. Fees payable; public numeric redemption fee schedule not pinned. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRefFull("USDU January 2026 whitepaper", "https://cdn.prod.website-files.com/644c2f7bb9ee913b81ea51df/69a5e87340361f8d03e80be5_USDU_Whitepaper_English_Arabic_Jan_2026.pdf")],
    },
    docs: [
      sourceRef("Crowe August 2026 reserve examination", "https://cdn.prod.website-files.com/68cf1072d23d4d5b68d8f496/6aba3d94e9697870784a49e5_Final%20USDU%20Examination%20Report%20-%20August%202026%20Countersigned.pdf", ["capacity"]),
      sourceRefFull("USDU January 2026 whitepaper", "https://cdn.prod.website-files.com/644c2f7bb9ee913b81ea51df/69a5e87340361f8d03e80be5_USDU_Whitepaper_English_Arabic_Jan_2026.pdf"),
      sourceRef("ADGM FSRA issuer register FSP250089", "https://www.adgm.com/public-registers/fsra/firms/financial-firms/universal-digital-intl-limited-250089", ["access"]),
    ],
    notes: [
      "Eligibility: Aquanow-onboarded professional clients after KYC/AML; issuer FSRA permission excludes retail clients.",
      "Minimum: $100,000 minimum redemption in January 2026 whitepaper benchmark; current terms should be rechecked before runtime modeling.",
      "Do not inherit Paxos 25% hot-buffer capacity or fee values.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "filqa-fidelity-international": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "nav",
    costModel: undisclosedReviewedFee("Outside-market-hours redemption fee is 0.02% of NAV per day plus network gas, subject to directors changing terms."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Redemption is recognized investor exit; current unconditional off-hours or stress capacity not disclosed. Normal valuation21:00UK; usual dealing01:00-21:00London eligible weekdays. Off-hours facilities conditional; gates or suspension can extend realization. No guaranteed payout deadline asserted. Outside-market-hours redemption fee0.02%NAV per day plus network gas, subject to directors changing terms; maximum TER0.50% is a separate annual operating expense, not a redemption fee. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Fidelity September 14, 2026 fund prospectus", "https://www.fidelityinternational.com/legal/documents/FISGF/en/pr.fisgf.en.xx.pdf", ["route"])],
    },
    docs: [
      sourceRefFull("Fidelity September 14, 2026 fund prospectus", "https://www.fidelityinternational.com/legal/documents/FISGF/en/pr.fisgf.en.xx.pdf"),
      sourceRefFull("Retrieved Fidelity prospectus text", "https://r.jina.ai/https://www.fidelityinternational.com/legal/documents/FISGF/en/pr.fisgf.en.xx.pdf"),
    ],
    notes: [
      "Eligibility: Onboarded eligible qualified/professional investors; prospectus subscriptions/redemptions through TA or Token Distributor.",
      "Minimum: Class initial investment approximately$100,000; distinct redemption-specific minimum not established.",
      "Token transfers are legally unrecognized for on-chain investors; no secondary trading route or instant supply-full capacity credited.",
      "Models the prospectus cash-to-USD-bank-account branch only. Distributor stablecoin conversion is a separate service with an unenumerated approved payout set, not an inferred USDC route.",
      "The maximum TER of 0.50% is a separate annual operating expense, not a redemption fee or a capacity limit.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "eurw-newrails": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    costModel: fixedFee(0, "Zero issuer redemption fee; receiving-bank and blockchain network charges may apply."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Holder-wide statutory/contractual par redemption from safeguarded reserves independent of new issuance; numerical executable capacity/daily limit undisclosed. Without undue delay, no contractual lock-up or discretionary delay; numerical bank-settlement SLA undisclosed. Zero issuer redemption fee; receiving-bank and blockchain network charges may apply. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Newrails EMT redemption policy effective February 9, 2026", "https://www.newrails.xyz/en/legal/emt-redemption-policy", ["route"])],
    },
    docs: [
      sourceRefFull("Newrails EMT redemption policy effective February 9, 2026", "https://www.newrails.xyz/en/legal/emt-redemption-policy"),
      sourceRefFull("Newrails EURW MiCA whitepaper notified May 26, 2026", "https://cmpl-docs.newrails.xyz/docs/Newrails%20EURW%20WP%202026-05-26.xhtml"),
      sourceRef("Bank of Lithuania Newrails EMI and EMT issuer register", "https://www.lb.lt/en/sfi-financial-market-participants/newrails-uab", ["access"]),
    ],
    notes: [
      "Eligibility: Any natural or legal holder after identity, wallet-control and own-name SEPA-bank-account verification; customers use the platform, other holders may onboard or contact eurw@newrails.xyz.",
      "Minimum: Undisclosed",
      "Full-holder legal route established. Do not infer instant bank settlement from marketing or copy precedent full-supply scoring capacity; preserve numeric capacity/settlement/all-in-cost gaps.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "brsrv-blackrock": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "nav",
    costModel: fixedFee(0, "No sales/redemption sales charge per prospectus; investor network gas and intermediary charges may apply."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Ordinary fund NAV redemption; current unconditional instant USD/USDC facility capacity not established. Good-order requests before5pmET: ordinarily same-day federal-funds wire when custodian open, otherwise next open day; statutory fund right to take up to7days. No sales/redemption sales charge per prospectus; investor network gas and intermediary charges may apply. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("BlackRock July 31, 2026 OnChain share prospectus", "https://www.blackrock.com/cash/literature/prospectus/pro-brsrv.pdf", ["route"])],
    },
    docs: [
      sourceRefFull("BlackRock July 31, 2026 OnChain share prospectus", "https://www.blackrock.com/cash/literature/prospectus/pro-brsrv.pdf"),
      sourceRef("BlackRock BRSRV fund reporting", "https://www.blackrock.com/cash/en-us/products/351891/blackrock-daily-reinvestment-stablecoin-reserve-vehicle", ["capacity"]),
    ],
    notes: [
      "Eligibility: Registered whitelisted investors through Securitize; $3M initial investment (not a redemption minimum).",
      "Minimum: No subsequent investment minimum; redemption-specific minimum not found.",
      "Blockchain outages do not suspend off-chain good-order redemption processing. Do not credit full instant capacity or third-party facility capacity.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "zaru-blocktower": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "opaque",
    outputAssetType: "stable-single",
    costModel: undisclosedReviewedFee("Partner/issuer fees not numerically disclosed"),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Undisclosed; no executable capacity is inferred from historical reserves Fiat settlement may take up to five business days; no guaranteed SLA Partner/issuer fees not numerically disclosed No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Primary holder redemption terms", "https://zaru.network/blog/zar-universal-white-paper", ["route"])],
    },
    docs: [
      sourceRefFull("Primary holder redemption terms", "https://zaru.network/blog/zar-universal-white-paper"),
    ],
    notes: [
      "Eligibility: Verified institutions directly; retail through network partners, with issuer contingency claim",
      "Minimum: Partner-defined thresholds, numerical minimum not published",
      "Evidence proposal only. Do not copy supply-full capacity or fee/cadence defaults from the precedent without exact current token evidence.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "frnt-wyoming": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    costModel: undisclosedReviewedFee("Commission fee disclosed as zero; LSP and payment-rail all-in charges are not quantified."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Current executable LSP capacity and minimum are not public. Trust balance is eventual backing, not an immediate redemption-capacity measure. Commission submits the USD notional value promptly, no more than two Business Days for an authenticated approved-LSP Redemption Request made in business hours. Out-of-hours requests are treated as next-Business-Day requests. Section 4 permits delays for unforeseen circumstances; bank receipt time is not guaranteed by this submission deadline. Commission fee disclosed as zero; LSP and payment-rail all-in charges are not quantified. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Wyoming reserve and redemption rules, Chapter 4", "https://stabletoken.wyo.gov/assets/media/reserves.pdf", ["route"])],
    },
    docs: [
      sourceRefFull("Wyoming reserve and redemption rules, Chapter 4", "https://stabletoken.wyo.gov/assets/media/reserves.pdf"),
      sourceRef("Commission issuance/redemption and fee disclosure", "https://stabletoken.wyo.gov/assets/IssuanceRedemptionPage-CM6vPxSM.js", ["route", "fees", "access"]),
    ],
    notes: [
      "Eligibility: Direct issuance/redemption restricted to approved KYB Licensed Service Providers. Ordinary retail exit is through an LSP; Commission direct-holder fallback applies only under the rules’ specified conditions.",
      "Minimum: Not publicly disclosed in retrieved issuance/redemption materials.",
      "Use LSP-gated eligibility, not permissionless issuer redemption. Preserve conditional direct-holder fallback, special-obligation limitation, unknown capacity, unknown minimum and service-provider cost gaps.",
      "Models only approved Licensed Service Providers. The Commission fee is zero; LSP and bank costs remain unquantified. Retail access and the conditional direct-holder fallback are not generalized to permissionless issuer access.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "gbpa-agant": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    costModel: undisclosedReviewedFee("Platform may charge fees; numerical redemption/all-in schedule undisclosed."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Undisclosed; reserve snapshot is not executable capacity and public full-holder/backstop terms were not retrieved. Off-ramp docs describe immediate conversion and subsequent bank delivery, without a numerical bank-credit SLA. Platform may charge fees; numerical redemption/all-in schedule undisclosed. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Agant business platform terms", "https://app.agant.io/terms-of-service", ["route"])],
    },
    docs: [
      sourceRefFull("Agant business platform terms", "https://app.agant.io/terms-of-service"),
      sourceRef("Agant off-ramp Rails procedure", "https://docs.agant.io/XDREhsGKwMiuddKPr5Rt/platform/off-ramp.md", ["route", "access", "settlement"]),
      sourceRef("Nephos GBPA reserve attestation as of September 30, 2026", "https://security.agant.io/doc/trust?rid=6abea083a941a8650c35ebf8&r=lz53fv2d0lk02myddnbz7&download=true", ["capacity"]),
    ],
    notes: [
      "Eligibility: Approved UK-incorporated, appropriately FCA-authorized/registered business distribution customers completing KYB/KYC; retail holders must use a distribution customer.",
      "Minimum: Undisclosed",
      "Model only the business issuer route. Do not copy same-day/days bounds, full-supply capacity or zero fee from precedent without evidence. Holder Terms and Distribution Agreement remain gaps.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "usdsm-stable-mint": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    costModel: fixedFee(0, "Issuer redemption fee zero; third-party bank and intermediary charges can apply and are unquantified."),
    v9RouteReviewTerms: {
      minRedeemUsd: 0,
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Undisclosed current executable daily capacity; do not equate advertised reserves with immediate exit capacity. Without undue delay after receipt of tokens and checks. Operational cutoffs and indicative periods live in the private platform, not retrieved publicly. Issuer redemption fee zero; third-party bank and intermediary charges can apply and are unquantified. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Stable Mint terms, sections 5, 6 and 9", "https://stablemint.io/legal/terms-conditions/", ["route"])],
    },
    docs: [
      sourceRefFull("Stable Mint terms, sections 5, 6 and 9", "https://stablemint.io/legal/terms-conditions/"),
    ],
    notes: [
      "Eligibility: Legal and natural holders after issuer acceptance and full AML/KYC onboarding, including Redemption-Only Clients; no self-serve registration.",
      "Minimum: No minimum applies to redemption under section 9.1.",
      "Par redemption right is verified; settlementModel null is an explicit missing public SLA, not a proposed same-day assumption. Model as a bounded-terms gap until the actual route configuration can honestly represent it.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "gldon-ondo": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "immediate",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-basket",
    outputAssets: ["usdon-ondo", "usdc-circle"],
    costModel: { ...documentedVariableFee("Final Terms permit issuer issuance and redemption fees up to 0.1%; live quote fee may vary."), feeBpsMax: 10 },
    v9RouteReviewTerms: {
      minRedeemUsd: 1,
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "USDC conversion depends on available swapper inventory; no measured current GLDON redemption throughput. Trade/net-position limits are not daily redemption capacity. Issuer docs describe instant USDon redemption and USDC conversion only when swapper liquidity is sufficient. Final Terms permit issuer issuance and redemption fees up to 0.1%; live quote fee may vary. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Ondo investor redemption mechanics", "https://docs.ondo.finance/ondo-stocks/investing-and-redeeming.md", ["route"])],
    },
    docs: [
      sourceRef("Ondo investor redemption mechanics", "https://docs.ondo.finance/ondo-stocks/investing-and-redeeming.md", ["route", "capacity", "access", "settlement"]),
      sourceRefFull("GLDon Final Terms", "https://cdn.sanity.io/files/8k2tqa6n/production/a598be5156bcda440276f01eea9258f82f851bd0.pdf"),
      sourceRef("Ondo holder eligibility notes", "https://docs.ondo.finance/ondo-stocks/important-notes.md", ["access"]),
      sourceRef("Ondo Stocks issuer and swapper contract addresses", "https://docs.ondo.finance/addresses.md", ["route", "capacity"]),
    ],
    notes: [
      "Eligibility: Onboarded eligible investors outside the United States; additional jurisdictional restrictions. USDon/USDC swap access is separately whitelisted.",
      "Minimum: Current operational docs state $1 redemption minimum; Final Terms state 0.01-USDC minimum subscription, a different scope.",
      "Same issuer family as IAUon/SLVon, but new retrieved docs identify USDon and liquidity-conditioned USDC settlement. Do not copy obsolete blanket days or imply ETF/physical gold delivery rights.",
      "The modeled token payout choices are USDon and liquidity-conditioned USDC. These are alternative outputs, not an invented equal-weight portfolio or direct ownership/delivery of GLD ETF shares.",
      "Ondo separately documents GMIssuerManager redemption into underlying securities through Alpaca's Instant Tokenization Network: Ethereum 0xec8bBB0c90c0B5F4D8240D0F7b49DA3b0aA41f4E and BNB Chain 0x341f9e6463161F0C90037Cbc0150DC54e6d1e06e. Holder eligibility, execution capacity and binding GLDon in-kind rights are unestablished; this rail is recorded without adding an output or upgrading exit scoring.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "chfsafo-spiko": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "nav",
    costModel: fixedFee(0, "Exact KID/API report no fund entry/exit fee; exceptional swing pricing up to 0.5% and operational/DLT/bank costs are not an all-in zero-cost guarantee. API management fee is 0.15% annually; the July KID 0.09% ongoing estimate is a different dated cost disclosure."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Ordinary NAV redemption; no guaranteed stressed minimum. Management may gate when net redemptions reach 25% of sub-fund assets, up to 20 valuation days over three months. Ordinary D+1 business-day settlement with 15:00 Paris order cutoff; holidays, gates and suspension can extend it. Exact KID/API report no fund entry/exit fee; exceptional swing pricing up to 0.5% and operational/DLT/bank costs are not an all-in zero-cost guarantee. API management fee is 0.15% annually; the July KID 0.09% ongoing estimate is a different dated cost disclosure. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Spiko SICAV prospectus, 1 September 2026", "https://cdn.spiko.finance/legal_docs/EN/Prospectus_Spiko_SICAV_EN.pdf", ["route"])],
    },
    docs: [
      sourceRefFull("Spiko SICAV prospectus, 1 September 2026", "https://cdn.spiko.finance/legal_docs/EN/Prospectus_Spiko_SICAV_EN.pdf"),
      sourceRefFull("Exact CHF KID, ISIN FR0014015LG6", "https://cdn.spiko.finance/legal_docs/EN/KID_chfSAFO_EN.pdf"),
      sourceRef("Exact CHF native registers and five share decimals", "https://public-api.spiko.io/share-classes/chfSAFO", ["route"]),
      sourceRef("CHF shares, assets and NAV at 2 October 2026", "https://public-api.spiko.io/share-classes/chfSAFO/totals", ["capacity"]),
    ],
    notes: [
      "Eligibility: KYC/allowlisted fund shareholder; US persons excluded by exact KID.",
      "Minimum: Issuer chfSAFO API minimumRedemption = 1; prospectus class minimum CHF 1.",
      "Do not inherit EUR Chainlink oracle or EUR fiat-to-USD exit conversion. CHF reference/FX conversion is required for USD-notional scoring.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "pyusdx-moonpay": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    outputAssets: ["pyusd-paypal"],
    costModel: undisclosedReviewedFee("Undisclosed numeric redemption fee; network and operational costs are not quantified"),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Undisclosed public executable capacity; 1:1 backing is not immediate redemption capacity Commercially reasonable efforts subject to compliance, network and infrastructure conditions; no guaranteed SLA Undisclosed numeric redemption fee; network and operational costs are not quantified No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("MoonPay PYUSDx holder and counterparty terms", "https://www.moonpay.com/legal/pyusdx_terms", ["route"])],
    },
    docs: [
      sourceRefFull("MoonPay PYUSDx holder and counterparty terms", "https://www.moonpay.com/legal/pyusdx_terms"),
    ],
    notes: [
      "Eligibility: MoonPay-onboarded eligible counterparties only; downstream holders need separate onboarding; U.S., EEA, Canada, India and Australia excluded",
      "Minimum: Undisclosed public numeric minimum",
      "Fixed token-for-token eligible issuer conversion, not a permissionless atomic on-chain backstop. Do not import precedent fees, settlement defaults, minimums or capacity ratios; all unquantified terms must remain bounded.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "stbt-matrixdock": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-basket",
    outputAssets: ["usdc-circle", "usdt-tether"],
    costModel: fixedFee(0, "April 28 2026 update states 0% redemption fee; signed terms permit liquidation losses and transactional costs. Custody fee 0.20% p.a. affects yield."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "T+0 global daily USD 1M limit; T+2 above. Legal issuer/account restrictions retained. T+0 within limited capacity, T+2 above. April 28 2026 update states 0% redemption fee; signed terms permit liquidation losses and transactional costs. Custody fee 0.20% p.a. affects yield. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("STBT January 2025 terms", "https://2505056629-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FZx9GNWaNV9JB3JZlW74D%2Fuploads%2FzHip8cJaP5aud3KfdVud%2FSTBT%20Token%C2%A0Terms%20and%20Conditions.pdf?alt=media&token=79d5fd49-deae-41b4-a809-9e1afaa02f32", ["route"])],
    },
    docs: [
      sourceRefFull("STBT January 2025 terms", "https://2505056629-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FZx9GNWaNV9JB3JZlW74D%2Fuploads%2FzHip8cJaP5aud3KfdVud%2FSTBT%20Token%C2%A0Terms%20and%20Conditions.pdf?alt=media&token=79d5fd49-deae-41b4-a809-9e1afaa02f32"),
      sourceRef("Matrixdock reserve and rebasing disclosures", "https://www.matrixdock.com/stbt", ["route", "capacity"]),
      sourceRef("April 2026 settlement and fee update", "https://matrixdock.gitbook.io/matrixdock-docs/english/announcements/stbt-custodian-and-conversion-fee-reduction-and-settlement-optimization.md", ["capacity", "fees", "settlement"]),
    ],
    notes: [
      "Eligibility: Accredited non-U.S. investors with approved accounts and allowlisted transfers.",
      "Minimum: Current redemption minimum not established; UK acquisition threshold is not a redemption minimum.",
      "Operational 2026 fee/settlement update and January 2025 legal account-only wording are not fully harmonized; preserve unsecured claim and payout losses.",
      "The published USD 1M T+0 threshold is a route limit, not a guaranteed funded buffer; no fixed-usd capacity is authored. Zero issuer fee excludes liquidation losses, transactional costs and gas permitted by governing terms.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "fiusd-sygnum": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "nav",
    costModel: undisclosedReviewedFee("Historical March 2025 application: 40 bps redemption, 20 bps subscription and 25 bps annual management; bank fees may apply and terms can change. Current binding client tariff unavailable"),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Not publicly quantified for the current same-notional holder route; no fund AUM proxy and no instant stress capacity credited Underlying fund same-day dealing with business-day cutoffs; current token/account credit deadline not publicly committed Historical March 2025 application: 40 bps redemption, 20 bps subscription and 25 bps annual management; bank fees may apply and terms can change. Current binding client tariff unavailable No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Sygnum issuer-authored FIUSD application dated March 20, 2025", "https://forum.arbitrum.foundation/t/sygnum-bank-ag-fidelity-international-fiusd-step-2-application/28779", ["route"])],
    },
    docs: [
      sourceRefFull("Sygnum issuer-authored FIUSD application dated March 20, 2025", "https://forum.arbitrum.foundation/t/sygnum-bank-ag-fidelity-international-fiusd-step-2-application/28779"),
      sourceRef("Verified deployed Arbitrum implementation", "https://arbitrum.blockscout.com/api/v2/smart-contracts/0x7616b08676117e1aab542e53fe3f7b12f7596d37", ["route", "access"]),
    ],
    notes: [
      "Eligibility: Professional bank clients with Sygnum-custodied whitelisted wallets",
      "Minimum: Historical underlying Class G has no subscription/holding minimum; current token-level bank-client minimum is not publicly established",
      "Do not admit the historical $25M collateralized off-hours lending concept as current guaranteed redemption capacity; client contract is private.",
      "Models the documented USD cash credit to the professional Sygnum investor account, not an unenumerated crypto withdrawal. The March 2025 40 bps redemption tariff is historical and is not a current fee bound; the $25M off-hours lending concept is not funded holder redemption capacity.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "cumiu-chinaamc": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "nav",
    costModel: documentedVariableFee("KFS up to 5% redemption charge; prospectus anti-dilution charge up to 5% when single investor redemption >=20% NAV. These distinct charges are not a single 5% all-in ceiling. Distributor/bank charges additional; do not substitute website up-to-1% marketing."),
    v9RouteReviewTerms: {
      minRedeemUsd: 1000,
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Daily NAV redemption subject to suspension/liquidity management and distributor processing; no guaranteed intraday amount. 11am Hong Kong daily cutoff; normally three business days, general one-calendar-month maximum with regulatory/FX exceptions. KFS up to 5% redemption charge; prospectus anti-dilution charge up to 5% when single investor redemption >=20% NAV. Distributor/bank charges additional; do not substitute website up-to-1% marketing. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("ChinaAMC September 2026 prospectus", "https://www.chinaamc.com.hk/jeecg-boot/sys/common/static/temp/E-CleanProspectus-ChinaAMCDigitalOFC-CN(September2026)_1789336483417.pdf", ["route"])],
    },
    docs: [
      sourceRefFull("ChinaAMC September 2026 prospectus", "https://www.chinaamc.com.hk/jeecg-boot/sys/common/static/temp/E-CleanProspectus-ChinaAMCDigitalOFC-CN(September2026)_1789336483417.pdf"),
      sourceRefFull("ChinaAMC tokenized unlisted class key facts", "https://www.chinaamc.com.hk/jeecg-boot/sys/common/static/chinaamc/resources/E-KFS-ChinaAMCUSDDigitalMMF(UnlistedClass)(April2026).pdf"),
      sourceRef("KPMG 2025 fund financial audit", "https://www.chinaamc.com.hk/jeecg-boot/sys/common/static/chinaamc/resources/E-25AFS_DigitalOFC_Cover.pdf", ["capacity"]),
    ],
    notes: [
      "Eligibility: Class I USD through eligible distributors; retail requires distributor trading/custody account.",
      "Minimum: Class I USD 1000 redemption and remaining holding minimum.",
      "Do not model unlimited immediate redemption or distributor-specific charges without evidence.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "uscc-superstate": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    outputAssets: ["usdc-circle"],
    costModel: undisclosedReviewedFee("Investor-borne gas and wire fees; current additional fund-specific redemption charges undisclosed"),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Not publicly quantified for the current same-notional holder route; no fund AUM proxy and no instant stress capacity credited T+1 before 5pm ET cutoff, T+2 after, market days Investor-borne gas and wire fees; current additional fund-specific redemption charges undisclosed No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("USCC fund, service providers and October 1 holdings", "https://superstate.com/assets/uscc", ["route"])],
    },
    docs: [
      sourceRef("USCC fund, service providers and October 1 holdings", "https://superstate.com/assets/uscc", ["route", "capacity"]),
      sourceRefFull("USCC current investor terms", "https://docs.superstate.com/investors/tokenized-funds/available-funds/bitwise-uscc"),
      sourceRef("Superstate deployments and administrative powers", "https://docs.superstate.com/investors/smart-contracts", ["route", "access"]),
      sourceRef("Superstate redemption procedure", "https://docs.superstate.com/investors/tokenized-funds/redeem", ["route", "fees", "access", "settlement"]),
    ],
    notes: [
      "Eligibility: Qualified Purchasers in supported jurisdictions, onboarded and allowlisted through Superstate",
      "Minimum: $100,000 initial subscription unless waived; redemption minimum not separately published",
      "Use documented market-day operational route only; do not copy USTB atomic-USDC liquidity config or assert full circulating-supply capacity.",
      "Models the explicitly documented USDC payout choice on Ethereum/Solana; the separately documented USD wire branch is not combined into an invented mixed basket. USCC is crypto-carry strategy exposure, not USTB, and neither AUM nor initial-subscription minimum establishes exit capacity or redemption minimum.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "mxnt-tether": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "opaque",
    outputAssetType: "stable-single",
    costModel: { ...documentedVariableFee("Greater of USD 1,000 or 0.1%; verification USD 150"), feeBpsMax: 10, minFeeUsd: 1_000 },
    v9RouteReviewTerms: {
      minRedeemUsd: 100000,
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Undisclosed; no executable capacity is inferred from historical reserves No guaranteed settlement deadline; issuer suspension rights apply Greater of USD 1,000 or 0.1%; verification USD 150 No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Primary holder redemption terms", "https://tether.to/en/legal/", ["route"])],
    },
    docs: [
      sourceRefFull("Primary holder redemption terms", "https://tether.to/en/legal/"),
      sourceRef("Issuer fee schedule", "https://tether.to/en/fees/", ["fees", "access"]),
    ],
    notes: [
      "Eligibility: Verified Tether customer with accepted bank account; jurisdiction and eligibility restrictions apply",
      "Minimum: USD 100,000 equivalent",
      "Evidence proposal only. Do not copy supply-full capacity or fee/cadence defaults from the precedent without exact current token evidence.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "oned-gennius": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "stable-single",
    outputAssets: ["usdc-circle"],
    costModel: undisclosedReviewedFee("Platform fees/spreads and network costs may apply; no fixed public numeric conversion fee established"),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Undisclosed public executable capacity; 1:1 backing is not immediate redemption capacity Variable settlement depending on network and partner infrastructure; no guaranteed SLA Platform fees/spreads and network costs may apply; no fixed public numeric conversion fee established No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("Coinbase ONED custody and conversion", "https://help.coinbase.com/en/coinbase/getting-started/crypto-education/cb-custom-stablecoins", ["route"])],
    },
    docs: [
      sourceRef("Coinbase ONED custody and conversion", "https://help.coinbase.com/en/coinbase/getting-started/crypto-education/cb-custom-stablecoins", ["route", "capacity", "access", "settlement"]),
      sourceRef("Coinbase ONED itemized reserve dashboard", "https://www.coinbase.com/en-in/oned/proof-of-reserves", ["capacity"]),
      sourceRefFull("ONED native holder terms", "https://oned.global/#/end-user-terms-and-conditions"),
      sourceRef("Gennius ONED platform terms", "https://tc.oned.global/#/oned", ["route", "fees", "access"]),
    ],
    notes: [
      "Eligibility: Eligible Coinbase account; native Base ONED external deposits supported; New York, Canada and EEA excluded",
      "Minimum: Undisclosed public numeric minimum",
      "Fixed token-for-token eligible issuer conversion, not a permissionless atomic on-chain backstop. Do not import precedent fees, settlement defaults, minimums or capacity ratios; all unquantified terms must remain bounded.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "jltxx-jpmorgan": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "verified-customer",
    settlementModel: "days",
    executionModel: "rules-based-nav",
    outputAssetType: "nav",
    costModel: undisclosedReviewedFee("No separately verified unconditional cash-redemption fee schedule. Fund operating expenses are not a redemption transaction fee; suspension/liquidation terms must remain visible."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Reviewed holder redemption right, ordinarily within seven days; no numeric unconditional daily capacity disclosed. Statutory/SEC/NYSE emergency suspensions and permanent suspension/liquidation may apply. Ordinarily payment within seven days after a proper redemption order; multiple hourly dealing cutoffs9am-5pm ET. Suspension can extend payment beyond seven days; no always-on immediate payout asserted. No separately verified unconditional cash-redemption fee schedule. Fund operating expenses are not a redemption transaction fee; suspension/liquidation terms must remain visible. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("SEC JLTXX prospectus: Minimum Investments, How Your Account Works, Redeeming Shares, Suspension of Redemptions", "https://www.sec.gov/Archives/edgar/data/1659326/000119312526217424/d44657d485bpos.htm", ["route"])],
    },
    docs: [
      sourceRefFull("SEC JLTXX prospectus: Minimum Investments, How Your Account Works, Redeeming Shares, Suspension of Redemptions", "https://www.sec.gov/Archives/edgar/data/1659326/000119312526217424/d44657d485bpos.htm"),
    ],
    notes: [
      "Eligibility: Approved institutional Morgan Money/investor account and compatible approved blockchain address; the off-chain Investor Register determines the legal shareholding.",
      "Minimum: USD1,000,000 initial account investment, waivable; no subsequent purchase minimum. No numeric minimum redemption verified. Below-minimum accounts may be closed after60 days' notice.",
      "Model the off-chain cash shareholder route rather than fabricate USDC payout or a full-supply daily capacity. The token-burn operation is a redemption request, subject to Fund processing and Investor Register reconciliation.",
      "The ordinary seven-day cash payment term has statutory/emergency suspension exceptions. Blockchain burn submits an order; the off-chain Investor Register governs legal ownership. Initial $1M account minimum is not a redemption minimum.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
  "umint-ubs": {
    ...issuerBase,
    reviewedAt: "2026-10-03",
    holderEligibility: "whitelisted-primary",
    settlementModel: "days",
    executionModel: "opaque",
    outputAssetType: "nav",
    costModel: undisclosedReviewedFee("March2025 schedule is historical, not current binding fee evidence; current fee unknown."),
    v9RouteReviewTerms: {
      scoringDisposition: "bounded-terms-gap",
      missingScoringFields: ["capacity", "settlement", "cost"],
      rationale: "Native subscriptions/redemptions executed in production; current facility and stress capacity undisclosed. March2025 dossier described dailyT+0; current cutoff/payout guarantee unverified. March2025 schedule is historical, not current binding fee evidence; current fee unknown. No current executable same-notional capacity, unconditional end-to-end settlement bound or all-in cost bound is established.",
      reviewedAt: "2026-10-03",
      docs: [sourceRef("DigiFT native uMINT disclosure within STEP2 application (March 20, 2025)", "https://forum.arbitrum.foundation/t/digift-dr-umint-step2-application/28764", ["route"])],
    },
    docs: [
      sourceRefFull("DigiFT native uMINT disclosure within STEP2 application (March 20, 2025)", "https://forum.arbitrum.foundation/t/digift-dr-umint-step2-application/28764"),
      sourceRef("UBS production subscription and redemption (November 4, 2025)", "https://www.ubs.com/global/en/media/display-page-ndp/en-20251104-chainlink.html", ["route", "access", "settlement"]),
      sourceRef("UBS Ethereum uMINT launch", "https://www.ubs.com/global/en/media/display-page-ndp/en-20241101-first-tokenized-investment-fund.html", ["route", "access"]),
    ],
    notes: [
      "Eligibility: Authorized distributor onboarding and native fund investor eligibility; current binding PPM not public.",
      "Minimum: March2025 dossier quoted$1,000; current binding minimum unknown.",
      "Use UBS production workflow only as route-existence proof; historical distributor terms and DR bare-trust terms cannot establish current native guarantees.",
      "The November 2025 production workflow proves native uMINT redemption exists. March 2025 distributor minimum, T+0 timing and fee claims remain historical; current native payout currency and binding PPM are unconfirmed. The inherited fiat projection is diagnostic compatibility, not new USD/stablecoin settlement evidence.",
      "Capacity and settlement categories are diagnostic defaults only; no immediate ratio, funded USD capacity, guaranteed settlement duration or all-in zero cost is inferred.",
    ],
  },
};
