#!/usr/bin/env node

import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { DEAD_STABLECOINS } from "@shared/lib/dead-stablecoins";
import {
  ACTIVE_STABLE_VALUE_INVESTMENTS,
  ACTIVE_VARIANT_STABLECOINS,
  CORE_AGGREGATE_ACTIVE_STABLECOINS,
} from "@shared/lib/stablecoins/aggregate-registry";
import {
  ACTIVE_STABLECOINS,
  PRE_LAUNCH_STABLECOINS,
  TRACKED_STABLECOINS,
} from "@shared/lib/stablecoins/registry";
import { syncGeneratedArtifacts } from "../lib/generated-artifacts";
import { isDirectRun } from "../lib/smoke-runtime.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "../..");
const STATIC_OUTPUT = resolve(REPO_ROOT, "src/generated/stablecoin-static-data.ts");
const PALETTE_OUTPUT = resolve(REPO_ROOT, "src/generated/command-palette-search-data.ts");

const PEG_ORDER = [
  "USD",
  "EUR",
  "GBP",
  "CHF",
  "BRL",
  "JPY",
  "KRW",
  "SGD",
  "MYR",
  "TRY",
  "AUD",
  "ZAR",
  "CAD",
  "PHP",
  "RUB",
  "CNY",
  "CNH",
  "MXN",
  "VND",
  "UAH",
  "ARS",
  "KGS",
  "NGN",
  "XOF",
  "COP",
  "CLP",
  "GHS",
  "KES",
  "PEN",
  "IDR",
  "INR",
  "HKD",
  "GOLD",
  "SILVER",
  "VAR",
  "OTHER",
] as const;

// Preserve the established serialized key order independently from the route
// order above. New active peg currencies fall back to registry encounter order.
const PEG_COUNT_ORDER = [
  "USD",
  "RUB",
  "EUR",
  "BRL",
  "VAR",
  "CHF",
  "GBP",
  "SGD",
  "JPY",
  "AUD",
  "CNH",
  "IDR",
  "KGS",
  "TRY",
  "GOLD",
  "SILVER",
  "PHP",
  "CAD",
  "ZAR",
  "MXN",
  "NGN",
  "ARS",
  "MYR",
  "KRW",
  "XOF",
  "COP",
  "CLP",
  "GHS",
  "KES",
  "PEN",
] as const;

export interface StablecoinClientProjectionCoin {
  id: string;
  name: string;
  symbol: string;
  status?: string;
  frozenAt?: string;
  flags: {
    pegCurrency: string;
  };
}

export interface StablecoinClientProjectionSources {
  tracked: readonly StablecoinClientProjectionCoin[];
  active: readonly StablecoinClientProjectionCoin[];
  coreAggregateActive: readonly StablecoinClientProjectionCoin[];
  activeVariants: readonly unknown[];
  activeStableValueInvestments: readonly unknown[];
  preLaunch: readonly unknown[];
  dead: readonly unknown[];
  pegOrder?: readonly string[];
  pegCountOrder?: readonly string[];
}

export function buildStablecoinClientProjections({
  tracked,
  active,
  coreAggregateActive,
  activeVariants,
  activeStableValueInvestments,
  preLaunch,
  dead,
  pegOrder = PEG_ORDER,
  pegCountOrder = PEG_COUNT_ORDER,
}: StablecoinClientProjectionSources) {
  const rawPegCurrencyCounts: Record<string, number> = {};
  for (const coin of active) {
    const peg = coin.flags.pegCurrency;
    rawPegCurrencyCounts[peg] = (rawPegCurrencyCounts[peg] ?? 0) + 1;
  }

  const activePegCurrencyCounts: Record<string, number> = {};
  for (const peg of [...pegCountOrder, ...Object.keys(rawPegCurrencyCounts)]) {
    if (rawPegCurrencyCounts[peg] != null && activePegCurrencyCounts[peg] == null) {
      activePegCurrencyCounts[peg] = rawPegCurrencyCounts[peg];
    }
  }

  const activePegCurrencies = pegOrder.filter((peg) => activePegCurrencyCounts[peg] != null);
  const commandPaletteStablecoins = tracked.map((coin) => {
    const row: string[] = [coin.id, coin.name, coin.symbol];
    if (coin.status != null && coin.status !== "active") {
      row.push(coin.status);
    }
    if (coin.status === "frozen" && coin.frozenAt) {
      row.push(coin.frozenAt);
    }
    return row;
  });

  return {
    trackedStablecoinCount: tracked.length,
    activeStablecoinCount: active.length,
    coreAggregateStablecoinCount: coreAggregateActive.length,
    activeVariantStablecoinCount: activeVariants.length,
    activeStableValueInvestmentCount: activeStableValueInvestments.length,
    preLaunchStablecoinCount: preLaunch.length,
    deadStablecoinCount: dead.length,
    activePegCurrencyCounts,
    activePegCurrencies,
    activeStablecoinIds: active.map((coin) => coin.id),
    homepageTopCoreStablecoins: coreAggregateActive.slice(0, 20).map(({ id, name, symbol }) => ({
      id,
      name,
      symbol,
    })),
    commandPaletteStablecoins,
  };
}

export function renderStablecoinStaticData(
  projection: ReturnType<typeof buildStablecoinClientProjections>,
): string {
  return `/** Auto-generated by scripts/build-data/generate-stablecoin-client-projections.ts. */
export const TRACKED_STABLECOIN_COUNT = ${projection.trackedStablecoinCount};
export const ACTIVE_STABLECOIN_COUNT = ${projection.activeStablecoinCount};
export const CORE_AGGREGATE_STABLECOIN_COUNT = ${projection.coreAggregateStablecoinCount};
export const ACTIVE_VARIANT_STABLECOIN_COUNT = ${projection.activeVariantStablecoinCount};
export const ACTIVE_STABLE_VALUE_INVESTMENT_COUNT = ${projection.activeStableValueInvestmentCount};
export const PRE_LAUNCH_STABLECOIN_COUNT = ${projection.preLaunchStablecoinCount};
export const DEAD_STABLECOIN_COUNT = ${projection.deadStablecoinCount};

export const ACTIVE_PEG_CURRENCY_COUNTS = ${JSON.stringify(projection.activePegCurrencyCounts, null, 2)} as const;

export const ACTIVE_PEG_CURRENCIES = ${JSON.stringify(projection.activePegCurrencies, null, 2)} as const;

export const ACTIVE_PEG_CURRENCY_COUNT = ACTIVE_PEG_CURRENCIES.length;

export const ACTIVE_STABLECOIN_ID_SET: ReadonlySet<string> = new Set(${JSON.stringify(projection.activeStablecoinIds, null, 2)});

export const HOMEPAGE_TOP_CORE_STABLECOINS = ${JSON.stringify(projection.homepageTopCoreStablecoins, null, 2)} as const;
`;
}

export function renderCommandPaletteSearchData(
  projection: ReturnType<typeof buildStablecoinClientProjections>,
): string {
  return `/** Auto-generated by scripts/build-data/generate-stablecoin-client-projections.ts. */
export const COMMAND_PALETTE_STABLECOINS = ${JSON.stringify(projection.commandPaletteStablecoins, null, 2)} as const;
`;
}

export function runCli({ check = process.argv.includes("--check") } = {}): void {
  const projection = buildStablecoinClientProjections({
    tracked: TRACKED_STABLECOINS,
    active: ACTIVE_STABLECOINS,
    coreAggregateActive: CORE_AGGREGATE_ACTIVE_STABLECOINS,
    activeVariants: ACTIVE_VARIANT_STABLECOINS,
    activeStableValueInvestments: ACTIVE_STABLE_VALUE_INVESTMENTS,
    preLaunch: PRE_LAUNCH_STABLECOINS,
    dead: DEAD_STABLECOINS,
  });

  syncGeneratedArtifacts({
    artifacts: [
      { path: STATIC_OUTPUT, contents: renderStablecoinStaticData(projection) },
      { path: PALETTE_OUTPUT, contents: renderCommandPaletteSearchData(projection) },
    ],
    check,
    staleMessage:
      "Stablecoin client projections are stale. Run `node --import tsx scripts/build-data/generate-stablecoin-client-projections.ts`.",
    currentMessage: `Stablecoin client projections are current for ${projection.trackedStablecoinCount} tracked coins`,
    writtenMessage: `Generated client projections for ${projection.trackedStablecoinCount} tracked coins`,
  });
}

if (isDirectRun(import.meta.url, process.argv[1])) {
  runCli();
}
