import type {
  DependencyCriticality,
  DependencyImpactLayer,
  PublicationSurfaceId,
} from "../types/status";
import {
  DATA_SURFACE_DESCRIPTORS,
  type DataSurfaceDescriptor,
} from "./data-surface-descriptors";

export interface DataDependencyDefinition {
  id: string;
  label: string;
  sourceOfTruth: string;
  producerJob: string | null;
  cacheKey: string | null;
  publicationSurface: PublicationSurfaceId | null;
  impactLayer: DependencyImpactLayer;
  criticality: DependencyCriticality;
  dependsOn: readonly string[];
  consumers: readonly string[];
  runbookPath: string | null;
}

const REPORT_CARDS_SURFACE: DataSurfaceDescriptor = DATA_SURFACE_DESCRIPTORS.reportCards;

export const DATA_DEPENDENCY_REGISTRY = [
  {
    id: "stablecoins",
    label: "Stablecoin market snapshot",
    sourceOfTruth: "cache:stablecoins",
    producerJob: DATA_SURFACE_DESCRIPTORS.stablecoins.producerJob,
    cacheKey: DATA_SURFACE_DESCRIPTORS.stablecoins.cacheKey,
    publicationSurface: null,
    impactLayer: "availability",
    criticality: DATA_SURFACE_DESCRIPTORS.stablecoins.dependencyCriticality,
    dependsOn: [],
    consumers: ["home", "stablecoin-detail", "report-cards", "api:stablecoins"],
    runbookPath: "docs/runbooks/stablecoins-cache.md",
  },
  {
    id: "stablecoin-charts",
    label: "Stablecoin chart history",
    sourceOfTruth: "cache:stablecoin-charts",
    producerJob: "sync-stablecoin-charts",
    cacheKey: "stablecoin-charts",
    publicationSurface: null,
    impactLayer: "availability",
    criticality: "watch",
    dependsOn: ["stablecoins"],
    consumers: ["stablecoin-detail", "api:stablecoin-charts"],
    runbookPath: null,
  },
  {
    id: "fx-rates",
    label: "FX reference rates",
    sourceOfTruth: "cache:fx-rates",
    producerJob: "sync-fx-rates",
    cacheKey: "fx-rates",
    publicationSurface: null,
    impactLayer: "availability",
    criticality: "critical",
    dependsOn: [],
    consumers: ["stablecoin-pricing", "api:stablecoins"],
    runbookPath: null,
  },
  {
    id: "dex-liquidity",
    label: "DEX liquidity scoring",
    sourceOfTruth: "dex_liquidity_publication_generations",
    producerJob: DATA_SURFACE_DESCRIPTORS.dexLiquidity.producerJob,
    cacheKey: DATA_SURFACE_DESCRIPTORS.dexLiquidity.cacheKey,
    publicationSurface: "dex-liquidity",
    impactLayer: "availability",
    criticality: DATA_SURFACE_DESCRIPTORS.dexLiquidity.dependencyCriticality,
    dependsOn: ["stablecoins"],
    consumers: ["liquidity-ranking", "dews", "report-cards", "redemption-backstops", "yield-rankings"],
    runbookPath: null,
  },
  {
    id: "yield-rankings",
    label: "Yield rankings",
    sourceOfTruth: "yield_publication_generations",
    producerJob: DATA_SURFACE_DESCRIPTORS.yieldRankings.producerJob,
    cacheKey: DATA_SURFACE_DESCRIPTORS.yieldRankings.cacheKey,
    publicationSurface: "yield-rankings",
    impactLayer: "availability",
    criticality: DATA_SURFACE_DESCRIPTORS.yieldRankings.dependencyCriticality,
    dependsOn: ["dex-liquidity"],
    consumers: ["yield-intelligence", "report-cards", "api:yield"],
    runbookPath: null,
  },
  {
    id: "dews",
    label: "DEWS risk signals",
    sourceOfTruth: "cache:dews",
    producerJob: DATA_SURFACE_DESCRIPTORS.stressSignals.producerJob,
    cacheKey: DATA_SURFACE_DESCRIPTORS.stressSignals.cacheKey,
    publicationSurface: "dews",
    impactLayer: "availability",
    criticality: DATA_SURFACE_DESCRIPTORS.stressSignals.dependencyCriticality,
    dependsOn: ["dex-liquidity"],
    consumers: ["stress-signals", "telegram-alerts", "report-cards"],
    runbookPath: null,
  },
  {
    id: "psi",
    label: "PSI compute",
    sourceOfTruth: "cron_runs:stability-index",
    producerJob: "stability-index",
    cacheKey: null,
    publicationSurface: "psi",
    impactLayer: "availability",
    criticality: "watch",
    dependsOn: ["dews"],
    consumers: ["psi", "shadow-assets"],
    runbookPath: null,
  },
  {
    id: "project-tape",
    label: "Tape projector",
    sourceOfTruth: "cron_runs:project-tape",
    producerJob: "project-tape",
    cacheKey: null,
    publicationSurface: null,
    impactLayer: "availability",
    criticality: "watch",
    dependsOn: ["dews"],
    consumers: ["project-tape"],
    runbookPath: null,
  },
  {
    id: "safety-score-v9",
    label: "Safety Score V9 publication",
    sourceOfTruth: "cache:report-cards:v9",
    producerJob: DATA_SURFACE_DESCRIPTORS.reportCards.producerJob,
    cacheKey: REPORT_CARDS_SURFACE.cacheKey ?? null,
    publicationSurface: "safety-score-v9",
    impactLayer: "availability",
    criticality: DATA_SURFACE_DESCRIPTORS.reportCards.dependencyCriticality,
    dependsOn: ["stablecoins", "dex-liquidity", "redemption-backstops", "live-reserves"],
    consumers: ["report-cards", "stablecoin-detail", "yield-rankings"],
    runbookPath: null,
  },
  {
    id: "redemption-backstops",
    label: "Redemption backstops",
    sourceOfTruth: "cron_runs:sync-redemption-backstops",
    producerJob: "sync-redemption-backstops",
    cacheKey: null,
    publicationSurface: null,
    impactLayer: "availability",
    criticality: "watch",
    dependsOn: ["stablecoins", "dex-liquidity"],
    consumers: ["reserve-risk", "report-cards", "safety-score-v9"],
    runbookPath: null,
  },
  {
    id: "live-reserves",
    label: "Live reserve composition",
    sourceOfTruth: "reserve_sync_state",
    producerJob: "sync-live-reserves",
    cacheKey: null,
    publicationSurface: null,
    impactLayer: "data-quality",
    criticality: "watch",
    dependsOn: ["stablecoins"],
    consumers: ["reserve-risk", "report-cards", "safety-score-v9", "stablecoin-detail"],
    runbookPath: null,
  },
  {
    id: "bluechip-ratings",
    label: "Bluechip ratings",
    sourceOfTruth: "cache:bluechip-ratings",
    producerJob: "sync-bluechip",
    cacheKey: "bluechip-ratings",
    publicationSurface: null,
    impactLayer: "data-quality",
    criticality: "watch",
    dependsOn: [],
    consumers: ["report-cards", "stablecoin-detail"],
    runbookPath: null,
  },
  {
    id: "usds-status",
    label: "USDS status",
    sourceOfTruth: "cache:usds-status",
    producerJob: "sync-usds-status",
    cacheKey: "usds-status",
    publicationSurface: null,
    impactLayer: "data-quality",
    criticality: "watch",
    dependsOn: [],
    consumers: ["stablecoin-detail", "report-cards"],
    runbookPath: null,
  },
] as const satisfies readonly DataDependencyDefinition[];

export const DATA_DEPENDENCY_BY_ID: ReadonlyMap<string, DataDependencyDefinition> = new Map(
  DATA_DEPENDENCY_REGISTRY.map((definition) => [definition.id, definition]),
);
