// Generated by scripts/maintenance/generate-editorial-style.ts from the
// `editorial-policy` fence in docs/editorial-style.md. Do not edit by hand:
// edit the document and regenerate. Serialized data only, no logic.
import type { EditorialPolicy } from "./editorial-style";

export const EDITORIAL_STYLE_VERSION = "1.2";

/** Deterministic hash of the policy block. Bumps whenever enforcement changes. */
export const EDITORIAL_STYLE_HASH = "baf6b0f7f9efd4cc";

export const EDITORIAL_POLICY: EditorialPolicy = {
  "version": "1.2",
  "oneLineDirective": "Write like an FT markets reporter with the tape in front of you: strongest verified fact first, distinguish observation from inference, explain the consequence plainly, no clause dashes, no corrective \"this is not X, it is Y\", no personified metrics, no nickname titles, no slogan closers. Wit only if deleting the names and figures kills the line; the default is none.",
  "registers": [
    {
      "id": "daily",
      "label": "Daily editorial",
      "group": "editorial",
      "promptLine": "Lead with the highest-impact verified fact in 150 to 280 words plus a compact hook. Zero sharp lines is the default and one is the cap; sardonic is rare, never consecutive, and rotation-enforced. Preserve lead-family, opening-shape, and tone anti-repetition rules. Name a material observable trigger when the evidence contains one; never force a threshold ending."
    },
    {
      "id": "weekly",
      "label": "Weekly synthesis",
      "group": "editorial",
      "promptLine": "Build the week's causal arc from daily evidence, separate persistent moves from reversals, and score prior expectations honestly. This is the strictest temperature, not the loosest; never personify indexes."
    },
    {
      "id": "coin-summary",
      "label": "Coin summary",
      "group": "editorial",
      "promptLine": "120 to 180 words as guidance with a hard ceiling of 250; shorter is legal when the evidence is complete, and length above the band must be carried by evidence, not narration. One main claim per sentence. The title is a plain descriptor or a characterization this coin's own record supports; puns, mascots, rhymes, and generic slogans are banned, and a title that would fit any other coin is generic. Explain what the asset is, its central trade-off, and what Pharos data reveals that a listing page would miss. Close on the durable constraint; no punch required."
    },
    {
      "id": "cemetery",
      "label": "Cemetery",
      "group": "editorial",
      "promptLine": "Obituary: chronological, sober, complete. Epitaph: short, with one evidence-backed barb permitted because the outcome is settled. No animal or mascot nicknames."
    },
    {
      "id": "long-form",
      "label": "Long-form",
      "group": "editorial",
      "promptLine": "Narrative and first person are allowed where they add provenance. Claims need dates, scope, and receipts."
    },
    {
      "id": "profile-reference",
      "label": "Profile reference",
      "group": "technical",
      "promptLine": "Compressed reference copy: specific, factual, no wit, no marketing. Terms of art are allowed."
    },
    {
      "id": "pre-launch",
      "label": "Pre-launch record",
      "group": "technical",
      "promptLine": "Dated factual record: what was announced, by whom, with what commitment. No predictions, launch copy, or dash-glossed titles."
    },
    {
      "id": "notice",
      "label": "Notice",
      "group": "technical",
      "promptLine": "Urgent register: the event, the effect on holders, the source. Direct, calm, complete. No wit."
    },
    {
      "id": "lifecycle",
      "label": "Lifecycle reason",
      "group": "technical",
      "promptLine": "Operational register: event, effective date, concise rationale. Administrative unless the underlying event is urgent."
    },
    {
      "id": "release-note",
      "label": "Release note",
      "group": "technical",
      "promptLine": "Material change and its consequence for readers or operators. Wit is unavailable. Name the moves the period actually had; a three-item headline shape is banned as a template."
    },
    {
      "id": "technical-release-note",
      "label": "Technical release note",
      "group": "technical",
      "promptLine": "Precise deltas and version references, no editorial framing."
    },
    {
      "id": "reference-teaching",
      "label": "Reference teaching",
      "group": "technical",
      "promptLine": "Definitions and mechanisms with defined terms and no performance. Teaching basics is this register's job."
    },
    {
      "id": "technical-evidence",
      "label": "Technical evidence",
      "group": "technical",
      "promptLine": "Accuracy, uncertainty, defined terms, and source fidelity outrank flourish. Completeness beats concision."
    },
    {
      "id": "page-description",
      "label": "Page description",
      "group": "product",
      "promptLine": "One or two plain sentences on what the page contains and why it is useful. No jokes, suspense, slogans, or unsupported uniqueness claims."
    },
    {
      "id": "analytical-explanation",
      "label": "Analytical explanation",
      "group": "product",
      "promptLine": "Claim-safety rules in full: no recommendations, no unqualified safety or convenience claims, qualified comparisons only."
    },
    {
      "id": "product-utility",
      "label": "Product utility",
      "group": "product",
      "promptLine": "Direct and calm. No wit where a reader needs an instruction or warning. Error copy states what happened and what to do."
    },
    {
      "id": "brand",
      "label": "Brand",
      "group": "product",
      "promptLine": "Universal rules without exemption. State the commitment and the evidence for it; aphoristic contrast is not a house voice."
    },
    {
      "id": "alert",
      "label": "Alert",
      "group": "product",
      "promptLine": "Fast, factual, scannable. Registered data-tied glyphs are functional, not decorative."
    },
    {
      "id": "delivery-wrapper",
      "label": "Delivery wrapper",
      "group": "product",
      "promptLine": "Utility register, not editorial. Wrapper strings pass the same scanner as the copy they frame. The cemetery-appendix footer rotation alone keeps its dark data-tied flavor under a named exemption."
    }
  ],
  "rules": [
    {
      "id": "no-clause-dash",
      "promptLabel": "Never use em, en, figure, or horizontal-bar dashes. Use a period, comma, colon, or semicolon.",
      "patterns": [
        {
          "source": "[\\u2012\\u2013\\u2014\\u2015]",
          "flags": "gu"
        }
      ],
      "severity": {
        "default": "hard"
      },
      "exceptions": [
        "quoted-source",
        "external-title",
        "code",
        "identifier"
      ],
      "replacementAdvice": "Most clause dashes split into two sentences; use a colon, comma, or semicolon only where the logic calls for one, and never answer every dash with the same mark.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "Supply fell — the peg held."
        ],
        "clean": [
          "Scores run 0-100.",
          "The reserve holds 1-3 month Treasury bills.",
          "Keep the answer to 45-80 words."
        ]
      }
    },
    {
      "id": "no-minus-as-dash",
      "promptLabel": "Never use a mathematical minus as a clause dash. Signed numbers keep their minus.",
      "patterns": [
        {
          "source": "\\u2212(?![\\d.,])",
          "flags": "gu"
        }
      ],
      "severity": {
        "default": "hard"
      },
      "exceptions": [
        "quoted-source",
        "code",
        "identifier",
        "numeric-sign"
      ],
      "replacementAdvice": "A style rule never rewrites a number. If this is a clause break, use punctuation; if it is a signed value, keep it.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "Supply fell − the peg held."
        ],
        "clean": [
          "PSI moved −5% on the day.",
          "Deviation was −0.3bps against the peg."
        ]
      }
    },
    {
      "id": "no-corrective-cleft",
      "promptLabel": "Review pronoun-led corrective clefts such as \"this is not A, it is B\"; necessary technical distinctions can share this grammar.",
      "patterns": [
        {
          "source": "\\b(?:it|this|that|they)\\s+(?:is|was|are|were)\\s+not\\s+[^.,;:!?]{1,60}[,;]\\s+(?:it|this|that|they)\\s+(?:is|was|are|were)\\b",
          "flags": "giu"
        },
        {
          "source": "\\b(?:it|this|that|they)\\s+(?:is|was|are|were)n['\\u2019]t\\s+[^.,;:!?]{1,60}[,;]\\s+(?:it|this|that|they)\\s*(?:is|was|are|were|['\\u2019]s)\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "advisory"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Check whether this is a rhetorical flip. If so, state the fact and consequence directly; preserve necessary technical distinctions.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "This isn't a tweak; it's a rebuild."
        ],
        "clean": [
          "The 72h backstop is not a weaker forecast-readiness score; it is the public accountability deadline.",
          "The $0.87 floor was not a loss of backing; it was the issuer codifying the redemption discount."
        ]
      }
    },
    {
      "id": "no-corrective-cleft-split",
      "promptLabel": "Do not split a corrective cleft across two sentences (\"X is not A. It is B.\").",
      "patterns": [
        {
          "source": "\\b(?:It|This|That|They)\\s+(?:is|was|are|were)\\s+not\\s+[^.,;:!?]{1,60}\\.\\s+(?:It|This|That|They)\\s+(?:is|was|are|were)\\b",
          "flags": "gu"
        },
        {
          "source": "\\b(?:It|This|That|They)\\s+(?:is|was|are|were)n['\\u2019]t\\s+[^.,;:!?]{1,60}\\.\\s+(?:It|This|That|They)\\s*(?:is|was|are|were|['\\u2019]s)\\b",
          "flags": "gu"
        }
      ],
      "severity": {
        "default": "advisory"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Advisory because a sentence boundary often separates two unrelated facts; a reviewer decides whether this is a rhetorical flip.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "This is not a coincidence. It is a preference."
        ],
        "clean": [
          "Its timelock semantics were not resolved. It is retained as an evidence gap."
        ]
      }
    },
    {
      "id": "no-suspense-opener",
      "promptLabel": "Never open with withheld-subject suspense (\"What it doesn't have is ...\").",
      "patterns": [
        {
          "source": "(?:^|[.!?]\\s+)What\\s+(?:(?:it|this|that|they|[A-Z][A-Za-z0-9'\\u2019-]*(?:\\s+[A-Z][A-Za-z0-9'\\u2019-]*){0,3})\\s+(?:(?:does|do|did)\\s+(?:not|n['\\u2019]?t)\\s+(?:have|do|show)|lacks?))\\s+is\\b",
          "flags": "gmu"
        }
      ],
      "severity": {
        "default": "hard"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Put the substantive fact first.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "What it does not have is liquidity.",
          "What USDC lacks is users."
        ],
        "clean": [
          "The guide quotes \"What it doesn't have is users\" as an anti-example."
        ]
      }
    },
    {
      "id": "no-stale-phrase",
      "promptLabel": "Never use context-independent boilerplate: testament to, time will tell, it remains to be seen, in a world where, game-changing, cutting-edge, needless to say, it's worth noting or it is worth noting, or a sentence opened with In summary, or In conclusion,.",
      "patterns": [
        {
          "source": "\\btestament to\\b",
          "flags": "giu"
        },
        {
          "source": "\\btime will tell\\b",
          "flags": "giu"
        },
        {
          "source": "\\bit remains to be seen\\b",
          "flags": "giu"
        },
        {
          "source": "\\bin a world where\\b",
          "flags": "giu"
        },
        {
          "source": "\\bgame[- ]changing\\b",
          "flags": "giu"
        },
        {
          "source": "\\bcutting[- ]edge\\b",
          "flags": "giu"
        },
        {
          "source": "\\bneedless to say\\b",
          "flags": "giu"
        },
        {
          "source": "\\bit(?:['\\u2019]s|\\s+is)\\s+worth noting\\b",
          "flags": "giu"
        },
        {
          "source": "(?:^|[.!?]\\s+)In (?:summary|conclusion),",
          "flags": "gmu"
        }
      ],
      "severity": {
        "default": "hard"
      },
      "exceptions": [
        "quoted-source",
        "external-title"
      ],
      "replacementAdvice": "Delete the phrase and state the fact.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "The growth is a testament to demand.",
          "It is worth noting that supply fell.",
          "In conclusion, the peg held."
        ],
        "clean": [
          "The testamentary trust holds the shares.",
          "The conclusion of the audit is dated June 2026."
        ]
      }
    },
    {
      "id": "no-ambiguous-stale-phrase",
      "promptLabel": "Avoid ambiguous stale phrasing where context permits: at its core, delve, lowercase revolutionary, bare worth noting, and a sentence opened with Overall,.",
      "patterns": [
        {
          "source": "\\bat its core\\b",
          "flags": "giu"
        },
        {
          "source": "\\bdelv(?:e|es|ed|ing)\\b",
          "flags": "giu"
        },
        {
          "source": "\\brevolutionary\\b",
          "flags": "gu"
        },
        {
          "source": "\\bworth noting\\b",
          "flags": "giu"
        },
        {
          "source": "(?:^|[.!?]\\s+)Overall,",
          "flags": "gmu"
        }
      ],
      "severity": {
        "default": "advisory"
      },
      "exceptions": [
        "quoted-source",
        "external-title"
      ],
      "replacementAdvice": "Prefer the specific mechanism; preserve legitimate historical or proper-name use.",
      "introducedIn": "1.1",
      "examples": {
        "violating": [
          "At its core, the protocol is a CDP.",
          "We delve into the reserve report.",
          "The design is revolutionary.",
          "Overall, the design held up.",
          "The reserve mix is worth noting."
        ],
        "clean": [
          "Revolutionary Finance Ltd. issued the token.",
          "The overall grade stayed at B+."
        ]
      }
    },
    {
      "id": "no-fashionable-tell",
      "promptLabel": "Avoid the fashionable tells: underscores the, poised to, stark reminder, marks a significant. State the consequence and let the size of the number carry the significance.",
      "patterns": [
        {
          "source": "\\bunderscor(?:es|ed|ing)\\s+(?:the|its|their|how|that|why|a|an)\\b",
          "flags": "giu"
        },
        {
          "source": "\\bpoised to\\b",
          "flags": "giu"
        },
        {
          "source": "\\bstark reminder\\b",
          "flags": "giu"
        },
        {
          "source": "\\bmark(?:s|ed)? a significant\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "advisory"
      },
      "exceptions": [
        "quoted-source",
        "external-title"
      ],
      "replacementAdvice": "Name the consequence directly; a number that matters does not need to be told it is significant.",
      "introducedIn": "1.2",
      "examples": {
        "violating": [
          "The freeze underscores the custodian's control.",
          "The issuer is poised to expand.",
          "The outage is a stark reminder of oracle dependence.",
          "The vote marks a significant shift."
        ],
        "clean": [
          "Provider ids with underscores are normalized before matching.",
          "The freeze shows the custodian can halt transfers unilaterally."
        ]
      }
    },
    {
      "id": "no-hedged-closer",
      "promptLabel": "Never close on: worth watching, worth monitoring, bears watching, for now, the question is whether. Name the next observable threshold instead.",
      "patterns": [
        {
          "source": "\\b(?:worth|bears?)\\s+(?:watching|monitoring)[.!?]?\\s*$",
          "flags": "giu"
        },
        {
          "source": "\\bfor now[.!?]?\\s*$",
          "flags": "giu"
        },
        {
          "source": "\\bthe (?:real )?question is whether\\b[^.!?]*[.!?]?\\s*$",
          "flags": "giu"
        }
      ],
      "closerOnly": true,
      "severity": {
        "default": "hard"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Say what to watch, when, and what it would mean.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "Supply fell 4%. The pool is worth watching. (Source: issuer report)"
        ],
        "clean": [
          "The cap stays unchanged for now because no vote has passed."
        ]
      }
    },
    {
      "id": "no-dead-metaphor",
      "promptLabel": "In editorial registers never use: beneath the calm, surface calm, restless depths, or something moving underneath.",
      "patterns": [
        {
          "source": "\\bbeneath the calm\\b",
          "flags": "giu"
        },
        {
          "source": "\\bsurface calm\\b",
          "flags": "giu"
        },
        {
          "source": "\\brestless depths\\b",
          "flags": "giu"
        },
        {
          "source": "\\bsomething (?:is )?moving underneath\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "advisory",
        "byRegister": {
          "daily": "hard",
          "weekly": "hard",
          "coin-summary": "hard",
          "cemetery": "hard",
          "long-form": "hard"
        }
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Describe the mechanism instead of the weather.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "Beneath the calm, redemptions accelerated."
        ],
        "clean": [
          "The headline figure belies a change in reserve composition.",
          "The cable remains below the waterline."
        ]
      }
    },
    {
      "id": "no-unqualified-safety",
      "promptLabel": "Never make unqualified safety claims: safe, safest, risk-free, low-risk, guaranteed. Rankings name metric, scope, and date.",
      "patterns": [
        {
          "source": "(?<![A-Za-z-])safe(?!\\s+harbou?r\\b)(?![A-Za-z-])",
          "flags": "gu"
        },
        {
          "source": "(?<![A-Za-z-])safest(?![A-Za-z-])",
          "flags": "giu"
        },
        {
          "source": "\\brisk[- ]free\\b",
          "flags": "giu"
        },
        {
          "source": "\\blow[- ]risk\\b",
          "flags": "giu"
        },
        {
          "source": "(?<!no )\\bguarantee(?:d|s)?\\b(?!\\s+(?:schemes?|funds?)\\b)(?!\\s+by\\s+(?:the\\s+)?issuer\\b)",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "advisory",
        "byRegister": {
          "profile-reference": "hard",
          "page-description": "hard",
          "analytical-explanation": "hard",
          "product-utility": "hard",
          "brand": "hard",
          "alert": "hard",
          "delivery-wrapper": "hard"
        }
      },
      "exceptions": [
        "quoted-source",
        "external-title",
        "legal-term"
      ],
      "replacementAdvice": "Name the metric, scope, and date, or drop the claim.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "USDC is a low-risk place to park dollars."
        ],
        "clean": [
          "MiCA safe harbor",
          "There is no guarantee",
          "deposit guarantee scheme",
          "deposit guarantee schemes",
          "guaranteed by the issuer",
          "guarantee fund",
          "Control sits with a 3-of-5 Safe.",
          "The asset is not a safe-haven trade."
        ]
      }
    },
    {
      "id": "no-investment-recommendation",
      "promptLabel": "Never recommend buying, holding, selling, or switching.",
      "patterns": [
        {
          "source": "\\bwe recommend(?:\\s+(?:you\\s+)?(?:buy|hold|sell|switch|move|use))?\\b",
          "flags": "giu"
        },
        {
          "source": "\\byou should (?:buy|hold|sell|switch|move)\\b",
          "flags": "giu"
        },
        {
          "source": "\\bPharos recommends?\\b",
          "flags": "giu"
        },
        {
          "source": "(?:^|[.!?]\\s+)(?:Buy|Hold|Sell)\\s+(?:[A-Z][A-Z0-9]{1,9}|the\\s+(?:asset|coin|token)|this\\s+(?:asset|coin|token))\\b",
          "flags": "gmu"
        },
        {
          "source": "(?:^|[.!?]\\s+)Use\\s+[A-Z][A-Z0-9]{1,9}\\s+for\\s+(?:venue access|custody|yield|trading)\\b",
          "flags": "gmu"
        },
        {
          "source": "\\b(?:investors?|holders?|users?)\\s+should\\s+(?:consider\\s+)?(?:buying|holding|selling|switching|moving|using)\\b",
          "flags": "giu"
        },
        {
          "source": "\\b(?:our|the)\\s+top\\s+recommendation\\s+is\\s+to\\s+(?:buy|hold|sell|switch|move|use)\\b",
          "flags": "giu"
        },
        {
          "source": "\\b[A-Z][A-Z0-9]{1,9}\\s+is\\s+(?:the\\s+)?best\\s+buy\\b",
          "flags": "gu"
        },
        {
          "source": "\\b(?:our|Pharos['\\u2019]s)\\s+top pick\\b",
          "flags": "giu"
        },
        {
          "source": "\\bhold safely\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "hard"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Describe the trade-off and let the reader decide.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "Buy USDC.",
          "Investors should consider switching to USDC.",
          "Our top recommendation is to hold USDC.",
          "USDC is the best buy."
        ],
        "clean": [
          "The policy bans the phrase top pick.",
          "The issuer called USDC its top pick."
        ]
      }
    },
    {
      "id": "no-unqualified-convenience",
      "promptLabel": "Do not claim an asset or route is easy, simple, or convenient without naming the concrete operational property.",
      "patterns": [
        {
          "source": "\\b(?:easy|simple|convenient)\\s+(?:way|option|choice|asset|coin|stablecoin|route|solution|tool)\\b",
          "flags": "giu"
        },
        {
          "source": "\\b(?:easy|simple|convenient)\\s+(?:to|for)\\b",
          "flags": "giu"
        },
        {
          "source": "\\b(?:is|are|was|were)\\s+(?:easy|simple|convenient)\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "off",
        "byRegister": {
          "analytical-explanation": "hard"
        }
      },
      "exceptions": [
        "quoted-source",
        "external-title"
      ],
      "replacementAdvice": "Name the steps, access constraint, cost, or venue coverage that makes the route convenient.",
      "introducedIn": "1.1",
      "examples": {
        "violating": [
          "USDC is easy to use.",
          "This is a convenient option for custody."
        ],
        "clean": [
          "The calculation uses a simple moving average."
        ]
      }
    },
    {
      "id": "review-unsupported-reliability",
      "promptLabel": "Review probably, likely, and reliably in deterministic risk explanations; attach evidence or state the uncertainty directly.",
      "patterns": [
        {
          "source": "\\b(?:probably|likely|reliably)\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "off",
        "byRegister": {
          "analytical-explanation": "advisory"
        }
      },
      "exceptions": [
        "quoted-source",
        "external-title"
      ],
      "replacementAdvice": "Attach the probability, evidence, or mechanism behind the reliability claim.",
      "introducedIn": "1.1",
      "examples": {
        "violating": [
          "Redemptions will probably remain open."
        ],
        "clean": []
      }
    },
    {
      "id": "no-marketing-social-proof",
      "promptLabel": "Do not use trusted by or battle-tested as unsupported social proof in analytical explanations.",
      "patterns": [
        {
          "source": "\\btrusted by\\b",
          "flags": "giu"
        },
        {
          "source": "\\bbattle[- ]tested\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "off",
        "byRegister": {
          "analytical-explanation": "hard"
        }
      },
      "exceptions": [
        "quoted-source",
        "external-title"
      ],
      "replacementAdvice": "Replace social proof with dated usage, incident, or operational evidence.",
      "introducedIn": "1.1",
      "examples": {
        "violating": [
          "The route is battle-tested.",
          "The coin is trusted by institutions."
        ],
        "clean": []
      }
    },
    {
      "id": "review-unqualified-superlative",
      "promptLabel": "Review bare rankings and superlatives; name the metric, scope, and date.",
      "patterns": [
        {
          "source": "(?:^|[.!?]\\s+)(?=[^.!?]{0,180}\\b(?:largest|strongest|highest[- ]quality|best)\\b)(?![^.!?]{0,180}\\b(?:among|within|as of|liquidity score|market cap(?:italization)?|circulating supply|redemption depth|yield|20\\d{2})\\b)[^.!?]{0,180}(?:[.!?]|$)",
          "flags": "gimu"
        }
      ],
      "severity": {
        "default": "off",
        "byRegister": {
          "daily": "advisory",
          "weekly": "advisory",
          "coin-summary": "advisory",
          "profile-reference": "advisory",
          "page-description": "advisory",
          "analytical-explanation": "advisory",
          "product-utility": "advisory",
          "brand": "advisory",
          "alert": "advisory",
          "delivery-wrapper": "advisory"
        }
      },
      "exceptions": [
        "quoted-source",
        "external-title"
      ],
      "replacementAdvice": "Add the metric, comparison universe, and date, or remove the ranking.",
      "introducedIn": "1.1",
      "examples": {
        "violating": [
          "USDC is the largest stablecoin.",
          "This is the strongest design.",
          "The highest-quality reserve is here."
        ],
        "clean": [
          "USDC had the highest liquidity score among tracked USD coins in June 2026."
        ]
      }
    },
    {
      "id": "review-unattributed-technical-risk",
      "promptLabel": "Review technical risk labels that do not name a methodology or source.",
      "patterns": [
        {
          "source": "(?:^|[.!?]\\s+)(?=[^.!?]{0,180}\\b(?:high|medium|low)[- ]risk\\b)(?![^.!?]{0,180}\\b(?:according to|under|rated|methodology|score|audit|report|source|Pharos V\\d+)\\b)[^.!?]{0,180}(?:[.!?]|$)",
          "flags": "gimu"
        }
      ],
      "severity": {
        "default": "off",
        "byRegister": {
          "daily": "advisory",
          "weekly": "advisory",
          "coin-summary": "advisory",
          "profile-reference": "advisory",
          "page-description": "advisory",
          "analytical-explanation": "advisory",
          "product-utility": "advisory",
          "brand": "advisory",
          "alert": "advisory",
          "delivery-wrapper": "advisory"
        }
      },
      "exceptions": [
        "quoted-source",
        "external-title"
      ],
      "replacementAdvice": "Name the methodology, rating, audit, or source behind the risk label.",
      "introducedIn": "1.1",
      "examples": {
        "violating": [
          "This is a high-risk redemption route."
        ],
        "clean": [
          "Pharos V9 rates the route high-risk under the exit methodology."
        ]
      }
    },
    {
      "id": "no-booster-language",
      "promptLabel": "No booster language, empty intensifiers, exclamation marks, or clickbait questions.",
      "patterns": [
        {
          "source": "\\bbuckle up\\b",
          "flags": "giu"
        },
        {
          "source": "\\b(?:truly|incredibly|massively|hugely) (?:remarkable|impressive|significant)\\b",
          "flags": "giu"
        },
        {
          "source": "!",
          "flags": "gu"
        },
        {
          "source": "(?:^|[.!?]\\s+)(?:Can you believe|Guess what|What happens next|Ready to|Want to know)[^?]*\\?",
          "flags": "gimu"
        }
      ],
      "severity": {
        "default": "advisory",
        "byRegister": {
          "daily": "hard",
          "weekly": "hard",
          "coin-summary": "hard"
        }
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Let the number carry the emphasis.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "Supply jumped 40%!",
          "Buckle up, the peg moved."
        ],
        "clean": [
          "Supply increased 40% after the vote."
        ]
      }
    },
    {
      "id": "no-personified-metric",
      "promptLabel": "Named indexes, scores, gauges, and regimes do not nap, shrug, yawn, notice, refuse, or applaud. State what the number did.",
      "patterns": [
        {
          "source": "\\b(?:PSI|DEWS|the index|the score|the gauge|the model|the market|the tape|the regime)\\s+(?:napp?ed|naps|shrugg?ed|shrugs|yawn(?:ed|s)?|notic(?:ed|es)|refus(?:ed|es)|applaud(?:ed|s)|sleeps|slept)\\b",
          "flags": "giu"
        },
        {
          "source": "\\bleft the building\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "advisory"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Name the movement and its size.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "The model shrugged at the outflow."
        ],
        "clean": [
          "The model score fell by four points."
        ]
      }
    },
    {
      "id": "no-hedge-stack",
      "promptLabel": "Do not stack qualifiers. One warranted qualifier is honesty; three is mush.",
      "patterns": [
        {
          "source": "\\bcould potentially\\b",
          "flags": "giu"
        },
        {
          "source": "\\bmight arguably\\b",
          "flags": "giu"
        },
        {
          "source": "\\bmay possibly\\b",
          "flags": "giu"
        },
        {
          "source": "\\bsomewhat (?:arguably|possibly|potentially)\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "advisory"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Keep one qualifier or state the uncertainty directly.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "Redemptions could potentially slow."
        ],
        "clean": [
          "Redemptions may slow while the pause remains active."
        ]
      }
    },
    {
      "id": "no-recategorizing-flip",
      "promptLabel": "Avoid \"not merely X\" and \"isn't just X\" used to recategorize rather than to state a fact.",
      "patterns": [
        {
          "source": "\\bnot (?:merely|simply)\\b",
          "flags": "giu"
        },
        {
          "source": "\\b(?:is|are|was|were)n['\\u2019]t just\\b",
          "flags": "giu"
        },
        {
          "source": "\\b(?:is|are|was|were) not just\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "advisory"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Say what it is, with the evidence.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "This is not merely a reserve change."
        ],
        "clean": [
          "The report covers cash, not liabilities."
        ]
      }
    },
    {
      "id": "scoped-decorative-word",
      "promptLabel": "In editorial registers avoid decorative uses of: quietly, meanwhile, landscape, plumbing.",
      "patterns": [
        {
          "source": "\\bquietly\\b",
          "flags": "giu"
        },
        {
          "source": "\\bmeanwhile\\b",
          "flags": "giu"
        },
        {
          "source": "\\blandscape\\b",
          "flags": "giu"
        },
        {
          "source": "\\bplumbing\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "off",
        "byRegister": {
          "daily": "advisory",
          "weekly": "advisory",
          "coin-summary": "advisory",
          "cemetery": "advisory",
          "long-form": "advisory"
        }
      },
      "exceptions": [
        "quoted-source",
        "external-title"
      ],
      "replacementAdvice": "Describe the timing, visibility, or mechanism instead.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "Meanwhile, liquidity fell."
        ],
        "clean": [
          "The regulatory framework changed in June."
        ]
      }
    },
    {
      "id": "scoped-market-metaphor",
      "promptLabel": "Do not use obituary, post-mortem, carcass, or furniture as casual market metaphors.",
      "patterns": [
        {
          "source": "\\bobituar(?:y|ies)\\b",
          "flags": "giu"
        },
        {
          "source": "\\bpost[- ]?mortem\\b",
          "flags": "giu"
        },
        {
          "source": "\\bcarcass\\b",
          "flags": "giu"
        },
        {
          "source": "\\bfurniture\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "off",
        "byRegister": {
          "daily": "advisory",
          "weekly": "advisory",
          "coin-summary": "advisory"
        }
      },
      "exceptions": [
        "quoted-source",
        "external-title",
        "literal-cemetery"
      ],
      "replacementAdvice": "Use the literal event or outcome.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "The token became market furniture."
        ],
        "clean": []
      }
    },
    {
      "id": "spaced-hyphen-clause-dash",
      "promptLabel": "Do not use a spaced hyphen as a clause dash.",
      "patterns": [
        {
          "source": "(?<=\\S) - (?=\\S)",
          "flags": "gu"
        }
      ],
      "severity": {
        "default": "advisory"
      },
      "exceptions": [
        "quoted-source",
        "code",
        "identifier",
        "numeric-sign",
        "table"
      ],
      "replacementAdvice": "Use a colon, comma, semicolon, or period.",
      "introducedIn": "1.0",
      "examples": {
        "violating": [
          "Supply fell - the peg held."
        ],
        "clean": [
          "Scores run 0-100.",
          "The reserve holds 1-3 month Treasury bills.",
          "Keep the answer to 45-80 words."
        ]
      }
    }
  ]
} as const;
