// Generated by scripts/maintenance/generate-editorial-style.ts from the
// `editorial-policy` fence in docs/editorial-style.md. Do not edit by hand:
// edit the document and regenerate. Serialized data only, no logic.
import type { EditorialPolicy } from "./editorial-style";

export const EDITORIAL_STYLE_VERSION = "1.0";

/** Deterministic hash of the policy block. Bumps whenever enforcement changes. */
export const EDITORIAL_STYLE_HASH = "52b40f72c060dd1a";

export const EDITORIAL_POLICY: EditorialPolicy = {
  "version": "1.0",
  "oneLineDirective": "Write like an FT markets reporter with the tape in front of you: strongest verified fact first, distinguish observation from inference, explain the consequence plainly, no clause dashes, no corrective \"this is not X, it is Y\", no personified metrics, no nickname titles, no slogan closers. Wit only if deleting the names and figures kills the line; the default is none.",
  "registers": [
    {
      "id": "daily",
      "label": "Daily editorial",
      "group": "editorial",
      "promptLine": "Lead with the highest-impact verified fact in 150 to 280 words plus a compact hook. Zero sharp lines is the default and one is the cap. Name a material observable trigger when the evidence contains one; never force a threshold ending."
    },
    {
      "id": "weekly",
      "label": "Weekly synthesis",
      "group": "editorial",
      "promptLine": "Build the week's causal arc from daily evidence, separate persistent moves from reversals, and score prior expectations honestly. This is the strictest temperature, not the loosest."
    },
    {
      "id": "coin-summary",
      "label": "Coin summary",
      "group": "editorial",
      "promptLine": "120 to 180 words, one main claim per sentence. The title is a descriptor, never a nickname. Explain what the asset is, its central trade-off, and what Pharos data reveals that a listing page would miss. Close on the durable constraint; no punch required."
    },
    {
      "id": "cemetery",
      "label": "Cemetery",
      "group": "editorial",
      "promptLine": "Obituary: chronological, sober, complete. Epitaph: short, with one evidence-backed barb permitted because the outcome is settled. No mascot nicknames."
    },
    {
      "id": "long-form",
      "label": "Long-form",
      "group": "editorial",
      "promptLine": "Narrative and first person are allowed where they add provenance. Claims need dates, scope, and receipts."
    },
    {
      "id": "profile-reference",
      "label": "Profile reference",
      "group": "technical",
      "promptLine": "Compressed reference copy: specific, factual, no wit, no marketing. Terms of art are allowed."
    },
    {
      "id": "pre-launch",
      "label": "Pre-launch record",
      "group": "technical",
      "promptLine": "Dated factual record: what was announced, by whom, with what commitment. No predictions or launch copy."
    },
    {
      "id": "notice",
      "label": "Notice",
      "group": "technical",
      "promptLine": "Urgent register: the event, the effect on holders, the source. Direct, calm, complete. No wit."
    },
    {
      "id": "lifecycle",
      "label": "Lifecycle reason",
      "group": "technical",
      "promptLine": "Operational register: event, effective date, concise rationale. Administrative unless the underlying event is urgent."
    },
    {
      "id": "release-note",
      "label": "Release note",
      "group": "technical",
      "promptLine": "Material change and its consequence for readers or operators. Wit is unavailable. Name the moves the period actually had; a three-item headline shape is banned as a template."
    },
    {
      "id": "technical-release-note",
      "label": "Technical release note",
      "group": "technical",
      "promptLine": "Precise deltas and version references, no editorial framing."
    },
    {
      "id": "reference-teaching",
      "label": "Reference teaching",
      "group": "technical",
      "promptLine": "Definitions and mechanisms with defined terms and no performance. Teaching basics is this register's job."
    },
    {
      "id": "technical-evidence",
      "label": "Technical evidence",
      "group": "technical",
      "promptLine": "Accuracy, uncertainty, defined terms, and source fidelity outrank flourish. Completeness beats concision."
    },
    {
      "id": "page-description",
      "label": "Page description",
      "group": "product",
      "promptLine": "One or two plain sentences on what the page contains and why it is useful. No jokes, suspense, or slogans."
    },
    {
      "id": "analytical-explanation",
      "label": "Analytical explanation",
      "group": "product",
      "promptLine": "Claim-safety rules in full: no recommendations, no unqualified safety or convenience claims, qualified comparisons only."
    },
    {
      "id": "product-utility",
      "label": "Product utility",
      "group": "product",
      "promptLine": "Direct and calm. No wit where a reader needs an instruction or warning. Error copy states what happened and what to do."
    },
    {
      "id": "brand",
      "label": "Brand",
      "group": "product",
      "promptLine": "Universal rules without exemption. State the commitment and the evidence for it; aphoristic contrast is not a house voice."
    },
    {
      "id": "alert",
      "label": "Alert",
      "group": "product",
      "promptLine": "Fast, factual, scannable. Registered data-tied glyphs are functional, not decorative."
    },
    {
      "id": "delivery-wrapper",
      "label": "Delivery wrapper",
      "group": "product",
      "promptLine": "Utility register, not editorial. Wrapper strings pass the same scanner as the copy they frame."
    }
  ],
  "rules": [
    {
      "id": "no-clause-dash",
      "promptLabel": "Never use em, en, figure, or horizontal-bar dashes. Use a period, comma, colon, or semicolon.",
      "patterns": [
        {
          "source": "[\\u2012\\u2013\\u2014\\u2015]",
          "flags": "gu"
        }
      ],
      "severity": {
        "default": "hard"
      },
      "exceptions": [
        "quoted-source",
        "external-title",
        "code",
        "identifier"
      ],
      "replacementAdvice": "Split the clause or use a colon, comma, or semicolon.",
      "introducedIn": "1.0"
    },
    {
      "id": "no-minus-as-dash",
      "promptLabel": "Never use a mathematical minus as a clause dash. Signed numbers keep their minus.",
      "patterns": [
        {
          "source": "\\u2212(?![\\d.,])",
          "flags": "gu"
        }
      ],
      "severity": {
        "default": "hard"
      },
      "exceptions": [
        "quoted-source",
        "code",
        "identifier",
        "numeric-sign"
      ],
      "replacementAdvice": "A style rule never rewrites a number. If this is a clause break, use punctuation; if it is a signed value, keep it.",
      "introducedIn": "1.0"
    },
    {
      "id": "no-corrective-cleft",
      "promptLabel": "Never write the corrective cleft: \"X is not A, it is B\" and its variants.",
      "patterns": [
        {
          "source": "\\b(?:is|was|are|were)\\s+not\\s+[^.,;:!?]{1,60}[,;]\\s+(?:it|this|that|they)\\s+(?:is|was|are|were)\\b",
          "flags": "giu"
        },
        {
          "source": "\\b(?:is|was|are|were)n['\\u2019]t\\s+[^.,;:!?]{1,60}[,;]\\s+(?:it|this|that|they)\\s*(?:is|was|are|were|['\\u2019]s)\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "hard"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "State the fact and its consequence in separate defensible clauses.",
      "introducedIn": "1.0"
    },
    {
      "id": "no-corrective-cleft-split",
      "promptLabel": "Do not split a corrective cleft across two sentences (\"X is not A. It is B.\").",
      "patterns": [
        {
          "source": "\\b(?:is|was|are|were)\\s+not\\s+[^.,;:!?]{1,60}\\.\\s+(?:It|This|That|They)\\s+(?:is|was|are|were)\\b",
          "flags": "gu"
        },
        {
          "source": "\\b(?:is|was|are|were)n['\\u2019]t\\s+[^.,;:!?]{1,60}\\.\\s+(?:It|This|That|They)\\s*(?:is|was|are|were|['\\u2019]s)\\b",
          "flags": "gu"
        }
      ],
      "severity": {
        "default": "advisory"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Advisory because a sentence boundary often separates two unrelated facts; a reviewer decides whether this is a rhetorical flip.",
      "introducedIn": "1.0"
    },
    {
      "id": "no-suspense-opener",
      "promptLabel": "Never open with withheld-subject suspense (\"What it doesn't have is ...\").",
      "patterns": [
        {
          "source": "\\bWhat\\s+(?:it|this|that|they)\\s+(?:does|do|did)\\s*n['\\u2019]?t\\s+(?:have|do|show)\\s+is\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "hard"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Put the substantive fact first.",
      "introducedIn": "1.0"
    },
    {
      "id": "no-stale-phrase",
      "promptLabel": "Never use: testament to, time will tell, it remains to be seen, in a world where, at its core, delve, game-changing, cutting-edge, revolutionary, needless to say, it's worth noting.",
      "patterns": [
        {
          "source": "\\btestament to\\b",
          "flags": "giu"
        },
        {
          "source": "\\btime will tell\\b",
          "flags": "giu"
        },
        {
          "source": "\\bit remains to be seen\\b",
          "flags": "giu"
        },
        {
          "source": "\\bin a world where\\b",
          "flags": "giu"
        },
        {
          "source": "\\bat its core\\b",
          "flags": "giu"
        },
        {
          "source": "\\bdelv(?:e|es|ed|ing)\\b",
          "flags": "giu"
        },
        {
          "source": "\\bgame[- ]changing\\b",
          "flags": "giu"
        },
        {
          "source": "\\bcutting[- ]edge\\b",
          "flags": "giu"
        },
        {
          "source": "\\brevolutionary\\b",
          "flags": "giu"
        },
        {
          "source": "\\bneedless to say\\b",
          "flags": "giu"
        },
        {
          "source": "\\bit['\\u2019]s worth noting\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "hard"
      },
      "exceptions": [
        "quoted-source",
        "external-title"
      ],
      "replacementAdvice": "Delete the phrase and state the fact.",
      "introducedIn": "1.0"
    },
    {
      "id": "no-hedged-closer",
      "promptLabel": "Never close on: worth watching, worth monitoring, bears watching, for now, the question is whether. Name the next observable threshold instead.",
      "patterns": [
        {
          "source": "\\b(?:worth|bears?)\\s+(?:watching|monitoring)\\b",
          "flags": "giu"
        },
        {
          "source": "\\bfor now\\b",
          "flags": "giu"
        },
        {
          "source": "\\bthe (?:real )?question is whether\\b",
          "flags": "giu"
        }
      ],
      "closerOnly": true,
      "severity": {
        "default": "hard"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Say what to watch, when, and what it would mean.",
      "introducedIn": "1.0"
    },
    {
      "id": "no-dead-metaphor",
      "promptLabel": "Never use: beneath the calm, surface calm, restless depths, below the waterline, something moving underneath, belies.",
      "patterns": [
        {
          "source": "\\bbeneath the (?:calm|bedrock|surface)\\b",
          "flags": "giu"
        },
        {
          "source": "\\b(?:surface|calm) (?:calm|surfaces)\\b",
          "flags": "giu"
        },
        {
          "source": "\\brestless (?:depths|currents|plumbing)\\b",
          "flags": "giu"
        },
        {
          "source": "\\bbelow the waterline\\b",
          "flags": "giu"
        },
        {
          "source": "\\bsomething (?:is )?moving (?:underneath|beneath|below)\\b",
          "flags": "giu"
        },
        {
          "source": "\\bbelies\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "advisory",
        "byRegister": {
          "daily": "hard",
          "weekly": "hard",
          "coin-summary": "hard",
          "cemetery": "hard",
          "long-form": "hard"
        }
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Describe the mechanism instead of the weather.",
      "introducedIn": "1.0"
    },
    {
      "id": "no-unqualified-safety",
      "promptLabel": "Never make unqualified safety claims: safe, safest, risk-free, low-risk, guaranteed. Rankings name metric, scope, and date.",
      "patterns": [
        {
          "source": "(?<![A-Za-z-])safe(?![A-Za-z-])",
          "flags": "gu"
        },
        {
          "source": "(?<![A-Za-z-])safest(?![A-Za-z-])",
          "flags": "giu"
        },
        {
          "source": "\\brisk[- ]free\\b",
          "flags": "giu"
        },
        {
          "source": "\\bguarantee(?:d|s)?\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "advisory",
        "byRegister": {
          "page-description": "hard",
          "analytical-explanation": "hard",
          "product-utility": "hard",
          "brand": "hard",
          "alert": "hard",
          "delivery-wrapper": "hard"
        }
      },
      "exceptions": [
        "quoted-source",
        "external-title",
        "legal-term"
      ],
      "replacementAdvice": "Name the metric, scope, and date, or drop the claim.",
      "introducedIn": "1.0"
    },
    {
      "id": "no-investment-recommendation",
      "promptLabel": "Never recommend buying, holding, selling, or switching.",
      "patterns": [
        {
          "source": "\\bwe recommend\\b",
          "flags": "giu"
        },
        {
          "source": "\\byou should (?:buy|hold|sell|switch|move)\\b",
          "flags": "giu"
        },
        {
          "source": "\\bPharos recommends?\\b",
          "flags": "giu"
        },
        {
          "source": "\\btop pick\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "hard"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Describe the trade-off and let the reader decide.",
      "introducedIn": "1.0"
    },
    {
      "id": "no-booster-language",
      "promptLabel": "No booster language, empty intensifiers, exclamation marks, or clickbait questions.",
      "patterns": [
        {
          "source": "\\bbuckle up\\b",
          "flags": "giu"
        },
        {
          "source": "\\b(?:truly|incredibly|massively|hugely) (?:remarkable|impressive|significant)\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "advisory",
        "byRegister": {
          "daily": "hard",
          "weekly": "hard",
          "coin-summary": "hard"
        }
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Let the number carry the emphasis.",
      "introducedIn": "1.0"
    },
    {
      "id": "no-personified-metric",
      "promptLabel": "Named indexes, scores, gauges, and regimes do not nap, shrug, yawn, notice, refuse, or applaud. State what the number did.",
      "patterns": [
        {
          "source": "\\b(?:PSI|DEWS|the index|the score|the gauge|the market|the tape|the regime)\\s+(?:napp?ed|naps|shrugg?ed|shrugs|yawn(?:ed|s)?|notic(?:ed|es)|refus(?:ed|es)|applaud(?:ed|s)|sleeps|slept)\\b",
          "flags": "giu"
        },
        {
          "source": "\\bleft the building\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "advisory"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Name the movement and its size.",
      "introducedIn": "1.0"
    },
    {
      "id": "no-hedge-stack",
      "promptLabel": "Do not stack qualifiers. One warranted qualifier is honesty; three is mush.",
      "patterns": [
        {
          "source": "\\bcould potentially\\b",
          "flags": "giu"
        },
        {
          "source": "\\bmight arguably\\b",
          "flags": "giu"
        },
        {
          "source": "\\bmay possibly\\b",
          "flags": "giu"
        },
        {
          "source": "\\bsomewhat (?:arguably|possibly|potentially)\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "advisory"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Keep one qualifier or state the uncertainty directly.",
      "introducedIn": "1.0"
    },
    {
      "id": "no-recategorizing-flip",
      "promptLabel": "Avoid \"not merely X\" and \"isn't just X\" used to recategorize rather than to state a fact.",
      "patterns": [
        {
          "source": "\\bnot (?:merely|simply)\\b",
          "flags": "giu"
        },
        {
          "source": "\\b(?:is|are|was|were)n['\\u2019]t just\\b",
          "flags": "giu"
        },
        {
          "source": "\\b(?:is|are|was|were) not just\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "advisory"
      },
      "exceptions": [
        "quoted-source"
      ],
      "replacementAdvice": "Say what it is, with the evidence.",
      "introducedIn": "1.0"
    },
    {
      "id": "scoped-decorative-word",
      "promptLabel": "In editorial registers avoid decorative uses of: quietly, meanwhile, landscape, plumbing.",
      "patterns": [
        {
          "source": "\\bquietly\\b",
          "flags": "giu"
        },
        {
          "source": "\\bmeanwhile\\b",
          "flags": "giu"
        },
        {
          "source": "\\blandscape\\b",
          "flags": "giu"
        },
        {
          "source": "\\bplumbing\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "off",
        "byRegister": {
          "daily": "advisory",
          "weekly": "advisory",
          "coin-summary": "advisory",
          "cemetery": "advisory",
          "long-form": "advisory"
        }
      },
      "exceptions": [
        "quoted-source",
        "external-title"
      ],
      "replacementAdvice": "Describe the timing, visibility, or mechanism instead.",
      "introducedIn": "1.0"
    },
    {
      "id": "scoped-market-metaphor",
      "promptLabel": "Do not use obituary, post-mortem, carcass, or furniture as casual market metaphors.",
      "patterns": [
        {
          "source": "\\bobituar(?:y|ies)\\b",
          "flags": "giu"
        },
        {
          "source": "\\bpost[- ]?mortem\\b",
          "flags": "giu"
        },
        {
          "source": "\\bcarcass\\b",
          "flags": "giu"
        }
      ],
      "severity": {
        "default": "off",
        "byRegister": {
          "daily": "advisory",
          "weekly": "advisory",
          "coin-summary": "advisory"
        }
      },
      "exceptions": [
        "quoted-source",
        "external-title",
        "literal-cemetery"
      ],
      "replacementAdvice": "Use the literal event or outcome.",
      "introducedIn": "1.0"
    },
    {
      "id": "spaced-hyphen-clause-dash",
      "promptLabel": "Do not use a spaced hyphen as a clause dash.",
      "patterns": [
        {
          "source": "(?<=\\S) - (?=\\S)",
          "flags": "gu"
        }
      ],
      "severity": {
        "default": "advisory"
      },
      "exceptions": [
        "quoted-source",
        "code",
        "identifier",
        "numeric-sign",
        "table"
      ],
      "replacementAdvice": "Use a colon, comma, semicolon, or period.",
      "introducedIn": "1.0"
    }
  ]
} as const;
