export const CIRCUIT_OPEN_THRESHOLD = 3;
export const CIRCUIT_PROBE_INTERVAL_SEC = 1800; // 30 min

export const API_KEY_DEFAULT_RATE_LIMIT_PER_MINUTE = 120;
export const API_KEY_MIN_RATE_LIMIT_PER_MINUTE = 1;
export const API_KEY_MAX_RATE_LIMIT_PER_MINUTE = 10_000;
export const API_KEY_DEFAULT_EXPIRY_SEC = 90 * 24 * 60 * 60;
export const API_KEY_DEPENDENCY_RETRY_AFTER_SEC = 60;

export const FEEDBACK_RATE_LIMIT_WINDOW_SEC = 600;
export const FEEDBACK_RATE_LIMIT_MAX_SUBMISSIONS = 3;

export const SELF_SERVE_API_KEY_RATE_LIMIT_PER_MINUTE = 30;
export const SELF_SERVE_API_KEY_EXPIRY_SEC = 60 * 24 * 60 * 60;
export const SELF_SERVE_MAX_ACTIVE_KEYS_PER_EMAIL = 1;
export const SELF_SERVE_MAX_CREATIONS_PER_IP_24H = 1;
export const SELF_SERVE_SUBMISSION_RATE_LIMIT_PER_IP_PER_HOUR = 5;
export const SELF_SERVE_SUBMISSION_RATE_LIMIT_PER_EMAIL_PER_DAY = 3;
export const SELF_SERVE_VERIFICATION_TOKEN_TTL_SEC = 30 * 60;
export const SELF_SERVE_VERIFICATION_ATTEMPT_LIMIT_PER_IP_10M = 20;
export const SELF_SERVE_VERIFICATION_ATTEMPT_LIMIT_PER_TOKEN_10M = 5;
export const SELF_SERVE_DEPENDENCY_RETRY_AFTER_SEC = 60;
export const SELF_SERVE_USE_CASE_MIN_LENGTH = 10;
export const SELF_SERVE_USE_CASE_MAX_LENGTH = 1200;
