export const CIRCUIT_OPEN_THRESHOLD = 3;
export const CIRCUIT_PROBE_INTERVAL_SEC = 1800; // 30 min

export const PUBLIC_API_RATE_LIMIT_MAX_REQUESTS = 300;
export const PUBLIC_API_RATE_LIMIT_WINDOW_SEC = 60;

export const FEEDBACK_RATE_LIMIT_WINDOW_SEC = 600;
export const FEEDBACK_RATE_LIMIT_MAX_SUBMISSIONS = 3;
