export type PricingSourceTrustTier =
  | "hard_oracle"
  | "hard_market"
  | "hard_protocol"
  | "soft_aggregator"
  | "soft_dex"
  | "fallback_search"
  | "cached_replay";

export interface PricingSourceRegistryEntry {
  key: string;
  label: string;
  shortLabel: string;
  trustTier: PricingSourceTrustTier;
  defaultWeight: number;
  isSoftSource: boolean;
  isReplaySafe: boolean;
  isPoolChallengeExempt: boolean;
  isGtProbeEligible: boolean;
  canBeDepegAuthoritative: boolean;
  requiresObservedAt: boolean;
  isSearchDerived: boolean;
}

const REGISTRY = [
  {
    key: "coingecko",
    label: "CoinGecko",
    shortLabel: "CG",
    trustTier: "soft_aggregator",
    defaultWeight: 2,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: true,
    canBeDepegAuthoritative: false,
    requiresObservedAt: false,
    isSearchDerived: false,
  },
  {
    key: "defillama",
    label: "DefiLlama",
    shortLabel: "DL",
    trustTier: "soft_aggregator",
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    requiresObservedAt: false,
    isSearchDerived: false,
  },
  {
    key: "defillama-list",
    label: "DefiLlama (list)",
    shortLabel: "DL-list",
    trustTier: "soft_aggregator",
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: true,
    canBeDepegAuthoritative: false,
    requiresObservedAt: false,
    isSearchDerived: false,
  },
  {
    key: "geckoterminal",
    label: "GeckoTerminal",
    shortLabel: "GT",
    trustTier: "soft_dex",
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    requiresObservedAt: false,
    isSearchDerived: false,
  },
  {
    key: "pyth",
    label: "Pyth Network",
    shortLabel: "Pyth",
    trustTier: "hard_oracle",
    defaultWeight: 2,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    requiresObservedAt: true,
    isSearchDerived: false,
  },
  {
    key: "binance",
    label: "Binance",
    shortLabel: "Binance",
    trustTier: "hard_market",
    defaultWeight: 2,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    requiresObservedAt: false,
    isSearchDerived: false,
  },
  {
    key: "kraken",
    label: "Kraken",
    shortLabel: "Kraken",
    trustTier: "hard_market",
    defaultWeight: 2,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    requiresObservedAt: false,
    isSearchDerived: false,
  },
  {
    key: "bitstamp",
    label: "Bitstamp",
    shortLabel: "Bitstamp",
    trustTier: "hard_market",
    defaultWeight: 1,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    requiresObservedAt: false,
    isSearchDerived: false,
  },
  {
    key: "coinbase",
    label: "Coinbase",
    shortLabel: "Coinbase",
    trustTier: "hard_market",
    defaultWeight: 2,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    requiresObservedAt: false,
    isSearchDerived: false,
  },
  {
    key: "redstone",
    label: "RedStone",
    shortLabel: "RedStone",
    trustTier: "hard_oracle",
    defaultWeight: 1,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    requiresObservedAt: true,
    isSearchDerived: false,
  },
  {
    key: "curve-onchain",
    label: "Curve on-chain",
    shortLabel: "Curve",
    trustTier: "hard_protocol",
    defaultWeight: 3,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    requiresObservedAt: false,
    isSearchDerived: false,
  },
  {
    key: "curve-oracle",
    label: "Curve oracle",
    shortLabel: "Curve oracle",
    trustTier: "hard_protocol",
    defaultWeight: 3,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    requiresObservedAt: false,
    isSearchDerived: false,
  },
  {
    key: "dex-promoted",
    label: "DEX prices",
    shortLabel: "DEX",
    trustTier: "soft_dex",
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    requiresObservedAt: true,
    isSearchDerived: false,
  },
  {
    key: "fluid-dex",
    label: "Fluid",
    shortLabel: "Fluid",
    trustTier: "soft_dex",
    defaultWeight: 3,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    requiresObservedAt: true,
    isSearchDerived: false,
  },
  {
    key: "balancer-dex",
    label: "Balancer",
    shortLabel: "Balancer",
    trustTier: "soft_dex",
    defaultWeight: 3,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    requiresObservedAt: true,
    isSearchDerived: false,
  },
  {
    key: "raydium-dex",
    label: "Raydium",
    shortLabel: "Raydium",
    trustTier: "soft_dex",
    defaultWeight: 2,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    requiresObservedAt: true,
    isSearchDerived: false,
  },
  {
    key: "orca-dex",
    label: "Orca",
    shortLabel: "Orca",
    trustTier: "soft_dex",
    defaultWeight: 2,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    requiresObservedAt: true,
    isSearchDerived: false,
  },
  {
    key: "jupiter",
    label: "Jupiter",
    shortLabel: "Jupiter",
    trustTier: "fallback_search",
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    requiresObservedAt: false,
    isSearchDerived: true,
  },
  {
    key: "coinmarketcap",
    label: "CoinMarketCap",
    shortLabel: "CMC",
    trustTier: "fallback_search",
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    requiresObservedAt: false,
    isSearchDerived: true,
  },
  {
    key: "dexscreener",
    label: "DexScreener",
    shortLabel: "DexScreener",
    trustTier: "fallback_search",
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    requiresObservedAt: false,
    isSearchDerived: true,
  },
  {
    key: "defillama-contract",
    label: "DefiLlama (contract)",
    shortLabel: "Contract",
    trustTier: "soft_aggregator",
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    requiresObservedAt: false,
    isSearchDerived: false,
  },
  {
    key: "protocol-redeem",
    label: "Protocol Redemption",
    shortLabel: "Protocol",
    trustTier: "hard_protocol",
    defaultWeight: 3,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    requiresObservedAt: false,
    isSearchDerived: false,
  },
  {
    key: "pool-tvl-weighted",
    label: "Pool TVL-weighted",
    shortLabel: "Pool",
    trustTier: "soft_dex",
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    requiresObservedAt: true,
    isSearchDerived: false,
  },
  {
    key: "cached",
    label: "Cached fallback",
    shortLabel: "Cached",
    trustTier: "cached_replay",
    defaultWeight: 0,
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    requiresObservedAt: true,
    isSearchDerived: false,
  },
] as const satisfies readonly PricingSourceRegistryEntry[];

export const PRICING_SOURCE_REGISTRY = REGISTRY;
export const PRICING_SOURCE_KEYS = REGISTRY.map((entry) => entry.key);
export type PricingSourceKey = (typeof REGISTRY)[number]["key"];

const REGISTRY_MAP = new Map<string, PricingSourceRegistryEntry>(
  REGISTRY.map((entry) => [entry.key, entry]),
);

export function getPricingSourceRegistryEntry(sourceKey: string): PricingSourceRegistryEntry | undefined {
  return REGISTRY_MAP.get(sourceKey);
}

export function isKnownPricingSourceKey(sourceKey: string): sourceKey is PricingSourceKey {
  return REGISTRY_MAP.has(sourceKey);
}
