import type { PricingSourceRegistryEntry } from "./pricing-source-registry-types";

export const PRICING_SOURCE_REGISTRY_MARKET_FEEDS = [
  {
    key: "cg-ticker",
    label: "CoinGecko ticker",
    shortLabel: "CG-ticker",
    trustTier: "hard_market",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 2,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: false,
    },
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "geckoterminal",
    label: "GeckoTerminal",
    shortLabel: "GT",
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "pyth",
    label: "Pyth Network",
    shortLabel: "Pyth",
    trustTier: "hard_oracle",
    freshnessKind: "upstream",
    maxTrustedAgeSec: 5 * 60,
    defaultWeight: 2,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: true,
    supportsUpstreamObservedAt: true,
    requiresObservedAt: true,
    isSearchDerived: false,
    capabilities: {
      hasUpstreamTimestamp: true,
    },
    defaultObservedAtMode: "upstream",
  },
  {
    key: "binance",
    label: "Binance",
    shortLabel: "Binance",
    trustTier: "hard_market",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 2,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    capabilities: {
      hasBidAsk: false,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: true,
    },
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "kraken",
    label: "Kraken",
    shortLabel: "Kraken",
    trustTier: "hard_market",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 2,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: false,
    },
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "bitstamp",
    label: "Bitstamp",
    shortLabel: "Bitstamp",
    trustTier: "hard_market",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 1,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: false,
    },
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "coinbase",
    label: "Coinbase",
    shortLabel: "Coinbase",
    trustTier: "hard_market",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 2,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: false,
    },
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "redstone",
    label: "RedStone",
    shortLabel: "RedStone",
    trustTier: "hard_oracle",
    freshnessKind: "upstream",
    maxTrustedAgeSec: 5 * 60,
    defaultWeight: 1,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: true,
    supportsUpstreamObservedAt: true,
    requiresObservedAt: true,
    isSearchDerived: false,
    capabilities: {
      hasUpstreamTimestamp: true,
    },
    defaultObservedAtMode: "upstream",
  },
  {
    key: "curve-onchain",
    label: "Curve on-chain",
    shortLabel: "Curve",
    trustTier: "hard_protocol",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 3,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "curve-oracle",
    label: "Curve oracle",
    shortLabel: "Curve oracle",
    trustTier: "hard_protocol",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 3,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
] as const satisfies readonly PricingSourceRegistryEntry[];
