import type { PricingSourceRegistryEntry } from "./pricing-source-registry-types";

export const PRICING_SOURCE_REGISTRY_DEX_SEARCH = [
  {
    key: "dex-promoted",
    label: "DEX prices",
    shortLabel: "DEX",
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "fluid-dex",
    label: "Fluid",
    shortLabel: "Fluid",
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 3,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "balancer-dex",
    label: "Balancer",
    shortLabel: "Balancer",
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 3,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "raydium-dex",
    label: "Raydium",
    shortLabel: "Raydium",
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 2,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "orca-dex",
    label: "Orca",
    shortLabel: "Orca",
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 2,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "jupiter",
    label: "Jupiter",
    shortLabel: "Jupiter",
    trustTier: "fallback_search",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: true,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "coinmarketcap",
    label: "CoinMarketCap",
    shortLabel: "CMC",
    trustTier: "fallback_search",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 60 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: true,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "dexscreener",
    label: "DexScreener",
    shortLabel: "DexScreener",
    trustTier: "fallback_search",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: true,
    defaultObservedAtMode: "local_fetch",
  },
] as const satisfies readonly PricingSourceRegistryEntry[];
