import type { PricingSourceRegistryEntry } from "./pricing-source-registry-types";
import { definePricingSource, PRICING_SOURCE_PRESETS } from "./pricing-source-registry-presets";

export const PRICING_SOURCE_REGISTRY_DEX_SEARCH = [
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "dex-promoted",
    label: "DEX prices",
    shortLabel: "DEX",
    depegSourceFamily: "dex:aggregate",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 1,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "fluid-dex",
    label: "Fluid",
    shortLabel: "Fluid",
    depegSourceFamily: "dex:fluid",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 3,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "balancer-dex",
    label: "Balancer",
    shortLabel: "Balancer",
    depegSourceFamily: "dex:balancer",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 3,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "curve-dex",
    label: "Curve",
    shortLabel: "Curve",
    depegSourceFamily: "dex:curve",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 3,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "curve-thin-onchain",
    label: "Curve exact-pool quote",
    shortLabel: "Curve exact",
    depegSourceFamily: "dex:curve",
    maxTrustedAgeSec: 5 * 60,
    defaultWeight: 1,
    isReplaySafe: false,
    bypassesSoftValidationGuardrails: true,
    freshnessKind: "upstream",
    supportsUpstreamObservedAt: true,
    defaultObservedAtMode: "upstream",
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "uniswap-v3-dex",
    label: "Uniswap V3",
    shortLabel: "Uniswap V3",
    depegSourceFamily: "dex:uniswap-v3",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 2,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "uniswap-v3-exact",
    label: "Uniswap V3 exact-pool quote",
    shortLabel: "Uniswap V3 exact",
    depegSourceFamily: "dex:uniswap-v3",
    maxTrustedAgeSec: 5 * 60,
    defaultWeight: 1,
    isReplaySafe: false,
    freshnessKind: "upstream",
    supportsUpstreamObservedAt: true,
    defaultObservedAtMode: "upstream",
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "uniswap-v4-dex",
    label: "Uniswap V4",
    shortLabel: "Uniswap V4",
    depegSourceFamily: "dex:uniswap-v4",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 2,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "raydium-dex",
    label: "Raydium",
    shortLabel: "Raydium",
    depegSourceFamily: "dex:raydium",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 2,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "orca-dex",
    label: "Orca",
    shortLabel: "Orca",
    depegSourceFamily: "dex:orca",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 2,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "meteora-dex",
    label: "Meteora",
    shortLabel: "Meteora",
    depegSourceFamily: "dex:meteora",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 2,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "pancakeswap-dex",
    label: "PancakeSwap",
    shortLabel: "PancakeSwap",
    depegSourceFamily: "dex:pancakeswap",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 2,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "aerodrome-dex",
    label: "Aerodrome Slipstream",
    shortLabel: "Aerodrome",
    depegSourceFamily: "dex:aerodrome-slipstream",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 2,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "velodrome-dex",
    label: "Velodrome Slipstream",
    shortLabel: "Velodrome",
    depegSourceFamily: "dex:velodrome-slipstream",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 2,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.fallbackSearch, {
    key: "jupiter",
    label: "Jupiter",
    shortLabel: "Jupiter",
    depegSourceFamily: "fallback:jupiter",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.fallbackSearch, {
    key: "coinmarketcap",
    label: "CoinMarketCap",
    shortLabel: "CMC",
    depegSourceFamily: "coinmarketcap",
    maxTrustedAgeSec: 60 * 60,
    defaultWeight: 1,
    isListAggregator: true,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.fallbackSearch, {
    key: "dexscreener-exact",
    label: "DexScreener (exact)",
    shortLabel: "DS-exact",
    depegSourceFamily: "fallback:dexscreener",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSearchDerived: false,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.fallbackSearch, {
    key: "dexscreener-address",
    label: "DexScreener (address)",
    shortLabel: "DS-address",
    depegSourceFamily: "fallback:dexscreener-address",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSearchDerived: false,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.fallbackSearch, {
    key: "dexpaprika-address",
    label: "DexPaprika",
    shortLabel: "DexPaprika",
    depegSourceFamily: "fallback:dexpaprika-address",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSearchDerived: false,
    supportsUpstreamObservedAt: true,
    defaultObservedAtMode: "upstream",
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.fallbackSearch, {
    key: "alchemy-address",
    label: "Alchemy Prices",
    shortLabel: "Alchemy",
    depegSourceFamily: "fallback:alchemy-address",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSearchDerived: false,
    supportsUpstreamObservedAt: true,
    defaultObservedAtMode: "upstream",
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.fallbackSearch, {
    key: "moralis-address",
    label: "Moralis Prices",
    shortLabel: "Moralis",
    depegSourceFamily: "fallback:moralis-address",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSearchDerived: false,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.fallbackSearch, {
    key: "birdeye-address",
    label: "Birdeye",
    shortLabel: "Birdeye",
    depegSourceFamily: "fallback:birdeye-address",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSearchDerived: false,
    supportsUpstreamObservedAt: true,
    defaultObservedAtMode: "upstream",
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.fallbackSearch, {
    key: "coingecko-onchain-address",
    label: "CoinGecko Onchain (address)",
    shortLabel: "CG-onchain",
    depegSourceFamily: "fallback:coingecko-onchain-address",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSearchDerived: false,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.fallbackSearch, {
    key: "dexscreener-search",
    label: "DexScreener (search)",
    shortLabel: "DS-search",
    depegSourceFamily: "fallback:dexscreener-search",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
  }),
] as const satisfies readonly PricingSourceRegistryEntry[];
