import type { PricingSourceRegistryEntry } from "./pricing-source-registry-types";

export const PRICING_SOURCE_REGISTRY_SPECIAL = [
  {
    key: "defillama-contract",
    label: "DefiLlama (contract)",
    shortLabel: "Contract",
    trustTier: "soft_aggregator",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "protocol-redeem",
    label: "Protocol Redemption",
    shortLabel: "Protocol",
    trustTier: "hard_protocol",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 3,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    isProtocolOverride: true,
    bypassesSoftValidationGuardrails: true,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "pool-tvl-weighted",
    label: "Pool TVL-weighted",
    shortLabel: "Pool",
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    bypassesSoftValidationGuardrails: true,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "cached",
    label: "Cached fallback",
    shortLabel: "Cached",
    trustTier: "cached_replay",
    freshnessKind: "unknown",
    maxTrustedAgeSec: null,
    defaultWeight: 0,
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: null,
  },
] as const satisfies readonly PricingSourceRegistryEntry[];
