import type { PricingSourceRegistryEntry } from "./pricing-source-registry-types";
import { definePricingSource, PRICING_SOURCE_PRESETS } from "./pricing-source-registry-presets";

export const PRICING_SOURCE_REGISTRY_MARKET_FEEDS = [
  definePricingSource(PRICING_SOURCE_PRESETS.hardMarket, {
    key: "cg-ticker",
    label: "CoinGecko ticker",
    shortLabel: "CG-ticker",
    depegSourceFamily: "coingecko",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 2,
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: false,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.softDex, {
    key: "geckoterminal",
    label: "GeckoTerminal",
    shortLabel: "GT",
    depegSourceFamily: "dex:geckoterminal",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    requiresObservedAt: false,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardOracle, {
    key: "pyth",
    label: "Pyth Network",
    shortLabel: "Pyth",
    depegSourceFamily: "oracle:pyth",
    maxTrustedAgeSec: 5 * 60,
    defaultWeight: 2,
    capabilities: {
      hasUpstreamTimestamp: true,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardMarket, {
    key: "binance",
    label: "Binance",
    shortLabel: "Binance",
    depegSourceFamily: "market:binance",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 2,
    capabilities: {
      hasBidAsk: false,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: true,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardMarket, {
    key: "kraken",
    label: "Kraken",
    shortLabel: "Kraken",
    depegSourceFamily: "market:kraken",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 2,
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: false,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardMarket, {
    key: "bitstamp",
    label: "Bitstamp",
    shortLabel: "Bitstamp",
    depegSourceFamily: "market:bitstamp",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 1,
    freshnessKind: "upstream",
    supportsUpstreamObservedAt: true,
    defaultObservedAtMode: "upstream",
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: true,
      isLastTradeOnly: false,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardMarket, {
    key: "coinbase",
    label: "Coinbase",
    shortLabel: "Coinbase",
    depegSourceFamily: "market:coinbase",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 2,
    freshnessKind: "upstream",
    supportsUpstreamObservedAt: true,
    defaultObservedAtMode: "upstream",
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: true,
      isLastTradeOnly: false,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardOracle, {
    key: "redstone",
    label: "RedStone",
    shortLabel: "RedStone",
    depegSourceFamily: "oracle:redstone",
    maxTrustedAgeSec: 5 * 60,
    defaultWeight: 1,
    capabilities: {
      hasUpstreamTimestamp: true,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardOracle, {
    key: "kava-pricefeed",
    label: "Kava Pricefeed",
    shortLabel: "Kava",
    depegSourceFamily: "oracle:kava-pricefeed",
    maxTrustedAgeSec: 30 * 60,
    defaultWeight: 3,
    isProtocolOverride: true,
    capabilities: {
      hasUpstreamTimestamp: true,
    },
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardMarket, {
    key: "aerodrome-onchain",
    label: "Aerodrome on-chain",
    shortLabel: "Aerodrome",
    depegSourceFamily: "dex:aerodrome-onchain",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 2,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardMarket, {
    key: "velodrome-onchain",
    label: "Velodrome on-chain",
    shortLabel: "Velodrome",
    depegSourceFamily: "dex:velodrome-onchain",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 2,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardProtocol, {
    key: "curve-onchain",
    label: "Curve on-chain",
    shortLabel: "Curve",
    depegSourceFamily: "protocol:curve",
    maxTrustedAgeSec: 300,
    defaultWeight: 3,
    freshnessKind: "upstream",
    supportsUpstreamObservedAt: true,
    defaultObservedAtMode: "upstream",
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardProtocol, {
    key: "curve-oracle",
    label: "Curve oracle",
    shortLabel: "Curve oracle",
    depegSourceFamily: "protocol:curve",
    maxTrustedAgeSec: 300,
    defaultWeight: 3,
    freshnessKind: "upstream",
    supportsUpstreamObservedAt: true,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardProtocol, {
    key: "chainlink-nav",
    label: "Chainlink NAV",
    shortLabel: "Chainlink NAV",
    depegSourceFamily: "protocol:chainlink-nav",
    maxTrustedAgeSec: 4 * 24 * 60 * 60,
    defaultWeight: 3,
    freshnessKind: "upstream",
    supportsUpstreamObservedAt: true,
    requiresObservedAt: true,
  }),
  definePricingSource(PRICING_SOURCE_PRESETS.hardProtocol, {
    key: "superstate-liquidity",
    label: "Superstate NAV",
    shortLabel: "Superstate",
    depegSourceFamily: "protocol:superstate-nav",
    maxTrustedAgeSec: 4 * 24 * 60 * 60,
    defaultWeight: 3,
    freshnessKind: "upstream",
    supportsUpstreamObservedAt: true,
    requiresObservedAt: true,
  }),
] as const satisfies readonly PricingSourceRegistryEntry[];
