import type { PricingSourceRegistryEntry } from "./pricing-source-registry-types";

export const PRICING_SOURCE_REGISTRY_AGGREGATORS = [
  {
    key: "coingecko",
    label: "CoinGecko",
    shortLabel: "CG",
    trustTier: "soft_aggregator",
    freshnessKind: "upstream",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 2,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: true,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: true,
    requiresObservedAt: false,
    isSearchDerived: false,
    capabilities: {
      hasUpstreamTimestamp: true,
    },
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "coingecko-native-implied",
    label: "CoinGecko native+FX",
    shortLabel: "CG native",
    trustTier: "soft_aggregator",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "defillama",
    label: "DefiLlama",
    shortLabel: "DL",
    trustTier: "soft_aggregator",
    freshnessKind: "unknown",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: null,
  },
  {
    key: "defillama-list",
    label: "DefiLlama (list)",
    shortLabel: "DL-list",
    trustTier: "soft_aggregator",
    freshnessKind: "unknown",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: true,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: null,
  },
  {
    key: "coingecko-mirror",
    label: "CoinGecko mirror",
    shortLabel: "CG-mirror",
    trustTier: "soft_aggregator",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
] as const satisfies readonly PricingSourceRegistryEntry[];
