import type { PriceObservedAtMode } from "../types/core";

export type PricingSourceTrustTier =
  | "hard_oracle"
  | "hard_market"
  | "hard_protocol"
  | "soft_aggregator"
  | "soft_dex"
  | "fallback_search"
  | "cached_replay";

export type PricingSourceFreshnessKind = "upstream" | "local_fetch" | "unknown";

export interface PricingSourceCapabilities {
  hasBidAsk?: boolean;
  hasTradeAge?: boolean;
  hasUpstreamTimestamp?: boolean;
  isLastTradeOnly?: boolean;
}

export interface PricingSourceRegistryEntry {
  key: string;
  label: string;
  shortLabel: string;
  trustTier: PricingSourceTrustTier;
  freshnessKind: PricingSourceFreshnessKind;
  maxTrustedAgeSec: number | null;
  defaultWeight: number;
  isSoftSource: boolean;
  isReplaySafe: boolean;
  isPoolChallengeExempt: boolean;
  isGtProbeEligible: boolean;
  canBeDepegAuthoritative: boolean;
  canSingleSourceDepegAuthoritative: boolean;
  supportsUpstreamObservedAt: boolean;
  requiresObservedAt: boolean;
  isSearchDerived: boolean;
  isProtocolOverride?: boolean;
  bypassesSoftValidationGuardrails?: boolean;
  capabilities?: PricingSourceCapabilities;
  defaultObservedAtMode: PriceObservedAtMode | null;
}

const REGISTRY = [
  {
    key: "coingecko",
    label: "CoinGecko",
    shortLabel: "CG",
    trustTier: "soft_aggregator",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 2,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: true,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "coingecko-native-implied",
    label: "CoinGecko native+FX",
    shortLabel: "CG native",
    trustTier: "soft_aggregator",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "defillama",
    label: "DefiLlama",
    shortLabel: "DL",
    trustTier: "soft_aggregator",
    freshnessKind: "unknown",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: null,
  },
  {
    key: "defillama-list",
    label: "DefiLlama (list)",
    shortLabel: "DL-list",
    trustTier: "soft_aggregator",
    freshnessKind: "unknown",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: true,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: null,
  },
  {
    key: "coingecko-mirror",
    label: "CoinGecko mirror",
    shortLabel: "CG-mirror",
    trustTier: "soft_aggregator",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "cg-ticker",
    label: "CoinGecko ticker",
    shortLabel: "CG-ticker",
    trustTier: "hard_market",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 2,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: false,
    },
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "geckoterminal",
    label: "GeckoTerminal",
    shortLabel: "GT",
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "pyth",
    label: "Pyth Network",
    shortLabel: "Pyth",
    trustTier: "hard_oracle",
    freshnessKind: "upstream",
    maxTrustedAgeSec: 5 * 60,
    defaultWeight: 2,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: true,
    supportsUpstreamObservedAt: true,
    requiresObservedAt: true,
    isSearchDerived: false,
    capabilities: {
      hasUpstreamTimestamp: true,
    },
    defaultObservedAtMode: "upstream",
  },
  {
    key: "binance",
    label: "Binance",
    shortLabel: "Binance",
    trustTier: "hard_market",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 2,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    capabilities: {
      hasBidAsk: false,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: true,
    },
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "kraken",
    label: "Kraken",
    shortLabel: "Kraken",
    trustTier: "hard_market",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 2,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: false,
    },
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "bitstamp",
    label: "Bitstamp",
    shortLabel: "Bitstamp",
    trustTier: "hard_market",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 1,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: false,
    },
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "coinbase",
    label: "Coinbase",
    shortLabel: "Coinbase",
    trustTier: "hard_market",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 10 * 60,
    defaultWeight: 2,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    capabilities: {
      hasBidAsk: true,
      hasTradeAge: false,
      hasUpstreamTimestamp: false,
      isLastTradeOnly: false,
    },
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "redstone",
    label: "RedStone",
    shortLabel: "RedStone",
    trustTier: "hard_oracle",
    freshnessKind: "upstream",
    maxTrustedAgeSec: 5 * 60,
    defaultWeight: 1,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: true,
    supportsUpstreamObservedAt: true,
    requiresObservedAt: true,
    isSearchDerived: false,
    capabilities: {
      hasUpstreamTimestamp: true,
    },
    defaultObservedAtMode: "upstream",
  },
  {
    key: "curve-onchain",
    label: "Curve on-chain",
    shortLabel: "Curve",
    trustTier: "hard_protocol",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 3,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "curve-oracle",
    label: "Curve oracle",
    shortLabel: "Curve oracle",
    trustTier: "hard_protocol",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 3,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "dex-promoted",
    label: "DEX prices",
    shortLabel: "DEX",
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "fluid-dex",
    label: "Fluid",
    shortLabel: "Fluid",
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 3,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "balancer-dex",
    label: "Balancer",
    shortLabel: "Balancer",
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 3,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "raydium-dex",
    label: "Raydium",
    shortLabel: "Raydium",
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 2,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "orca-dex",
    label: "Orca",
    shortLabel: "Orca",
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 2,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "jupiter",
    label: "Jupiter",
    shortLabel: "Jupiter",
    trustTier: "fallback_search",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: true,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "coinmarketcap",
    label: "CoinMarketCap",
    shortLabel: "CMC",
    trustTier: "fallback_search",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 60 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: true,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "dexscreener",
    label: "DexScreener",
    shortLabel: "DexScreener",
    trustTier: "fallback_search",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: true,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "defillama-contract",
    label: "DefiLlama (contract)",
    shortLabel: "Contract",
    trustTier: "soft_aggregator",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "protocol-redeem",
    label: "Protocol Redemption",
    shortLabel: "Protocol",
    trustTier: "hard_protocol",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 15 * 60,
    defaultWeight: 3,
    isSoftSource: false,
    isReplaySafe: true,
    isPoolChallengeExempt: true,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: true,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: false,
    isSearchDerived: false,
    isProtocolOverride: true,
    bypassesSoftValidationGuardrails: true,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "pool-tvl-weighted",
    label: "Pool TVL-weighted",
    shortLabel: "Pool",
    trustTier: "soft_dex",
    freshnessKind: "local_fetch",
    maxTrustedAgeSec: 35 * 60,
    defaultWeight: 1,
    isSoftSource: true,
    isReplaySafe: true,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    bypassesSoftValidationGuardrails: true,
    defaultObservedAtMode: "local_fetch",
  },
  {
    key: "cached",
    label: "Cached fallback",
    shortLabel: "Cached",
    trustTier: "cached_replay",
    freshnessKind: "unknown",
    maxTrustedAgeSec: null,
    defaultWeight: 0,
    isSoftSource: true,
    isReplaySafe: false,
    isPoolChallengeExempt: false,
    isGtProbeEligible: false,
    canBeDepegAuthoritative: false,
    canSingleSourceDepegAuthoritative: false,
    supportsUpstreamObservedAt: false,
    requiresObservedAt: true,
    isSearchDerived: false,
    defaultObservedAtMode: null,
  },
] as const satisfies readonly PricingSourceRegistryEntry[];

export const PRICING_SOURCE_REGISTRY = REGISTRY;
export type PricingSourceKey = (typeof REGISTRY)[number]["key"];

const REGISTRY_MAP = new Map<string, PricingSourceRegistryEntry>(
  REGISTRY.map((entry): [string, PricingSourceRegistryEntry] => [entry.key, entry]),
);

export function getPricingSourceRegistryEntry(sourceKey: string): PricingSourceRegistryEntry | undefined {
  return REGISTRY_MAP.get(sourceKey);
}

export function isPricingSourceProtocolOverride(sourceKey: string | null | undefined): boolean {
  if (!sourceKey) return false;
  return getPricingSourceRegistryEntry(sourceKey)?.isProtocolOverride ?? false;
}

export function isPricingSourceSoftGuardrailExempt(sourceKey: string | null | undefined): boolean {
  if (!sourceKey) return false;
  return getPricingSourceRegistryEntry(sourceKey)?.bypassesSoftValidationGuardrails ?? false;
}
