export const REDEMPTION_BACKSTOP_VERSION = "1.0";
export const REDEMPTION_BACKSTOP_VERSION_LABEL = `v${REDEMPTION_BACKSTOP_VERSION}`;
export const REDEMPTION_BACKSTOP_METHODOLOGY_PATH = "/methodology/#safety-scores";
