import { describe, expect, it } from "vitest";
import { buildPendingAlertEnqueueStatement } from "../../lib/telegram-pending-queue";
import { buildPendingAlertUpsertSql, pendingPrioritySql } from "../telegram-pending/upsert-sql";
import { buildSetBasedPendingHandoffStatements } from "../telegram-alert-target-plans/delivery";
import type { BatchMessage } from "../../lib/telegram";
import { makeNoopD1 } from "../../test-helpers/noop-d1";

/**
 * Byte-level pin for the `telegram_pending_alerts` upsert.
 *
 * Two producers write this row: the bind-parameterized `VALUES` form
 * (`lib/telegram-pending-queue.ts`) and the set-based `SELECT ... FROM
 * telegram_alert_job_targets` form (`telegram-alert-target-plans/delivery.ts`).
 * Both are generated by `buildPendingAlertUpsertSql`, so the conflict clause,
 * the TTL refresh predicate and the claim guard must be identical text; only
 * the value source differs. The pinned strings below were captured from the
 * pre-consolidation authoritative-handoff statement.
 */

interface CapturedStatement {
  sql: string;
  binds: unknown[];
}

function capturingDb(captured: CapturedStatement[]): D1Database {
  return makeNoopD1({
    prepare(sql: string) {
      const record: CapturedStatement = { sql, binds: [] };
      captured.push(record);
      const statement = {
        bind(...binds: unknown[]) {
          record.binds = binds;
          return statement;
        },
      };
      return statement as unknown as D1PreparedStatement;
    },
  });
}

function normalize(sql: string): string {
  return sql.replace(/\s+/g, " ").trim();
}

const CONFLICT_MARKER = "ON CONFLICT(dedupe_key) DO UPDATE SET";

/** The generated conflict clause + claim guard shared verbatim by both producers. */
const PINNED_CONFLICT_CLAUSE =
  "ON CONFLICT(dedupe_key) DO UPDATE SET message_html = excluded.message_html, disable_notification = "
  + "excluded.disable_notification, created_at = CASE WHEN COALESCE( telegram_pending_alerts.expires_at, "
  + "telegram_pending_alerts.created_at + 7200 ) <= excluded.created_at OR telegram_pending_alerts.created_at < "
  + "excluded.created_at - 7200 THEN excluded.created_at ELSE telegram_pending_alerts.created_at END, attempts = "
  + "CASE WHEN COALESCE( telegram_pending_alerts.expires_at, telegram_pending_alerts.created_at + 7200 ) <= "
  + "excluded.created_at OR telegram_pending_alerts.created_at < excluded.created_at - 7200 THEN 0 ELSE "
  + "telegram_pending_alerts.attempts END, not_before_at = CASE WHEN COALESCE( telegram_pending_alerts.expires_at, "
  + "telegram_pending_alerts.created_at + 7200 ) <= excluded.created_at OR telegram_pending_alerts.created_at < "
  + "excluded.created_at - 7200 THEN excluded.not_before_at WHEN excluded.not_before_at IS NULL THEN "
  + "telegram_pending_alerts.not_before_at WHEN telegram_pending_alerts.not_before_at IS NULL THEN "
  + "excluded.not_before_at ELSE MAX(telegram_pending_alerts.not_before_at, excluded.not_before_at) END, "
  + "last_error_class = COALESCE(excluded.last_error_class, telegram_pending_alerts.last_error_class), "
  + "retry_after_sec = COALESCE(excluded.retry_after_sec, telegram_pending_alerts.retry_after_sec), updated_at = "
  + "excluded.updated_at, chunk_index = excluded.chunk_index, priority = "
  + "MIN(COALESCE(telegram_pending_alerts.priority, excluded.priority), excluded.priority), source_type = CASE WHEN "
  + "excluded.priority < COALESCE(telegram_pending_alerts.priority, excluded.priority) THEN excluded.source_type "
  + "ELSE telegram_pending_alerts.source_type END, alert_type = COALESCE(excluded.alert_type, "
  + "telegram_pending_alerts.alert_type), expires_at = CASE WHEN COALESCE( telegram_pending_alerts.expires_at, "
  + "telegram_pending_alerts.created_at + 7200 ) <= excluded.created_at OR telegram_pending_alerts.created_at < "
  + "excluded.created_at - 7200 THEN excluded.expires_at ELSE COALESCE(telegram_pending_alerts.expires_at, "
  + "excluded.expires_at) END, processing_owner = CASE WHEN COALESCE( telegram_pending_alerts.expires_at, "
  + "telegram_pending_alerts.created_at + 7200 ) <= excluded.created_at OR telegram_pending_alerts.created_at < "
  + "excluded.created_at - 7200 THEN NULL ELSE telegram_pending_alerts.processing_owner END, processing_started_at "
  + "= CASE WHEN COALESCE( telegram_pending_alerts.expires_at, telegram_pending_alerts.created_at + 7200 ) <= "
  + "excluded.created_at OR telegram_pending_alerts.created_at < excluded.created_at - 7200 THEN NULL ELSE "
  + "telegram_pending_alerts.processing_started_at END, processing_expires_at = CASE WHEN COALESCE( "
  + "telegram_pending_alerts.expires_at, telegram_pending_alerts.created_at + 7200 ) <= excluded.created_at OR "
  + "telegram_pending_alerts.created_at < excluded.created_at - 7200 THEN NULL ELSE "
  + "telegram_pending_alerts.processing_expires_at END, delivery_owner = CASE WHEN COALESCE( "
  + "telegram_pending_alerts.expires_at, telegram_pending_alerts.created_at + 7200 ) <= excluded.created_at OR "
  + "telegram_pending_alerts.created_at < excluded.created_at - 7200 THEN NULL ELSE "
  + "telegram_pending_alerts.delivery_owner END, delivery_started_at = CASE WHEN COALESCE( "
  + "telegram_pending_alerts.expires_at, telegram_pending_alerts.created_at + 7200 ) <= excluded.created_at OR "
  + "telegram_pending_alerts.created_at < excluded.created_at - 7200 THEN NULL ELSE "
  + "telegram_pending_alerts.delivery_started_at END, delivery_completed_at = CASE WHEN COALESCE( "
  + "telegram_pending_alerts.expires_at, telegram_pending_alerts.created_at + 7200 ) <= excluded.created_at OR "
  + "telegram_pending_alerts.created_at < excluded.created_at - 7200 THEN NULL ELSE "
  + "telegram_pending_alerts.delivery_completed_at END, delivery_claim_expires_at = CASE WHEN COALESCE( "
  + "telegram_pending_alerts.expires_at, telegram_pending_alerts.created_at + 7200 ) <= excluded.created_at OR "
  + "telegram_pending_alerts.created_at < excluded.created_at - 7200 THEN NULL ELSE "
  + "telegram_pending_alerts.delivery_claim_expires_at END, source_event_id = CASE WHEN COALESCE( "
  + "telegram_pending_alerts.expires_at, telegram_pending_alerts.created_at + 7200 ) <= excluded.created_at OR "
  + "telegram_pending_alerts.created_at < excluded.created_at - 7200 THEN excluded.source_event_id ELSE "
  + "telegram_pending_alerts.source_event_id END, alert_scope_json = CASE WHEN COALESCE( "
  + "telegram_pending_alerts.expires_at, telegram_pending_alerts.created_at + 7200 ) <= excluded.created_at OR "
  + "telegram_pending_alerts.created_at < excluded.created_at - 7200 THEN excluded.alert_scope_json ELSE "
  + "telegram_pending_alerts.alert_scope_json END, preference_generation = CASE WHEN COALESCE( "
  + "telegram_pending_alerts.expires_at, telegram_pending_alerts.created_at + 7200 ) <= excluded.created_at OR "
  + "telegram_pending_alerts.created_at < excluded.created_at - 7200 THEN excluded.preference_generation ELSE "
  + "telegram_pending_alerts.preference_generation END, markup_policy_json = CASE WHEN COALESCE( "
  + "telegram_pending_alerts.expires_at, telegram_pending_alerts.created_at + 7200 ) <= excluded.created_at OR "
  + "telegram_pending_alerts.created_at < excluded.created_at - 7200 THEN excluded.markup_policy_json ELSE "
  + "telegram_pending_alerts.markup_policy_json END WHERE telegram_pending_alerts.delivery_state = 'pending' AND ( "
  + "telegram_pending_alerts.processing_owner IS NULL OR telegram_pending_alerts.processing_expires_at IS NULL OR "
  + "telegram_pending_alerts.processing_expires_at <= excluded.created_at OR COALESCE( "
  + "telegram_pending_alerts.expires_at, telegram_pending_alerts.created_at + 7200 ) <= excluded.created_at OR "
  + "telegram_pending_alerts.created_at < excluded.created_at - 7200 )";

const PINNED_ENQUEUE_HEAD =
  "INSERT INTO telegram_pending_alerts ( chat_id, message_html, disable_notification, created_at, not_before_at, "
  + "last_error_class, retry_after_sec, updated_at, dedupe_key, chunk_index, priority, source_type, alert_type, "
  + "expires_at, source_event_id, alert_scope_json, preference_generation, markup_policy_json ) VALUES (?, ?, ?, ?, "
  + "?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

const PINNED_HANDOFF_HEAD =
  "INSERT INTO telegram_pending_alerts ( chat_id, message_html, disable_notification, created_at, not_before_at, "
  + "last_error_class, retry_after_sec, updated_at, dedupe_key, chunk_index, priority, source_type, alert_type, "
  + "expires_at, source_event_id, alert_scope_json, preference_generation, markup_policy_json ) SELECT "
  + "target.chat_id, target.message_html, target.disable_notification, ?, NULL, NULL, NULL, ?, "
  + "target.pending_dedupe_key, target.chunk_index, CASE target.alert_type WHEN 'dews' THEN 20 WHEN 'depeg' THEN 10 "
  + "WHEN 'safety' THEN 20 WHEN 'launch' THEN 30 WHEN 'reserve' THEN 30 WHEN 'freeze' THEN 10 ELSE 30 END, "
  + "'risk_alert', target.alert_type, target.target_expires_at, target.source_event_id, target.alert_scope_json, "
  + "target.preference_generation, target.markup_policy_json FROM telegram_alert_job_targets target WHERE "
  + "target.source_event_id = ? AND target.plan_generation = ? AND target.status = 'planned' AND target.target_key "
  + "IN (SELECT value FROM json_each(?))";

const MESSAGE: BatchMessage = {
  chatId: "111",
  html: "<b>pin</b>",
  alertType: "depeg",
  chunkIndex: 0,
  disableNotification: false,
} as BatchMessage;

function captureEnqueueSql(): string {
  const captured: CapturedStatement[] = [];
  buildPendingAlertEnqueueStatement(capturingDb(captured), MESSAGE, 1_700_000_000);
  expect(captured).toHaveLength(1);
  return normalize(captured[0].sql);
}

function captureHandoffSql(): string {
  const captured: CapturedStatement[] = [];
  buildSetBasedPendingHandoffStatements(capturingDb(captured), "src-1", 3, 1_700_000_000, ["target-a"]);
  return normalize(captured[0].sql);
}

describe("telegram_pending_alerts upsert SQL", () => {
  it("pins the bind-parameterized enqueue form", () => {
    const sql = captureEnqueueSql();
    expect(sql.slice(0, sql.indexOf(CONFLICT_MARKER)).trim()).toBe(PINNED_ENQUEUE_HEAD);
    expect(sql.slice(sql.indexOf(CONFLICT_MARKER))).toBe(PINNED_CONFLICT_CLAUSE);
  });

  it("pins the set-based authoritative handoff form", () => {
    const sql = captureHandoffSql();
    expect(sql.slice(0, sql.indexOf(CONFLICT_MARKER)).trim()).toBe(PINNED_HANDOFF_HEAD);
    expect(sql.slice(sql.indexOf(CONFLICT_MARKER))).toBe(PINNED_CONFLICT_CLAUSE);
  });

  it("emits one conflict clause for both value sources", () => {
    const enqueue = captureEnqueueSql();
    const handoff = captureHandoffSql();
    expect(enqueue.slice(enqueue.indexOf(CONFLICT_MARKER)))
      .toBe(handoff.slice(handoff.indexOf(CONFLICT_MARKER)));
  });

  it("binds only the insert values now that the TTL constant is inlined", () => {
    const captured: CapturedStatement[] = [];
    buildPendingAlertEnqueueStatement(capturingDb(captured), MESSAGE, 1_700_000_000);
    expect(captured[0].binds).toHaveLength(18);
  });

  it("generates a priority arm for every canonical alert type", () => {
    const sql = normalize(pendingPrioritySql("target.alert_type"));
    expect(sql).toBe(
      "CASE target.alert_type WHEN 'dews' THEN 20 WHEN 'depeg' THEN 10 WHEN 'safety' THEN 20"
      + " WHEN 'launch' THEN 30 WHEN 'reserve' THEN 30 WHEN 'freeze' THEN 10 ELSE 30 END",
    );
  });

  it("keeps the conflict clause independent of the value source", () => {
    const values = normalize(buildPendingAlertUpsertSql("VALUES (1)"));
    const select = normalize(buildPendingAlertUpsertSql("SELECT 1"));
    expect(values.slice(values.indexOf(CONFLICT_MARKER)))
      .toBe(select.slice(select.indexOf(CONFLICT_MARKER)));
  });
});
