import type { VisualCue } from "./world-types";

export function buildVisualCueRegistry(): VisualCue[] {
  return [
    {
      id: "cue.lighthouse.psi",
      target: { kind: "lighthouse" },
      primaryChannels: ["glow", "color", "opacity"],
      visual: "lighthouse great fire",
      sourceField: "stability.current.band",
      questionAnswered: "What is the overall Pharos Stability Index state?",
      failureState: "unlit/fogged lighthouse",
      domEquivalent: "lighthouse detail panel",
      reducedMotionEquivalent: "static great-fire color and lighthouse detail PSI rows",
    },
    {
      id: "cue.dock.size",
      target: { kind: "dock" },
      primaryChannels: ["size", "shape", "position"],
      visual: "dock footprint and harbor style",
      sourceField: "chains.chains[].totalUsd, chains.chains[].topStablecoins",
      questionAnswered: "Which chains hold the largest stablecoin supply, and which stablecoins dominate each chain?",
      failureState: "dock unavailable state",
      domEquivalent: "dock ledger rows",
      reducedMotionEquivalent: "static dock footprint and dock ledger rows",
    },
    {
      id: "cue.ship.distance",
      target: { kind: "ship" },
      primaryChannels: ["position", "motion", "opacity"],
      visual: "ship placement from Calm Anchorage through Watch Breakwater, Alert Channel, Warning Shoals, and Danger Strait",
      sourceField: "pegSummary.coins[], stress.signals[]",
      questionAnswered: "Which stablecoins are under peg or DEWS stress?",
      failureState: "data fog",
      domEquivalent: "ship detail placement explanation with named risk water area and zone",
      reducedMotionEquivalent: "static harbor mooring when docked, or static risk-water patrol position, with named risk-water facts in DOM",
    },
    {
      id: "cue.ship.motion",
      target: { kind: "ship" },
      primaryChannels: ["motion", "position", "opacity"],
      visual: "ship route and docking cadence",
      sourceField: "stablecoins.peggedAssets[].chainCirculating, pegSummary.coins[], stress.signals[]",
      questionAnswered: "Where can this ship dock, how often does it visit, and which risk water anchors its route?",
      failureState: "reduced-motion static harbor mooring or risk patrol / data fog",
      domEquivalent: "ship detail route facts and accessibility ledger",
      reducedMotionEquivalent: "representative harbor or risk-water position without RAF",
    },
    {
      id: "cue.water.semantic-terrain",
      target: { kind: "area" },
      primaryChannels: ["color", "shape", "motion"],
      visual: "printed cartographic water labels over calm DEWS anchorage, watch breakwater chop, alert current, warning shoals, storm strait, brackish evidence fog, and ledger-water texture",
      sourceField: "stress.signals[], pegSummary.coins[], stablecoinMeta.flags.navToken",
      questionAnswered: "Which named water areas encode calm, stale-evidence, NAV-ledger, alert, warning, or danger conditions?",
      failureState: "generic water texture with DOM area detail still available",
      domEquivalent: "named area detail panel and accessibility ledger rows",
      reducedMotionEquivalent: "static semantic water texture and printed labels",
    },
    {
      id: "cue.ship.hull",
      target: { kind: "ship" },
      primaryChannels: ["shape", "size"],
      visual: "ship class silhouette",
      sourceField: "stablecoinMeta.flags.governance",
      questionAnswered: "Is the stablecoin CeFi, CeFi-dependent, or DeFi?",
      failureState: "generic hull",
      domEquivalent: "ship detail class row",
      reducedMotionEquivalent: "same static hull silhouette",
    },
    {
      id: "cue.ship.rigging",
      target: { kind: "ship" },
      primaryChannels: ["shape", "position"],
      visual: "ship rigging style",
      sourceField: "stablecoinMeta.flags.governance",
      questionAnswered: "Which governance class controls the base ship model?",
      failureState: "generic rigging",
      domEquivalent: "ship detail class row",
      reducedMotionEquivalent: "same static rigging silhouette",
    },
    {
      id: "cue.ship.pennant",
      target: { kind: "ship" },
      primaryChannels: ["shape", "color", "position"],
      visual: "ship sail logo and pennant color",
      sourceField: "data/logos.json, stablecoinMeta.flags.pegCurrency",
      questionAnswered: "Which stablecoin is this, and what is its peg currency?",
      failureState: "symbol monogram on slate pennant",
      domEquivalent: "ship detail identity and peg rows",
      reducedMotionEquivalent: "same static sail logo or monogram",
    },
    {
      id: "cue.ship.scale",
      target: { kind: "ship" },
      primaryChannels: ["size", "shape"],
      visual: "compressed ship scale tier",
      sourceField: "stablecoins.peggedAssets[].circulating",
      questionAnswered: "Roughly how large is the stablecoin supply without letting outliers dominate the map?",
      failureState: "small default scale",
      domEquivalent: "ship detail market-cap and size-tier rows",
      reducedMotionEquivalent: "same static compressed size tier",
    },
    {
      id: "cue.cemetery",
      target: { kind: "grave" },
      primaryChannels: ["shape", "size", "color"],
      visual: "cemetery graves",
      sourceField: "CEMETERY_ENTRIES",
      questionAnswered: "Which assets are dead or frozen?",
      failureState: "cemetery unavailable row",
      domEquivalent: "cemetery ledger rows",
      reducedMotionEquivalent: "same static tomb marker and cause plaque",
    },
    {
      id: "cue.ship-cluster",
      target: { kind: "ship-cluster" },
      primaryChannels: ["size", "position", "shape"],
      visual: "count-capped water-zone cluster marker",
      sourceField: "stablecoins.peggedAssets[], pegSummary.coins[], stress.signals[]",
      questionAnswered: "Where are long-tail stablecoins grouped after the individual ship budget is reached?",
      failureState: "cluster omitted and represented in DOM ledger only",
      domEquivalent: "long-tail cluster detail panel and accessibility ledger rows with risk-water area and zone",
      reducedMotionEquivalent: "same static cluster marker and member list",
    },
    {
      id: "cue.building.mint-burn-foundry",
      target: { kind: "building", buildingType: "mint-burn-foundry" },
      primaryChannels: ["glow", "motion", "opacity"],
      visual: "foundry press, furnace glow, smoke, and sparks",
      sourceField: "mintBurnFlows.gauge, mintBurnFlows.coins[], mintBurnFlows.hourly[], mintBurnFlows.sync",
      questionAnswered: "Are configured issuance-chain events mint-heavy, burn-heavy, balanced, quiet, or stale?",
      failureState: "dim foundry with data fog",
      domEquivalent: "Royal Mint And Burn Foundry detail facts and accessibility ledger row",
      reducedMotionEquivalent: "static foundry glow, frozen sparks, and detail facts",
    },
    {
      id: "cue.building.exit-route-gatehouse",
      target: { kind: "building", buildingType: "exit-route-gatehouse" },
      primaryChannels: ["shape", "motion", "glow"],
      visual: "gate doors, contained gauge wheel, and guarded arch lantern",
      sourceField: "dexLiquidity[__global__], dexLiquidity[coin], redemptionBackstops.coins",
      questionAnswered: "How deep, open, concentrated, or stale are observed and modeled exit routes?",
      failureState: "closed gray gate with dim arch",
      domEquivalent: "Exit Route Gatehouse detail facts and accessibility ledger row",
      reducedMotionEquivalent: "static gate lantern, contained gauge, and detail facts",
    },
  ];
}
