import type { VisualCue } from "./world-types";

export function buildVisualCueRegistry(): VisualCue[] {
  return [
    {
      id: "cue.lighthouse.psi",
      visual: "lighthouse great fire",
      sourceField: "stability.current.band",
      questionAnswered: "What is the overall Pharos Stability Index state?",
      failureState: "unlit/fogged lighthouse",
      domEquivalent: "lighthouse detail panel",
    },
    {
      id: "cue.dock.size",
      visual: "dock footprint and harbor style",
      sourceField: "chains.chains[].totalUsd, chains.chains[].topStablecoins",
      questionAnswered: "Which chains hold the largest stablecoin supply, and which stablecoins dominate each chain?",
      failureState: "dock unavailable state",
      domEquivalent: "dock ledger rows",
    },
    {
      id: "cue.ship.distance",
      visual: "ship placement from harbor to storm shelf",
      sourceField: "pegSummary.coins[], stress.signals[]",
      questionAnswered: "Which stablecoins are under peg or DEWS stress?",
      failureState: "data fog",
      domEquivalent: "ship detail placement explanation",
    },
    {
      id: "cue.ship.motion",
      visual: "ship route and docking cadence",
      sourceField: "stablecoins.peggedAssets[].chainCirculating, pegSummary.coins[], stress.signals[]",
      questionAnswered: "Where can this ship dock, how often does it visit, and which risk water anchors its route?",
      failureState: "reduced-motion static harbor mooring or risk patrol / data fog",
      domEquivalent: "ship detail route facts and accessibility ledger",
    },
    {
      id: "cue.ship.hull",
      visual: "ship class silhouette",
      sourceField: "stablecoinMeta.flags.governance",
      questionAnswered: "Is the stablecoin CeFi, CeFi-dependent, or DeFi?",
      failureState: "generic hull",
      domEquivalent: "ship detail class row",
    },
    {
      id: "cue.ship.rigging",
      visual: "ship rigging style",
      sourceField: "stablecoinMeta.flags.governance",
      questionAnswered: "Which governance class controls the base ship model?",
      failureState: "generic rigging",
      domEquivalent: "ship detail class row",
    },
    {
      id: "cue.ship.pennant",
      visual: "ship sail logo and pennant color",
      sourceField: "data/logos.json, stablecoinMeta.flags.pegCurrency",
      questionAnswered: "Which stablecoin is this, and what is its peg currency?",
      failureState: "symbol monogram on slate pennant",
      domEquivalent: "ship detail identity and peg rows",
    },
    {
      id: "cue.ship.scale",
      visual: "compressed ship scale tier",
      sourceField: "stablecoins.peggedAssets[].circulating",
      questionAnswered: "Roughly how large is the stablecoin supply without letting outliers dominate the map?",
      failureState: "small default scale",
      domEquivalent: "ship detail market-cap and size-tier rows",
    },
    {
      id: "cue.cemetery",
      visual: "cemetery graves",
      sourceField: "CEMETERY_ENTRIES",
      questionAnswered: "Which assets are dead or frozen?",
      failureState: "cemetery unavailable row",
      domEquivalent: "cemetery ledger rows",
    },
    {
      id: "cue.building.mint-burn-foundry",
      visual: "foundry press, furnace glow, smoke, and sparks",
      sourceField: "mintBurnFlows.gauge, mintBurnFlows.coins[], mintBurnFlows.hourly[], mintBurnFlows.sync",
      questionAnswered: "Are configured issuance-chain events mint-heavy, burn-heavy, balanced, quiet, or stale?",
      failureState: "dim foundry with data fog",
      domEquivalent: "Royal Mint And Burn Foundry detail facts and accessibility ledger row",
    },
    {
      id: "cue.building.frost-ward-keep",
      visual: "frost, cold mist, lock chains, and blue lanterns",
      sourceField: "blacklistSummary.stats, blacklistSummary.stats.perCoinFrozenTotal, blacklistSummary.chains",
      questionAnswered: "How much observed freeze activity is active or recent in the blacklist tracker?",
      failureState: "fogged keep with muted lanterns",
      domEquivalent: "Frost Ward Keep detail facts and accessibility ledger row",
    },
    {
      id: "cue.building.exit-route-gatehouse",
      visual: "gate doors, water level, waterwheel, and ferry lantern",
      sourceField: "dexLiquidity[__global__], dexLiquidity[coin], redemptionBackstops.coins",
      questionAnswered: "How deep, open, concentrated, or stale are observed and modeled exit routes?",
      failureState: "closed gray gate with still water",
      domEquivalent: "Exit Route Gatehouse detail facts and accessibility ledger row",
    },
    {
      id: "cue.building.yield-orchard",
      visual: "orchard glints, moonwell glow, irrigation sparkles, and windmill motion",
      sourceField: "yieldRankings.rankings[], yieldRankings.provenance",
      questionAnswered: "How broad and fresh is yield source coverage, and is source context switching or warning?",
      failureState: "dim orchard with static well",
      domEquivalent: "Yield Orchard And Moonwell detail facts and accessibility ledger row",
    },
    {
      id: "cue.building.dependency-loom",
      visual: "chainworks gears, thread arcs, and pulse dots",
      sourceField: "reportCards.dependencyGraph.edges[], reportCards.cards[]",
      questionAnswered: "How many direct dependency links and hubs exist in the report-card graph?",
      failureState: "desaturated loom with no thread pulses",
      domEquivalent: "Dependency Loom / Chainworks detail facts and accessibility ledger row",
    },
  ];
}
