import type { SafetyScoreV9AdminResponse } from "@shared/types/safety-score-v9-admin";

const DIGEST = "a".repeat(64);
const BASE_INPUT = `report-cards-input:v1:${DIGEST}`;

export function makeSafetyScoreV9AdminAvailableResponse(): Extract<
  SafetyScoreV9AdminResponse,
  { status: "available" }
> {
  return {
    schemaVersion: 1,
    status: "available",
    envelope: {
      schemaVersion: 1,
      candidate: {
        model: "v9-critical-path",
        schemaVersion: 1,
        lifecycle: "candidate",
        candidateId: "v9-candidate-1",
        policyVersion: "candidate-v1",
        publicationGenerationId: "v9-generation-1",
        baseInputGenerationId: BASE_INPUT,
        factSetDigest: DIGEST,
        resultDigest: DIGEST,
        policy: { id: "policy-1", semanticDigest: DIGEST },
        evaluationBuildDigest: DIGEST,
        sourceGenerations: { reserves: "r1" },
        asOfSec: 1_700_000_000,
        publishedAtSec: 1_700_000_100,
        completeness: { expectedCount: 2, ratedCount: 1, notRatedCount: 1, notRatedIds: ["coin-b"] },
        cards: [
          {
            id: "coin-a",
            score: 91,
            grade: "A+",
            qualityScore: 92,
            pegMultiplier: 0.99,
            pegAdjustedScore: 91,
            pillars: {
              backing: { score: 94, evidenceLevel: "strong", freshness: "current", components: [], reasons: [] },
              exit: { score: 90, evidenceLevel: "strong", freshness: "current", components: [], reasons: [] },
              control: { score: 89, evidenceLevel: "adequate", freshness: "current", components: [], reasons: [] },
            },
            weakestPillar: { pillar: "control", score: 89 },
            caps: [],
            bindingCap: null,
            nrReasons: [],
            reasonCodes: [],
            evidence: { level: "adequate", freshness: "current", reasons: [] },
            accessPosture: {
              transfer: "permissionless",
              freezeExposure: "direct",
              primaryExit: "eligibility-gated",
              governance: "single-entity",
              unknownFields: [],
              signals: ["issuer freeze control"],
              reasons: [],
            },
            dependencies: { serial: [], basket: [], cycleBlocked: false, reasonCodes: [] },
            stressStateDigest: DIGEST,
          },
          {
            id: "coin-b",
            score: null,
            grade: "NR",
            qualityScore: null,
            pegMultiplier: null,
            pegAdjustedScore: null,
            pillars: {
              backing: {
                score: null,
                evidenceLevel: "insufficient",
                freshness: "unknown",
                components: [],
                reasons: [],
              },
              exit: { score: null, evidenceLevel: "insufficient", freshness: "unknown", components: [], reasons: [] },
              control: {
                score: null,
                evidenceLevel: "insufficient",
                freshness: "unknown",
                components: [],
                reasons: [],
              },
            },
            weakestPillar: null,
            caps: [],
            bindingCap: null,
            nrReasons: [
              { code: "insufficient-evidence", message: "Evidence review missing", field: "backing", origin: "asset" },
            ],
            reasonCodes: ["insufficient-evidence"],
            evidence: { level: "insufficient", freshness: "unknown", reasons: [] },
            accessPosture: {
              transfer: "unknown",
              freezeExposure: "unknown",
              primaryExit: "unknown",
              governance: "unknown",
              unknownFields: ["freezeExposure", "governance", "primaryExit", "transfer"],
              signals: [],
              reasons: [],
            },
            dependencies: { serial: [], basket: [], cycleBlocked: false, reasonCodes: [] },
            stressStateDigest: null,
          },
        ],
      },
      compilerFactSchemaDigest: DIGEST,
      producerCapabilityDigest: DIGEST,
      releaseCoveragePolicyDigest: DIGEST,
      consumerThresholdRegistryDigest: DIGEST,
      coverage: {
        expectedActiveCount: 2,
        observedResultCount: 2,
        presentExpectedCount: 2,
        ratedResultCount: 1,
        notRatedResultCount: 1,
        expectedActiveIdsDigest: DIGEST,
        presentExpectedIdsDigest: DIGEST,
        missingIds: [],
        unexpectedIds: [],
        duplicateIds: [],
        compilerExceptions: [],
        futureDatedEvidenceIds: [],
        coverageFloors: [
          { id: "rated-coverage", status: "fail", observed: 0.5, required: "99%", detail: "Only half rated" },
        ],
        publicationRegression: false,
        unresolvedReleaseBlockers: ["Independent validation is not sealed"],
        unresolvedCriticalMovementIds: [],
      },
      replayArtifacts: [],
    },
    diff: {
      schemaVersion: 1,
      generatedAtSec: 1_700_000_100,
      expectedActiveIdsDigest: DIGEST,
      v8Identity: {
        publicationGenerationId: "v8-generation",
        baseInputGenerationId: BASE_INPUT,
        methodologyVersion: "8.0",
        evaluationBuildDigest: DIGEST,
      },
      v9Identity: {
        candidateId: "v9-candidate-1",
        policyVersion: "candidate-v1",
        publicationGenerationId: "v9-generation-1",
        baseInputGenerationId: BASE_INPUT,
        factSetDigest: DIGEST,
        policyId: "policy-1",
        policyDigest: DIGEST,
        evaluationBuildDigest: DIGEST,
        resultDigest: DIGEST,
      },
      thresholds: { absoluteScoreDelta: 5, topCutoffScoreDelta: 2, downstream: [] },
      summary: {
        expectedCount: 2,
        comparedCount: 2,
        missingInputCount: 0,
        gradeOrNrTransitionCount: 1,
        bindingCapChangeCount: 0,
        largeScoreMovementCount: 1,
        topCutoffMovementCount: 1,
        downstreamCrossingCount: 0,
        requiresReviewCount: 1,
        pendingReviewCount: 1,
        comparableSupplyUsd: 100,
        supplyWeightedMeanAbsoluteDelta: 3.2,
      },
      topSupplyWeightedMovements: [],
      cards: [
        {
          id: "coin-a",
          v8: { score: 82, grade: "A-", bindingCap: null, reasonCodes: [] },
          v9: { score: 91, grade: "A+", bindingCap: null, reasonCodes: [] },
          v9WeakestPillar: { pillar: "control", score: 89 },
          transition: "both-rated",
          scoreDelta: 9,
          absoluteScoreDelta: 9,
          newReasonCodes: [],
          removedReasonCodes: [],
          supplyUsd: 100,
          supplyWeightedImpact: 900,
          flags: {
            inputMissing: false,
            gradeOrNrTransition: true,
            bindingCapChanged: false,
            absoluteScoreDeltaAtLeast5: true,
            topCutoffScoreDeltaAtLeast2: true,
            downstreamThresholdCrossingIds: [],
            requiresReview: true,
          },
          review: { key: DIGEST, status: "pending", disposition: null },
        },
      ],
      reportDigest: DIGEST,
    },
    movementReviews: [],
    history: [
      {
        schemaVersion: 1,
        utcDay: "2026-07-13",
        updatedAtSec: 1_700_000_100,
        attemptCounts: { successful: 1, failed: 0 },
        selectedRun: {
          selectedAtSec: 1_700_000_100,
          identity: {
            candidateId: "v9-candidate-1",
            policyVersion: "candidate-v1",
            publicationGenerationId: "v9-generation-1",
            baseInputGenerationId: BASE_INPUT,
            factSetDigest: DIGEST,
            policyId: "policy-1",
            policyDigest: DIGEST,
            evaluationBuildDigest: DIGEST,
            resultDigest: DIGEST,
            compilerFactSchemaDigest: DIGEST,
            producerCapabilityDigest: DIGEST,
            releaseCoveragePolicyDigest: DIGEST,
            consumerThresholdRegistryDigest: DIGEST,
            envelopeDigest: DIGEST,
            sourceGenerations: {},
          },
          coverage: {
            expectedActiveCount: 2,
            observedResultCount: 2,
            presentExpectedCount: 2,
            ratedResultCount: 1,
            notRatedResultCount: 1,
            expectedActiveIdsDigest: DIGEST,
            presentExpectedIdsDigest: DIGEST,
            missingIds: [],
            unexpectedIds: [],
            duplicateIds: [],
            compilerExceptions: [],
            futureDatedEvidenceIds: [],
            coverageFloors: [
              { id: "rated-coverage", status: "fail", observed: 0.5, required: "99%", detail: "Only half rated" },
            ],
            publicationRegression: false,
            unresolvedReleaseBlockers: ["Independent validation is not sealed"],
            unresolvedCriticalMovementIds: [],
          },
          movement: {
            expectedCount: 2,
            comparedCount: 2,
            missingInputCount: 0,
            gradeOrNrTransitionCount: 1,
            bindingCapChangeCount: 0,
            largeScoreMovementCount: 1,
            topCutoffMovementCount: 1,
            downstreamCrossingCount: 0,
            requiresReviewCount: 1,
            pendingReviewCount: 1,
            comparableSupplyUsd: 100,
            supplyWeightedMeanAbsoluteDelta: 3.2,
          },
          qualification: { qualifies: false, blockers: ["coverage-floor-failed"] },
          diffReportDigest: DIGEST,
          archiveSelectionReasons: [],
          artifactKeys: [],
        },
        latestError: null,
      },
    ],
  };
}
