// @generated by scripts/generate-stablecoin-frozen-registry.mjs
// Do not edit by hand. Run `node scripts/generate-stablecoin-frozen-registry.mjs`
// after modifying any shared/data/stablecoins/coins/*.json file or
// shared/data/stablecoins/coins.generated.json.
//
// This module mirrors coins.generated.json as a typed snapshot so the
// Worker / Next.js runtime can skip the per-boot Zod parse. The embedded
// fingerprint lets registry.ts detect drift (e.g. someone edited a coin
// JSON without regenerating) and fall back to the live Zod path.

import type { StablecoinMeta } from "../../types";
import coinsGenerated from "./coins.generated.json";

/** FNV-1a 32-bit fingerprint of `coins.generated.json` at generation time. */
export const STABLECOIN_META_ASSETS_FROZEN_HASH = "79692350";

/** Number of stablecoin metas captured in the frozen snapshot. */
export const STABLECOIN_META_ASSETS_FROZEN_COUNT = 381;

/**
 * Pre-validated stablecoin metas, exposed in source order. The generator
 * runs alongside `npm run check:stablecoin-data`, which performs the
 * authoritative Zod + invariant validation; consumers may use this array
 * directly when the runtime fingerprint matches
 * `STABLECOIN_META_ASSETS_FROZEN_HASH`.
 */
export const STABLECOIN_META_ASSETS_FROZEN: readonly StablecoinMeta[] =
  coinsGenerated as readonly StablecoinMeta[];
