// @generated by scripts/maintenance/generate-stablecoin-prevalidated-registry.mjs
// Do not edit by hand. Run `node scripts/maintenance/generate-stablecoin-prevalidated-registry.mjs`
// after modifying any shared/data/stablecoins/coins/*.json file or
// shared/data/stablecoins/coins.generated.json.
//
// This module mirrors coins.generated.json as a typed snapshot so the
// Worker / Next.js runtime can trust the checked artifact without bundling
// the full Zod registry validator into browser-facing chunks.

import type { StablecoinMeta } from "../../types";
import coinsGenerated from "./coins.generated.json";

// FNV-1a 32-bit fingerprint of `coins.generated.json` at generation time: de1d50b2.

/**
 * Pre-validated stablecoin metas, exposed in source order. The generator
 * runs alongside `npm run check:stablecoin-data`, which performs the
 * authoritative Zod + invariant validation.
 */
export const STABLECOIN_META_ASSETS_PREVALIDATED: readonly StablecoinMeta[] =
  coinsGenerated as readonly StablecoinMeta[];
