// @generated by scripts/maintenance/generate-report-card-registry-fingerprint.ts
// Do not edit by hand. Run `npx tsx scripts/maintenance/generate-report-card-registry-fingerprint.ts`
// after modifying the tracked or dead stablecoin registries.

/**
 * SHA-256 of the canonical report-card registry identity projection.
 * The generator computes this from the fully validated registry so Worker
 * requests do not serialize and hash the full catalog at runtime.
 */
export const REPORT_CARDS_REGISTRY_FINGERPRINT =
  "e45dfcdd62d79527df0eefac2a2f461a67d666888ef2b01ff193131f540e91f8";
