// @generated by scripts/maintenance/generate-stablecoin-prevalidated-registry.mjs
// Do not edit by hand. Run `node scripts/maintenance/generate-stablecoin-prevalidated-registry.mjs`
// after modifying the tracked or dead stablecoin registries.

/**
 * SHA-256 of the canonical report-card registry identity projection.
 * The generator computes this from the fully validated registry so Worker
 * requests do not serialize and hash the full catalog at runtime.
 */
export const REPORT_CARDS_REGISTRY_FINGERPRINT =
  "2fc29e3b5622939f33b826f8d09ba57936fff1d403d1a95002df876b483e7396";
