import type { DataQuality, StatusResponse } from "@shared/types/status";
import { emptyReserveCompositionOverview } from "@shared/types/live-reserves";

export function makeDataQuality(overrides?: Partial<DataQuality>): DataQuality {
  return {
    stablecoinsCacheStatus: "ok",
    stablecoinsCacheReason: null,
    blacklistGapStatus: "ok",
    activeDepegStatus: "ok",
    onchainSupplyQueryStatus: "ok",
    repairDebt: {
      status: "ok",
      openCount: 0,
      oldestAgeSec: null,
      byKind: {},
      availabilityEscalated: false,
      nextRunnerDueAt: null,
      source: "worker-repair-tasks",
    },
    ddrRepairDebtStatus: "ok",
    ddrRepairDebtCount: 0,
    ddrRepairDebtCheckedAt: null,
    ddrRepairDebtEvents: [],
    ddrRepairDebtEventsTruncated: false,
    sourceFailures: [],
    totalStablecoins: 10,
    missingPrices: 0,
    blacklistMissingAmounts: 0,
    blacklistRecentMissingAmounts: 0,
    blacklistRecentWindowSec: 86400,
    blacklistMissingRatio: 0,
    blacklistTotal: 0,
    blacklistOldestRecoverableAgeSec: null,
    blacklistNeverAttemptedCount: 0,
    blacklistRepeatedFailureCount: 0,
    onchainSupplyDivergences: 0,
    onchainDivergenceRatio: 0,
    onchainSupplyMonitoring: "active",
    onchainSupplyLatestAt: null,
    onchainSupplyTrackedCoins: 0,
    activeDepegs: 0,
    staleOnchainSupply: 0,
    onchainStaleRatio: 0,
    ...overrides,
  };
}

export function makeReserveComposition(overrides: Partial<StatusResponse["reserveComposition"]> = {}): StatusResponse["reserveComposition"] {
  return {
    ...emptyReserveCompositionOverview(),
    status: "healthy",
    freshCoverageRatio: 0,
    authoritativeFreshCoverageRatio: 0,
    ...overrides,
  };
}

export function makeStatusSummary(overrides: Partial<StatusResponse["summary"]> = {}): StatusResponse["summary"] {
  return {
    unhealthyCrons: 0,
    availabilityImpactingUnhealthyCrons: 0,
    watchUnhealthyCrons: 0,
    degradedCrons: 0,
    cronErrors: 0,
    availabilityImpactingCronErrors: 0,
    availabilityImpactingConsecutiveCronErrors: 0,
    diagnosticIssueCount: 0,
    worstCacheRatio: 0,
    transitionsLast24h: 0,
    ...overrides,
  };
}

export function reserveComposition() {
  return {
    configuredCoins: 267,
    freshCoins: 250,
    staleCoins: 4,
    missingCoins: 3,
    degradedCoins: 5,
    errorCoins: 2,
    corruptCoins: 1,
    independentFreshEligible: 140,
    independentFreshUnverified: 8,
    staticValidatedFresh: 60,
    weakProbeFresh: 42,
    writeTimeoutUncertain: 1,
    deferredCoins: 12,
    runBudgetTruncated: true,
    deferredAt: 1_780_000_000,
    nextCursorStablecoinId: "usdc-circle",
    cursorTailState: "incomplete",
    cursorTailError: "cursor write failed",
    cursorRecordedAt: 1_780_000_010,
    cursorTailCompletedAt: null,
    cursorTailFailedAt: 1_780_000_020,
    runBudgetTruncationCount: 2,
    historyWriteGaps: [
      {
        stablecoinId: "usdc-circle",
        fetchedAt: 1_780_000_030,
        attemptId: "attempt-1",
        compositionHistoryMissing: true,
        attemptHistoryMissing: false,
      },
    ],
    persistentlyStaleIndependentCoins: [
      { stablecoinId: "hbusdt-hyperbeat", ageSec: 1_300_000 },
    ],
    lastSuccessAt: 1_780_000_030,
    oldestFreshAgeSec: 3_600,
    status: "degraded",
    freshCoverageRatio: 0.93,
    authoritativeFreshCoverageRatio: 0.74,
  };
}

export function statusResponse() {
  return {
    timestamp: 1_780_000_100,
    dbHealthy: true,
    availabilityStatus: "healthy",
    dataQualityStatus: "degraded",
    rawOverallStatus: "degraded",
    overallStatus: "degraded",
    confidence: 0.95,
    causes: { availability: [], dataQuality: [], overall: [] },
    state: {
      scope: "global",
      currentStatus: "degraded",
      rawStatus: "degraded",
      lastEvaluatedAt: 1_780_000_100,
      lastChangedAt: 1_780_000_000,
      minDwellSec: 120,
      staleMinDwellSec: 180,
      consecutiveRaw: { healthy: 0, degraded: 2, stale: 0 },
      thresholds: {
        escalateToDegraded: 2,
        escalateToStale: 1,
        recoverToDegraded: 2,
        recoverToHealthy: 3,
      },
    },
    staleness: { ageSeconds: 10, maxAgeSec: 60, isStale: false },
    probe: {
      timestamp: 1_780_000_090,
      status: "healthy",
      sampleCount: 1,
      passCount: 1,
      failCount: 0,
      p95LatencyMs: 100,
    },
    discrepancy: {
      hasDivergence: false,
      severityDelta: 0,
      statusSeverity: 1,
      probeSeverity: 0,
      details: null,
      probeAgeSeconds: 10,
      consecutiveDivergent: 0,
      discrepancyReason: "in-sync",
    },
    timeline: [],
    caches: {},
    crons: {},
    budgetOnlySurfaces: [],
    dataQuality: makeDataQuality({ totalStablecoins: 0, blacklistRecentWindowSec: 0 }),
    telegramBot: null,
    sectionErrors: {},
    datasetFreshness: {
      stablecoins: null,
      blacklist: null,
      mintBurn: null,
      supply: null,
      safetyGrades: null,
      yield: null,
      depegs: null,
      dews: null,
      digest: null,
    },
    summary: makeStatusSummary(),
    liquidityHealth: null,
    yieldHealth: null,
    publicationHealth: null,
    dependencyHealth: null,
    providerCircuitHealth: null,
    canaries: null,
    priceSourceHealth: null,
    coingeckoPriceDiff: null,
    d1Usage: null,
    mintBurnReconciliation: null,
    reserveComposition: reserveComposition(),
  };
}

