-- Daily editorial digest generated by LLM
CREATE TABLE daily_digest (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  generated_at INTEGER NOT NULL,
  digest_text TEXT NOT NULL,
  input_data TEXT NOT NULL
);

CREATE INDEX idx_daily_digest_generated_at ON daily_digest(generated_at);
