import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { CRON_SCHEDULE_CADENCES } from "@shared/lib/cron-cadences";
import { CRON_SCHEDULES, CRON_TRIGGER_SCHEDULES, type CronScheduleKey } from "@shared/lib/cron-jobs";
import { SCHEDULED_SLOT_PLANS, type ScheduledWorkerRole } from "@shared/lib/scheduled-runner-registry";
import { evaluateCronScheduleSync, parseWranglerCronTriggers } from "../ci/check-cron-schedule-sync";
import { parseStrictCliArgs, runDirectCli, writeCliHelpIfRequested } from "../lib/cli-args.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const DOC_PATH = "docs/worker-infrastructure.md";
const HEADING = "## Cron Scheduling\n";
export const START_MARKER = "<!-- GENERATED-START: cron-doc-view -->";
export const END_MARKER = "<!-- GENERATED-END: cron-doc-view -->";
const USAGE = `Usage: node --import tsx scripts/maintenance/generate-cron-doc-view.ts [options]

Options:
  --check       Check freshness without writing
  -h, --help    Show this help`;

type WorkerTriggers = Record<ScheduledWorkerRole, readonly string[]>;

export function loadCronDocTriggers(repoRoot: string): WorkerTriggers {
  return {
    public: parseWranglerCronTriggers(readFileSync(resolve(repoRoot, "worker/wrangler.toml"), "utf8")),
    heavy: parseWranglerCronTriggers(readFileSync(resolve(repoRoot, "worker/wrangler.heavy.toml"), "utf8")),
  };
}

export function renderCronDocView(triggers: WorkerTriggers): string {
  const report = evaluateCronScheduleSync({ wranglerCronTriggers: triggers });
  if (report.failed) {
    throw new Error("Cron sources disagree; resolve check:cron-sync findings before generating the cadence table");
  }
  const rows = (Object.keys(CRON_SCHEDULES) as CronScheduleKey[]).map((key) => {
    const plan = SCHEDULED_SLOT_PLANS[key];
    if (plan.scheduleKey !== key || plan.schedule !== CRON_SCHEDULES[key]) {
      throw new Error(`Cron slot identity disagrees for ${key}`);
    }
    const cadence = CRON_SCHEDULE_CADENCES[key];
    const physical = CRON_TRIGGER_SCHEDULES[key].map((expression) => `\`${expression}\``).join("<br>");
    return `| \`${key}\` | \`${CRON_SCHEDULES[key]}\` | ${cadence.intervalSec} / ${cadence.offsetSec} | ${physical} | ${plan.worker} |`;
  });
  return [
    START_MARKER,
    "<!-- Generated by scripts/maintenance/generate-cron-doc-view.ts. Do not edit by hand. -->",
    "",
    "UTC inventory from `shared/lib/cron-jobs.ts`, `shared/lib/cron-cadences.ts`, `shared/lib/scheduled-runner-registry.ts`, `worker/wrangler.toml` and `worker/wrangler.heavy.toml`. Public = `stablecoin-api`; heavy = scheduled-only `stablecoin-heavy`.",
    "",
    "Interval / offset are logical-slot seconds, not job freshness or delivery evidence. Aliases can move without changing logical slot identity. The monthly cron owns calendar firing dates.",
    "",
    "| Logical slot key | Logical cron | Interval / offset (s) | Physical trigger expression(s) | Worker role |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
    "",
    END_MARKER,
  ].join("\n");
}

export function replaceCronDocView(doc: string, block: string): string {
  const start = doc.indexOf(START_MARKER);
  const end = doc.indexOf(END_MARKER);
  if (start === -1 && end === -1) {
    const heading = doc.indexOf(HEADING);
    if (heading === -1 || doc.indexOf(HEADING, heading + HEADING.length) !== -1) {
      throw new Error("Expected exactly one Cron Scheduling heading");
    }
    const insertion = heading + HEADING.length;
    return `${doc.slice(0, insertion)}\n${block}\n${doc.slice(insertion)}`;
  }
  if (start === -1 || end < start
      || doc.indexOf(START_MARKER, start + START_MARKER.length) !== -1
      || doc.indexOf(END_MARKER, end + END_MARKER.length) !== -1) {
    throw new Error("Expected exactly one complete cron-doc-view generated block");
  }
  return `${doc.slice(0, start)}${block}${doc.slice(end + END_MARKER.length)}`;
}

export function runCronDocViewCli(argv: readonly string[], repoRoot = ROOT): void {
  const { values } = parseStrictCliArgs(argv, { options: { check: { type: "boolean" } } });
  if (writeCliHelpIfRequested(values, USAGE)) return;
  const path = resolve(repoRoot, DOC_PATH);
  const existing = readFileSync(path, "utf8");
  const next = replaceCronDocView(existing, renderCronDocView(loadCronDocTriggers(repoRoot)));
  if (values.check === true) {
    if (next !== existing) {
      throw new Error(`${DOC_PATH} cron view is out of date. Run node --import tsx scripts/maintenance/generate-cron-doc-view.ts`);
    }
    console.log(`${DOC_PATH} cron view is current`);
    return;
  }
  if (next === existing) {
    console.log(`${DOC_PATH} cron view unchanged`);
    return;
  }
  writeFileSync(path, next, "utf8");
  console.log(`${DOC_PATH} cron view regenerated`);
}

runDirectCli(import.meta.url, () => runCronDocViewCli(process.argv.slice(2)), {
  label: "cron-doc-view",
  usage: USAGE,
});
