import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { syncGeneratedArtifacts } from "../lib/generated-artifacts";
import { CASE_STUDY_LIST } from "../../src/lib/case-studies";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = join(
  __dirname,
  "../../src/lib/case-study-client-index.ts",
);
const CHECK_MODE = process.argv.includes("--check");

function stableStringify(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

const coinLookup = Object.fromEntries(
  CASE_STUDY_LIST.filter((study) => study.primaryCoinId).map((study) => [
    study.primaryCoinId!,
    {
      slug: study.slug,
      title: study.title,
      outcome: study.outcome,
    },
  ]),
);

const cemeteryLookup = Object.fromEntries(
  CASE_STUDY_LIST.filter((study) => study.cemeteryId).map((study) => [
    study.cemeteryId!,
    {
      slug: study.slug,
      title: study.title,
      outcome: study.outcome,
    },
  ]),
);

const eventWindows = CASE_STUDY_LIST.map((study) => ({
  slug: study.slug,
  primaryCoinId: study.primaryCoinId ?? null,
  relatedCoinIds: (study.relatedCoins ?? []).map((coin) => coin.coinId),
  startISO: study.eventWindow.startISO,
  endISO: study.eventWindow.endISO ?? null,
}));

const contents = `// Generated by scripts/maintenance/generate-case-study-client-index.ts.
// Do not edit by hand. Run \`npm run prebuild\` or \`tsx scripts/maintenance/generate-case-study-client-index.ts\`.

import type { CaseStudyOutcome } from "@/lib/case-study-outcomes";
import {
  resolveCaseStudySlugForEvent,
  type CaseStudyEventWindowResolverItem,
} from "@/lib/case-study-event-window";

export interface CaseStudyClientSummary {
  readonly slug: string;
  readonly title: string;
  readonly outcome: CaseStudyOutcome;
}

export const CASE_STUDY_CLIENT_BY_COIN_ID: Record<string, CaseStudyClientSummary> = ${stableStringify(coinLookup)};

/**
 * Client-safe cemetery-id -> study lookup. Mirrors the server registry without
 * importing the full article modules, so client surfaces can link to studies
 * without shipping long-form prose.
 */
export const CASE_STUDY_CLIENT_BY_CEMETERY_ID: Record<string, CaseStudyClientSummary> = ${stableStringify(cemeteryLookup)};

/**
 * Minimal event-window index used by chart annotations. Keep this module free
 * of imports from ./index or content modules; it is part of charted-page client
 * bundles.
 */
export const CASE_STUDY_EVENT_WINDOWS: readonly CaseStudyEventWindowResolverItem[] = ${stableStringify(eventWindows)};

/**
 * Resolve the case study that covers a charted event for \`coinId\` at \`tsMs\`
 * without importing article bodies into the client bundle.
 */
export function caseStudySlugForEvent(coinId: string, tsMs: number): string | undefined {
  return resolveCaseStudySlugForEvent(CASE_STUDY_EVENT_WINDOWS, coinId, tsMs);
}
`;

syncGeneratedArtifacts({
  artifacts: [{ path: OUTPUT, contents }],
  check: CHECK_MODE,
  staleMessage:
    "src/lib/case-study-client-index.ts is out of date. Run `tsx scripts/maintenance/generate-case-study-client-index.ts`.",
  currentMessage: "Case-study client index is current",
  writtenMessage: "Generated case-study client index",
});
