#!/usr/bin/env node
/** Projects curated labels from existing ownership references; never derives incident semantics from filenames. */
import { readFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseStrictCliArgs, runDirectCli, writeCliHelpIfRequested } from "../lib/cli-args.mjs";
import { getVerifiedDocFiles } from "../lib/doc-files.mts";
import type { DocOwnershipRegistry, DocReference } from "../lib/doc-ownership-registry.mts";
import { syncGeneratedArtifacts } from "../lib/generated-artifacts";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
export const START_MARKER = "<!-- GENERATED-START: runbook-index -->";
export const END_MARKER = "<!-- GENERATED-END: runbook-index -->";
const KINDS = ["symptom", "procedure", "reference"] as const;
export type RunbookIndexEntry = DocReference & { runbook: NonNullable<DocReference["runbook"]> };

export function isRunbookPath(path: string): boolean {
  return /^docs\/(?:runbooks|incident-response)\/.+\.md$/.test(path);
}

export function collectRunbookIndex(registry: DocOwnershipRegistry): RunbookIndexEntry[] {
  const entries = new Map<string, RunbookIndexEntry>();
  for (const mapping of registry.mappings ?? []) {
    for (const reference of [...mapping.docs, ...(mapping.background ?? [])]) {
      if (typeof reference === "string" || !reference.runbook) continue;
      const { label, kind } = reference.runbook;
      if (!isRunbookPath(reference.path) || typeof label !== "string" || !label.trim() ||
          !KINDS.includes(kind)) {
        throw new Error(`Invalid runbook index metadata: ${mapping.id}: ${reference.path}`);
      }
      if (entries.has(reference.path)) throw new Error(`Duplicate runbook index metadata: ${reference.path}`);
      entries.set(reference.path, { ...reference, runbook: { label: label.trim(), kind } });
    }
  }
  return [...entries.values()].sort((a, b) =>
    KINDS.indexOf(a.runbook.kind) - KINDS.indexOf(b.runbook.kind) ||
    (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
}

export function assertRunbookIndexComplete(entries: readonly RunbookIndexEntry[], verifiedPaths: readonly string[]): void {
  const corpus = new Set(verifiedPaths.filter(isRunbookPath));
  const indexed = new Set(entries.map((entry) => entry.path));
  const missing = [...corpus].filter((path) => !indexed.has(path)).sort();
  const stale = [...indexed].filter((path) => !corpus.has(path)).sort();
  if (missing.length || stale.length) {
    throw new Error(`Runbook index coverage mismatch:\nMissing labels: ${missing.join(", ")}\nStale labels: ${stale.join(", ")}`);
  }
}

export function renderRunbookIndex(entries: readonly RunbookIndexEntry[]): string {
  return [
    START_MARKER,
    "<!-- Generated by scripts/maintenance/generate-runbook-index.ts from docs/doc-ownership.json. Do not edit by hand. -->",
    "",
    "Complete coverage of `docs/runbooks/` and `docs/incident-response/`. Labels and applicability are curated in existing ownership references, not inferred from filenames. **Symptom** pages diagnose an observed failure; **procedure** pages guide an operator task; **reference** pages provide queries or configuration. Follow each page's prerequisites, authority and stop conditions before acting.",
    "",
    "| Applicability | Runbook |",
    "| --- | --- |",
    ...entries.map((entry) => {
      const label = entry.runbook.label.replace(/([\\[\]|])/g, "\\$1").replace(/[\r\n]+/g, " ");
      return `| ${entry.runbook.kind} | [${label}](./${entry.path.slice(5)}${entry.anchor ? `#${entry.anchor}` : ""}) |`;
    }),
    "",
    END_MARKER,
  ].join("\n");
}

export function replaceRunbookIndex(doc: string, block: string): string {
  const start = doc.indexOf(START_MARKER);
  const end = doc.indexOf(END_MARKER);
  if (start === -1 || end < start || doc.indexOf(START_MARKER, start + START_MARKER.length) !== -1 ||
      doc.indexOf(END_MARKER, end + END_MARKER.length) !== -1) {
    throw new Error("Expected exactly one valid runbook-index block in docs/README.md");
  }
  return `${doc.slice(0, start)}${block}${doc.slice(end + END_MARKER.length)}`;
}

export function main(argv: readonly string[] = process.argv.slice(2), root = REPO_ROOT): void {
  const { values } = parseStrictCliArgs(argv, { options: { check: { type: "boolean" } } });
  if (writeCliHelpIfRequested(values, "Usage: node --import tsx scripts/maintenance/generate-runbook-index.ts [--check]")) return;
  const registry = JSON.parse(readFileSync(resolve(root, "docs/doc-ownership.json"), "utf8")) as DocOwnershipRegistry;
  const entries = collectRunbookIndex(registry);
  assertRunbookIndexComplete(entries, getVerifiedDocFiles(root).map((path) => relative(root, path)));
  const output = resolve(root, "docs/README.md");
  syncGeneratedArtifacts({
    artifacts: [{ path: output, contents: replaceRunbookIndex(readFileSync(output, "utf8"), renderRunbookIndex(entries)) }],
    check: values.check === true,
    staleMessage: "docs/README.md runbook index is stale. Run `node --import tsx scripts/maintenance/generate-runbook-index.ts`.",
    currentMessage: "docs/README.md runbook index is current",
    writtenMessage: "docs/README.md runbook index generated",
  });
}

runDirectCli(import.meta.url, () => main());
