/**
 * Generate the report-card registry fingerprint.
 *
 * The fingerprint is a SHA-256 over the canonical identity projection of the
 * tracked/frozen/dead stablecoin registries, so Worker requests never serialize
 * and hash the full catalog at runtime.
 *
 * The registry itself is loaded through the normal TypeScript modules, so this
 * generator needs no child processes: `npm run check:stablecoin-data` remains
 * the authoritative validation and runs on its own in CI.
 */

import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { DEAD_STABLECOINS } from "@shared/lib/dead-stablecoins";
import { fingerprintReportCardRegistryRows } from "../lib/report-card-registry-fingerprint";
import { ACTIVE_STABLECOINS, FROZEN_STABLECOINS } from "@shared/lib/stablecoins/registry";
import { syncGeneratedArtifacts } from "../lib/generated-artifacts";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const OUTPUT_TS_REL = "shared/data/stablecoins/report-card-registry-fingerprint.generated.ts";
const OUTPUT_TS_ABS = resolve(REPO_ROOT, OUTPUT_TS_REL);
const CHECK_MODE = process.argv.includes("--check");

const fingerprint = fingerprintReportCardRegistryRows({
  activeStablecoins: ACTIVE_STABLECOINS,
  frozenStablecoins: FROZEN_STABLECOINS,
  deadStablecoins: DEAD_STABLECOINS,
});
const contents = `// @generated by scripts/maintenance/generate-report-card-registry-fingerprint.ts
// Do not edit by hand. Run \`npx tsx scripts/maintenance/generate-report-card-registry-fingerprint.ts\`
// after modifying the tracked or dead stablecoin registries.

/**
 * SHA-256 of the canonical report-card registry identity projection.
 * The generator computes this from the fully validated registry so Worker
 * requests do not serialize and hash the full catalog at runtime.
 */
export const REPORT_CARDS_REGISTRY_FINGERPRINT =
  "${fingerprint}";
`;

syncGeneratedArtifacts({
  artifacts: [{ path: OUTPUT_TS_ABS, contents }],
  check: CHECK_MODE,
  staleMessage: `${OUTPUT_TS_REL} is stale. Run: npx tsx scripts/maintenance/generate-report-card-registry-fingerprint.ts`,
  currentMessage: `${OUTPUT_TS_REL}: report-card registry fingerprint is current (${fingerprint}).`,
  writtenMessage: `${OUTPUT_TS_REL}: wrote report-card registry fingerprint (${fingerprint}).`,
});
