import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  type DepegEventSearchEntry,
} from "@shared/types/market";
import { selectStaticDepegEventPages } from "../../src/lib/depeg-event-config";
import { readDepegEventIndex, type DepegEventIndexEntry } from "../../src/lib/depeg-event-snapshot";
import { syncGeneratedArtifacts } from "../lib/generated-artifacts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = join(__dirname, "../../src/generated/depeg-event-search-data.json");
const OUTPUT_TYPES = join(__dirname, "../../src/generated/depeg-event-search-data.json.d.ts");
const RELATED_OUTPUT = join(__dirname, "../../src/generated/depeg-event-related-data.json");
const RELATED_OUTPUT_TYPES = join(__dirname, "../../src/generated/depeg-event-related-data.json.d.ts");
const CHECK_MODE = process.argv.includes("--check");
// Keep the command-palette bootstrap payload bounded; the client consumes every
// generated search entry and does not apply a second depeg-event result cap.
const SEARCH_EVENT_LIMIT = 10;

function buildClientEntries(events: readonly DepegEventIndexEntry[]): DepegEventSearchEntry[] {
  return [...selectStaticDepegEventPages(events)]
    .sort((a, b) => {
      if (b.startedAt !== a.startedAt) return b.startedAt - a.startedAt;
      return a.slug.localeCompare(b.slug);
    })
    .map((event) => ({
      slug: event.slug,
      stablecoinId: event.stablecoinId,
      symbol: event.symbol,
      pegType: event.pegType,
      direction: event.direction,
      peakDeviationBps: event.peakDeviationBps,
      startedAt: event.startedAt,
    }));
}

const relatedEntries = buildClientEntries(readDepegEventIndex({ missing: "throw" }));
const searchEntries = relatedEntries.slice(0, SEARCH_EVENT_LIMIT);

const clientIndexTypes = "readonly DepegEventSearchEntry[]";

syncGeneratedArtifacts({
  artifacts: [
    {
      path: OUTPUT,
      contents: JSON.stringify(searchEntries, null, 2) + "\n",
    },
    {
      path: OUTPUT_TYPES,
      contents: `/** Auto-generated by scripts/maintenance/generate-depeg-event-search-data.ts during prebuild. */
import type { DepegEventSearchEntry } from "@shared/types/market";

declare const depegEventSearchData: ${clientIndexTypes};
export default depegEventSearchData;
`,
    },
    {
      path: RELATED_OUTPUT,
      contents: JSON.stringify(relatedEntries, null, 2) + "\n",
    },
    {
      path: RELATED_OUTPUT_TYPES,
      contents: `/** Auto-generated by scripts/maintenance/generate-depeg-event-search-data.ts during prebuild. */
import type { DepegEventSearchEntry } from "@shared/types/market";

declare const depegEventRelatedData: ${clientIndexTypes};
export default depegEventRelatedData;
`,
    },
  ],
  check: CHECK_MODE,
  staleMessage:
    "src/generated/depeg-event-search-data.json is out of date. Run `tsx scripts/maintenance/generate-depeg-event-search-data.ts`.",
  currentMessage: `Depeg event client data is current for ${relatedEntries.length} events`,
  writtenMessage: `Generated depeg event client data for ${relatedEntries.length} events`,
});
