/**
 * Generate the report-card registry fingerprint.
 *
 * The fingerprint is a SHA-256 over the canonical identity projection of the
 * tracked/frozen/dead stablecoin registries, so Worker requests never serialize
 * and hash the full catalog at runtime.
 *
 * The registry itself is loaded through the normal TypeScript modules, so this
 * generator needs no child processes: `npm run check:stablecoin-data` remains
 * the authoritative validation and runs on its own in CI.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { DEAD_STABLECOINS } from "../../shared/lib/dead-stablecoins";
import { sha256Hex } from "../../shared/lib/sha256";
import { stableJsonStringifyV1 } from "../../shared/lib/stable-json";
import { ACTIVE_STABLECOINS, FROZEN_STABLECOINS } from "../../shared/lib/stablecoins/registry";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const OUTPUT_TS_REL = "shared/data/stablecoins/report-card-registry-fingerprint.generated.ts";
const OUTPUT_TS_ABS = resolve(REPO_ROOT, OUTPUT_TS_REL);
const CHECK_MODE = process.argv.includes("--check");

function computeReportCardRegistryFingerprint(): string {
  return sha256Hex(
    stableJsonStringifyV1({
      domain: "report-cards.fixed-input.registry.v1",
      activeStablecoins: [...ACTIVE_STABLECOINS].sort((left, right) => left.id.localeCompare(right.id)),
      frozenStablecoins: [...FROZEN_STABLECOINS].sort((left, right) => left.id.localeCompare(right.id)),
      deadStablecoins: [...DEAD_STABLECOINS].sort((left, right) => left.id.localeCompare(right.id)),
    }),
  );
}

const fingerprint = computeReportCardRegistryFingerprint();
const contents = `// @generated by scripts/maintenance/generate-report-card-registry-fingerprint.ts
// Do not edit by hand. Run \`npx tsx scripts/maintenance/generate-report-card-registry-fingerprint.ts\`
// after modifying the tracked or dead stablecoin registries.

/**
 * SHA-256 of the canonical report-card registry identity projection.
 * The generator computes this from the fully validated registry so Worker
 * requests do not serialize and hash the full catalog at runtime.
 */
export const REPORT_CARDS_REGISTRY_FINGERPRINT =
  "${fingerprint}";
`;

if (CHECK_MODE) {
  // Repo-owned generator only reads the checked-in fingerprint artifact.
  const current = existsSync(OUTPUT_TS_ABS) ? readFileSync(OUTPUT_TS_ABS, "utf8") : "";
  if (current !== contents) {
    console.error(
      `${OUTPUT_TS_REL} is stale. Run: npx tsx scripts/maintenance/generate-report-card-registry-fingerprint.ts`,
    );
    process.exit(1);
  }
  console.log(`${OUTPUT_TS_REL}: report-card registry fingerprint is current (${fingerprint}).`);
} else {
  // Repo-owned generator only writes the checked-in fingerprint artifact.
  mkdirSync(dirname(OUTPUT_TS_ABS), { recursive: true });
  writeFileSync(OUTPUT_TS_ABS, contents, "utf8");
  console.log(`${OUTPUT_TS_REL}: wrote report-card registry fingerprint (${fingerprint}).`);
}
