import { execFileSync } from "node:child_process";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { PUBLIC_DOCS } from "@shared/lib/public-docs";
import { syncGeneratedArtifacts } from "../lib/generated-artifacts";
import { assertFullGitHistory } from "../lib/git-history.mts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = join(__dirname, "../../src/generated/docs-metadata.json");
const OUTPUT_TYPES = join(__dirname, "../../src/generated/docs-metadata.json.d.ts");
const CHECK_MODE = process.argv.includes("--check");

interface DocMetadata {
  dateModified: string;
  dateCreated: string;
}

function gitLog(args: string[]): string {
  return execFileSync("git", args, { encoding: "utf-8" }).trim();
}

/** Committer time: `dateModified` is deployment modification time, not author clock time. */
function getLastCommitDate(filePath: string): string {
  const output = gitLog(["log", "--follow", "-1", "--format=%cI", "--", relative(process.cwd(), filePath)]);
  if (!output) {
    throw new Error(`[docs-metadata] no git history for ${filePath}`);
  }
  return output;
}

/** Author time: `dateCreated` is the authored-inception date of the document. */
function getFirstGitDate(filePath: string): string {
  const output = gitLog(["log", "--follow", "--reverse", "--format=%aI", "--", relative(process.cwd(), filePath)])
    .split(/\r?\n/)
    .find(Boolean);
  if (!output) {
    throw new Error(`[docs-metadata] no git creation history for ${filePath}`);
  }
  return output;
}

const metadata: Record<string, DocMetadata> = {};

assertFullGitHistory("docs-metadata");

for (const doc of PUBLIC_DOCS) {
  const filePath = join(__dirname, "..", "..", "docs", doc.source);
  metadata[doc.slug] = {
    dateModified: getLastCommitDate(filePath),
    dateCreated: getFirstGitDate(filePath),
  };
}

syncGeneratedArtifacts({
  artifacts: [
    { path: OUTPUT, contents: JSON.stringify(metadata, null, 2) + "\n" },
    {
      path: OUTPUT_TYPES,
      contents: `/** Auto-generated by scripts/maintenance/generate-docs-metadata.ts during prebuild. */
declare const docsMetadata: Record<string, { dateModified: string; dateCreated: string }>;
export default docsMetadata;
`,
    },
  ],
  check: CHECK_MODE,
  staleMessage:
    "src/generated/docs-metadata.json is out of date. Run `tsx scripts/maintenance/generate-docs-metadata.ts`.",
  currentMessage: `Docs metadata is current for ${PUBLIC_DOCS.length} public docs`,
  writtenMessage: `Generated docs metadata for ${PUBLIC_DOCS.length} public docs`,
});
