import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { DepegEvent } from "../../shared/types/market";
import { hasDedicatedDepegEventPage } from "../../src/app/depeg/[event]/config";
import { syncGeneratedArtifacts } from "../lib/generated-artifacts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE = join(__dirname, "../../data/depeg-events.json");
const OUTPUT = join(__dirname, "../../src/generated/depeg-event-search-data.json");
const OUTPUT_TYPES = join(__dirname, "../../src/generated/depeg-event-search-data.json.d.ts");
const CHECK_MODE = process.argv.includes("--check");
const SEARCH_EVENT_LIMIT = 10;

interface DepegEventEntry extends DepegEvent {
  slug: string;
}

interface DepegEventSearchEntry {
  slug: string;
  stablecoinId: string;
  symbol: string;
  pegType: string;
  direction: "above" | "below";
  peakDeviationBps: number;
  startedAt: number;
}

function readDepegEvents(): readonly DepegEventEntry[] {
  return JSON.parse(readFileSync(SOURCE, "utf8")) as DepegEventEntry[];
}

function buildSearchEntries(events: readonly DepegEventEntry[]): DepegEventSearchEntry[] {
  return events
    .filter(hasDedicatedDepegEventPage)
    .sort((a, b) => {
      if (b.startedAt !== a.startedAt) return b.startedAt - a.startedAt;
      return a.slug.localeCompare(b.slug);
    })
    .slice(0, SEARCH_EVENT_LIMIT)
    .map((event) => ({
      slug: event.slug,
      stablecoinId: event.stablecoinId,
      symbol: event.symbol,
      pegType: event.pegType,
      direction: event.direction,
      peakDeviationBps: event.peakDeviationBps,
      startedAt: event.startedAt,
    }));
}

const entries = buildSearchEntries(readDepegEvents());

syncGeneratedArtifacts({
  artifacts: [
    {
      path: OUTPUT,
      contents: JSON.stringify(entries, null, 2) + "\n",
    },
    {
      path: OUTPUT_TYPES,
      contents: `/** Auto-generated by scripts/maintenance/generate-depeg-event-search-data.ts during prebuild. */
declare const depegEventSearchData: readonly {
  slug: string;
  stablecoinId: string;
  symbol: string;
  pegType: string;
  direction: "above" | "below";
  peakDeviationBps: number;
  startedAt: number;
}[];
export default depegEventSearchData;
`,
    },
  ],
  check: CHECK_MODE,
  staleMessage:
    "src/generated/depeg-event-search-data.json is out of date. Run `tsx scripts/maintenance/generate-depeg-event-search-data.ts`.",
  currentMessage: `Depeg event search data is current for ${entries.length} events`,
  writtenMessage: `Generated depeg event search data for ${entries.length} events`,
});
