import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { MetadataRoute } from "next";
import { PUBLIC_DATASET_TOPICS } from "@shared/lib/api-endpoints/datasets";
import { getActiveChainIds } from "@shared/lib/chains";
import { TRACKED_STABLECOINS } from "@shared/lib/stablecoins/registry";
import { MECHANISM_ARCHETYPE_VALUES } from "@shared/types/core";
import { CASE_STUDY_ORDER } from "@/app/learn/case-studies/content";
import { STATIC_COMPARISON_PAGES } from "@/lib/compare-pages";
import { ACTIVE_PEGS, PEG_SLUGS } from "@/lib/peg-landing";
import { ALL_STABLECOIN_TAXONOMY_PAGES } from "@/lib/stablecoin-taxonomy";
import { buildStablecoinUrl } from "@/lib/urls";
import { SITE_ORIGIN as SITE_URL } from "@shared/lib/runtime-origins";
import { PUBLIC_DOCS } from "@shared/lib/public-docs";
import digests from "../../data/digests.json";
import sitemapDates from "@/generated/sitemap-dates.json";
import docsMetadata from "@/generated/docs-metadata.json";
import costsData from "@shared/data/funding/costs.json";
import donationsData from "@shared/data/funding/donations.json";
import type { CostsFile, DonationsFile } from "@shared/lib/funding/types";
import { selectIndexableDepegEvents, selectStaticDepegEventPages } from "@/app/depeg/[event]/config";

export const dynamic = "force-static";

/**
 * Git-derived last-edited dates for static pages (avoid misleading Google with build-time dates).
 * Auto-generated by `scripts/maintenance/generate-sitemap-dates.ts` during prebuild.
 */
const LAST_EDITED: Record<string, string> = sitemapDates;
const fundingCosts = costsData as CostsFile;
const fundingDonations = donationsData as DonationsFile;

interface DepegEventSitemapEntry {
  slug: string;
  startedAt: number;
  endedAt: number | null;
  peakDeviationBps: number;
}

function readDepegEventEntries(): readonly DepegEventSitemapEntry[] {
  const filePath = join(process.cwd(), "data/depeg-events.json");
  return JSON.parse(readFileSync(filePath, "utf8")) as DepegEventSitemapEntry[];
}

const depegEventEntries = selectStaticDepegEventPages(readDepegEventEntries());
const indexableDepegEventEntries = selectIndexableDepegEvents(depegEventEntries);

/** Safely resolve a last-edited date, falling back to build time for unmapped routes. */
function lastEdited(path: string): Date {
  const iso = LAST_EDITED[path];
  return iso ? new Date(iso) : new Date();
}

function fundingLastModified(): Date {
  return new Date(
    Math.max(
      lastEdited("/funding/").getTime(),
      fundingCosts.last_reviewed_at * 1000,
      fundingDonations.last_updated_at * 1000,
    ),
  );
}

function comparisonLastModified(page: (typeof STATIC_COMPARISON_PAGES)[number]): Date {
  return new Date(
    Math.max(
      lastEdited(buildStablecoinUrl(page.left.id)).getTime(),
      lastEdited(buildStablecoinUrl(page.right.id)).getTime(),
    ),
  );
}

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  const staticPages: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/`,
      lastModified: now,
      changeFrequency: "hourly",
      priority: 1.0,
    },
    {
      url: `${SITE_URL}/coverage/`,
      lastModified: lastEdited("/coverage/"),
      changeFrequency: "weekly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/alt-pegs/`,
      lastModified: lastEdited("/alt-pegs/"),
      changeFrequency: "daily",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/start/`,
      lastModified: lastEdited("/start/"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/freezewatch/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/depeg/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/cemetery/`,
      lastModified: lastEdited("/cemetery/"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/compare/`,
      lastModified: lastEdited("/compare/"),
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/liquidity/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/upcoming/`,
      lastModified: lastEdited("/upcoming/"),
      changeFrequency: "daily",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/digest/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/safety-scores/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/stability-index/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/dependency-map/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/yield/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/screener/`,
      lastModified: lastEdited("/screener/"),
      changeFrequency: "daily",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/funding/`,
      lastModified: fundingLastModified(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: `${SITE_URL}/status/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/flows/`,
      lastModified: lastEdited("/flows/"),
      changeFrequency: "daily",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/timeline/`,
      lastModified: now,
      changeFrequency: "hourly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/compliance/`,
      lastModified: lastEdited("/compliance/"),
      changeFrequency: "weekly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/pharoswatchbot/`,
      lastModified: lastEdited("/pharoswatchbot/"),
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/methodology/`,
      lastModified: lastEdited("/methodology/"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/methodology/scoring-changelog/`,
      lastModified: lastEdited("/methodology/scoring-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/depeg-changelog/`,
      lastModified: lastEdited("/methodology/depeg-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/depeg-resolver-changelog/`,
      lastModified: lastEdited("/methodology/depeg-resolver-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/blacklist-tracker-changelog/`,
      lastModified: lastEdited("/methodology/blacklist-tracker-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/liquidity-score-changelog/`,
      lastModified: lastEdited("/methodology/liquidity-score-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/stability-index-changelog/`,
      lastModified: lastEdited("/methodology/stability-index-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/mint-burn-flow-changelog/`,
      lastModified: lastEdited("/methodology/mint-burn-flow-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/yield-changelog/`,
      lastModified: lastEdited("/methodology/yield-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/pricing-pipeline-changelog/`,
      lastModified: lastEdited("/methodology/pricing-pipeline-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/chain-health-changelog/`,
      lastModified: lastEdited("/methodology/chain-health-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/changelog/`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: `${SITE_URL}/about/`,
      lastModified: lastEdited("/about/"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: `${SITE_URL}/about/api/`,
      lastModified: lastEdited("/about/api/"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: `${SITE_URL}/about/editorial/`,
      lastModified: lastEdited("/about/editorial/"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: `${SITE_URL}/about/principles/`,
      lastModified: lastEdited("/about/principles/"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: `${SITE_URL}/about/style/`,
      lastModified: lastEdited("/about/style/"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: `${SITE_URL}/about/bluechip/`,
      lastModified: lastEdited("/about/bluechip/"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: `${SITE_URL}/learn/`,
      lastModified: lastEdited("/learn/"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/learn/glossary/`,
      lastModified: lastEdited("/learn/glossary/"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: `${SITE_URL}/sitemap-tree/`,
      lastModified: lastEdited("/sitemap-tree/"),
      changeFrequency: "monthly",
      priority: 0.3,
    },
    {
      url: `${SITE_URL}/api/`,
      // eslint-disable-next-line no-restricted-syntax -- "/api/" here is the public docs page slug, not an API endpoint; LAST_EDITED is keyed by site URLs.
      lastModified: lastEdited("/api/"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: `${SITE_URL}/stablecoins/`,
      lastModified: lastEdited("/stablecoins/"),
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/stablecoins/backing/`,
      lastModified: lastEdited("/stablecoins/backing/"),
      changeFrequency: "weekly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/stablecoins/governance/`,
      lastModified: lastEdited("/stablecoins/governance/"),
      changeFrequency: "weekly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/stablecoins/infrastructure/`,
      lastModified: lastEdited("/stablecoins/infrastructure/"),
      changeFrequency: "weekly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/privacy/`,
      lastModified: lastEdited("/privacy/"),
      changeFrequency: "yearly",
      priority: 0.3,
    },
  ];

  const stablecoinPages: MetadataRoute.Sitemap = TRACKED_STABLECOINS.map((coin) => ({
    url: `${SITE_URL}${buildStablecoinUrl(coin.id)}`,
    lastModified: lastEdited(buildStablecoinUrl(coin.id)),
    changeFrequency: "daily" as const,
    priority: 0.6,
  }));

  const chainPages: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/chains/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    ...getActiveChainIds().map((chainId) => ({
      url: `${SITE_URL}/chains/${chainId}/`,
      lastModified: now,
      changeFrequency: "daily" as const,
      priority: 0.5,
    })),
  ];

  const pegPages: MetadataRoute.Sitemap = ACTIVE_PEGS.map((peg) => ({
    url: `${SITE_URL}/stablecoins/${PEG_SLUGS[peg]}/`,
    lastModified: now,
    changeFrequency: "daily" as const,
    priority: 0.7,
  }));

  const digestPages: MetadataRoute.Sitemap = digests.map((d) => ({
    url: `${SITE_URL}/digest/${d.date}/`,
    lastModified: new Date(d.generatedAt * 1000),
    changeFrequency: "never" as const,
    priority: 0.5,
  }));

  const depegEventPages: MetadataRoute.Sitemap = indexableDepegEventEntries.map((e) => ({
    url: `${SITE_URL}/depeg/${e.slug}/`,
    lastModified: new Date((e.endedAt ?? e.startedAt) * 1000),
    changeFrequency: (e.endedAt ? "never" : "daily") as "never" | "daily",
    priority: 0.55,
  }));

  const taxonomyPages: MetadataRoute.Sitemap = ALL_STABLECOIN_TAXONOMY_PAGES.map((page) => ({
    url: `${SITE_URL}${page.href}`,
    lastModified: lastEdited(page.href),
    changeFrequency: "weekly" as const,
    priority: 0.7,
  }));

  const learnMechanismPages: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/learn/mechanisms/`,
      lastModified: lastEdited("/learn/mechanisms/"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    ...MECHANISM_ARCHETYPE_VALUES.map((archetype) => ({
      url: `${SITE_URL}/learn/mechanisms/${archetype}/`,
      lastModified: lastEdited(`/learn/mechanisms/${archetype}/`),
      changeFrequency: "monthly" as const,
      priority: 0.7,
    })),
  ];

  const learnCaseStudyPages: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/learn/case-studies/`,
      lastModified: lastEdited("/learn/case-studies/"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    ...CASE_STUDY_ORDER.map((slug) => ({
      url: `${SITE_URL}/learn/case-studies/${slug}/`,
      lastModified: lastEdited(`/learn/case-studies/${slug}/`),
      changeFrequency: "monthly" as const,
      priority: 0.7,
    })),
  ];

  const comparisonPages: MetadataRoute.Sitemap = STATIC_COMPARISON_PAGES.map((page) => ({
    url: `${SITE_URL}${page.href}`,
    lastModified: comparisonLastModified(page),
    changeFrequency: "monthly" as const,
    priority: 0.6,
  }));

  const docsIndex: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/docs/`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.6,
    },
  ];

  const docsPages: MetadataRoute.Sitemap = PUBLIC_DOCS.map((doc) => {
    const meta = (docsMetadata as Record<string, { dateModified: string }>)[doc.slug];
    return {
      url: `${SITE_URL}/docs/${doc.slug}/`,
      lastModified: meta ? new Date(meta.dateModified) : now,
      changeFrequency: "monthly" as const,
      priority: 0.5,
    };
  });

  // RSS feeds live at /feed/<topic>.xml as XML (Content-Type:
  // application/rss+xml). They're discoverable via the <link rel="alternate">
  // tags in layout.tsx and the footer "Subscribe" cluster; sitemap inclusion
  // would fail the SEO check (no HTML artifact at those paths).
  const feedPages: MetadataRoute.Sitemap = [];

  // Public dataset + Sheets mirrors live at non-HTML URLs (.csv/.json),
  // so sitemap inclusion isn't appropriate — the SEO check rejects URLs
  // without HTML artifacts. They remain discoverable via /llms.txt,
  // /about/api/, and direct linking.
  const datasetPages: MetadataRoute.Sitemap = PUBLIC_DATASET_TOPICS.flatMap(() => []);

  return [
    ...staticPages,
    ...stablecoinPages,
    ...chainPages,
    ...pegPages,
    ...taxonomyPages,
    ...learnMechanismPages,
    ...learnCaseStudyPages,
    ...comparisonPages,
    ...digestPages,
    ...depegEventPages,
    ...docsIndex,
    ...docsPages,
    ...feedPages,
    ...datasetPages,
  ];
}
