import type { MetadataRoute } from "next";
import { getActiveChainIds } from "@shared/lib/chains";
import { TRACKED_STABLECOINS } from "@shared/lib/stablecoins";
import { STATIC_COMPARISON_PAGES } from "@/lib/compare-pages";
import { ACTIVE_PEGS, PEG_SLUGS } from "@/lib/peg-landing";
import { ALL_STABLECOIN_TAXONOMY_PAGES } from "@/lib/stablecoin-taxonomy";
import { buildStablecoinUrl } from "@/lib/urls";
import { SITE_URL } from "@/lib/site-config";
import digests from "../../data/digests.json";
import sitemapDates from "@/generated/sitemap-dates.json";

export const dynamic = "force-static";

/**
 * Git-derived last-edited dates for static pages (avoid misleading Google with build-time dates).
 * Auto-generated by `scripts/generate-sitemap-dates.ts` during prebuild.
 */
const LAST_EDITED: Record<string, string> = sitemapDates;

/** Safely resolve a last-edited date, falling back to build time for unmapped routes. */
function lastEdited(path: string): Date {
  const iso = LAST_EDITED[path];
  return iso ? new Date(iso) : new Date();
}

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  const staticPages: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/`,
      lastModified: now,
      changeFrequency: "hourly",
      priority: 1.0,
    },
    {
      url: `${SITE_URL}/coverage/`,
      lastModified: lastEdited("/coverage/"),
      changeFrequency: "weekly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/start/`,
      lastModified: lastEdited("/start/"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/blacklist/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/depeg/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/cemetery/`,
      lastModified: lastEdited("/cemetery/"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/liquidity/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/portfolio/`,
      lastModified: lastEdited("/portfolio/"),
      changeFrequency: "daily",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/upcoming/`,
      lastModified: lastEdited("/upcoming/"),
      changeFrequency: "daily",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/digest/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/safety-scores/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/stability-index/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/dependency-map/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/yield/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/status/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/flows/`,
      lastModified: lastEdited("/flows/"),
      changeFrequency: "daily",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/telegram/`,
      lastModified: lastEdited("/telegram/"),
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/methodology/`,
      lastModified: lastEdited("/methodology/"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/methodology/scoring-changelog/`,
      lastModified: lastEdited("/methodology/scoring-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/depeg-changelog/`,
      lastModified: lastEdited("/methodology/depeg-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/blacklist-tracker-changelog/`,
      lastModified: lastEdited("/methodology/blacklist-tracker-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/liquidity-score-changelog/`,
      lastModified: lastEdited("/methodology/liquidity-score-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/stability-index-changelog/`,
      lastModified: lastEdited("/methodology/stability-index-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/mint-burn-flow-changelog/`,
      lastModified: lastEdited("/methodology/mint-burn-flow-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/yield-changelog/`,
      lastModified: lastEdited("/methodology/yield-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/pricing-pipeline-changelog/`,
      lastModified: lastEdited("/methodology/pricing-pipeline-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/methodology/chain-health-changelog/`,
      lastModified: lastEdited("/methodology/chain-health-changelog/"),
      changeFrequency: "monthly",
      priority: 0.4,
    },
    {
      url: `${SITE_URL}/changelog/`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: `${SITE_URL}/about/`,
      lastModified: lastEdited("/about/"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: `${SITE_URL}/about/api/`,
      lastModified: lastEdited("/about/api/"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: `${SITE_URL}/privacy/`,
      lastModified: lastEdited("/privacy/"),
      changeFrequency: "yearly",
      priority: 0.3,
    },
  ];

  const stablecoinPages: MetadataRoute.Sitemap = TRACKED_STABLECOINS.map(
    (coin) => ({
      url: `${SITE_URL}${buildStablecoinUrl(coin.id)}`,
      lastModified: now,
      changeFrequency: "daily" as const,
      priority: 0.6,
    })
  );

  const chainPages: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/chains/`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    ...getActiveChainIds().map((chainId) => ({
      url: `${SITE_URL}/chains/${chainId}/`,
      lastModified: now,
      changeFrequency: "daily" as const,
      priority: 0.5,
    })),
  ];

  const pegPages: MetadataRoute.Sitemap = ACTIVE_PEGS.map((peg) => ({
    url: `${SITE_URL}/stablecoins/${PEG_SLUGS[peg]}/`,
    lastModified: now,
    changeFrequency: "daily" as const,
    priority: 0.7,
  }));

  const digestPages: MetadataRoute.Sitemap = digests.map((d) => ({
    url: `${SITE_URL}/digest/${d.date}/`,
    lastModified: new Date(d.generatedAt * 1000),
    changeFrequency: "never" as const,
    priority: 0.5,
  }));

  const taxonomyPages: MetadataRoute.Sitemap = ALL_STABLECOIN_TAXONOMY_PAGES.map((page) => ({
    url: `${SITE_URL}${page.href}`,
    lastModified: lastEdited(page.href),
    changeFrequency: "weekly" as const,
    priority: 0.7,
  }));

  const comparisonPages: MetadataRoute.Sitemap = STATIC_COMPARISON_PAGES.map((page) => ({
    url: `${SITE_URL}${page.href}`,
    lastModified: new Date("2026-03-07"),
    changeFrequency: "monthly" as const,
    priority: 0.6,
  }));

  return [...staticPages, ...stablecoinPages, ...chainPages, ...pegPages, ...taxonomyPages, ...comparisonPages, ...digestPages];
}
