import type { MetadataRoute } from "next";
import { getActiveChainIds } from "@shared/lib/chains";
import { TRACKED_STABLECOINS } from "@shared/lib/stablecoins/registry";
import { MECHANISM_ARCHETYPE_VALUES } from "@shared/types/core";
import { CASE_STUDY_LIST } from "@/lib/case-studies";
import { STATIC_COMPARISON_PAGES } from "@/lib/compare-pages";
import { ACTIVE_PEGS, PEG_SLUGS } from "@/lib/peg-landing";
import { ALL_STABLECOIN_TAXONOMY_PAGES } from "@/lib/stablecoin-taxonomy";
import { buildStablecoinUrl } from "@shared/lib/urls";
import { SITE_ORIGIN as SITE_URL } from "@shared/lib/runtime-origins";
import { PUBLIC_DOCS } from "@shared/lib/public-docs";
import {
  METHODOLOGY_CHANGELOG_SITEMAP_PATHS as SHARED_METHODOLOGY_CHANGELOG_SITEMAP_PATHS,
} from "@shared/lib/methodology-versions/registry";
import { DIGEST_ENTRIES } from "@/lib/digest-registry";
import sitemapDates from "@/generated/sitemap-dates.json";
import docsMetadata from "@/generated/docs-metadata.json";
import costsData from "@shared/data/funding/costs.json";
import donationsData from "@shared/data/funding/donations.json";
import type { CostsFile, DonationsFile } from "@shared/lib/funding/types";
import { changelogs } from "@/data/changelogs";
import { BLOG_POSTS } from "@/data/blog";
import {
  COLLIDING_DEPEG_EVENT_SLUGS,
  DEPEG_COLLISION_CONTENT_REVISED_AT_SECONDS,
  DEPEG_EVENT_ENTRIES,
} from "@/lib/depeg-event-page-data";

export const dynamic = "force-static";

/**
 * Git-derived last-edited dates for static pages (avoid misleading Google with build-time dates).
 * Auto-generated by `scripts/maintenance/generate-sitemap-dates.ts` during prebuild.
 */
const LAST_EDITED: Record<string, string> = sitemapDates;
const fundingCosts = costsData as CostsFile;
const fundingDonations = donationsData as DonationsFile;

type SitemapChangeFrequency = NonNullable<MetadataRoute.Sitemap[number]["changeFrequency"]>;
type StaticPageSpec = readonly [
  path: string,
  changeFrequency: SitemapChangeFrequency,
  priority: number,
  resolveLastModified?: (path: string) => Date,
];

export const METHODOLOGY_CHANGELOG_SITEMAP_PATHS = SHARED_METHODOLOGY_CHANGELOG_SITEMAP_PATHS;


/** Resolve a Git-derived edit date without turning an unmapped route into a deploy-time change. */
function lastEdited(path: string, fallbackPath = "/"): Date {
  const iso = LAST_EDITED[path] ?? LAST_EDITED[fallbackPath];
  return new Date(iso);
}

function fundingLastModified(): Date {
  return new Date(
    Math.max(
      lastEdited("/funding/").getTime(),
      fundingCosts.last_reviewed_at * 1000,
      fundingDonations.last_updated_at * 1000,
    ),
  );
}

/** /changelog/ moves when a new weekly entry lands, not with the daily data snapshot. */
function changelogLastModified(): Date {
  return new Date(
    Math.max(
      lastEdited("/changelog/").getTime(),
      ...changelogs.map((entry) => new Date(entry.dateRange.to).getTime()),
    ),
  );
}

/** /docs/ moves when a published doc is edited, not with the daily data snapshot. */
function docsIndexLastModified(): Date {
  const metadata = docsMetadata as Record<string, { dateModified: string }>;
  return new Date(
    Math.max(
      lastEdited("/docs/").getTime(),
      ...PUBLIC_DOCS.map((doc) => {
        const meta = metadata[doc.slug];
        return meta ? new Date(meta.dateModified).getTime() : 0;
      }),
    ),
  );
}

function comparisonLastModified(page: (typeof STATIC_COMPARISON_PAGES)[number]): Date {
  return new Date(
    Math.max(
      lastEdited(buildStablecoinUrl(page.left.id)).getTime(),
      lastEdited(buildStablecoinUrl(page.right.id)).getTime(),
    ),
  );
}

function buildStaticSitemapEntries(
  specs: readonly StaticPageSpec[],
  defaultLastModified: (path: string) => Date,
): MetadataRoute.Sitemap {
  return specs.map(([path, changeFrequency, priority, resolveLastModified = defaultLastModified]) => ({
    url: `${SITE_URL}${path}`,
    lastModified: resolveLastModified(path),
    changeFrequency,
    priority,
  }));
}

export default function sitemap(): MetadataRoute.Sitemap {
  // Live-data routes bake fresh data at deploy time, but stamping build-time
  // `now` on every deploy claims constant content change. Use the freshest
  // data-snapshot timestamp the build actually baked in (latest digest
  // publication or depeg event — moves daily), floored by the route's own
  // git-derived edit date.
  const latestDataSnapshotMs = Math.max(
    0,
    ...DIGEST_ENTRIES.map((d) => d.generatedAt * 1000),
    ...DEPEG_EVENT_ENTRIES.map((e) => (e.endedAt ?? e.startedAt) * 1000),
  );
  const liveDataLastModified = (path: string): Date => {
    const editedMs = LAST_EDITED[path] ? new Date(LAST_EDITED[path]).getTime() : 0;
    const ms = Math.max(editedMs, latestDataSnapshotMs);
    return ms > 0 ? new Date(ms) : lastEdited(path);
  };

  const staticPageSpecs = [
    ["/", "hourly", 1.0, liveDataLastModified],
    ["/coverage/", "weekly", 0.6],
    ["/alt-pegs/", "daily", 0.7],
    ["/start/", "monthly", 0.6],
    ["/freezewatch/", "daily", 0.85, liveDataLastModified],
    ["/depeg/", "daily", 0.8, liveDataLastModified],
    ["/cemetery/", "monthly", 0.7],
    ["/compare/", "weekly", 0.7],
    ["/liquidity/", "daily", 0.8, liveDataLastModified],
    ["/upcoming/", "daily", 0.6],
    ["/digest/", "daily", 0.6, liveDataLastModified],
    ["/safety-scores/", "daily", 0.8, liveDataLastModified],
    ["/stability-index/", "daily", 0.8, liveDataLastModified],
    ["/dependency-map/", "daily", 0.7, liveDataLastModified],
    ["/yield/", "daily", 0.7, liveDataLastModified],
    ["/screener/", "daily", 0.7],
    ["/funding/", "weekly", 0.5, fundingLastModified],
    ["/status/", "daily", 0.4, liveDataLastModified],
    ["/flows/", "daily", 0.7],
    ["/timeline/", "hourly", 0.75, liveDataLastModified],
    ["/compliance/", "weekly", 0.6],
    ["/pharoswatchbot/", "weekly", 0.7],
    ["/methodology/", "monthly", 0.6],
  ] as const satisfies readonly StaticPageSpec[];

  const referencePageSpecs = [
    ["/changelog/", "weekly", 0.5, changelogLastModified],
    ["/blog/", "weekly", 0.6],
    ["/about/", "monthly", 0.5],
    ["/about/api/", "monthly", 0.5],
    ["/about/bluechip/", "monthly", 0.5],
    ["/learn/", "monthly", 0.5],
    ["/learn/glossary/", "monthly", 0.5],
    ["/sitemap-tree/", "monthly", 0.3],
    ["/api/", "monthly", 0.5],
    ["/stablecoins/", "weekly", 0.7],
    ["/stablecoins/backing/", "weekly", 0.6],
    ["/stablecoins/governance/", "weekly", 0.6],
    ["/stablecoins/infrastructure/", "weekly", 0.6],
    ["/privacy/", "yearly", 0.3],
  ] as const satisfies readonly StaticPageSpec[];

  const staticPages: MetadataRoute.Sitemap = [
    ...buildStaticSitemapEntries(staticPageSpecs, lastEdited),
    ...METHODOLOGY_CHANGELOG_SITEMAP_PATHS.map((path) => ({
      url: `${SITE_URL}${path}`,
      lastModified: lastEdited(path),
      changeFrequency: "monthly" as const,
      priority: 0.4,
    })),
    ...buildStaticSitemapEntries(referencePageSpecs, lastEdited),
  ];

  const stablecoinPages: MetadataRoute.Sitemap = TRACKED_STABLECOINS.map((coin) => ({
    url: `${SITE_URL}${buildStablecoinUrl(coin.id)}`,
    lastModified: lastEdited(buildStablecoinUrl(coin.id)),
    changeFrequency: "daily" as const,
    priority: 0.6,
  }));

  const chainPages: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/chains/`,
      lastModified: liveDataLastModified("/chains/"),
      changeFrequency: "daily",
      priority: 0.8,
    },
    ...getActiveChainIds().map((chainId) => ({
      url: `${SITE_URL}/chains/${chainId}/`,
      lastModified: new Date(
        Math.max(
          lastEdited(`/chains/${chainId}/`, "/chains/").getTime(),
          latestDataSnapshotMs,
        ),
      ),
      changeFrequency: "daily" as const,
      priority: 0.5,
    })),
  ];

  const pegPages: MetadataRoute.Sitemap = ACTIVE_PEGS.map((peg) => ({
    url: `${SITE_URL}/stablecoins/${PEG_SLUGS[peg]}/`,
    lastModified: lastEdited(`/stablecoins/${PEG_SLUGS[peg]}/`, "/stablecoins/"),
    changeFrequency: "daily" as const,
    priority: 0.7,
  }));

  const digestPages: MetadataRoute.Sitemap = DIGEST_ENTRIES.map((d) => ({
    url: `${SITE_URL}/digest/${d.date}/`,
    lastModified: new Date(d.generatedAt * 1000),
    changeFrequency: "never" as const,
    priority: 0.5,
  }));

  const depegEventPages: MetadataRoute.Sitemap = DEPEG_EVENT_ENTRIES.map((e) => ({
    url: `${SITE_URL}/depeg/${e.slug}/`,
    lastModified: new Date(
      Math.max(
        e.endedAt ?? e.startedAt,
        COLLIDING_DEPEG_EVENT_SLUGS.has(e.slug) ? DEPEG_COLLISION_CONTENT_REVISED_AT_SECONDS : 0,
      ) * 1000,
    ),
    changeFrequency: (e.endedAt ? "never" : "daily") as "never" | "daily",
    priority: 0.55,
  }));

  const taxonomyPages: MetadataRoute.Sitemap = ALL_STABLECOIN_TAXONOMY_PAGES.map((page) => ({
    url: `${SITE_URL}${page.href}`,
    lastModified: lastEdited(page.href),
    changeFrequency: "weekly" as const,
    priority: 0.7,
  }));

  const learnMechanismPages: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/learn/mechanisms/`,
      lastModified: lastEdited("/learn/mechanisms/"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    ...MECHANISM_ARCHETYPE_VALUES.map((archetype) => ({
      url: `${SITE_URL}/learn/mechanisms/${archetype}/`,
      lastModified: lastEdited(`/learn/mechanisms/${archetype}/`, "/learn/mechanisms/"),
      changeFrequency: "monthly" as const,
      priority: 0.7,
    })),
  ];

  const learnCaseStudyPages: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/learn/case-studies/`,
      lastModified: lastEdited("/learn/case-studies/"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    ...CASE_STUDY_LIST.map((study) => ({
      url: `${SITE_URL}/learn/case-studies/${study.slug}/`,
      lastModified: lastEdited(`/learn/case-studies/${study.slug}/`),
      changeFrequency: "monthly" as const,
      priority: 0.7,
    })),
  ];

  // /blog/ hub lives in referencePageSpecs above; these are the post detail
  // pages. Per-post lastmod comes from the git-derived sitemap-dates entry
  // (see addBlogDates in generate-sitemap-dates.ts).
  const blogPages: MetadataRoute.Sitemap = BLOG_POSTS.map((post) => ({
    url: `${SITE_URL}/blog/${post.slug}/`,
    lastModified: lastEdited(`/blog/${post.slug}/`),
    changeFrequency: "monthly" as const,
    priority: 0.5,
  }));

  const comparisonPages: MetadataRoute.Sitemap = STATIC_COMPARISON_PAGES.map((page) => ({
    url: `${SITE_URL}${page.href}`,
    lastModified: comparisonLastModified(page),
    changeFrequency: "monthly" as const,
    priority: 0.6,
  }));

  const docsIndex: MetadataRoute.Sitemap = [
    {
      url: `${SITE_URL}/docs/`,
      lastModified: docsIndexLastModified(),
      changeFrequency: "monthly",
      priority: 0.6,
    },
  ];

  const docsPages: MetadataRoute.Sitemap = PUBLIC_DOCS.map((doc) => {
    const meta = (docsMetadata as Record<string, { dateModified: string }>)[doc.slug];
    return {
      url: `${SITE_URL}/docs/${doc.slug}/`,
      lastModified: meta ? new Date(meta.dateModified) : lastEdited("/docs/"),
      changeFrequency: "monthly" as const,
      priority: 0.5,
    };
  });

  // RSS feeds (/feed/<topic>.xml) and public datasets (.csv/.json) are excluded
  // from the sitemap — both are non-HTML URLs and the SEO check rejects entries
  // without HTML artifacts. They remain discoverable via <link rel="alternate">
  // tags, the footer "Subscribe" cluster, /llms.txt, and /about/api/.

  return [
    ...staticPages,
    ...stablecoinPages,
    ...chainPages,
    ...pegPages,
    ...taxonomyPages,
    ...learnMechanismPages,
    ...learnCaseStudyPages,
    ...blogPages,
    ...comparisonPages,
    ...digestPages,
    ...depegEventPages,
    ...docsIndex,
    ...docsPages,
  ];
}
