import { chainConfig } from "./blacklist-contracts";
import type {
  MintBurnBridgeDetectionConfig,
  MintBurnContractConfigSpec,
} from "./mint-burn-contracts-types";
import {
  ccipBridgeDetection,
  cctpBridgeDetection,
  layerZeroOftBridgeDetection,
  transferMintBurn,
} from "./mint-burn-contracts-helpers";

// --- reUSD (Re Protocol) event topic hashes ---
// Deposited(address user, address token, uint256 amount) — all params unindexed
// Confirmed from ETH tx 0xf58255931c37cbca0859946c45d9a19e48b1da5476d1aab76ec788100c8d7a59
const REUSD_DEPOSITED_TOPIC = "0x8752a472e571a816aea92eec8dae9baf628e840f4929fbcc2d155e6233ff68a7";
// InstantRedemptionRouted(address indexed user, uint256 sharesBurned, uint256 netPayout) — user indexed
// Confirmed from ETH tx 0x831367d37ebb2bd3bf41a1152124a493c309b1f092ce161da578d635b49d23e8
const REUSD_INSTANT_REDEEM_TOPIC = "0xa58dba63852b106a5b3bbc558fa3fbcfe606497cbc0af66837a83c3560ec6220";

const ETHEREUM = chainConfig("ethereum");
const ARBITRUM = chainConfig("arbitrum");

// Phase 2 readiness — USDT Tron uses these instead of Transfer
const USDT_ISSUE_TOPIC = "0xcb8241adb0c3fdb35b70c24ce35c5eb0c17af7431c99f827d44a445ca624176a";
const USDT_REDEEM_TOPIC = "0x702d5967f45f6513a38ffc42d6ba9bf230bd40e8f53b16363c7eb4fd2deb9a44";

// Reviewed Arbitrum deployment bound: the USDai proxy is live by block
// 336,209,932 (2025-05-13), with first observed contract activity the next day.
const USD_AI_ARBITRUM_DEPLOY_BLOCK = 336_209_932;

const EXTENDED_ETHEREUM_TRANSFER_EXPANSION_SPECS: Array<{
  stablecoinId: string;
  dustThreshold: number;
  bridgeDetection?: MintBurnBridgeDetectionConfig;
}> = [
  { stablecoinId: "u-united-stables", dustThreshold: 10_000 },
  { stablecoinId: "a7a5-old-vector", dustThreshold: 10_000 },
  { stablecoinId: "usda-avalon", dustThreshold: 10_000 },
  { stablecoinId: "brz-transfero", dustThreshold: 10_000 },
  { stablecoinId: "kag-kinesis", dustThreshold: 10 },
  { stablecoinId: "satusd-river", dustThreshold: 10_000 },
  { stablecoinId: "rwausdi-multipli", dustThreshold: 10_000 },
  { stablecoinId: "fpi-frax", dustThreshold: 10_000 },
  { stablecoinId: "aeur-anchored-coins", dustThreshold: 10_000 },
  { stablecoinId: "usdq-quantoz", dustThreshold: 10_000 },
  { stablecoinId: "usdx-hex-trust", dustThreshold: 10_000 },
  { stablecoinId: "mim-abracadabra", dustThreshold: 10_000 },
  { stablecoinId: "usat-tether", dustThreshold: 10_000 },
  { stablecoinId: "zeusd-zoth", dustThreshold: 10_000 },
  { stablecoinId: "ggbr-goldfish-gold", dustThreshold: 10 },
  { stablecoinId: "xsgd-straitsx", dustThreshold: 10_000 },
  { stablecoinId: "idrt-rupiah-token", dustThreshold: 10_000 },
  { stablecoinId: "tryb-bilira", dustThreshold: 10_000 },
  { stablecoinId: "eurs-stasis", dustThreshold: 10_000 },
  { stablecoinId: "pusd-plume", dustThreshold: 10_000 },
  { stablecoinId: "usbd-bima", dustThreshold: 10_000 },
  { stablecoinId: "dgld-gold-token-sa", dustThreshold: 10 },
  { stablecoinId: "axcnh-anchorx", dustThreshold: 10_000 },
  { stablecoinId: "eurq-quantoz", dustThreshold: 10_000 },
  { stablecoinId: "gyen-gyen", dustThreshold: 10_000 },
  { stablecoinId: "usdu-usdu-finance", dustThreshold: 10_000 },
  { stablecoinId: "zarp-zarp", dustThreshold: 10_000 },
  { stablecoinId: "usdp-parallel", dustThreshold: 10_000 },
  { stablecoinId: "pht-pht", dustThreshold: 10_000 },
  { stablecoinId: "vchf-vnx", dustThreshold: 10_000 },
  { stablecoinId: "ussd-sonic-labs", dustThreshold: 10_000 },
  { stablecoinId: "cadc-cad-coin", dustThreshold: 10_000 },
  { stablecoinId: "veur-vnx", dustThreshold: 10_000 },
  { stablecoinId: "dusd-dtrinity", dustThreshold: 10_000 },
  { stablecoinId: "usdaf-asymmetry", dustThreshold: 10_000 },
  { stablecoinId: "eurau-allunity", dustThreshold: 10_000 },
  { stablecoinId: "dusd-alto", dustThreshold: 10_000 },
  { stablecoinId: "ebusd-ebisu", dustThreshold: 10_000 },
  { stablecoinId: "ftusd-flying-tulip", dustThreshold: 10_000 },
  { stablecoinId: "usdkg-gold-dollar", dustThreshold: 10_000 },
  { stablecoinId: "buck-buck-assets", dustThreshold: 10_000 },
  { stablecoinId: "chfau-allunity", dustThreshold: 10_000 },
  { stablecoinId: "mxnb-juno", dustThreshold: 10_000 },
  { stablecoinId: "cjpy-yamato", dustThreshold: 10_000 },
  { stablecoinId: "stusds-sky", dustThreshold: 10_000 },
  { stablecoinId: "busd0-usual", dustThreshold: 10_000 },
  { stablecoinId: "stkgho-umbrella-aave", dustThreshold: 10_000 },
  { stablecoinId: "stcusd-cap", dustThreshold: 10_000 },
  { stablecoinId: "msy-main-street", dustThreshold: 10_000 },
  { stablecoinId: "sbold-k3-capital", dustThreshold: 10_000 },
  { stablecoinId: "yusd-yieldfi", dustThreshold: 10_000 },
  { stablecoinId: "said-gaib", dustThreshold: 10_000 },
];

export const MINT_BURN_CONFIG_SPECS: MintBurnContractConfigSpec[] = [
  // --- Safe havens ---
  {
    chain: ETHEREUM,
    stablecoinId: "usdt-tether",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    // USDT issue()/redeem() emit only Issue/Redeem, not Transfer.
    // No zero-address Transfer events are produced.
    events: [
      {
        signature: "Issue(uint256)",
        topicHash: USDT_ISSUE_TOPIC,
        direction: "mint" as const,
        amountEncoding: "first-data-uint256" as const,
      },
      {
        signature: "Redeem(uint256)",
        topicHash: USDT_REDEEM_TOPIC,
        direction: "burn" as const,
        amountEncoding: "first-data-uint256" as const,
      },
    ],
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usdc-circle",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    events: transferMintBurn(),
    bridgeDetection: cctpBridgeDetection([
      "0xfd78ee919681417d192449715b2594ab58f5d002",
    ]),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "fdusd-first-digital",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "pyusd-paypal",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },

  // --- Risky / crypto-backed ---
  {
    chain: ETHEREUM,
    stablecoinId: "dai-makerdao",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "gho-aave",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usde-ethena",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usds-sky",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "frxusd-frax",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "bold-liquity",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "fxusd-f-x-protocol",
    dustThreshold: 10_000,
    startBlock: 19_287_523,
    tier: "extended",
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "crvusd-curve",
    dustThreshold: 10_000,
    startBlock: 17_257_952,
    tier: "extended",
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "ausd-agora",
    dustThreshold: 10_000,
    startBlock: 20_257_620,
    tier: "extended",
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "zchf-frankencoin",
    dustThreshold: 10_000,
    startBlock: 18_451_518,
    tier: "extended",
    events: transferMintBurn(),
    bridgeDetection: ccipBridgeDetection([
      "0x9359cd75549dae00cdd8d22297bc9b13fbbe4b79",
    ]),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "eurc-circle",
    dustThreshold: 10_000,
    startBlock: 14_807_227,
    tier: "extended",
    events: transferMintBurn(),
    bridgeDetection: cctpBridgeDetection([
      "0xfd78ee919681417d192449715b2594ab58f5d002",
    ]),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "paxg-paxos",
    dustThreshold: 10,
    startBlock: 8_426_430,
    tier: "extended",
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "xaut-tether",
    dustThreshold: 10,
    startBlock: 13_524_498,
    tier: "extended",
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usdg-paxos",
    dustThreshold: 10_000,
    startBlock: 20_915_336,
    tier: "extended",
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usd1-world-liberty-financial",
    dustThreshold: 10_000,
    startBlock: 21_720_503,
    tier: "extended",
    events: transferMintBurn(),
    bridgeDetection: ccipBridgeDetection([
      "0x36a72ed0096b414521c45e3ddc9ed657d1d9c141",
    ]),
  },

  // --- Top-50 supported expansion (Ethereum only) ---
  {
    chain: ETHEREUM,
    stablecoinId: "usdf-falcon",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usyc-hashnote",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "rlusd-ripple",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usdy-ondo-finance",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "buidl-blackrock",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usdd-tron-dao-reserve",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usdtb-ethena",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "m-m0",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usd0-usual",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "tusd-trueusd",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "cusd-cap",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usr-resolv",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "frax-frax",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "dola-inverse-finance",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "iusd-infinifi",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "gusd-gate",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "avusd-avant",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
    bridgeDetection: ccipBridgeDetection([
      "0x81b72171642fab457aa815c0b8412a22b63a6af8",
    ]),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "pmusd-precious-metals",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usdz-anzen",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "mnee-mnee",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "tbill-openeden",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    // Saturn USDat — proxy 0x23238f20b894f29041f48d88ee91131c395aaa71, deployed 2026-03-10
    chain: ETHEREUM,
    stablecoinId: "usdat-saturn",
    dustThreshold: 10_000,
    startBlock: 24_629_431,
    tier: "extended",
    events: transferMintBurn(),
  },
  {
    // Wrapped M (wM) — WrappedMToken proxy 0x437cc33344a0b27a429f795ff6b469c72698b291, deployed ~Aug 2024
    // startBlock bisected via eth_getCode: contract absent at 20_527_909, present at 20_527_947
    chain: ETHEREUM,
    stablecoinId: "wm-m0",
    dustThreshold: 10_000,
    startBlock: 20_527_947,
    tier: "extended",
    events: transferMintBurn(),
  },
  {
    // Nerona USD (USDnr) — proxy 0xd48e565561416de59da1050ed70b8d75e8ef28f9
    // Default start block (deploy block unresolved without Etherscan API key); ~$50M supply
    chain: ETHEREUM,
    stablecoinId: "usdnr-nerona",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },

  // --- Top-100 supported expansion (Ethereum only) ---
  {
    chain: ETHEREUM,
    stablecoinId: "usdo-openeden",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
    bridgeDetection: ccipBridgeDetection([
      "0x500d4882938020e939a5666c1b4200873da7efd3",
    ]),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "eurcv-societe-generale-forge",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "reusd-resupply",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "euri-banking-circle",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "gusd-gemini",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usdp-paxos",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "xusd-straitsx",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "musd-metamask",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "yusd-aegis",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "susd-synthetix",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "lusd-liquity",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usdcv-societe-generale-forge",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "eure-monerium",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usn-noon",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "eusd-electronic-usd",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "meusd-mezo",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "msusd-metronome",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "nusd-neutrl",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "alusd-alchemix",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "fidd-fidelity",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "msusd-main-street",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },

  // --- Top-150 supported expansion (Ethereum only) ---
  {
    chain: ETHEREUM,
    stablecoinId: "wusd-worldwide",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "sbc-brale",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "ousd-origin-protocol",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usp-pikudao",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "usdr-stablr",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "ustb-superstate",
    dustThreshold: 1_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "ousg-ondo-finance",
    dustThreshold: 100,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "mtbill-midas",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "thbill-theo",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "wsrusd-reservoir",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "audd-novatti",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "jpyc-jpyc",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "xaum-matrixdock",
    dustThreshold: 10,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "eurr-stablr",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "europ-schuman",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "deuro-deuro",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "tgbp-tokenised",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "syrupusdc-maple",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "syrupusdt-maple",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "aid-gaib",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  {
    chain: ETHEREUM,
    stablecoinId: "apxusd-apyx",
    dustThreshold: 10_000,
    startBlock: 21_900_000,
    tier: "extended",
    isDefaultStartBlock: true,
    events: transferMintBurn(),
  },
  ...EXTENDED_ETHEREUM_TRANSFER_EXPANSION_SPECS.map(
    ({ stablecoinId, dustThreshold, bridgeDetection }): MintBurnContractConfigSpec => ({
      chain: ETHEREUM,
      stablecoinId,
      dustThreshold,
      bridgeDetection,
      startBlock: 21_900_000,
      tier: "extended",
      isDefaultStartBlock: true,
      events: transferMintBurn(),
    }),
  ),
  {
    chain: ARBITRUM,
    stablecoinId: "usdai-usd-ai",
    dustThreshold: 10_000,
    startBlock: USD_AI_ARBITRUM_DEPLOY_BLOCK,
    tier: "extended",
    bridgeDetection: layerZeroOftBridgeDetection([
      "0xffa10065ce1d1c42fabc46e06b84ed8ffeb4bae5",
      "0x31cae3b7fb82d847621859fb1585353c5720660d",
    ]),
    startBlockSource: "reviewed-arbitrum-deployment-2025-05-13",
    startBlockConfidence: "high",
    events: transferMintBurn(),
  },

  // --- reUSD (Re Protocol, ID 339) — Ethereum only ---
  {
    chain: ETHEREUM,
    stablecoinId: "reusd-re-protocol",
    contractAddressOverride: "0x4691c475be804fa85f91c2d6d0adf03114de3093",
    decimalsOverride: 18,
    dustThreshold: 10_000,
    startBlock: 21_675_000,
    tier: "extended",
    events: [
      {
        signature: "Deposited(address,address,uint256)",
        topicHash: REUSD_DEPOSITED_TOPIC,
        direction: "mint",
        amountEncoding: "nth-data-uint256",
        dataSlot: 2,
        counterpartyEncoding: { source: "data", slot: 0 },
      },
    ],
  },
  {
    chain: ETHEREUM,
    stablecoinId: "reusd-re-protocol",
    contractAddressOverride: "0x8aeb9453ef22cb38abc7a3af9c208f65c1bfe31e",
    decimalsOverride: 18,
    dustThreshold: 10_000,
    startBlock: 23_479_000,
    tier: "extended",
    events: [
      {
        signature: "InstantRedemptionRouted(address,uint256,uint256)",
        topicHash: REUSD_INSTANT_REDEEM_TOPIC,
        direction: "burn",
        amountEncoding: "first-data-uint256",
      },
    ],
  },
];
