import {
  SECONDS_PER_MINUTE,
  HOUR_SECONDS,
  DAY_SECONDS,
  WEEK_SECONDS,
  THIRTY_DAYS_SECONDS,
} from "@shared/lib/time-constants";

/** Named durations in seconds — worker convenience alias. */
export const SECONDS = {
  ONE_MINUTE: SECONDS_PER_MINUTE,
  FIFTEEN_MINUTES: 15 * SECONDS_PER_MINUTE,
  THIRTY_MINUTES: 30 * SECONDS_PER_MINUTE,
  ONE_HOUR: HOUR_SECONDS,
  TWO_HOURS: 2 * HOUR_SECONDS,
  SIX_HOURS: 6 * HOUR_SECONDS,
  TWELVE_HOURS: 12 * HOUR_SECONDS,
  ONE_DAY: DAY_SECONDS,
  TWO_DAYS: 2 * DAY_SECONDS,
  ONE_WEEK: WEEK_SECONDS,
  THIRTY_DAYS: THIRTY_DAYS_SECONDS,
} as const;
