import type { DdrrRow } from "@shared/types/depeg-resolver-review";
import type { DdrrSummary } from "@shared/types/depeg-resolver-review";

export const predictionRow: DdrrRow = {
  kind: "prediction_review",
  eventId: 42,
  currentEventId: 42,
  incidentKey: "lusd-liquity:below:1",
  stablecoinId: "lusd-liquity",
  symbol: "LUSD",
  name: "Liquity USD",
  pegCurrency: "USD",
  governance: "decentralized",
  direction: "below",
  startedAt: 1,
  eligibleAt: 1,
  sourceEventState: "recovered",
  terminalEvidenceAt: null,
  terminalEvidenceInterval: null,
  terminalEvidencePrecision: null,
  publicPredictionId: 7,
  assessmentId: 9,
  predictionState: "frozen",
  predictionMethodologyVersion: "1.0",
  predictionPolicyVersion: "sticky-24h-v1",
  lockedAt: 2,
  publishedAt: 3,
  publicationSnapshotToken: "snapshot-1",
  frozen: {
    resolutionTier: "recovery_likely",
    predictedRemainingSec: 3600,
    iqrRemainingSec: [1800, 7200],
    horizonCells: [],
    stratum: "below - moderate - robust - USD",
    factors: [],
  },
  actual: {
    kind: "recovered",
    actualEndedAt: 7202,
    actualRemainingSec: 7200,
    terminalEvidenceAt: null,
    terminalEvidenceInterval: null,
    terminalEvidencePrecision: null,
    reviewedAt: 7202,
  },
  verdictReview: "correct_recoverable",
  durationReview: "inside_band",
  horizonReviews: [],
  predictedRemainingSec: 3600,
  actualRemainingSec: 7200,
  medianReview: "median_late_by",
  signedDurationErrorSec: 3600,
  absoluteDurationErrorSec: 3600,
  withinIqr: true,
};

export const coverageRow: DdrrRow = {
  kind: "coverage",
  eventId: 43,
  currentEventId: 43,
  incidentKey: "lusd-liquity:below:2",
  stablecoinId: "lusd-liquity",
  symbol: "LUSD",
  name: "Liquity USD",
  pegCurrency: "USD",
  governance: "decentralized",
  direction: "below",
  startedAt: 1,
  eligibleAt: 1,
  sourceEventState: "recovered",
  terminalEvidenceAt: null,
  terminalEvidenceInterval: null,
  terminalEvidencePrecision: null,
  predictionState: "missed_lock_recovered",
  actualEndedAt: 7202,
  terminalEvidenceSourceDate: null,
  coverageCause: "lock_missed",
  operationalCoverageCause: "lock_missed",
  outcomeQualityState: "classified",
  reason: null,
  failedPublication: null,
};

export function makePredictionPolicySegment(
  template: DdrrSummary["byPredictionPolicy"][number]["metrics"],
  version: string,
  scored: number,
  correct: number,
  durationScored = 0,
  meanSignedDurationErrorSec: number | null = null,
  meanAbsoluteDurationErrorSec: number | null = null,
) {
  return {
    segmentKind: "prediction_policy" as const,
    predictionMethodologyVersion: version,
    predictionPolicyVersion: "sticky-24h-v1",
    metrics: {
      ...template,
      recoveryLikelihoodScoredCount: scored,
      recoveryLikelihoodCorrectCount: correct,
      durationScoredCount: durationScored,
      meanSignedDurationErrorSec,
      meanAbsoluteDurationErrorSec,
    },
  };
}
