export type LiveReserveSourceQuality =
  | "independent"
  | "static-validated"
  | "weak-proof"
  | "not-plausible"
  | "unreviewed";

export interface LiveReserveSourceQualityNote {
  sourceUrl: string | null;
  sourceQuality: LiveReserveSourceQuality;
  expectedAdapterFamily: string;
  freshnessEvidence: string;
  scoreGradePlausible: boolean;
  note: string;
}

/**
 * Per-coin source-quality review notes for curated-only reserve candidates.
 * Keyed by stablecoin id; keys must stay in sync with the active registry.
 * generate-reserve-coverage-audit.ts warns at run time when a key here no
 * longer matches any active stablecoin (the coin is gone or frozen), and a
 * second warning class fires when the coin is now live-configured — both stale
 * classes surface instead of being silently skipped, so the note can be
 * deleted.
 */
export const REVIEWED_LIVE_RESERVE_SOURCE_NOTES: Record<string, LiveReserveSourceQualityNote> = {
  "usdh-hubble": {
    sourceUrl: "https://docs.hubbleprotocol.io/resources/technical-resources",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Hubble PSM and complete borrowing-market/receipt valuation reader",
    freshnessEvidence: "Reviewed 2026-10-01: technical resources still expose vault identities, while the app yields a JavaScript shell. Existing SDK/Scope collateral observations remain historical.",
    scoreGradePlausible: false,
    note: "The prior claim that decoding had not started is obsolete: the sidecar records decoded PSM and three borrowing markets. The missing requirement is a current coherent collateral/receipt valuation and liability census, including kToken LP look-through and residual assets previously spot-priced with placeholders. A USDC-only PSM read would omit the CDP branch.",
  },
  "moveusd-cfx": {
    sourceUrl: "https://trust.cfx.to/",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "single-asset or disclosure parser only after a current reserve/timestamp field is exposed",
    freshnessEvidence: "Reviewed 2026-10-01: the CFX Trust Center states segregated custodial bank accounts, but exposes no dated reserve amounts or composition in the fetched disclosure.",
    scoreGradePlausible: false,
    note: "A token supply/liveness probe would not independently verify bank deposits; score-grade use needs current reserve disclosure or attestation.",
  },
  "usda-avalon": {
    sourceUrl: "https://docs.avalonfinance.xyz",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "new Avalon collateral API/parser if current collateral balances and timestamps are published",
    freshnessEvidence: "Reviewed 2026-10-01: official minting docs describe FBTC collateral and USDT conversion, but no dated full CeDeFi reserve accounting source was verified.",
    scoreGradePlausible: false,
    note: "Do not bind selected pool balances as the full reserve book. The current DefiLlama adapter explicitly excludes team-deposited wrappers and several networks; its USDa contract list also differs from the tracked deployments. Reopen on a primary complete custody/collateral census reconciled to the tracked USDa liability perimeter.",
  },
  "usdf-astherus": {
    sourceUrl: "https://www.asterdex.com/en/usdf",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "new Astherus/Aster collateral API parser if a current composition endpoint is published",
    freshnessEvidence: "Reviewed 2026-10-01: issuer documentation and the deployed USDF page describe Ceffu custody and matching Binance short positions, without a dated reserve composition payload.",
    scoreGradePlausible: false,
    note: "USDT mint deposits are transferred into custodial strategies; token balances or the existing astherus-earn-wrapper adapter cannot measure the base USDF book. Reopen when Aster publishes dated net assets and composition, including futures liabilities.",
  },
  "msusd-metronome": {
    sourceUrl: "https://docs.metronome.io/metronome-synth/metronome-synth-protocol/supported-assets",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Metronome synth-specific reserve and treasury reconciliation",
    freshnessEvidence: "Reviewed 2026-10-01: the app shows protocol TVL and minted totals but deposited wallet fields are N/A; the July 30 post-mortem is historical.",
    scoreGradePlausible: false,
    note: "Eligible collateral and shared multi-synth TVL do not allocate reserves to msUSD. The issuer post-mortem identifies unbacked msUSD float and looped treasury/LP remediation; raw DepositToken balances omit this liability structure. Require current synth-specific debt, float, treasury and collateral allocation before binding.",
  },
  "pmusd-precious-metals": {
    sourceUrl: "https://data.chain.link/feeds/ethereum/mainnet/ion-por",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Chainlink proof-of-reserve feed plus liability reconciliation only if pmUSD supply and TokenBlender backing can be tied together",
    freshnessEvidence: "Reviewed 2026-10-01: pmusd.raac.io/collateral and the ION feed page return HTTP 429; no current pmUSD-specific reserve/liability timestamp was verified.",
    scoreGradePlausible: false,
    note: "The referenced ION PoR is upstream gold-claim evidence, not a pmUSD-specific Treasury/TokenBlender/PSM reconciliation. Retain curated evidence; neither a failed read nor the upstream feed can establish current pmUSD backing.",
  },
  "usdkg-gold-dollar": {
    sourceUrl: "https://www.usdkg.com/transparency",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "attestation-pdf-index if current Kreston reserve reports are consistently published with parseable dates",
    freshnessEvidence: "Reviewed 2026-10-01: the transparency index still lists only the Q4 2025 Kreston reserve report; its $54.8M gold valuation is explicitly the audit-date pricing snapshot.",
    scoreGradePlausible: false,
    note: "No binding: the November 2025 reserve report is stale under existing admission limits. Consensys January 2025 links are smart-contract audits, not newer reserve evidence. Reopen on a fresh dated Kreston reserve disclosure; do not refresh report time from HTML fetch time.",
  },
  "usp-pikudao": {
    sourceUrl: "https://public-api.piku.co/v1/tokens/usp",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "new Piku strategy parser only if current strategy allocations and stablecoin buffers become public and timestamped",
    freshnessEvidence: "Reviewed 2026-10-01: the public USP JSON returns price, APYs and redemption fee only, with no reserve amounts, allocations or source timestamp.",
    scoreGradePlausible: false,
    note: "The July 1 reserve documentation labels its table potential backing partners, not current USP allocations. Published backing wallets do not measure off-chain strategies. No reserve adapter is justified by the token-price API.",
  },
  "usdo-openeden": {
    sourceUrl: "https://prod-gw.openeden.com/usdo/sys/reserve-composition-last",
    sourceQuality: "independent",
    expectedAdapterFamily: "openeden-usdo (registered and parked; Worker egress prerequisite)",
    freshnessEvidence: "Reviewed 2026-10-01: ordinary-client JSON publishes date 2026-10-01T08:00:19.111Z, reserveAssetsInUsd 15548412.154918937 and usdoAmount 15285701.014818601.",
    scoreGradePlausible: true,
    note: "The dated source remains viable, but the descriptor is deliberately parked following failed Cloudflare Worker egress. Ordinary-client success does not prove that prerequisite resolved. Obtain a successful Worker-origin fetch before restoring the binding; no egress recovery is claimed by this review.",
  },
  "buck-bucket-protocol": {
    sourceUrl: "https://docs.bucketprotocol.io/user-guides/bucket-upgrade-and-migration",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Sui V1 collateral census with non-circular LP valuation",
    freshnessEvidence: "Reviewed 2026-10-01: current migration docs separate legacy BUCK from new USDB. The prior V1 inventory remains historical; no reserve date is refreshed.",
    scoreGradePlausible: false,
    note: "V2 CDP/PSM assets back USDB. The authored V1 envelope is dominated by LP face values whose underlying BUCK component is unresolved; normalization cannot establish non-circular backing. Require complete V1 constituent valuation and LP look-through before binding, not a partial custody or supply probe.",
  },
  "scusd-rings": {
    sourceUrl: "https://api.veda.tech/",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Veda BoringVault complete position reader after an accessible accounting source exists",
    freshnessEvidence: "Reviewed 2026-10-01: Veda root API returns HTTP 401 Unauthorized; Ethereum block 0x18e320e totalAssets() on the documented stablecoin BoringVault reverts. Historical 2026-09-09 Sonic scUSD (0xd3dce716f3ef535c5ff8d041c1a41c3bd89b97ae) supply was ~648,816.9 (6 decimals), with totalAssets() also reverting; this does not refresh reserve accounting.",
    scoreGradePlausible: false,
    note: "Trevee documents accepted stablecoins and strategic deployment across protocols, not a complete current allocation. The non-4626 Veda BoringVault's accountant and Aave/Morpho-style deployed positions cannot be enumerated from bare ERC-20 balanceOf reads; ERC-4626, idle escrow and single-asset supply probes cannot establish complete backing. The sidecar stays 100% unknown (basket-needs-split). Reopen on accessible dated Veda accounting or verified complete strategy decoding.",
  },
  "pht-pht": {
    sourceUrl: "https://docs.apacx.io/transparency",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "multi-ilk PHT reserve/liability reconciliation",
    freshnessEvidence: "Reviewed 2026-10-01: issuer transparency still names one Tron apcxUSDT wallet and leaves apcxUSDC unannounced; no complete dated reserve inventory appears.",
    scoreGradePlausible: false,
    note: "The current mint guide still claims all existing PHT uses apcxUSDT, while the authored Ethereum ILK conflict remains unresolved. One Tron USDT balance cannot represent the multichain reserve perimeter or value PHP liabilities. Preserve historical observations and require complete same-block collateral and bridge/liability reconciliation before binding.",
  },
  "hollar-hydrated": {
    sourceUrl: "https://rpc.hydradx.cloud",
    sourceQuality: "independent",
    expectedAdapterFamily: "hydration-hollar (new Substrate+EVM adapter; not bound — HSM balance census and cross-debt model incomplete)",
    freshnessEvidence: "Reviewed 2026-10-01: official HOLLAR docs confirm Aave-GHO architecture plus a separate HSM deploying received stablecoins into yield strategies. Prior pinned EVM census remains historical; no complete same-checkpoint HSM and cross-debt attribution was established in this review.",
    scoreGradePlausible: false,
    note: "Reviewed 2026-09-09. The EVM side of the census is fully proven: all three live Aave v3 markets enumerate reserves with same-block totalAToken and per-block AaveOracle prices (base currency USD, 1e8), and the GhoToken facilitator buckets reconcile to supply exactly. Binding is blocked on the two non-EVM pieces. (1) The native HSM pallet (prefix twox128('HSM'), PalletId b'py/hsmod', module account 0x6d6f646c70792f68736d6f6400000000000000) is decoded: Collaterals maps assets 1002 (aUSDT) and 1003 (aUSDC) in HOLLAR stableswap pools 111/110 with buyback params, but the HSM account's actual balance storage was not resolved — Hydration's orml_tokens fork uses a non-standard Accounts key layout and an acct-first prefix probe returned empty, so the current aToken balance held by the HSM's EVM account still needs pinning down before the bucket can be valued (the pool getReserveData fork layout puts aTokenAddress at word 8). (2) aUSDC/aUSDT valuation needs a reviewed path (Aave liquidity-index-derived rate or the native ema-oracle entry for assets 1002/1003). (3) The Hydration Market shares collateral with non-HOLLAR borrows (apyUSD ~85.5k tokens at $1.367, ETH, tBTC, PAXG), so an attribution model must subtract them before publishing HOLLAR backing. Bind hydration-hollar only after those three settle; the EVM read path above is proven and reusable.",
  },
  "fxd-fathom": {
    sourceUrl: "https://docs.fathom.fi/fxd-stablecoin/deployments/xdc-network",
    sourceQuality: "independent",
    expectedAdapterFamily: "evm-branch-balances (not bound; psXDC collateral pool has no independent market price)",
    freshnessEvidence: "Reviewed 2026-10-01: official deployment docs still list XDC and CGO pools, while the reviewed sidecar includes a material psXDC pool. The live DefiLlama psXDC query still returns an empty coins map.",
    scoreGradePlausible: false,
    note: "Reviewed 2026-09-09. FXD is a three-pool Maker-fork CDP (psXDC 74.5%, WXDC 25.5%, CGO ~0% by value, matching the reviewed 2026-07-30 sidecar), but evm-branch-balances cannot value the largest pool honestly. DefiLlama returns no price for psXDC 0x9b8e12b0bac165b86967e771d98b520ec3f665a6 (empty coins map), and the protocol only carries a 1:1-as-XDC priceWithSafetyMargin assumption with no market exchange-rate feed. A three-branch config would either omit psXDC (publishing a false ~27% collateralization from the WXDC+CGO sum) or require a hardcoded 1:1 XDC price (a silent-constant valuation fallback). Bind only once an independent psXDC market price exists (DefiLlama/CoinGecko listing or a reviewed staking-receipt rate feed); the XDC RPC is verified but not yet registered since no config uses it.",
  },
  "iusd-indigo-protocol": {
    sourceUrl: "https://analytics.indigoprotocol.io/api/cdps",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "indigo-cardano (deferred; full same-checkpoint CDP and peg-stability accounting required)",
    freshnessEvidence: "Reviewed 2026-10-01: the issuer CDP JSON is reachable with collateralAmount and mintedAmount rows, but exposes no shared ledger checkpoint or reserve-observation timestamp; per-position interest settlement is not snapshot freshness.",
    scoreGradePlausible: false,
    note: "The prior full-supply reconciliation leaves a 7.6906% unresolved non-CDP residual. Current issuer configuration exposes V3 validator identities but does not turn the CDP index into a complete supply-reconciled reserve census. No live adapter until collateral valuation, PSM inventory and debt share a source checkpoint; do not normalize surviving indexed debt to 100%.",
  },
  "nusd-neutrl": {
    sourceUrl: "https://cache.accountable.capital/dashboard/neutrl",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "accountable after the issuer-authorized reserve feed recovers",
    freshnessEvidence: "Reviewed 2026-10-01: both reader and direct workstation requests returned HTTP 503 with {\"message\":\"No data available\",\"res\":\"err\"}; no current reserve timestamp or composition could be verified.",
    scoreGradePlausible: false,
    note: "The issuer still links Accountable and its deployed page consumes type_split, but historical curated weights cannot replace a missing current payload. Reopen when the endpoint serves a dated, internally reconciled reserve snapshot.",
  },
  "aid-gaib": {
    sourceUrl: "https://aid.gaib.ai/transparency",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "new GAIB accounting adapter after dated off-chain loan NAV is published",
    freshnessEvidence: "Reviewed 2026-10-01: deployed Transparency-THDQWk7j.js contains literal facility principal and remainingPrincipal values; its visible Last updated uses fetchedAt.",
    scoreGradePlausible: false,
    note: "Current on-chain balances do not date or validate hardcoded GPU-loan principal. A fetch clock is not an off-chain reserve measurement. Reopen on dated facility accounting reconciled with the liquid reserve book and AID liabilities.",
  },
  "usdm-moneta": {
    sourceUrl: "https://moneta.global/transparency/",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "new Moneta/Charli3 reserve adapter after a dated measured payload is exposed",
    freshnessEvidence: "Reviewed 2026-10-01: the transparency page bundle hardcodes both reserve and circulating balances as 9,609,507.48; Verified on-chain and today labels have no source measurement timestamp.",
    scoreGradePlausible: false,
    note: "Do not scrape the literal display as a current reserve feed or infer the historical 80/20 split from undated category descriptions. Reopen on a dated Charli3 or issuer reserve payload covering the relevant issuer pools.",
  },
  "kgst-kyrgyz-som": {
    sourceUrl: "https://www.kgstoken.kg/",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "attestation or issuer reserve API after public dated reserve reports exist",
    freshnessEvidence: "Reviewed 2026-10-01: the official Attestation of Reserve section describes cash/cash-equivalent backing but exposes no dated balance, report link, or reserve API.",
    scoreGradePlausible: false,
    note: "The BEP-20 contract proves token state, not licensed-bank balances. Reopen on a dated reserve report or machine-readable bank-reserve disclosure.",
  },
  "usg-tangent": {
    sourceUrl: "https://docs.tangent.finance/docs/faq/contracts",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "new Tangent market census and productive-collateral valuation adapter",
    freshnessEvidence: "Reviewed 2026-10-01: primary docs list twelve productive-collateral markets and three market classes; Control Tower source retrieval failed (Etherscan 403, Sourcify full/partial metadata 404).",
    scoreGradePlausible: false,
    note: "No full live market/issuance census or reviewed productive-collateral valuation contract was established. The documented static market list and prior partial LP decomposition do not establish complete current reserves. Reopen after verified enumerable market accounting and complete LP/PT valuations; do not publish only the known frxUSD leg.",
  },
  "audf-forte": {
    sourceUrl: "https://www.forteaud.com/transparency",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "reviewed independent-assurance profile with machine-readable report discovery",
    freshnessEvidence: "Reviewed 2026-10-01: official August report audits AUD 5,142,851.53 cash as at 31 August 2026 11:59pm (signed 7 September); the static index exposes no dated PDF anchors.",
    scoreGradePlausible: false,
    note: "The client discovers reports through a documents table and serves extensionless /api/documents/view/<slug> URLs, which attestation-pdf-index does not accept as PDF links. No binding until a reviewed discovery/hash-pinned report profile and liability scope exist; do not substitute the current 1:1 marketing claim for measured liabilities.",
  },
  "usdm-monetrix": {
    sourceUrl: "https://api.monetrix.xyz/data/api/collateral",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "new Monetrix parser after source accounting reconciliation is reliable",
    freshnessEvidence: "Reviewed 2026-10-01: dated collateral JSON reports backing.reconciled=false, spotUsd 4,184,028.3796285638, marginUsd 420,062.530902, and negative bufferUsd -1,121,000.4021373498.",
    scoreGradePlausible: false,
    note: "A FULL_BACKED label and stale=false do not override failed reconciliation. Do not normalize positive rows, drop the negative buffer, or publish totalUsd as validated reserves. Reopen on a reconciled gross-assets/net-liabilities perimeter with documented overlap treatment.",
  },
  "isc-international-stable-currency": {
    sourceUrl: "https://isc.money/api/reserve-balances",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "new ISC reserve parser after a portfolio measurement timestamp is supplied",
    freshnessEvidence: "Reviewed 2026-10-01: reserve-balances returns two holdings objects without an as-of clock; isc-composition also returns asset coefficients without a timestamp.",
    scoreGradePlausible: false,
    note: "The target-price history cannot date reserve composition. ISC holdings within Reserve A/B need explicit self-held-token exclusion and liability reconciliation before a ratio. Reopen on dated reserve accounting; do not use HTTP fetch time as verified portfolio freshness.",
  },
  "usdv-solomon": {
    sourceUrl: "https://data.solomonlabs.io/api/solomon-protocol/protocol-data",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "solomon-protocol remains parked for the tracked legacy mint",
    freshnessEvidence: "Reviewed 2026-10-01: API protocolTvl is 7,234,390.481688 while legacy custodyNotionalUsd is only 74.15, vault and reserve fund are zero; issuer explicitly distinguishes legacy and new USDv.",
    scoreGradePlausible: false,
    note: "The issuer announces separate tokens/programs/reserve models and no automatic conversion. Do not bind the replacement product's TVL to legacy mint Ex5DaKYMCN6QWFA4n67TmMwsH8MJV68RX6YXTmVM532C or treat futures notional as reserve NAV. Reopen only on a dated legacy-specific reconciled reserve source.",
  },
  "dusd-dtrinity": {
    sourceUrl: "https://docs.dtrinity.org/protocol-components/dusd",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "new chain-scoped dTRINITY collateral and AMO accounting adapter",
    freshnessEvidence: "Reviewed 2026-10-01: Ethereum block 0x18e320e confirms seven collateral entries and nonzero totalValue on 0x84c58066a4408454b7380f168c95F571419253f4; primary docs say deployments are chain-isolated and non-fungible.",
    scoreGradePlausible: false,
    note: "Idle-vault accounting alone omits the separately documented AMO deployed reserves and can include self-referential dUSD LP accounting. The tracked Sonic deployment has no matching current primary reserve table. Reopen after per-deployment liability identity and complete non-circular AMO look-through are established; no idle-only aggregate binding.",
  },
  "zkusd-goal3": {
    sourceUrl: "https://explorer.zksync.io/address/0xfc7e56298657b002b3e656400e746b7212912757",
    sourceQuality: "not-plausible",
    expectedAdapterFamily: "none until current reserve custody and assets are established",
    freshnessEvidence: "Reviewed 2026-10-01: issuer and docs hosts return ENOTFOUND; zkSync block 0x44f07ad reads token supply but treasuryAddress() on the previously reviewed Lockdrop implementation returns the zero address.",
    scoreGradePlausible: false,
    note: "Token supply and a historical deposit-routing contract do not establish present backing. Reopen on current primary reserve custody, asset identities, dated balances, and liabilities; do not revive a historical USDC reserve claim from token liveness.",
  },
  "emxn-telcoin": {
    sourceUrl: "https://www.telco.in/en/digital-cash",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Telcoin eMXN-specific attestation adapter after reports are published",
    freshnessEvidence: "Reviewed 2026-10-01: official Digital Cash page identifies the tracked Polygon eMXN token and says monthly external-auditor attestations will be published, but links no dated eMXN report.",
    scoreGradePlausible: false,
    note: "Do not apply eUSD bank disclosures or a Polygon supply probe to Mexican-peso backing. Reopen on a dated eMXN-specific reserve report or machine-readable reserve balance source.",
  },
  "wpen-ripio": {
    sourceUrl: "https://action.ripio.com/en/wfiat-attestations",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "attestation-pdf-index after a current wPEN-specific report exists",
    freshnessEvidence: "Reviewed 2026-10-01: issuer wFIAT page lists wPEN, but the alternate attestation index lists only June 30 reports for wARS, wBRL, wMXN, wCOP, and wCLP.",
    scoreGradePlausible: false,
    note: "No wPEN report was verified on either official index. Sibling-currency attestations cannot validate PEN reserves, and their June dates exceed the existing 33-day ceiling. Reopen on a fresh wPEN-specific dated report; do not bind a no-match PDF index.",
  },
  "sofid-sofi": {
    sourceUrl: "https://www.sofi.com/crypto/sofiusd/",
    sourceQuality: "independent",
    expectedAdapterFamily: "independent-assurance report adapter after a reliably fetchable newest-report index is established",
    freshnessEvidence: "Reviewed 2026-10-01: Deloitte July 31 examination is reachable at the official CloudFront PDF; the product/index page returns HTTP 403 and a browser challenge, so newest-report discovery was not verified.",
    scoreGradePlausible: false,
    note: "The July examination identifies $309,934,457 cash and $304,041,093 redeemable liabilities, but direct access to a historical PDF is not an updating feed. Do not treat its August 31 signature or a fresh download as current reserves.",
  },
  "lisusd-lista": {
    sourceUrl: "https://docs.bsc.lista.org/for-developer/collateral-debt-position/smart-contract",
    sourceQuality: "independent",
    expectedAdapterFamily: "evm-branch-balances after complete collateral, PSM and D3M accounting and valuation",
    freshnessEvidence: "Reviewed 2026-10-01: issuer registry publishes GemJoins, including BBTC/cemBTC, and a distinct USDT PSM/VaultManager/Venus adapter. No complete dated reserve basket was established from the app shell.",
    scoreGradePlausible: false,
    note: "The selected-slices sidecar explicitly excludes unpriced cemBTC/BBTC and unverified cewBETH claims. A GemJoin-only config also misses non-CDP issuance. Keep the deleted lista adapter unbound; do not normalize the priced subset into full backing.",
  },
  "slvon-ondo": {
    sourceUrl: "https://app.ondo.finance/api/v2/assets/slvon/info",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Ondo Stocks token-specific reserve accounting, not chainlink-nav or underlying ETF holdings",
    freshnessEvidence: "Reviewed 2026-10-01: SLVon info JSON timestamps topHoldings of the underlying SLV ETF, but its supply/TVL fields are null. Linked August Ankura report reconciles pooled Ondo Stocks assets and obligations, not SLVon separately.",
    scoreGradePlausible: false,
    note: "The 100% Physical Silver row describes the ETF, not the issuer's ETF-share/cash-in-transit backing of SLVon. Dropbox daily/monthly report archives do not establish a bounded token-specific machine-readable reserve census.",
  },
  "mai-qidao": {
    sourceUrl: "https://app.mai.finance/transparency-dashboard",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "QiDao complete multichain vault and treasury adapter after debt and liability reconciliation",
    freshnessEvidence: "Reviewed 2026-10-01: rendered dashboard reads RPCs directly and reports $1,716,093.11 collateral, $780,180.16 global debt and $11,863,768.17 MAI circulation during this review; no common observation checkpoint is published.",
    scoreGradePlausible: false,
    note: "The dashboard explicitly curates some treasury and lending information. Its debt and collateral are not a reconciled full reserve denominator for multichain circulating MAI. A partial live vault basket would conceal legacy liabilities and treasury scope uncertainty.",
  },
  "usda-anzens": {
    sourceUrl: "https://www.anzens.com/landing/terms-and-conditions",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "issuer reserve disclosure or attestation adapter after dated balances are published",
    freshnessEvidence: "Reviewed 2026-10-01: official terms identify cash, cash equivalents, Treasury bills and Treasury-focused funds, but neither fetched homepage nor terms supplies dated reserve amounts or allocations.",
    scoreGradePlausible: false,
    note: "Cardano policy supply cannot validate BitGo-custodied off-chain reserves. Anzens USDA is not Anzen USDz; the anzen-usdz adapter is inapplicable.",
  },
  "cgo-comtech": {
    sourceUrl: "https://cgold.ae/Digitalgold",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "dated gold-stock attestation index after current issuer artifacts are discoverable",
    freshnessEvidence: "Reviewed 2026-10-01: the reachable self-signed February 26 letter confirms 39 one-kilogram bars. Current rendered Digitalgold links include FAQ, terms and fatwa PDFs, not a fresh stock index or reserve JSON.",
    scoreGradePlausible: false,
    note: "The historical issuer letter is not independent assurance and is over seven months old. Token balances or a gold price feed cannot refresh custody quantity.",
  },
  "hbusdt-hyperbeat": {
    sourceUrl: "https://docs.hyperbeat.org/hyperbeat-earn/usdt-vault",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Accountable strategy composition adapter after the published proof endpoint is restored",
    freshnessEvidence: "Reviewed 2026-10-01: accountable.hyperbeat.org/hbUSDT fails DNS resolution. At pinned HyperEVM block 0x2d2afd9, asset() and totalAssets() both revert on the tracked hbUSDT token.",
    scoreGradePlausible: false,
    note: "hbUSDT is a dynamic DeFi strategy claim, not a proven ERC-4626 USDT vault. Do not bind erc4626-single-asset or count idle deposit-token balances as complete strategy backing.",
  },
  "fusd-finchain": {
    sourceUrl: "https://api.finchain.global/api/v0/fusd-data",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "FinChain composition API adapter only after source accounting freshness is repaired",
    freshnessEvidence: "Reviewed 2026-10-01: discovered official JSON reconciles three MMF holdings to 1,224,186.54 USD, but fusdlp.updated_at is 1776736295 (2026-04-21), despite the webpage's September 2026 label.",
    scoreGradePlausible: false,
    note: "The dated machine-readable payload is roughly 163 days old. Preserve its actual accounting clock; neither request_id, HTTP response time nor the webpage month can repair stale reserve data. No new binding until the publisher refreshes the source timestamp and values.",
  },
  "eurot-token-teknoloji": {
    sourceUrl: "https://www.token.com.tr/en/proof-of-reserves/",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "currency-scoped attestation adapter after current EUROT-specific balances exist",
    freshnessEvidence: "Reviewed 2026-10-01: official proof page remains modified August 9, 2024; its EUROT section links May 3 and July 24, 2024 shared bank PDFs, not a current currency-specific reserve balance.",
    scoreGradePlausible: false,
    note: "An HTML/PDF-index adapter would admit stale reports or select sibling-token disclosures from the shared page. No binding until a current EUROT reserve amount and balance date are published.",
  },
  "usdu-usdu-finance": {
    sourceUrl: "https://usdu.finance/wp-json/usdu-transparency/v1/backing-snapshot",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "USDU backing API with dated, noncircular vault and LP look-through",
    freshnessEvidence: "Reviewed 2026-10-01: official JSON returns total 57623.76703685068, Curve 22684.148785465073, Morpho 34939.618251385094 and dust TermMax, with no source timestamp or pinned block.",
    scoreGradePlausible: false,
    note: "The totals reconcile arithmetically but the Curve bucket contains USDU itself. A new API fetch is not dated reserve evidence and cannot value circular own-token collateral as exogenous dollar backing. Require source checkpoint and noncircular look-through before binding.",
  },
  "a7a5-old-vector": {
    sourceUrl: "https://docs.a7a5.io/legal/transparency.md",
    sourceQuality: "not-plausible",
    expectedAdapterFamily: "none until a dated reserve statement is published",
    freshnessEvidence: "Reviewed 2026-10-01: transparency supplies an issuance-channel statement only; audit.pdf still returns HTML rather than a reserve PDF.",
    scoreGradePlausible: false,
    note: "No measured reserve amount, composition, balance date or bank inventory was found on the primary transparency surfaces. Token issuance and an HTML application shell cannot refresh RUB reserves.",
  },
  "jpysc-sbi-startale": {
    sourceUrl: "https://www.shinseitrust.com/stablecoin/jpysc.html",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "issuer disclosure parser after accessible rolling balance statements",
    freshnessEvidence: "Reviewed 2026-10-01: the statutory page timed out in reader and direct HTTP probes; the September 7 allocation PDF is dated but not a rolling reserve source.",
    scoreGradePlausible: false,
    note: "A one-off announcement is not a reproducible current reserve feed. The PDF states 10億円 (JPY1bn) of short-term JGBs against about 201億円 (JPY20.1bn) issuance; the sidecar's JPY10bn source-label discrepancy was flagged to the coordinator. Do not encode that error in an adapter.",
  },
  "ggbr-goldfish-gold": {
    sourceUrl: "https://goldfishgold.com/collateral",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "none until dated mineral quantity/title and liability evidence reconcile",
    freshnessEvidence: "Reviewed 2026-10-01: the issuer asserts a fixed in-situ trust position; its collateral client reads wallet ETH and stamps local time.",
    scoreGradePlausible: false,
    note: "The dashboard client duplicates the insurance/fireblocks wallet, sums native ETH balances and derives issuedSupply as 75% of that sum. This is neither GGBR supply nor measured mineral reserves. No dated geological/trust reserve statement suitable for a live adapter was identified.",
  },
  "fusd-freedom-dollar": {
    sourceUrl: "https://www.freedomdollar.com/en/verify-reserves",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Zano reserve-wallet observer after a usable dated balance transport is published",
    freshnessEvidence: "Reviewed 2026-10-01: homepage reserve/supply/coverage fields render dashes; client chunks expose no functioning reserve transport.",
    scoreGradePlausible: false,
    note: "The issuer publishes a view-only tracking seed and desktop-wallet synchronization instructions, not a Worker-compatible dated reserve feed. Current reserve figures remain unavailable; historical September figures and access time must not become a new balance observation.",
  },
  "usdv-solomon-v2": {
    sourceUrl: "https://docs.solomonlabs.org/usdv/peg-stability-and-reserves/",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Chancery reserve/treasury reader after complete reserve scope is established",
    freshnessEvidence: "Reviewed 2026-10-01: finalized slots 452228749/751/796 observed supply 7234390.481688, authority USDC 475889.1294 and USDG 6758499.81; these are separate response slots.",
    scoreGradePlausible: false,
    note: "The protocol-data headline equals replacement supply but its itemized legacy Ceffu/derivatives buckets do not inventory Chancery backing. Authority accounts provide a selected nominal mix with a 1.542288-unit gap, not complete treasury/off-chain attribution or market-valued coverage. Do not bind the legacy solomon-protocol adapter or promote this selected scope to whole-reserve evidence.",
  },
  "hlscope-hamilton-lane": {
    sourceUrl: "https://www.hamiltonlane.com/en-us/strategies/evergreen/global/senior-credit-opportunities-fund",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "token-specific fund NAV/reserve attribution API",
    freshnessEvidence: "Reviewed 2026-10-01: the manager page dates share-class performance to 31/08/2026 and states monthly valuation; no hlSCOPE feeder inventory is exposed.",
    scoreGradePlausible: false,
    note: "Fund-wide fair market value, performance and target portfolio charts do not reconcile tokenized-feeder holdings or liabilities. Require dated NAV data with exact token/share-class identity and feeder attribution; a supply probe cannot verify private-credit assets.",
  },
  "stusd-stoneyield": {
    sourceUrl: "https://docs.stoneyield.io/docs/protocol/contract-design",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "stoneyield-router-pool (parked; identity/layout contradiction unresolved)",
    freshnessEvidence: "Reviewed 2026-10-01: docs describe an 18-decimal BSC USDC/Venus route; the September 30 sidecar read reports Venus vault asset() as USDC, while the parked adapter requires vUSDC.",
    scoreGradePlausible: false,
    note: "The existing adapter's required vault identity contradicts reviewed USDC lineage. Complete router/strategy backing and stUSD/sUSDC liability attribution remain unreconciled. Resolve contract semantics and the strategy census before revival; idle balance and supply probes omit deployed assets.",
  },
  "usdh-hermetica": {
    sourceUrl: "https://blog.hermetica.fi/archive",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "reviewed custodian-attestation parser after current structured composition is published",
    freshnessEvidence: "Reviewed 2026-10-01: the current archive's newest attestation measures August 20 at 14:00 UTC, published August 26; the reserve basis is 42 days old.",
    scoreGradePlausible: false,
    note: "The dated blog mixes prose and image disclosures without a stable composition schema, and the newest reserve basis exceeds the 33-day monthly-disclosure ceiling. Keep August STRCx/cash holdings historical. Reopen with current complete machine-readable holdings or a reviewed report manifest; access time cannot renew balances.",
  },
  "dusd-alto": {
    sourceUrl: "https://www.altofoundation.org/api/protocol-snapshot",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "complete Alto mint-market and USM reserve/liability adapter",
    freshnessEvidence: "Reviewed 2026-10-01: JSON generatedAt is 2026-10-01T07:57:35.123Z, but blockNumber is convex and market totals omit the USM reserve.",
    scoreGradePlausible: false,
    note: "The API is a market inventory, not complete DUSD backing: separately observed USM frxUSD is absent, and borrow-market supplied DUSD is not exogenous collateral. The sidecar is explicitly selected-slices and unreconciled to all supply. Require the complete USM/mint perimeter and coherent valuation before binding.",
  },
  "weusd-picwe": {
    sourceUrl: "https://docs.picwe.org/what-is-weusd",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "complete EVM and Movement mint-state reserve census",
    freshnessEvidence: "Reviewed 2026-10-01: docs dated April 27 still claim Phase 1 100% USDC and publish contract addresses but no dated reconciled reserve inventory.",
    scoreGradePlausible: false,
    note: "Current 1:1 USDC prose does not resolve the authored Movement dual-reserve state or insufficient EVM mint-contract balances. Require coherent collateral-account discovery and liabilities across native deployments. A single escrow or supply probe would publish a misleading partial reserve perimeter.",
  },
  "wclp-ripio": {
    sourceUrl: "https://action.ripio.com/en/wfiat-attestations",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "attestation-pdf-index (compatible but current report is stale)",
    freshnessEvidence: "Reviewed 2026-10-01: official HubSpot index exposes wCLP June 2026 certification with balance date 30/06/2026, now 93 days old.",
    scoreGradePlausible: false,
    note: "The existing PDF-index family fits, but its unchanged 33-day disclosure cap would reject this stale balance basis. The August upload-folder date and other currencies' reports cannot renew wCLP reserves. Reopen when Ripio publishes a current wCLP certification; no new parser is justified.",
  },
};

export const DEFAULT_SOURCE_QUALITY_NOTE: LiveReserveSourceQualityNote = {
  sourceUrl: null,
  sourceQuality: "unreviewed",
  expectedAdapterFamily: "unreviewed",
  freshnessEvidence: "Not reviewed in this source-quality pass.",
  scoreGradePlausible: false,
  note: "No source-quality note has been recorded yet.",
};
