export type LiveReserveSourceQuality =
  | "independent"
  | "static-validated"
  | "weak-proof"
  | "not-plausible"
  | "unreviewed";

export interface LiveReserveSourceQualityNote {
  sourceUrl: string | null;
  sourceQuality: LiveReserveSourceQuality;
  expectedAdapterFamily: string;
  freshnessEvidence: string;
  scoreGradePlausible: boolean;
  note: string;
}

/**
 * Reviewed source-quality dispositions for effective-unconfigured active coins.
 * RS7/RS8 primary probes were captured on 2026-10-07; their request times are
 * evidence of access, never substitutes for reserve accounting dates. Historical
 * sidecar pins remain historical. A plausible lead is not admitted live coverage.
 * The audit warns for inactive keys and effective live bindings; remove a note
 * when its binding is actually activated, including static-validated bindings.
 */
export const REVIEWED_LIVE_RESERVE_SOURCE_NOTES: Record<string, LiveReserveSourceQualityNote> = {
  "usdy-ondo-finance": {
    sourceUrl: "https://www.dropbox.com/scl/fo/375wdvar3rbc7o23nxsgp/ABoF-avpNclglsNxAeWZO_k/2026/09%20September?rlkey=4icqn1z9bez725wywr30fx52a&dl=0",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "runtime discovery retired 2026-10-08; manual reviewed holdings refresh retained",
    freshnessEvidence: "Reviewed 2026-10-07: Dropbox returns a proprietary JavaScript listing; newest complete daily inventory discovery is unverified. The suspended runtime config and executable were retired on October 8.",
    scoreGradePlausible: false,
    note: "A future source requires reliable complete daily archive discovery and the full tracked liability perimeter, including BVI rather than only LLC scope. Neither HTTP 200 nor a manual static generation establishes independent eligible composition.",
  },
  "cumiu-chinaamc": {
    sourceUrl: "https://www.chinaamc.com.hk/jeecg-boot/mainFund/fundQuery/getHoldingsDetail?fundID=USDDMMF&curLang=EN",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "ChinaAMC dated workbook or JSON holdings reader after denominator and instrument reconciliation",
    freshnessEvidence: "Reviewed 2026-10-07: current daily XLSX has C2=2026/10/07, 62 holdings rows, weights totaling 100.0514% and blank TotalNAV. The August 31 factsheet is a separate older basis.",
    scoreGradePlausible: false,
    note: "The largest 23.5664% Credit Agricole row lacks ISIN/instrument class and has zero quantity/price; several deposit maturities truncate. Require a reconciled current denominator and complete large-row identity. Do not borrow August categories, invent tolerance or normalize the discrepancy away.",
  },
  "a7a5-old-vector": {
    sourceUrl: "https://docs-en.a7a5.tech/legal/transparency.md",
    sourceQuality: "not-plausible",
    expectedAdapterFamily: "reserve disclosure or assurance reader after dated bank accounting exists",
    freshnessEvidence: "Reviewed 2026-10-07: the original docs host fails TLS; the official docs-en mirror provides an issuance-channel statement. audit.pdf returns HTML; October 7 distribution measures issuance.",
    scoreGradePlausible: false,
    note: "Require dated bank reserve inventory, matching liabilities and independent assurance. Network issuance and an HTML application shell do not measure RUB reserves; failed access is not zero backing.",
  },
  "ylds-figure": {
    sourceUrl: "https://www.sec.gov/Archives/edgar/data/1974395/000197439526000011/fcc-20260630.htm",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "native FCC qualified-assets report reader after current inventory and liability attribution",
    freshnessEvidence: "Reviewed 2026-10-07: direct SEC access returns 403. The June 30 unaudited quarterly schedule is 99 days old; the December 2025 KPMG inventory remains historical.",
    scoreGradePlausible: false,
    note: "Require reachable current qualified-assets inventory matched to native Provenance/Stellar YLDS certificates and liabilities. Do not reuse the removed Solana wYLDS wrapper probe or treat a fresh report download as current reserves.",
  },
  "sofid-sofi": {
    sourceUrl: "https://d32ijn7u0aqfv4.cloudfront.net/wp/wp-content/uploads/raw/SoFiUSD-Stablecoin-Attestation-Report-8.31.2026.pdf",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "sofid-reviewed-report for historical detail; independent assurance only after newest-series discovery",
    freshnessEvidence: "Reviewed 2026-10-07: the exact August 31 Deloitte examination is reachable; signature is September 30. Product/media indexes remain 403; a guessed September PDF returning AccessDenied does not prove absence.",
    scoreGradePlausible: false,
    note: "The report measures USD cash 314771112 and redeemable liabilities 308322426, excluding 6448686 issuer-held tokens from circulation. A pinned URL/hash can validate this historical report but cannot certify the newest series member. Preserve accounting basis and static-validated classification until authoritative complete index discovery exists.",
  },
  "usda-avalon": {
    sourceUrl: "https://docs.avalonfinance.xyz/avalon-btcfi-products/cedefi-cdp-usda.md",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Avalon complete CeDeFi custody and collateral census",
    freshnessEvidence: "Reviewed 2026-10-07: official Bitcoin-backed USDa CDP docs are reachable but publish no dated supply-weighted custody/collateral book.",
    scoreGradePlausible: false,
    note: "Require the complete tracked USDa custody, collateral and liability snapshot with a source timestamp. Selected on-chain pools omit CeDeFi scope; supply and eligible collateral prose cannot establish full reserves.",
  },
  "moveusd-cfx": {
    sourceUrl: "https://trust.cfx.to/",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "aggregate bank reserve and liability disclosure reader",
    freshnessEvidence: "Reviewed 2026-10-07: Trust Center segregation/FDIC-bank statements are standing disclosures. The documented ledger API is customer-scoped and keyed, not a public aggregate reserve book.",
    scoreGradePlausible: false,
    note: "Require public or authorized current aggregate bank balances and matched MoveUSD liabilities. Customer API keys or token liveness alone cannot independently verify all custodial deposits.",
  },
  "usdf-astherus": {
    sourceUrl: "https://docs.asterdex.com/usdf-stablecoin/overview/how-usdf-works.md",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Aster full strategy reserve and derivatives accounting reader",
    freshnessEvidence: "Reviewed 2026-10-07: issuer docs describe Ceffu custody, Binance strategy and T+1 terms but no dated assets, hedge/margin liabilities or matched reserve book.",
    scoreGradePlausible: false,
    note: "Require dated full USDF reserve accounting, derivatives and token liabilities. Mint deposits are deployed into strategies; the existing asUSDF wrapper measures a different holder claim and cannot measure base USDF backing.",
  },
  "pyusdx-moonpay": {
    sourceUrl: "https://www.moonpay.com/legal/pyusdx_terms",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "issuer-authorized PYUSD custody and all-chain PYUSDx liability reader",
    freshnessEvidence: "Reviewed 2026-10-07: terms promise 1:1 PYUSD mint/redemption; the M0 registry lists four chains/gateway, not dated custody quantities.",
    scoreGradePlausible: false,
    note: "Require authorized reserve addresses, observed PYUSD quantities and matched current all-chain PYUSDx liabilities. Deployment identity and terms do not prove custody; Saturn's custom-token extension has a different reserve scope.",
  },
  "ggbr-goldfish-gold": {
    sourceUrl: "https://goldfishgold.com/collateral",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "dated independent mineral title and quantity reconciliation",
    freshnessEvidence: "Reviewed 2026-10-07: the standing one-million-ounce/25-million-token claim and wallet/price refresh do not date in-situ mineral quantity or trust title.",
    scoreGradePlausible: false,
    note: "Require dated independent mineral/title inventory and same-basis GGBR liabilities. Dashboard wallet balances and local refresh time cannot verify geological reserves or ownership.",
  },
  "lisusd-lista": {
    sourceUrl: "https://docs.bsc.lista.org/for-developer/collateral-debt-position/smart-contract.md",
    sourceQuality: "independent",
    expectedAdapterFamily: "Lista Maker-style branches plus PSM and Venus D3M accounting",
    freshnessEvidence: "Reviewed 2026-10-07: official registry exposes 22 GemJoins, separate USDT PSM, VaultManager and Venus D3M. Complete valued receipts, issuance and global debt were not established.",
    scoreGradePlausible: false,
    note: "Require a complete same-block roster, receipt conversions/prices including BBTC/cemBTC/ceaBNBc, PSM/Venus assets and debt, and full supply reconciliation. Generic branch balances are only a component; Liquity ABIs are incompatible. Unknown categories must not be dropped into a known-only 100% book.",
  },
  "susdat-saturn": {
    sourceUrl: "https://raw.githubusercontent.com/saturn-organization/saturn-yield-dollar/main/docs/v2-deployment-runbook.md",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "composition-preserving saturn-susdat vault and recognized-module reader",
    freshnessEvidence: "Reviewed 2026-10-07: verified V2 totalAssets combines USDat, vested surplus, STRCon and legacy STRCMirror recognized values. Current accounting/module/oracle values were not pinned in this review.",
    scoreGradePlausible: false,
    note: "Require same-block proxy/module identities, asset, totalAssets, USDat balance, surplus, both recognizedValue terms and STRCon balance/oracle currency/as-of. Preserve the known STRCon/USDat split; a generic opaque pooledClaim or 100% parent USDat exposure would discard known composition. Nonzero unknown mirrors remain unresolved.",
  },
  "pmusd-precious-metals": {
    sourceUrl: "https://data.chain.link/feeds/ethereum/mainnet/ion-por",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "ION PoR plus pmUSD Treasury and TokenBlender claim reconciliation",
    freshnessEvidence: "Reviewed 2026-10-07: ION feed and pmUSD collateral leads return 429. Historical TokenBlender/ION.au observations are not current pmUSD accounting.",
    scoreGradePlausible: false,
    note: "Require reachable current feed evidence and pinned pmUSD Treasury/TokenBlender/ION.au quantities matched to pmUSD liabilities. Upstream gold PoR cannot replace the token-specific backing census; failed reads never imply zero reserves.",
  },
  "earnusd-lido": {
    sourceUrl: "https://points.mellow.finance/v1/vaults",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Mellow Vault/ShareManager/Oracle/RiskManager and subvault accounting reader",
    freshnessEvidence: "Reviewed 2026-10-07: Mellow JSON has lido-earn-usd aggregateTVL, without reserve checkpoint or subvault weights. APY updated_at dates APY, not portfolio holdings.",
    scoreGradePlausible: false,
    note: "Tracked ShareManager is not the separate ERC-4626 Vault. Require same-block two-subvault holdings, fees, pending queues and allocated/active-share denominator. Redemption queue telemetry does not supply composition; do not assume USDC cash or bind the wrong vault identity.",
  },
  "usdkg-gold-dollar": {
    sourceUrl: "https://www.usdkg.com/",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "post-cessation outstanding-liability and remaining-reserve disclosure reader",
    freshnessEvidence: "Reviewed 2026-10-07: transparency is 404; the official homepage announces termination under Order 639-t dated 2026-08-20. The November 2025 Kreston PDF remains historical.",
    scoreGradePlausible: false,
    note: "Require post-cessation outstanding liabilities and remaining gold/cash accounting; route and lifecycle review belongs to the catalog owners. The report predates issued supply and cessation. Neither smart-contract audits nor a fresh download renew its reserve basis.",
  },
  "msusd-metronome": {
    sourceUrl: "https://docs.metronome.io/metronome-synth/contracts.md",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Metronome synth-specific multichain collateral, debt and treasury reconciliation",
    freshnessEvidence: "Reviewed 2026-10-07: official contracts enumerate pools, MsUSDDebt/Synthetic and Treasury; shared msUSD/msETH/msBTC collateral is not token-specific allocation.",
    scoreGradePlausible: false,
    note: "Require same-block per-chain pools, debt, treasury and float with an evidenced synth allocation rule and reconciled cross-chain msUSD liabilities. Recovery/buyback/loan narratives and raw DepositToken TVL do not establish that allocation; branch-only normalization is insufficient.",
  },
  "nusd-neutrl": {
    sourceUrl: "https://cache.accountable.capital/dashboard/neutrl",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "accountable after the authorized dated portfolio feed recovers",
    freshnessEvidence: "Reviewed 2026-10-07: dashboard returns 503 with No data available/res err; no current composition or source timestamp. The August 13 sidecar remains historical.",
    scoreGradePlausible: false,
    note: "Reopen when the endpoint serves a complete dated reconciled reserve snapshot. Historical weights cannot replace an unavailable live payload; unavailable reserves must not become zero or a healthy empty portfolio.",
  },
  "tgbp-tokenised": {
    sourceUrl: "https://api.tgbp.io/api/v1/public/data/tgbp",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "timestamped complete bank composition reader after Worker access recovery",
    freshnessEvidence: "Reviewed 2026-10-07: aggregate collateral 20116187.48/supply 19992725.89 has no reserve clock/categories. August 31 Andersen AUP is expressly not assurance; transparency dates supply only. Config remains suspended for Worker 403.",
    scoreGradePlausible: false,
    note: "Require Worker-origin access plus current measured reserve dates and complete categories from an independent composition source. Do not borrow token-count time or an AUP signature to date bank reserves, or unsuspend the weak aggregate merely because workstation HTTP succeeds.",
  },
  "buck-bucket-protocol": {
    sourceUrl: "https://docs.bucketprotocol.io/user-guides/bucket-upgrade-and-migration",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Sui legacy V1 census with independently valued noncircular LP look-through",
    freshnessEvidence: "Reviewed 2026-10-07: BUCK V1 is exit-only with minting disabled; USDB V2 has a different book. Legacy registry lists identities only; July 27 checkpoint 303739938 remains historical.",
    scoreGradePlausible: false,
    note: "Require a current checkpoint-pinned V1 object/PSM/treasury and full liability census, plus LP underlying reserves/supply. LP face values may include BUCK itself. V2 collateral and partial custody/supply probes cannot establish legacy BUCK backing.",
  },
  "filqa-fidelity-international": {
    sourceUrl: "https://www.fidelityinternational.com/legal/documents/en/hffs.en.xx.6470869.pdf",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "token-class fund portfolio reader with legal pro-rata and denominator attribution",
    freshnessEvidence: "Reviewed 2026-10-07: direct factsheet access is 403. Existing July 31 whole-fund weights are 68 days old; September prospectus categories are eligible assets, not measured weights.",
    scoreGradePlausible: false,
    note: "Require reachable current dated token-class portfolio and token/fund share-liability reconciliation. Current NAV alone cannot update holdings or prove that the whole-fund allocations are the tracked token's attributed reserve book.",
  },
  "slvon-ondo": {
    sourceUrl: "https://app.ondo.finance/api/v2/assets/slvon/info",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Ondo token-specific SLV-share/cash-in-transit reserve accounting",
    freshnessEvidence: "Reviewed 2026-10-07: dated topHoldings says Physical Silver 100% for the underlying SLV ETF; token supply, TVL and market cap fields are null.",
    scoreGradePlausible: false,
    note: "Require dated issuer-owned SLV shares/cash-in-transit and matched SLVon liabilities. Underlying ETF gold/silver disclosures and pooled Global Markets reports do not establish this wrapper's allocation; retain the unresolved share/cash envelope.",
  },
  "aid-gaib": {
    sourceUrl: "https://aid.gaib.ai/transparency",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "GAIB dated facility fair-value and liquid-reserve accounting reader",
    freshnessEvidence: "Reviewed 2026-10-07: deployed module contains literal principal/remainingPrincipal; fetchedAt is the read clock. Google Drive report download is owner-restricted despite HTTP 200.",
    scoreGradePlausible: false,
    note: "Require publicly retrievable dated GPU facility accounting, liquid assets and matched AID liabilities. On-chain balances cannot date hardcoded loan NAV; HTML reachability cannot overcome a restricted report download.",
  },
  "usdo-openeden": {
    sourceUrl: "https://prod-gw.openeden.com/usdo/sys/reserve-composition-last",
    sourceQuality: "independent",
    expectedAdapterFamily: "executable retired 2026-10-08; a new complete reserve source and admissible Worker-origin fetch are required",
    freshnessEvidence: "Reviewed 2026-10-07: ordinary-client JSON date 2026-10-07T08:00:19.096Z reports reserves 15537989.483383574 and USDO 15275117.334802557; eight current component USD fields reconcile. Worker egress recovery is unverified.",
    scoreGradePlausible: true,
    note: "The operator retired the parked adapter on October 8; the October 7 ordinary-client capture remains historical evidence, not an access revival. PendingReserveAssetsRedeem and signed gap semantics remain unresolved: reserve/usdoAmount is not whole-economic-liability assurance or route openness. Any new source needs strict finite nonnegative components, keyed asset identity, complete liabilities and Worker-origin admission.",
  },
  "hollar-hydrated": {
    sourceUrl: "https://docs.hydration.net/products/hollar/",
    sourceQuality: "independent",
    expectedAdapterFamily: "new Substrate plus EVM HSM and shared-debt attribution reader",
    freshnessEvidence: "Reviewed 2026-10-07: official docs describe Aave-GHO and HSM yield strategies. Prior EVM facilitator census remains historical; RPC GET 405 requires POST and does not prove outage.",
    scoreGradePlausible: false,
    note: "Resolve native HSM module balances for assets 1002/1003, aUSDT/aUSDC receipt liquidity-index/oracle valuation and shared-market non-HOLLAR debt attribution at a common checkpoint. EVM buckets/supply alone omit native backing. hydration-hollar names a proposed family, not an existing registered adapter.",
  },
  "usdm-moneta": {
    sourceUrl: "https://moneta.global/transparency/",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Moneta/Charli3 measured reserve accounting reader",
    freshnessEvidence: "Reviewed 2026-10-07: the rendered page repeats 9609507.48 for reserve/supply and Verified on-chain/today without a reserve checkpoint or complete issuer allocation.",
    scoreGradePlausible: false,
    note: "Require a dated accounting payload covering all tracked issuer books and liabilities. Do not scrape literal display scalars as measured reserves or infer historical 80/20 allocations from undated eligible-category prose.",
  },
  "usdsm-stable-mint": {
    sourceUrl: "https://feed.stablemint.io/v1/supply/usdsm",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "dated cash/HQLA reserve reader joined to complete all-chain liabilities",
    freshnessEvidence: "Reviewed 2026-10-07: the feed timestamps cross-chain USDSM supply only. The issuer's 102% cash/HQLA claim publishes no dated measured asset amounts or allocations.",
    scoreGradePlausible: false,
    note: "Require current cash/HQLA asset amounts and categories with matching all-chain liability scope. Signed supply does not sign reserve composition; liability clocks and policy percentages cannot stand in for measured reserve accounting.",
  },
  "umint-ubs": {
    sourceUrl: "https://www.ubs.com/global/en/media/display-page-ndp/en-20241101-first-tokenized-investment-fund.html",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "exact uMINT fund/share accounting and current portfolio reader",
    freshnessEvidence: "Reviewed 2026-10-07: ordinary-client release fetch is 403; reader evidence covers 2024 launch/2025 subscriptions, without current portfolio or exact NAV/oracle source.",
    scoreGradePlausible: false,
    note: "Require current exact fund/share holdings, assets and share-liability attribution. Launch and subscription claims do not provide current inventory; do not invent Treasury weights or treat an access failure as absence of assets.",
  },
  "fusd-freedom-dollar": {
    sourceUrl: "https://www.freedomdollar.com/en",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "reproducible Zano wallet and matched fUSD supply observer",
    freshnessEvidence: "Reviewed 2026-10-07: homepage quantities and 0.96x coverage now render. Last updated lacks timezone/accounting semantics; view-only wallet instructions expose no reproducible Worker RPC/checkpoint.",
    scoreGradePlausible: false,
    note: "The old empty-dashboard claim is obsolete. Require reproducible wallet balances and matched fUSD supply at a block/time, or documented current accounting transport. The displayed shortfall remains an unadmitted observation; renderer/access time cannot establish accounting freshness.",
  },
  "mai-qidao": {
    sourceUrl: "https://docs.mai.finance/docs/functions/smart-contract-addresses",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "QiDao complete multichain vault, PSM, treasury and liability reader",
    freshnessEvidence: "Reviewed 2026-10-07: dashboard is a JavaScript shell without checkpoint. Official registry includes legacy vaults/PSMs, not a complete reconciled current book for the 15 tracked chain deployments.",
    scoreGradePlausible: false,
    note: "Require active chain-specific vault/PSM debts, receipt/LP pricing, treasury/residual assets and canonical/bridged supply with explicit cross-chain observation tolerance. Preserve CelsiusX/unpriced receipt uncertainty. Liquity ABIs and partial live normalization do not fit QiDao's full liability model.",
  },
  "kgst-kyrgyz-som": {
    sourceUrl: "https://www.kgstoken.kg/",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "dated KGS bank reserve disclosure or attestation reader",
    freshnessEvidence: "Reviewed 2026-10-07: cash/cash-equivalent and attestation claims remain undated, without a linked attestor report, reserve API or named bank allocations.",
    scoreGradePlausible: false,
    note: "Require dated measured KGS reserves/bank evidence and complete matching circulating liabilities. BNB/Tron supply observes tokens only; it cannot independently verify custodial bank deposits.",
  },
  "usp-pikudao": {
    sourceUrl: "https://public-api.piku.co/v1/tokens/usp",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "whole-USP strategy and buffer reserve accounting reader",
    freshnessEvidence: "Reviewed 2026-10-07: public JSON returns price, APY and 20 bps redemption fee, without reserve amounts, allocations or measurement clock.",
    scoreGradePlausible: false,
    note: "Require dated complete allocations, stable buffers, net strategy assets/liabilities and custody scope. Historical newsletter or single BMMF solvency cannot represent changing whole-USP strategies; price API success is not reserve measurement.",
  },
  "xgz-goldzip": {
    sourceUrl: "https://goldzip.info/transparency/",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "reviewed bullion inventory assurance or proof-of-reserve reader",
    freshnessEvidence: "Reviewed 2026-10-07: official transparency has loading/supply panels and promises report downloads, without dated custody quantities.",
    scoreGradePlausible: false,
    note: "Require a current dated independent bullion inventory reconciled to token liabilities. Supply multiplied by the one-ounce claim cannot establish custody, allocation or gold backing.",
  },
  "usda-anzens": {
    sourceUrl: "https://www.anzens.com/landing/terms-and-conditions",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Anzens product-specific reserve disclosure or assurance reader",
    freshnessEvidence: "Reviewed 2026-10-07: terms enumerate cash, Treasury bills and MMFs without dated amounts or allocations.",
    scoreGradePlausible: false,
    note: "Require current dated product-specific off-chain reserve accounting and matched liabilities. Cardano supply cannot validate custody. Anzens USDA and Anzen USDz are different issuers; anzen-usdz is not a suitable binding.",
  },
  "hlscope-hamilton-lane": {
    sourceUrl: "https://www.hamiltonlane.com/en-us/strategies/evergreen/global/senior-credit-opportunities-fund",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "exact tokenized feeder/share-class NAV and asset-liability attribution reader",
    freshnessEvidence: "Reviewed 2026-10-07: manager share-class performance remains dated 31/08/2026; no tokenized-feeder reserve accounting was found.",
    scoreGradePlausible: false,
    note: "Require exact feeder/share-class identity, dated NAV, assets and liabilities. Main-fund NAV, target allocations and monthly performance cannot establish tokenized-feeder holdings; supply cannot verify private-credit assets.",
  },
  "audf-forte": {
    sourceUrl: "https://www.forteaud.com/api/documents/view/audf-reserves-report-august-2026",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "independent-assurance manifest after fresh complete accounting and liabilities",
    freshnessEvidence: "Reviewed 2026-10-07: public REST document discovery exists and the extensionless report URL returns PDF bytes. Latest listed August 31 cash is AUD 5142851.53, signed September 7; bank unnamed and liabilities absent.",
    scoreGradePlausible: false,
    note: "Require a fresh complete scoped report and asset/liability reconciliation. Existing index parsing validates static slices only. Do not claim the endpoint is nonexistent, synthesize liability rows from 1:1 marketing, or expand the monthly source-age budget to admit the aged assets-only report.",
  },
  "usg-tangent": {
    sourceUrl: "https://docs.tangent.finance/docs/faq/contracts",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Tangent authorization census and productive-collateral valuation reader",
    freshnessEvidence: "Reviewed 2026-10-07: primary docs are reachable; the October 5 sidecar records a current 16-minter census, newer than the obsolete failed Control Tower retrieval note. Static docs list 12 markets.",
    scoreGradePlausible: false,
    note: "Require complete current authorization/market census and independent productive LP/PT valuation. The unresolved issue is full productive-collateral look-through, not absence of any market census. Historical partial decomposition or only the known frxUSD leg cannot establish complete backing.",
  },
  "gldon-ondo": {
    sourceUrl: "https://app.ondo.finance/api/v2/assets/gldon/info",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "GLDon-specific daily reserve and liability verification reader",
    freshnessEvidence: "Reviewed 2026-10-07: official info JSON exposes metadata/legal documents and underlying ETF descriptions; issuer docs promise daily Ankura verification, without retrieved GLDon-specific daily book.",
    scoreGradePlausible: false,
    note: "Require the actual GLDon-specific dated reserve/liability verification. Product createdAt is not a reserve date; underlying SPDR gold, OUSG or USDon inventories cannot substitute for GLDon issuer-owned ETF-share/cash accounting.",
  },
  "zaru-blocktower": {
    sourceUrl: "https://framerusercontent.com/assets/KsEvbTwWi32ctr1xYbVodL5yA8.pdf",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "AUP static report profile; assurance only after a current favorable engagement",
    freshnessEvidence: "Reviewed 2026-10-07: Moore report has July 31 basis, August 28 signature, ZAR cash 23314336.68 and MMF 30402618.53; explicitly ISRS 4400 agreed-upon procedures with no assurance opinion.",
    scoreGradePlausible: false,
    note: "Require a current favorable assurance engagement or independently measured complete reserve source. Preserve AUP/static-validated treatment; title, signature or fresh access cannot convert the historical procedures into independent assurance.",
  },
  "pht-pht": {
    sourceUrl: "https://docs.apacx.io/transparency",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "complete multichain multi-ilk collateral, debt and bridge census with PHP valuation",
    freshnessEvidence: "Reviewed 2026-10-07: transparency names one Tron collateral wallet; the historical Ethereum multi-ilk conflict and Tron pinning constraints remain unresolved.",
    scoreGradePlausible: false,
    note: "Require a complete dated multichain collateral/debt/bridge census with independent PHP valuation. Current prose cannot resolve historical lineage conflicts; a single Tron wallet cannot represent all liabilities or refresh historical chain observations.",
  },
  "cgo-comtech": {
    sourceUrl: "https://comtechgold.com/assets/pdf/ComTech%20FZCO%20-%20Gold%20Stock%20as%20on%2026th%20February%202026.pdf",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "current independent gold inventory and liability-linked report profile",
    freshnessEvidence: "Reviewed 2026-10-07: current product shell and fetched issuer-signed February 26 letter confirm 39 one-kilogram bars; this remains a historical issuer statement.",
    scoreGradePlausible: false,
    note: "Require current independent custody inventory reconciled to token liabilities. The self-signed stock letter is not current independent assurance; token supply or gold prices cannot refresh bullion quantities.",
  },
  "usdm-monetrix": {
    sourceUrl: "https://api.monetrix.xyz/data/api/collateral",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Monetrix parser after coherent gross/net overlap and debt accounting",
    freshnessEvidence: "Reviewed 2026-10-07: fresh asOf still reports backing.reconciled=false; spot 4423885.297397281, margin 445529.164104 and buffer -1296154.51325294 USD.",
    scoreGradePlausible: false,
    note: "Require a coherent publisher-defined gross/net overlap equation and debt perimeter. FULL_BACKED/stale=false labels cannot override failed reconciliation. Do not normalize positive rows, omit the negative buffer or publish headline total as validated reserves.",
  },
  "stusd-stoneyield": {
    sourceUrl: "https://docs.stoneyield.io/docs/protocol/contract-design",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "executable retired 2026-10-08; new reconciled whole-book source required",
    freshnessEvidence: "Reviewed 2026-10-07: official design describes an 18-decimal BSC USDC/Venus route. Historical September 30 sidecar reads show vault asset()=USDC; the retired adapter required vUSDC. No fresh complete accounting pin was established.",
    scoreGradePlausible: false,
    note: "Retirement does not resolve the adverse ledger. A new source must correct the vault identity model, separately value vault-held vUSDC at observed exchange rate and reconcile complete router/strategy assets with stUSD/sUSDC liabilities. Deleting the identity guard, idle-only accounting or naive ERC-4626 binding is insufficient.",
  },
  "gbpa-agant": {
    sourceUrl: "https://security.agant.io/",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "static report profile until engagement conflict and public discovery are resolved",
    freshnessEvidence: "Reviewed 2026-10-07: September 30 report gives GBP 597711.32 Griffin plus 1306302.77 State Street against 1900346.94 liabilities. Opening ISAE 3000 reasonable-assurance claim conflicts with final no-formal-assurance disclaimer.",
    scoreGradePlausible: false,
    note: "Require corrected engagement/report scope and stable public index discovery. Nephos states it is not a regulated UK auditor; do not select only the favorable opening text. Independent-assurance classification requires resolving the conflict, otherwise retain static validation.",
  },
  "hbusdt-hyperbeat": {
    sourceUrl: "https://docs.hyperbeat.org/hyperbeat-earn/usdt-vault",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Accountable complete strategy parser after source access recovery",
    freshnessEvidence: "Reviewed 2026-10-07: Accountable source DNS fails; a fresh pinned asset() call reverts on the tracked token. Accepted deposit tokens are documented, not deployed allocation.",
    scoreGradePlausible: false,
    note: "Require restored complete dated strategy accounting. DNS failure means unavailable evidence, not an empty portfolio. Reject erc4626-single-asset on the tracked token and idle deposit-token balances as full backing.",
  },
  "isc-international-stable-currency": {
    sourceUrl: "https://isc.money/api/reserve-balances",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "ISC measured holdings parser with source clock and self-held-token exclusion",
    freshnessEvidence: "Reviewed 2026-10-07: Reserve A/B JSON and composition coefficients still lack portfolio measurement time; holdings include substantial own ISC amounts.",
    scoreGradePlausible: false,
    note: "Require dated actual measured holdings, self-held ISC exclusion and liability reconciliation. Price history, coefficients or request time cannot date reserve composition or value circular own-token balances as independent backing.",
  },
  "usdh-hermetica": {
    sourceUrl: "https://blog.hermetica.fi/archive",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "composite mixed-custody/on-chain accounting reader with hedge attribution",
    freshnessEvidence: "Reviewed 2026-10-07: newest verified September post was published October 1 with September 30 14:00 UTC basis, within 33 days. Copper's signed image verifies aggregate BTC/USDT/USDC 472573.22, not category weights or the full book.",
    scoreGradePlausible: false,
    note: "The old August 20 staleness rejection is obsolete. Require complete independently measured mixed custody/on-chain assets and hedge netting/category attribution. Other locations and STRCx mark remain issuer statements; one-custodian assurance cannot certify the whole product.",
  },
  "fusd-finchain": {
    sourceUrl: "https://api.finchain.global/api/v0/fusd-data",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "FinChain API/bundle reader after publisher-defined accounting clock and ownership reconciliation",
    freshnessEvidence: "Reviewed 2026-10-07: three MMF-token amounts total 1224928.079620923 USD. Values changed since October 1 while fusdlp.updated_at=1776736295 (April 21) remained fixed; actual reserve clock is ambiguous.",
    scoreGradePlausible: false,
    note: "Require publisher clarification/repair of the reserve accounting clock, exact fund-share prices/ownership and matched liabilities. Do not assert every current value was measured in April; request_id, HTTP/UI time or a newer separate bundle sidecar cannot repair the API's accounting clock.",
  },
  "usdv-solomon": {
    sourceUrl: "https://data.solomonlabs.io/api/solomon-protocol/protocol-data",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "legacy executable retired 2026-10-08; new mint-specific reserve source required",
    freshnessEvidence: "Reviewed 2026-10-07: API headline TVL describes the replacement product; the tracked legacy mint has a distinct program/reserve perimeter.",
    scoreGradePlausible: false,
    note: "Require dated legacy-mint-specific reconciled reserves and liabilities. Do not bind replacement TVL to Ex5DaKYMCN6QWFA4n67TmMwsH8MJV68RX6YXTmVM532C, or treat futures custody notional as reserve NAV. Product migration prose does not establish an automatic conversion.",
  },
  "iusd-indigo-protocol": {
    sourceUrl: "https://analytics.indigoprotocol.io/api/cdps",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Cardano complete CDP, PSM, price and debt census at one finalized slot",
    freshnessEvidence: "Reviewed 2026-10-07: CDP JSON is reachable but UTxO/settlement rows lack a shared reserve ledger checkpoint. Prior 7.6906% unresolved residual is historical, not remeasured.",
    scoreGradePlausible: false,
    note: "Require complete same-finalized-slot CDPs, PSM assets, prices and debt/supply reconciliation. Per-position settlement or fresh HTTP access is not portfolio freshness; do not normalize surviving indexed debt to 100% or silently discard non-CDP liabilities.",
  },
  "dusd-alto": {
    sourceUrl: "https://www.altofoundation.org/api/protocol-snapshot",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "complete Alto USM/mint-market and noncircular LP/credit accounting reader",
    freshnessEvidence: "Reviewed 2026-10-07: generatedAt=2026-10-07T20:43:51.442Z, but blockNumber=convex and eight-market inventory omits the full USM reserve.",
    scoreGradePlausible: false,
    note: "Require a coherent complete USM and mint-market collateral/liability census with noncircular LP/credit valuation. Borrow-market DUSD supply is not external backing; a fresh generatedAt cannot cure missing reserve scope or an invalid ledger checkpoint.",
  },
  "dusd-dtrinity": {
    sourceUrl: "https://docs.dtrinity.org/protocol-components/dusd",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "chain-isolated dTRINITY liability, collateral and AMO/LP reader",
    freshnessEvidence: "Reviewed 2026-10-07: docs separate nonfungible Ethereum/Fraxtal/Katana deployments and deployed AMOs. The tracked Sonic perimeter remains unresolved; earlier decoded vault observations remain historical.",
    scoreGradePlausible: false,
    note: "Require exact per-deployment liabilities and complete noncircular deployed AMO/LP look-through. Idle vault totals omit AMOs; pooling isolated branches or substituting an Ethereum book for Sonic would misstate the tracked reserve perimeter.",
  },
  "zkusd-goal3": {
    sourceUrl: "https://explorer.zksync.io/address/0xfc7e56298657b002b3e656400e746b7212912757",
    sourceQuality: "not-plausible",
    expectedAdapterFamily: "reserve reader only after current proxy/custody identity and accounting exist",
    freshnessEvidence: "Reviewed 2026-10-07: explorer is a JavaScript shell. A newly pinned zero treasuryAddress() read targets the explicitly historical implementation, not a verified current proxy treasury.",
    scoreGradePlausible: false,
    note: "Require current primary deployment/custody identity and complete dated assets/liabilities. The historical implementation's zero getter proves neither zero current reserves nor proxy custody. Token liveness and historical deposit routing cannot establish present backing.",
  },
  "usdh-hubble": {
    sourceUrl: "https://docs.hubbleprotocol.io/resources/technical-resources",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "Hubble complete PSM/borrowing-market receipt valuation reader",
    freshnessEvidence: "Reviewed 2026-10-07: official vault identities are reachable; prior decoded PSM and three markets remain historical. Complete current LP/kToken/residual valuation is absent.",
    scoreGradePlausible: false,
    note: "Require coherent current Solana slot for collateral, receipts, PSM and liabilities, including LP/kToken look-through and residual assets without placeholder prices. A USDC-only PSM composition would omit CDP backing; decoding has already started and must not be described as absent.",
  },
  "eurw-newrails": {
    sourceUrl: "https://www.newrails.xyz/en/platform/eurw",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "EURW-specific current bank/fund reserve disclosure or assurance reader",
    freshnessEvidence: "Reviewed 2026-10-07: issuer/legal pages describe segregated EU bank/MMF reserves without dated measured allocations or reserve totals.",
    scoreGradePlausible: false,
    note: "Require current EURW-specific dated bank/fund amounts and matching liabilities. Eligible-asset prose cannot become allocation weights; the security audit is not a reserve audit.",
  },
  "scusd-rings": {
    sourceUrl: "https://api.veda.tech/",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "authorized Veda accounting or fully decoded BoringVault strategy reader",
    freshnessEvidence: "Reviewed 2026-10-07: Veda root returns 401; Trevee describes a multistrategy BoringVault and fresh pinned Ethereum totalAssets() reverts. Accepted-token lists do not measure holdings.",
    scoreGradePlausible: false,
    note: "Require readable authorized dated Veda accounting or complete verified strategy decoding. 401 means access failure, not an empty portfolio. ERC-4626, escrow and single-balance configs omit accountant/deployed positions and cannot establish full reserves.",
  },
  "fxd-fathom": {
    sourceUrl: "https://docs.fathom.fi/fxd-stablecoin/deployments/xdc-network",
    sourceQuality: "independent",
    expectedAdapterFamily: "evm-branch-balances only after independent psXDC rate and complete three-pool census",
    freshnessEvidence: "Reviewed 2026-10-07: primary docs identify XDC/CGO pools; dominant psXDC remains without a reviewed independent valuation rate. Empty supplemental quote query corroborates only lack of that quote.",
    scoreGradePlausible: false,
    note: "Require an independently measured psXDC receipt/market exchange rate and fresh complete three-pool collateral/debt census. Historical pool weights remain historical. Omitting psXDC or hardcoding 1:1 XDC would manufacture coverage; quote-service absence is not reserve proof.",
  },
  "weusd-picwe": {
    sourceUrl: "https://docs.picwe.org/what-is-weusd",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "complete EVM plus Movement mint-state collateral and liability census",
    freshnessEvidence: "Reviewed 2026-10-07: docs still claim Phase 1 USDC but do not reconcile historical Movement dual reserves and multichain issuance.",
    scoreGradePlausible: false,
    note: "Require complete collateral-account discovery and matched native EVM/Movement issuance. Current 1:1 prose cannot resolve prior dual-reserve state or historical balance gaps; a single escrow or supply read would omit reserve perimeter.",
  },
  "usdu-usdu-finance": {
    sourceUrl: "https://usdu.finance/wp-json/usdu-transparency/v1/backing-snapshot",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "dated USDU active-module census with noncircular LP/vault accounting",
    freshnessEvidence: "Reviewed 2026-10-07: JSON total 57625.89418, Curve 22686.27342, Morpho 34939.62076 and negligible TermMax lacks source timestamp/block; Curve includes own USDU.",
    scoreGradePlausible: false,
    note: "Require complete dated active modules, external LP/vault constituents and matched liabilities. Arithmetic reconciliation cannot cure circular own-USDU collateral or undated accounting; a fresh fetch must not supply the missing checkpoint.",
  },
  "eurot-token-teknoloji": {
    sourceUrl: "https://www.token.com.tr/en/proof-of-reserves/",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "current currency-scoped EUROT balance and liability report reader",
    freshnessEvidence: "Reviewed 2026-10-07: shared proof page links 2024 bank reports, not a current EUR-scoped EUROT reserve balance.",
    scoreGradePlausible: false,
    note: "Require a current EUR-specific amount, accounting date and liability reconciliation. Neither page metadata nor sibling-token reports can date EUROT reserves; reject unscoped report selection.",
  },
  "usdxl-last": {
    sourceUrl: "https://app.hypurrfi.com/",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "complete facilitator, borrower collateral/debt and USDT0 PSM reader",
    freshnessEvidence: "Reviewed 2026-10-07: authored evm-branch-balances config has been suspended since August 27; it measures pool cash, omits gross aToken collateral and USDT0 PSM. Docs expose unavailable content; Last publishes no reserve snapshot.",
    scoreGradePlausible: false,
    note: "Require current complete facilitator/borrower collateral, debts and PSM census, then repair or replace the suspended model. The effective registry is unconfigured despite an authored binding; never unsuspend the cash-only 17-branch roster to inflate coverage.",
  },
  "emxn-telcoin": {
    sourceUrl: "https://www.telco.in/en/digital-cash",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "current eMXN-specific reserve disclosure or assurance profile",
    freshnessEvidence: "Reviewed 2026-10-07: Digital Cash identifies the token and promises future attestations, without a dated eMXN report.",
    scoreGradePlausible: false,
    note: "Require current MXN-specific balances/report and liabilities. eUSD disclosures concern another currency/product; Polygon supply and promised publication cannot verify peso backing.",
  },
  "wclp-ripio": {
    sourceUrl: "https://action.ripio.com/en/wfiat-attestations",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "attestation-pdf-index only after a corrected current CLP certificate",
    freshnessEvidence: "Reviewed 2026-10-07: index links a June 30-named PDF, but actual procedures use March 31 token liabilities and conflicting ARS/CLP reserves; signed July 28. New retrieval does not resolve stale/conflicted scope.",
    scoreGradePlausible: false,
    note: "Require a corrected current currency-consistent CLP certificate. A compatible PDF-index family remains static-validated, not score-grade. Do not use upload folders, signature time or sibling-currency reports to refresh liabilities or resolve contradictions.",
  },
  "wpen-ripio": {
    sourceUrl: "https://action.ripio.com/en/wfiat-attestations",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "currency-scoped report reader after a current wPEN certificate exists",
    freshnessEvidence: "Reviewed 2026-10-07: reachable official index lists wARS/wBRL/wMXN/wCOP/wCLP, without a verified wPEN certificate.",
    scoreGradePlausible: false,
    note: "Require a current PEN-specific dated report and liability scope. An index no-match is unavailable evidence, not empty reserves; sibling-currency substitution and a no-match adapter binding are invalid.",
  },
  "jpysc-sbi-startale": {
    sourceUrl: "https://www.sbigroup.co.jp/news/pdf/group/2026/0907_a.pdf",
    sourceQuality: "static-validated",
    expectedAdapterFamily: "current complete trust-property statement and liability disclosure reader",
    freshnessEvidence: "Reviewed 2026-10-07: September 7 release measures JPY 1 billion short-term JGB investment against approximately JPY 20.1 billion issuance. Statutory-page access times out; announcement is not a rolling complete book.",
    scoreGradePlausible: false,
    note: "Require a current complete trust-property statement and exact liability scope. Do not infer a cash-only residual by subtraction or turn the statutory 50% investment ceiling into measured composition. The stated investment is JPY 1 billion, not JPY 10 billion.",
  },
  "inalpha-nest": {
    sourceUrl: "https://api.nest.credit/v1/vaults/nest-alpha-lp-vault/positions",
    sourceQuality: "weak-proof",
    expectedAdapterFamily: "nest-vault-positions after current complete position and accountant reconciliation",
    freshnessEvidence: "Reviewed 2026-10-07: current positions/price/last-price-update APIs respond but show dust NAV versus positions and February accountant clocks. The authored binding remains suspended.",
    scoreGradePlausible: false,
    note: "Require complete positions reconciled to current accountant prices and liabilities before revival. Reuse the existing Nest URLs, params and source keys rather than a new adapter; HTTP success and request time cannot renew February accounting.",
  },
};

export const DEFAULT_SOURCE_QUALITY_NOTE: LiveReserveSourceQualityNote = {
  sourceUrl: null,
  sourceQuality: "unreviewed",
  expectedAdapterFamily: "unreviewed",
  freshnessEvidence: "Not reviewed in this source-quality pass.",
  scoreGradePlausible: false,
  note: "No source-quality note has been recorded yet.",
};
