import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { gunzipSync } from "node:zlib";
import { describe, expect, it, vi } from "vitest";
import {
  buildWorkerStablecoinCatalog,
  renderWorkerStablecoinCatalog,
} from "../build-data/generate-worker-stablecoin-catalog";
import { syncGeneratedArtifacts } from "../lib/generated-artifacts";

const hash = (text: string) => createHash("sha256").update(text).digest("hex");
const decode = (row: [string, number, string]) => gunzipSync(Buffer.from(row[2], "base64"), {
  maxOutputLength: row[1],
}).toString("utf8");

describe("lossless Worker full catalog generator", () => {
  it("uses the pinned compressor's fixed timestamp vector across Node versions", () => {
    expect(buildWorkerStablecoinCatalog([{ id: "fixed", evidence: null }])).toEqual({
      version: 1,
      maxUncompressedBytes: 30,
      coins: [["fixed", 30, "H4sIAAAAAAACA6tWykxRslJKy6xITVHSUUoty0xJzUtOVbLKK83JqQUATPv9KR4AAAA="]],
    });
  });
  it("preserves complete records, explicit nulls, source order, and deterministic bytes", () => {
    const records = [
      { id: "z", status: "frozen", evidence: { note: "€ 🪙", empty: null, list: [false, 0, ""] } },
      { id: "a", liveReservesConfig: { suspended: true }, extra: { anyFutureField: "retained" } },
    ];
    const artifact = buildWorkerStablecoinCatalog(records);
    expect(artifact.coins.map((row) => row[0])).toEqual(["z", "a"]);
    expect(artifact.coins.map((row) => JSON.parse(decode(row)))).toEqual(records);
    expect(artifact.maxUncompressedBytes).toBe(Math.max(...artifact.coins.map((row) => row[1])));
    expect(renderWorkerStablecoinCatalog(records)).toBe(renderWorkerStablecoinCatalog(records));
    for (const row of artifact.coins) {
      expect(Buffer.from(decode(row), "utf8").length).toBe(row[1]);
      expect(Buffer.from(row[2], "base64").subarray(4, 8)).toEqual(Buffer.alloc(4));
    }
    expect(buildWorkerStablecoinCatalog([])).toEqual({ version: 1, maxUncompressedBytes: 0, coins: [] });
  });

  it("matches every canonical source record and serialized hash without lifecycle normalization", () => {
    const records = JSON.parse(readFileSync(new URL("../../shared/data/stablecoins/coins.generated.json", import.meta.url), "utf8"));
    const artifact = buildWorkerStablecoinCatalog(records);
    expect(artifact.coins).toHaveLength(records.length);
    artifact.coins.forEach((row, index) => {
      expect(row[0]).toBe(records[index].id);
      expect(hash(decode(row))).toBe(hash(JSON.stringify(records[index])));
      expect(JSON.parse(decode(row))).toEqual(records[index]);
    });
  });

  it("changes only the affected packed row when any full-record evidence changes", () => {
    const before = [{ id: "one", evidence: null }, { id: "two", evidence: "unchanged" }];
    const after = [{ id: "one", evidence: { proof: "new" } }, before[1]];
    const a = buildWorkerStablecoinCatalog(before);
    const b = buildWorkerStablecoinCatalog(after);
    expect(a.coins[0]).not.toEqual(b.coins[0]);
    expect(a.coins[1]).toEqual(b.coins[1]);
  });

  it("rejects stale generated bytes in check mode without overwriting the output", () => {
    const directory = mkdtempSync(join(tmpdir(), "pharos-worker-catalog-"));
    const output = join(directory, "catalog.json");
    const error = vi.spyOn(console, "error").mockImplementation(() => {});
    const exit = vi.spyOn(process, "exit").mockImplementation(() => { throw new Error("stale artifact"); });
    try {
      const stale = renderWorkerStablecoinCatalog([{ id: "coin", evidence: null }]);
      writeFileSync(output, stale);
      expect(() => syncGeneratedArtifacts({
        artifacts: [{ path: output, contents: renderWorkerStablecoinCatalog([{ id: "coin", evidence: "updated" }]) }],
        check: true, staleMessage: "stale", currentMessage: "current", writtenMessage: "written",
      })).toThrow("stale artifact");
      expect(exit).toHaveBeenCalledWith(1);
      expect(readFileSync(output, "utf8")).toBe(stale);
    } finally {
      exit.mockRestore();
      error.mockRestore();
      rmSync(directory, { recursive: true });
    }
  });
});
