import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { parse as parseYaml } from "yaml";
import { z } from "zod";

const stepSchema = z.object({
  id: z.string().optional(), name: z.string().optional(), uses: z.string().optional(), run: z.string().optional(),
  if: z.string().optional(), "continue-on-error": z.boolean().optional(),
  with: z.record(z.string(), z.unknown()).default({}),
});
const readYaml = (path: string): unknown => parseYaml(readFileSync(resolve(process.cwd(), path), "utf8"));
const { runs: { steps } } = z.object({ runs: z.object({ steps: z.array(stepSchema) }) })
  .parse(readYaml(".github/actions/setup-workspace/action.yml"));

describe("setup-workspace caches", () => {
  it("guards generated bytes before publishing the required workspace", () => {
    const bootstrap = steps.findIndex((step) => step.run === "npm run bootstrap:generated:history");
    const guard = steps.findIndex((step) => step.name === "Verify bootstrap preserved committed artifacts");
    const upload = steps.findIndex((step) => step.uses?.startsWith("actions/upload-artifact@"));
    expect(bootstrap).toBeGreaterThan(-1);
    expect(guard).toBeGreaterThan(bootstrap);
    expect(upload).toBeGreaterThan(guard);
    expect(steps[guard]["continue-on-error"]).toBeUndefined();
  });

  it("keeps static, Next and browser state independently restorable", () => {
    const cache = (prefix: string) => steps.find((step) => String(step.with.key).startsWith(prefix))!;
    expect(z.string().parse(cache("static-cache-").with.path).trim().split("\n"))
      .toEqual([".cache/eslint", "*.tsbuildinfo", "worker/*.tsbuildinfo"]);
    expect(cache("next-cache-").with.path).toBe(".next/cache");
    expect(cache("browser-cache-").with.path).toBe("~/.cache/ms-playwright");
    expect(cache("static-cache-").uses).toMatch(/^actions\/cache\/restore@/);
  });

  it("lets the nightly writer publish static state only after its checks", () => {
    const workflow = z.object({ jobs: z.record(z.string(), z.object({ steps: z.array(stepSchema) })) })
      .parse(readYaml(".github/workflows/nightly-validation.yml"));
    const nightly = workflow.jobs["full-static"].steps;
    const save = nightly.findIndex((step) => step.uses?.startsWith("actions/cache/save@"));
    expect(save).toBeGreaterThan(nightly.findIndex((step) => step.run === "npm run check:structural"));
    expect(nightly[save].with.key).toBe("${{ steps.workspace.outputs.static-cache-key }}");
    expect(steps.some((step) => step.uses?.startsWith("actions/cache/save@"))).toBe(false);
  });

  it.each([["24.16.0", "24"], ["v26.1.0", "26"], ["lts/*", "lts--"]])("normalizes Node %s into a usable cache key", (version, expected) => {
    const root = mkdtempSync(join(tmpdir(), "pharos-cache-key-"));
    try {
      const output = join(root, "output");
      execFileSync("bash", ["-e", "-c", steps.find((step) => step.id === "cache-key")!.run!], {
        env: { ...process.env, RAW_NODE_VERSION: version, GITHUB_OUTPUT: output },
      });
      expect(readFileSync(output, "utf8")).toBe(`node-key=${expected}\n`);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it.each(["generated", "history"])("runs the %s bootstrap only with dependencies and its explicit input enabled", (kind) => {
    const command = kind === "generated" ? "npm run bootstrap:generated" : "npm run bootstrap:generated:history";
    const input = kind === "generated" ? "bootstrap-generated" : "bootstrap-history";
    expect(steps.find((step) => step.run === command)?.if)
      .toBe(`\${{ inputs.install-deps == 'true' && inputs.${input} == 'true' }}`);
  });

  it.each(["chromium", "firefox"])("installs %s only on explicit request", (browser) => {
    const install = steps.find((step) => step.run === `npx --no-install playwright install --with-deps ${browser}`)!;
    expect(install.if).toBe(`\${{ inputs.install-playwright-${browser} == 'true' }}`);
  });
});
