import { execFileSync, spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { parse as parseYaml } from "yaml";
import { z } from "zod";

const stepSchema = z.object({
  id: z.string().optional(), name: z.string().optional(), uses: z.string().optional(), run: z.string().optional(),
  if: z.string().optional(), "continue-on-error": z.boolean().optional(),
  with: z.record(z.string(), z.unknown()).default({}),
  env: z.record(z.string(), z.unknown()).default({}),
});
const readYaml = (path: string): unknown => parseYaml(readFileSync(resolve(process.cwd(), path), "utf8"));
const { inputs, outputs, runs: { steps } } = z.object({
  inputs: z.record(z.string(), z.object({ default: z.string() })),
  outputs: z.record(z.string(), z.object({ value: z.string() })),
  runs: z.object({ steps: z.array(stepSchema) }),
})
  .parse(readYaml(".github/actions/setup-workspace/action.yml"));

describe("setup-workspace caches", () => {
  it("guards generated bytes before publishing the required workspace", () => {
    const bootstrap = steps.findIndex((step) => step.run === "npm run bootstrap:generated:history");
    const guard = steps.findIndex((step) => step.name === "Verify bootstrap preserved committed artifacts");
    const restore = steps.findIndex((step) => step.run?.startsWith("tar --zstd -xf"));
    const pack = steps.findIndex((step) => step.name === "Package required workspace");
    const upload = steps.findIndex((step) => step.uses?.startsWith("actions/upload-artifact@"));
    expect(bootstrap).toBeGreaterThan(-1);
    expect(guard).toBeGreaterThan(bootstrap);
    expect(restore).toBeGreaterThan(-1);
    expect(guard).toBeGreaterThan(restore);
    expect(pack).toBeGreaterThan(guard);
    expect(upload).toBeGreaterThan(pack);
    expect(steps[guard]["continue-on-error"]).toBeUndefined();
    expect(steps[guard].if).toBe("${{ inputs.workspace-artifact != 'none' || (inputs.install-deps == 'true' && inputs.bootstrap-generated == 'true') }}");
  });

  it("publishes and restores the same run-scoped zstd archive without redundant upload compression", () => {
    const pack = steps.find((step) => step.name === "Package required workspace")!;
    const upload = steps.find((step) => step.uses?.startsWith("actions/upload-artifact@"))!;
    const download = steps.find((step) => step.uses?.startsWith("actions/download-artifact@"))!;
    const restore = steps.find((step) => step.run?.startsWith("tar --zstd -xf"))!;
    expect(pack.run).toContain(`tar -I 'zstd -T0 -3' -cf "\${RUNNER_TEMP}/pharos-workspace/workspace.tar.zst" "\${paths[@]}"`);
    expect(restore.run).toBe('tar --zstd -xf "${RUNNER_TEMP}/pharos-workspace/workspace.tar.zst" --same-permissions');
    expect(restore.if).toBe("${{ inputs.workspace-artifact == 'restore' }}");
    expect(upload.with.path).toBe("${{ runner.temp }}/pharos-workspace/workspace.tar.zst");
    expect(upload.with["compression-level"]).toBe(0);
    expect(upload.with["if-no-files-found"]).toBe("error");
    expect(upload.with.name).toBe("${{ steps.workspace-artifact-name.outputs.name }}");
    expect(download.with.name).toBe(upload.with.name);
    expect(outputs["workspace-artifact-name"].value).toBe(upload.with.name);
    expect(pack.run).not.toContain("--dereference");
    expect(z.string().parse(pack.env.WORKSPACE_PATHS).trim().split("\n")).toContain("node_modules");
    expect(pack.run).toContain("if [ -d worker/node_modules ]; then paths+=(worker/node_modules); fi");
    expect(pack.run).toContain("if [ -f .tmp/pr-test-plan.json ]; then paths+=(.tmp/pr-test-plan.json); fi");
  });

  it("publishes the producer attempt and restores that name unchanged on a partial rerun", () => {
    const resolver = steps.find((step) => step.id === "workspace-artifact-name")!;
    const download = steps.find((step) => step.uses?.startsWith("actions/download-artifact@"))!;
    expect(resolver.env.WORKSPACE_ARTIFACT_NAME).toBe("${{ inputs.workspace-artifact-name }}");
    expect(resolver.run).not.toContain("${{");
    expect(steps.indexOf(resolver)).toBeLessThan(steps.indexOf(download));
    const root = mkdtempSync(join(tmpdir(), "pharos-workspace-name-"));
    try {
      const output = join(root, "output");
      const env = {
        ...process.env, GITHUB_RUN_ID: "123", GITHUB_RUN_ATTEMPT: "2",
        GITHUB_SHA: "a".repeat(40), GITHUB_OUTPUT: output,
      };
      const run = (mode: string, name: string) => spawnSync("bash", ["-e", "-c", resolver.run!], {
        env: { ...env, WORKSPACE_ARTIFACT_MODE: mode, WORKSPACE_ARTIFACT_NAME: name },
        encoding: "utf8",
      });
      expect(run("publish", "").status).toBe(0);
      expect(readFileSync(output, "utf8")).toBe(`name=pr-workspace-123-2-${env.GITHUB_SHA}\n`);
      rmSync(output);
      const producerName = `pr-workspace-123-1-${env.GITHUB_SHA}`;
      expect(run("restore", producerName).status).toBe(0);
      expect(readFileSync(output, "utf8")).toBe(`name=${producerName}\n`);
      rmSync(output);
      for (const name of [
        "", `pr-workspace-456-1-${env.GITHUB_SHA}`, "pr-workspace-123-1-" + "b".repeat(40),
        `pr-workspace-123-0-${env.GITHUB_SHA}`, `${producerName}\ninjected=value`,
        `$(touch ${join(root, "injected")})`,
      ]) {
        expect(run("restore", name).status).toBe(1);
      }
      expect(() => readFileSync(output)).toThrow();
      expect(() => readFileSync(join(root, "injected"))).toThrow();
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("supports a second publish-only invocation without reinstalling dependencies or caching npm", () => {
    const node = steps.filter((step) => step.uses?.startsWith("actions/setup-node@"));
    expect(node).toHaveLength(2);
    expect(node.find((step) => step.with.cache === "npm")?.if).toBe("${{ inputs.cache-npm == 'true' }}");
    const uncached = node.find((step) => step.with.cache === undefined)!;
    expect(uncached.if).toBe("${{ inputs.cache-npm != 'true' }}");
    expect(uncached.with["node-version"]).toBe("${{ inputs.node-version }}");
    expect(uncached.with["cache-dependency-path"]).toBeUndefined();
    expect(steps.find((step) => step.run === "npm ci")?.if).toBe("${{ inputs.install-deps == 'true' }}");
    expect(steps.find((step) => step.name === "Package required workspace")?.if)
      .toBe("${{ inputs.workspace-artifact == 'publish' }}");
    expect(steps.find((step) => step.uses?.startsWith("actions/upload-artifact@"))?.if)
      .toBe("${{ inputs.workspace-artifact == 'publish' }}");
  });

  it("installs pinned ripgrep only on request and verifies its official sha256 before extraction", () => {
    const install = steps.find((step) => step.name === "Install verified ripgrep")!;
    const run = install.run!;
    expect(inputs["install-ripgrep"].default).toBe("false");
    expect(install.if).toBe("${{ inputs.install-ripgrep == 'true' }}");
    expect(run).toContain("set -euo pipefail");
    expect(run).toContain('version="15.2.0"');
    expect(run).toContain('sha256="33e15bcf1624b25cdd2a55813a47a2f95dbe126268203e76aa6a585d1e7b149c"');
    expect(run).toContain("https://github.com/BurntSushi/ripgrep/releases/download/15.2.0/ripgrep-15.2.0-x86_64-unknown-linux-musl.tar.gz.sha256");
    expect(run).toContain('package="ripgrep-${version}-x86_64-unknown-linux-musl"');
    expect(run).toContain('curl --fail --location --silent --show-error');
    expect(run).toContain('"https://github.com/BurntSushi/ripgrep/releases/download/${version}/${package}.tar.gz"');
    const verify = run.indexOf(`printf '%s  %s\\n' "\${sha256}" "\${archive}" | sha256sum --check --strict`);
    expect(verify).toBeGreaterThan(run.indexOf("curl --fail"));
    expect(run.indexOf('tar -xzf "${archive}"')).toBeGreaterThan(verify);
    expect(run.indexOf('sudo install -m 755 "${root}/rg" /usr/local/bin/rg')).toBeGreaterThan(verify);
    expect(run).not.toContain("GITHUB_PATH");
    expect(install["continue-on-error"]).toBeUndefined();
  });

  it.each([["Darwin", "X64"], ["Linux", "ARM64"]])("rejects ripgrep installation on %s/%s before downloading", (os, arch) => {
    const run = steps.find((step) => step.name === "Install verified ripgrep")!.run!;
    const result = spawnSync("bash", ["-e", "-c", run], {
      env: { ...process.env, RUNNER_OS: os, RUNNER_ARCH: arch },
      encoding: "utf8",
    });
    expect(result.status).toBe(1);
    expect(result.stdout).toContain(`install-ripgrep supports Linux x64 runners only (got ${os}/${arch}).`);
  });

  it("keeps static, Next and browser state independently restorable", () => {
    const cache = (prefix: string) => steps.find((step) => String(step.with.key).startsWith(prefix))!;
    expect(z.string().parse(cache("static-cache-").with.path).trim().split("\n"))
      .toEqual([".cache/eslint", "*.tsbuildinfo", "worker/*.tsbuildinfo"]);
    expect(cache("next-cache-").with.path).toBe(".next/cache");
    expect(cache("browser-cache-").with.path).toBe("~/.cache/ms-playwright");
    expect(cache("static-cache-").uses).toMatch(/^actions\/cache\/restore@/);
  });

  it("publishes validated lint and compiler state before unrelated nightly guards can fail", () => {
    const workflow = z.object({ jobs: z.record(z.string(), z.object({ steps: z.array(stepSchema) })) })
      .parse(readYaml(".github/workflows/nightly-validation.yml"));
    const nightly = workflow.jobs["full-static"].steps;
    const save = nightly.findIndex((step) => step.uses?.startsWith("actions/cache/save@"));
    expect(save).toBeGreaterThan(-1);
    for (const command of ["lint", "typecheck", "typecheck:worker"]) {
      const index = nightly.findIndex((step) => step.run === `npm run ${command}`);
      expect(index).toBeGreaterThan(-1);
      expect(index).toBeLessThan(save);
      expect(nightly[index]["continue-on-error"]).toBeUndefined();
      expect(nightly[index].if).toBeUndefined();
    }
    expect(nightly[save - 1].run).toBe("npm run typecheck:worker");
    expect(nightly[save + 1].run).toBe("npm run lint:typed");
    expect(nightly[save].if).toBeUndefined();
    expect(nightly[save]["continue-on-error"]).toBeUndefined();
    expect(nightly[save].with.key).toBe("${{ steps.workspace.outputs.static-cache-key }}");
    expect(steps.some((step) => step.uses?.startsWith("actions/cache/save@"))).toBe(false);
  });

  it.each([["24.16.0", "24"], ["v26.1.0", "26"], ["lts/*", "lts--"]])("normalizes Node %s into a usable cache key", (version, expected) => {
    const root = mkdtempSync(join(tmpdir(), "pharos-cache-key-"));
    try {
      const output = join(root, "output");
      execFileSync("bash", ["-e", "-c", steps.find((step) => step.id === "cache-key")!.run!], {
        env: { ...process.env, RAW_NODE_VERSION: version, GITHUB_OUTPUT: output },
      });
      expect(readFileSync(output, "utf8")).toBe(`node-key=${expected}\n`);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it.each(["generated", "history"])("runs the %s bootstrap only with dependencies and its explicit input enabled", (kind) => {
    const command = kind === "generated" ? "npm run bootstrap:generated" : "npm run bootstrap:generated:history";
    const input = kind === "generated" ? "bootstrap-generated" : "bootstrap-history";
    expect(steps.find((step) => step.run === command)?.if)
      .toBe(`\${{ inputs.install-deps == 'true' && inputs.${input} == 'true' }}`);
  });

  it.each(["chromium", "firefox"])("installs %s only on explicit request", (browser) => {
    const install = steps.find((step) => step.run === `npx --no-install playwright install --with-deps ${browser}`)!;
    expect(install.if).toBe(`\${{ inputs.install-playwright-${browser} == 'true' }}`);
  });
});
