/** Captured from the eleven physical wrapper routes before their removal. */
export const LEGACY_CHANGELOG_ROUTE_FIXTURES = [
  {
    slug: "blacklist-tracker-changelog",
    path: "/methodology/blacklist-tracker-changelog/",
    metadataTitle: "Blacklist Tracker Changelog: Version History",
    metadataDescription: "Full version history of the Pharos Blacklist Tracker methodology, from v1.0 through v4.0. Every event-coverage, cursor, and enrichment revision documented.",
    breadcrumbName: "Blacklist Tracker Changelog",
    pageTitle: "Blacklist Tracker Changelog",
    datePublished: "2026-02-09",
    dateModified: "2026-08-11",
    citationUrn: "urn:pharos:methodology:blacklist-tracker@v4.0",
  },
  {
    slug: "chain-health-changelog",
    path: "/methodology/chain-health-changelog/",
    metadataTitle: "Chain Health Score Changelog: Version History",
    metadataDescription: "Full version history of the Pharos Chain Health Score methodology, from v1.0 through v1.5. Every weight, factor, and tier revision documented.",
    breadcrumbName: "Chain Health Changelog",
    pageTitle: "Chain Health Score Changelog",
    datePublished: "2026-03-16",
    dateModified: "2026-08-10",
    citationUrn: "urn:pharos:methodology:chain-health@v1.5",
  },
  {
    slug: "depeg-changelog",
    path: "/methodology/depeg-changelog/",
    metadataTitle: "Depeg Tracker + DEWS Changelog - Version History",
    metadataDescription: "Full version history of the Pharos Depeg Tracker + DEWS methodology, from v1.0 through v6.21. Every threshold, formula, and confirmation-policy revision documented.",
    breadcrumbName: "Depeg Tracker + DEWS Changelog",
    pageTitle: "Depeg Tracker + DEWS Changelog",
    datePublished: "2026-02-18",
    dateModified: "2026-08-12",
    citationUrn: "urn:pharos:methodology:dews@v6.21",
  },
  {
    slug: "depeg-resolver-changelog",
    path: "/methodology/depeg-resolver-changelog/",
    metadataTitle: "Depeg Duration Resolver Changelog: Version History",
    metadataDescription: "Full version history of the Pharos Depeg Duration Resolver methodology, from v1.0 through v4.3. Every resolution-rubric, stratification, and support-gate revision documented.",
    breadcrumbName: "Depeg Duration Resolver Changelog",
    pageTitle: "Depeg Duration Resolver Changelog",
    datePublished: "2026-05-25",
    dateModified: "2026-08-23",
    citationUrn: "urn:pharos:methodology:depeg-resolver@v4.3",
  },
  {
    slug: "liquidity-score-changelog",
    path: "/methodology/liquidity-score-changelog/",
    metadataTitle: "Liquidity Score Changelog - Version History",
    metadataDescription: "Full version history of the Pharos Liquidity Score methodology, from v1.0 through v6.2. Every scoring and normalization revision documented.",
    breadcrumbName: "Liquidity Score Changelog",
    pageTitle: "Liquidity Score Changelog",
    datePublished: "2026-02-19",
    dateModified: "2026-09-01",
    citationUrn: "urn:pharos:methodology:liquidity-score@v6.2",
  },
  {
    slug: "mint-burn-flow-changelog",
    path: "/methodology/mint-burn-flow-changelog/",
    metadataTitle: "Mint/Burn Flow Changelog - Version History",
    metadataDescription: "Full version history of the Pharos Mint/Burn Flow methodology, from v1.0 through v6.191. Every scoring and ingestion-policy revision documented.",
    breadcrumbName: "Mint/Burn Flow Changelog",
    pageTitle: "Mint/Burn Flow Changelog",
    datePublished: "2026-03-01",
    dateModified: "2026-08-21",
    citationUrn: "urn:pharos:methodology:mint-burn-flow@v6.191",
  },
  {
    slug: "pricing-pipeline-changelog",
    path: "/methodology/pricing-pipeline-changelog/",
    metadataTitle: "Pricing Pipeline Changelog - Version History",
    metadataDescription: "Full version history of the Pharos Pricing Pipeline methodology, from v1.0 through v6.213. Every source addition and consensus algorithm revision documented.",
    breadcrumbName: "Pricing Pipeline Changelog",
    pageTitle: "Pricing Pipeline Changelog",
    datePublished: "2026-02-01",
    dateModified: "2026-08-30",
    citationUrn: "urn:pharos:methodology:pricing-pipeline@v6.213",
  },
  {
    slug: "redemption-backstop-changelog",
    path: "/methodology/redemption-backstop-changelog/",
    metadataTitle: "Redemption Backstop Changelog - Version History",
    metadataDescription: "Full version history of the Pharos Redemption Backstop route methodology, including its v1.0 through v4.4 scoring changes.",
    breadcrumbName: "Redemption Backstop Changelog",
    pageTitle: "Redemption Backstop Changelog",
    datePublished: "2026-02-28",
    dateModified: "2026-08-26",
    citationUrn: "urn:pharos:methodology:redemption-backstop@v4.4",
  },
  {
    slug: "scoring-changelog",
    path: "/methodology/scoring-changelog/",
    metadataTitle: "Safety Scores Changelog: Version History",
    metadataDescription: "Safety Score methodology history from V1 through active V9.451, including the retained historical V8 methodology.",
    breadcrumbName: "Scoring Changelog",
    pageTitle: "Safety Scores Changelog",
    datePublished: "2026-02-25",
    dateModified: "2026-09-01",
    citationUrn: "urn:pharos:methodology:safety-score@v9.451",
  },
  {
    slug: "stability-index-changelog",
    path: "/methodology/stability-index-changelog/",
    metadataTitle: "Stability Index Changelog: Version History",
    metadataDescription: "Full version history of the Pharos Stability Index methodology, from v1.0 through v3.61. Every formula, cap, and component revision documented.",
    breadcrumbName: "Stability Index Changelog",
    pageTitle: "Stability Index Changelog",
    datePublished: "2026-02-25",
    dateModified: "2026-08-22",
    citationUrn: "urn:pharos:methodology:psi@v3.61",
  },
  {
    slug: "yield-changelog",
    path: "/methodology/yield-changelog/",
    metadataTitle: "Yield Intelligence Changelog - Version History",
    metadataDescription: "Full version history of the Pharos Yield Intelligence methodology, from v1.0 through v8.42. Every source-resolution and scoring revision documented.",
    breadcrumbName: "Yield Intelligence Changelog",
    pageTitle: "Yield Intelligence Changelog",
    datePublished: "2026-03-01",
    dateModified: "2026-08-31",
    citationUrn: "urn:pharos:methodology:yield@v8.42",
  },
] as const;
