import type { DexExecutionTargetFactoryInput } from "../../cron/dex-liquidity/execution-target-registry";

export function makeDexExecutionTargetFactoryInput(
  chainNorm: string,
  protocol: string,
  poolType = "",
): DexExecutionTargetFactoryInput {
  return {
    stablecoinId: "usdc-circle",
    context: {
      pools: [],
      dexProjects: new Set(),
      symbolToChainScopedIds: new Map(),
      chainAddressToId: new Map(),
      curvePoolMap: new Map(),
      uniV3PoolFees: new Map(),
      uniV3SymbolFees: new Map(),
      uniV3ExecutionCandidates: new Map(),
      stablecoinPriceById: new Map(),
      measuredTargetCapturedAt: 1_785_000_000,
      curvePoolCandidatesByFingerprint: new Map(),
      uniswapV4ExecutionCandidates: new Map(),
    },
    identity: {
      chainNorm,
      protocol,
      poolType,
      matchedIds: new Set(["usdc-circle"]),
      poolSymbols: [],
      addrCurveKey: "",
      fpCurveKey: null,
      symCurveKey: "",
      pool: {
        pool: "",
        chain: chainNorm,
        project: protocol,
        symbol: "",
        tvlUsd: 0,
        volumeUsd1d: null,
        volumeUsd7d: null,
        stablecoin: true,
        underlyingTokens: [],
        apyBase: null,
        apyReward: null,
        apy: 0,
        sigma: 0,
        exposure: "single",
        count: 0,
      },
    },
    enrichment: {
      curveData: undefined,
      curveMeasuredRouteData: undefined,
      curveAddressMatch: false,
      resolvedPoolType: poolType,
      qualityMultiplier: 1,
      feeTierForExtra: undefined,
      balanceRatio: 1,
      hasMeasuredBalance: false,
      poolMaturityDays: 0,
      organicFraction: 0.5,
      hasMeasuredOrganicFraction: false,
      effectivePoolTvl: 0,
      rawContribTvl: 0,
      balanceDetails: undefined,
      volumeUsd1d: null,
      volumeUsd7d: null,
      volumeObservedAtSec: null,
    },
  };
}
